// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

#include "internal/block_encoder/instr.hpp"

#include <string>

#include "iced_x86/iced_constants.hpp"
#include "iced_x86/op_kind.hpp"
#include "iced_x86/register.hpp"
#include "iced_x86/reloc_kind.hpp"
#include "internal/encoder/encoder_internal.hpp"

namespace iced_x86::internal {

std::uint32_t BlockEncInt::get_instruction_size(const Instruction& instruction, std::uint64_t ip) {
	EncoderInternal::clear_buffer(null_encoder);
	auto result = null_encoder.encode(instruction, ip);
	if (result.is_err())
		return static_cast<std::uint32_t>(IcedConstants::MAX_INSTRUCTION_LENGTH);
	return static_cast<std::uint32_t>(result.value());
}

std::int64_t correct_diff(bool in_block, std::int64_t diff, std::uint64_t gained) noexcept {
	if (in_block && diff >= 0) {
		ICED_DEBUG_ASSERT(static_cast<std::uint64_t>(diff) >= gained);
		return diff - static_cast<std::int64_t>(gained);
	}
	return diff;
}

std::pair<TargetInstr*, std::uint64_t> Instr::get_target_instr() noexcept {
	switch (type) {
	case InstrType::SimpleBranch:
	case InstrType::Jmp:
	case InstrType::Jcc:
	case InstrType::Call:
	case InstrType::Xbegin:
		return {&target_instr, instruction.near_branch_target()};
	case InstrType::IpRelMemOp:
		return {&target_instr, instruction.ip_rel_memory_address()};
	case InstrType::Simple:
	default:
		// Never called since base.done == true
		ICED_UNREACHABLE();
	}
}

bool Instr::optimize(InstrBase& base, InstrContext& ctx, std::uint64_t gained) {
	switch (type) {
	case InstrType::Simple:
		return false;
	case InstrType::SimpleBranch:
		return SimpleBranchInstr::optimize(*this, base, ctx, gained);
	case InstrType::Jmp:
		return JmpInstr::optimize(*this, base, ctx, gained);
	case InstrType::Jcc:
		return JccInstr::optimize(*this, base, ctx, gained);
	case InstrType::Call:
		return CallInstr::optimize(*this, base, ctx, gained);
	case InstrType::IpRelMemOp:
		return IpRelMemOpInstr::optimize(*this, base, ctx, gained);
	case InstrType::Xbegin:
		return XbeginInstr::optimize(*this, base, ctx, gained);
	default:
		ICED_UNREACHABLE();
	}
}

Result<InstrEncodeResult> Instr::encode(InstrBase& base, InstrContext& ctx) {
	switch (type) {
	case InstrType::Simple:
		return SimpleInstr::encode(*this, base, ctx);
	case InstrType::SimpleBranch:
		return SimpleBranchInstr::encode(*this, base, ctx);
	case InstrType::Jmp:
		return JmpInstr::encode(*this, base, ctx);
	case InstrType::Jcc:
		return JccInstr::encode(*this, base, ctx);
	case InstrType::Call:
		return CallInstr::encode(*this, base, ctx);
	case InstrType::IpRelMemOp:
		return IpRelMemOpInstr::encode(*this, base, ctx);
	case InstrType::Xbegin:
		return XbeginInstr::encode(*this, base, ctx);
	default:
		ICED_UNREACHABLE();
	}
}

IcedError InstrUtils::create_error_message(const char* error_message, const Instruction& instruction) {
	// "{error_message} : 0x{ip:X}"
	static const char HEX_DIGITS[] = "0123456789ABCDEF";
	char hex[16];
	std::size_t hex_len = 0;
	std::uint64_t ip = instruction.ip();
	do {
		hex[hex_len++] = HEX_DIGITS[ip & 0xF];
		ip >>= 4;
	} while (ip != 0);

	std::string message(error_message);
	message.append(" : 0x");
	while (hex_len > 0)
		message.push_back(hex[--hex_len]);
	return IcedError(std::move(message));
}

void InstrUtils::create(BlockEncInt& block_encoder, InstrBase& base, Instr& instr, const Instruction& instruction) {
	switch (instruction.code()) {
	// GENERATOR-BEGIN: JccInstr
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Jo_rel8_16:
	case Code::Jo_rel8_32:
	case Code::Jo_rel8_64:
	case Code::Jno_rel8_16:
	case Code::Jno_rel8_32:
	case Code::Jno_rel8_64:
	case Code::Jb_rel8_16:
	case Code::Jb_rel8_32:
	case Code::Jb_rel8_64:
	case Code::Jae_rel8_16:
	case Code::Jae_rel8_32:
	case Code::Jae_rel8_64:
	case Code::Je_rel8_16:
	case Code::Je_rel8_32:
	case Code::Je_rel8_64:
	case Code::Jne_rel8_16:
	case Code::Jne_rel8_32:
	case Code::Jne_rel8_64:
	case Code::Jbe_rel8_16:
	case Code::Jbe_rel8_32:
	case Code::Jbe_rel8_64:
	case Code::Ja_rel8_16:
	case Code::Ja_rel8_32:
	case Code::Ja_rel8_64:
	case Code::Js_rel8_16:
	case Code::Js_rel8_32:
	case Code::Js_rel8_64:
	case Code::Jns_rel8_16:
	case Code::Jns_rel8_32:
	case Code::Jns_rel8_64:
	case Code::Jp_rel8_16:
	case Code::Jp_rel8_32:
	case Code::Jp_rel8_64:
	case Code::Jnp_rel8_16:
	case Code::Jnp_rel8_32:
	case Code::Jnp_rel8_64:
	case Code::Jl_rel8_16:
	case Code::Jl_rel8_32:
	case Code::Jl_rel8_64:
	case Code::Jge_rel8_16:
	case Code::Jge_rel8_32:
	case Code::Jge_rel8_64:
	case Code::Jle_rel8_16:
	case Code::Jle_rel8_32:
	case Code::Jle_rel8_64:
	case Code::Jg_rel8_16:
	case Code::Jg_rel8_32:
	case Code::Jg_rel8_64:
	case Code::Jo_rel16:
	case Code::Jo_rel32_32:
	case Code::Jo_rel32_64:
	case Code::Jno_rel16:
	case Code::Jno_rel32_32:
	case Code::Jno_rel32_64:
	case Code::Jb_rel16:
	case Code::Jb_rel32_32:
	case Code::Jb_rel32_64:
	case Code::Jae_rel16:
	case Code::Jae_rel32_32:
	case Code::Jae_rel32_64:
	case Code::Je_rel16:
	case Code::Je_rel32_32:
	case Code::Je_rel32_64:
	case Code::Jne_rel16:
	case Code::Jne_rel32_32:
	case Code::Jne_rel32_64:
	case Code::Jbe_rel16:
	case Code::Jbe_rel32_32:
	case Code::Jbe_rel32_64:
	case Code::Ja_rel16:
	case Code::Ja_rel32_32:
	case Code::Ja_rel32_64:
	case Code::Js_rel16:
	case Code::Js_rel32_32:
	case Code::Js_rel32_64:
	case Code::Jns_rel16:
	case Code::Jns_rel32_32:
	case Code::Jns_rel32_64:
	case Code::Jp_rel16:
	case Code::Jp_rel32_32:
	case Code::Jp_rel32_64:
	case Code::Jnp_rel16:
	case Code::Jnp_rel32_32:
	case Code::Jnp_rel32_64:
	case Code::Jl_rel16:
	case Code::Jl_rel32_32:
	case Code::Jl_rel32_64:
	case Code::Jge_rel16:
	case Code::Jge_rel32_32:
	case Code::Jge_rel32_64:
	case Code::Jle_rel16:
	case Code::Jle_rel32_32:
	case Code::Jle_rel32_64:
	case Code::Jg_rel16:
	case Code::Jg_rel32_32:
	case Code::Jg_rel32_64:
	case Code::VEX_KNC_Jkzd_kr_rel8_64:
	case Code::VEX_KNC_Jknzd_kr_rel8_64:
	case Code::VEX_KNC_Jkzd_kr_rel32_64:
	case Code::VEX_KNC_Jknzd_kr_rel32_64:
		JccInstr::create(block_encoder, base, instr, instruction);
		return;
	// GENERATOR-END: JccInstr

	// GENERATOR-BEGIN: SimpleBranchInstr
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Loopne_rel8_16_CX:
	case Code::Loopne_rel8_32_CX:
	case Code::Loopne_rel8_16_ECX:
	case Code::Loopne_rel8_32_ECX:
	case Code::Loopne_rel8_64_ECX:
	case Code::Loopne_rel8_16_RCX:
	case Code::Loopne_rel8_64_RCX:
	case Code::Loope_rel8_16_CX:
	case Code::Loope_rel8_32_CX:
	case Code::Loope_rel8_16_ECX:
	case Code::Loope_rel8_32_ECX:
	case Code::Loope_rel8_64_ECX:
	case Code::Loope_rel8_16_RCX:
	case Code::Loope_rel8_64_RCX:
	case Code::Loop_rel8_16_CX:
	case Code::Loop_rel8_32_CX:
	case Code::Loop_rel8_16_ECX:
	case Code::Loop_rel8_32_ECX:
	case Code::Loop_rel8_64_ECX:
	case Code::Loop_rel8_16_RCX:
	case Code::Loop_rel8_64_RCX:
	case Code::Jcxz_rel8_16:
	case Code::Jcxz_rel8_32:
	case Code::Jecxz_rel8_16:
	case Code::Jecxz_rel8_32:
	case Code::Jecxz_rel8_64:
	case Code::Jrcxz_rel8_16:
	case Code::Jrcxz_rel8_64:
		SimpleBranchInstr::create(block_encoder, base, instr, instruction);
		return;
	// GENERATOR-END: SimpleBranchInstr

	// GENERATOR-BEGIN: CallInstr
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Call_rel16:
	case Code::Call_rel32_32:
	case Code::Call_rel32_64:
		CallInstr::create(block_encoder, base, instr, instruction);
		return;
	// GENERATOR-END: CallInstr

	// GENERATOR-BEGIN: JmpInstr
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Jmp_rel16:
	case Code::Jmp_rel32_32:
	case Code::Jmp_rel32_64:
	case Code::Jmp_rel8_16:
	case Code::Jmp_rel8_32:
	case Code::Jmp_rel8_64:
		JmpInstr::create(block_encoder, base, instr, instruction);
		return;
	// GENERATOR-END: JmpInstr

	// GENERATOR-BEGIN: XbeginInstr
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Xbegin_rel16:
	case Code::Xbegin_rel32:
		XbeginInstr::create(block_encoder, base, instr, instruction);
		return;
	// GENERATOR-END: XbeginInstr

	default:
		break;
	}

	if (block_encoder.bitness == 64) {
		if (instruction.is_ip_rel_memory_operand()) {
			const std::uint32_t op_count = instruction.op_count();
			for (std::uint32_t i = 0; i < op_count; i++) {
				if (instruction.op_kind(i) == OpKind::Memory) {
					IpRelMemOpInstr::create(block_encoder, base, instr, instruction);
					return;
				}
			}
		}
	}

	SimpleInstr::create(block_encoder, base, instr, instruction);
}

Result<std::uint32_t> InstrUtils::encode_branch_to_pointer_data(Block& block, bool is_call, std::uint64_t ip, std::uint32_t pointer_data,
	std::uint32_t min_size) {
	if (min_size > static_cast<std::uint32_t>(INT32_MAX))
		return IcedError("Internal error");

	Instruction instr;
	instr.set_op0_kind(OpKind::Memory);
	instr.set_memory_displ_size(block.encoder.bitness() / 8);
	RelocKind reloc_kind;
	switch (block.encoder.bitness()) {
	case 64: {
		instr.set_code(is_call ? Code::Call_rm64 : Code::Jmp_rm64);
		instr.set_memory_base(Register::RIP);

		auto target_addr_result = block.data(pointer_data).address();
		if (target_addr_result.is_err())
			return target_addr_result.error();
		const std::uint64_t target_addr = target_addr_result.value();
		const std::uint64_t next_rip = ip + CALL_OR_JMP_POINTER_DATA_INSTRUCTION_SIZE64;
		const auto diff = static_cast<std::int64_t>(target_addr - next_rip);
		if (!(INT32_MIN <= diff && diff <= INT32_MAX))
			return IcedError("Block is too big");

		instr.set_memory_displacement64(target_addr);
		reloc_kind = RelocKind::Offset64;
		break;
	}

	default:
		ICED_UNREACHABLE();
	}

	auto encode_result = block.encoder.encode(instr, ip);
	if (encode_result.is_err())
		return encode_result.error();
	auto size = static_cast<std::uint32_t>(encode_result.value());
	if (block.can_add_reloc_infos() && reloc_kind != RelocKind::Offset64) {
		auto co = block.encoder.get_constant_offsets();
		if (!co.has_displacement())
			return IcedError("Internal error");
		block.add_reloc_info(RelocInfo(reloc_kind, ip + co.displacement_offset()));
	}
	while (size < min_size) {
		size++;
		block.write_byte(0x90);
	}
	return size;
}

} // namespace iced_x86::internal
