// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>

#include "iced_x86/iced_constants.hpp"

namespace iced_x86::internal::masm {

/// The kind of an `InstrInfo` (the fields' meaning depend on it)
enum class InstrInfoKind : std::uint8_t {
	Simple,
	cc,
	memsize,
	AamAad,
	Int3,
	YD,
	DX,
	YX,
	XY,
	YA,
	AX,
	AY,
	XLAT,
	nop,
	STIG1,
	STi_ST,
	ST_STi,
	monitor,
	mwait,
	mwaitx,
	maskmovq,
	pblendvb,
	reverse,
	OpSize,
	OpSize_cc,
	OpSize2,
	fword,
	jcc,
	bnd,
	pops,
	pclmulqdq,
	imul,
	Reg16,
	Reg32,
	reg,
	invlpga,
	DeclareData,
};

/// Creates the `InstrOpInfo` of an instruction (Rust: `Box<dyn InstrInfo>`). Constant data, one per `Code` value.
/// Strings are offsets in `STRINGS` (`FormatterString` data), `ARGS` has extra data (see `kind`)
struct InstrInfo {
	/// Offset in `STRINGS` of the (first) mnemonic
	std::uint16_t mnemonic;
	/// Depends on `kind`
	std::uint16_t arg1;
	/// Depends on `kind`
	std::uint16_t arg2;
	InstrInfoKind kind;
	/// Depends on `kind`
	std::uint8_t arg3;
};
static_assert(sizeof(InstrInfo) == 8, "");

/// All strings (`FormatterString` data: a length byte followed by the lowercase and the uppercase chars)
extern const char STRINGS[];
/// Extra data used by some `InstrInfoKind`s
extern const std::uint16_t ARGS[];
/// The `InstrInfo` of each `Code` value (Rust: `ALL_INFOS`)
extern const InstrInfo INSTR_INFOS[IcedConstants::CODE_ENUM_COUNT];

} // namespace iced_x86::internal::masm
