// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::masm {

enum class InstrOpKind : std::uint8_t {
	Register = 0,
	NearBranch16 = 1,
	NearBranch32 = 2,
	NearBranch64 = 3,
	FarBranch16 = 4,
	FarBranch32 = 5,
	Immediate8 = 6,
	Immediate8_2nd = 7,
	Immediate16 = 8,
	Immediate32 = 9,
	Immediate64 = 10,
	Immediate8to16 = 11,
	Immediate8to32 = 12,
	Immediate8to64 = 13,
	Immediate32to64 = 14,
	MemorySegSI = 15,
	MemorySegESI = 16,
	MemorySegRSI = 17,
	MemorySegDI = 18,
	MemorySegEDI = 19,
	MemorySegRDI = 20,
	MemoryESDI = 21,
	MemoryESEDI = 22,
	MemoryESRDI = 23,
	Memory = 24,
	ExtraImmediate8_Value3 = 25,
	DeclareByte = 26,
	DeclareWord = 27,
	DeclareDword = 28,
	DeclareQword = 29,
};

} // namespace iced_x86::internal::masm
