// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::masm {

struct InstrOpInfoFlags {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t MEM_SIZE_MASK = 0x0000'0007;
	static constexpr std::uint32_t MEM_SIZE_SSE = 0x0000'0000;
	static constexpr std::uint32_t MEM_SIZE_MMX = 0x0000'0001;
	static constexpr std::uint32_t MEM_SIZE_NORMAL = 0x0000'0002;
	static constexpr std::uint32_t MEM_SIZE_NOTHING = 0x0000'0003;
	static constexpr std::uint32_t MEM_SIZE_XMMWORD_PTR = 0x0000'0004;
	static constexpr std::uint32_t MEM_SIZE_DWORD_OR_QWORD = 0x0000'0005;
	static constexpr std::uint32_t SHOW_NO_MEM_SIZE_FORCE_SIZE = 0x0000'0008;
	static constexpr std::uint32_t SHOW_MIN_MEM_SIZE_FORCE_SIZE = 0x0000'0010;
	static constexpr std::uint32_t JCC_NOT_TAKEN = 0x0000'0020;
	static constexpr std::uint32_t JCC_TAKEN = 0x0000'0040;
	static constexpr std::uint32_t BND_PREFIX = 0x0000'0080;
	static constexpr std::uint32_t IGNORE_INDEX_REG = 0x0000'0100;
	static constexpr std::uint32_t MNEMONIC_IS_DIRECTIVE = 0x0000'0200;
};

} // namespace iced_x86::internal::masm
