// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::fast {

struct FastFmtFlags {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t HAS_VPREFIX = 0x0000'0001;
	static constexpr std::uint32_t SAME_AS_PREV = 0x0000'0002;
	static constexpr std::uint32_t FORCE_MEM_SIZE = 0x0000'0004;
	static constexpr std::uint32_t PSEUDO_OPS_KIND_SHIFT = 0x0000'0003;
	static constexpr std::uint32_t CMPPS = 0x0000'0008;
	static constexpr std::uint32_t VCMPPS = 0x0000'0010;
	static constexpr std::uint32_t CMPPD = 0x0000'0018;
	static constexpr std::uint32_t VCMPPD = 0x0000'0020;
	static constexpr std::uint32_t CMPSS = 0x0000'0028;
	static constexpr std::uint32_t VCMPSS = 0x0000'0030;
	static constexpr std::uint32_t CMPSD = 0x0000'0038;
	static constexpr std::uint32_t VCMPSD = 0x0000'0040;
	static constexpr std::uint32_t PCLMULQDQ = 0x0000'0048;
	static constexpr std::uint32_t VPCLMULQDQ = 0x0000'0050;
	static constexpr std::uint32_t VPCOMB = 0x0000'0058;
	static constexpr std::uint32_t VPCOMW = 0x0000'0060;
	static constexpr std::uint32_t VPCOMD = 0x0000'0068;
	static constexpr std::uint32_t VPCOMQ = 0x0000'0070;
	static constexpr std::uint32_t VPCOMUB = 0x0000'0078;
	static constexpr std::uint32_t VPCOMUW = 0x0000'0080;
	static constexpr std::uint32_t VPCOMUD = 0x0000'0088;
	static constexpr std::uint32_t VPCOMUQ = 0x0000'0090;
	static constexpr std::uint32_t VPCMPB = 0x0000'0098;
	static constexpr std::uint32_t VPCMPW = 0x0000'00A0;
	static constexpr std::uint32_t VPCMPD = 0x0000'00A8;
	static constexpr std::uint32_t VPCMPQ = 0x0000'00B0;
	static constexpr std::uint32_t VPCMPUB = 0x0000'00B8;
	static constexpr std::uint32_t VPCMPUW = 0x0000'00C0;
	static constexpr std::uint32_t VPCMPUD = 0x0000'00C8;
	static constexpr std::uint32_t VPCMPUQ = 0x0000'00D0;
	static constexpr std::uint32_t VCMPPH = 0x0000'00D8;
	static constexpr std::uint32_t VCMPSH = 0x0000'00E0;
	static constexpr std::uint32_t VCMPPS8 = 0x0000'00E8;
	static constexpr std::uint32_t VCMPPD8 = 0x0000'00F0;
	static constexpr std::uint32_t VPCMPD6 = 0x0000'00F8;
};

} // namespace iced_x86::internal::fast
