// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>

namespace iced_x86::internal::fast {

// `MNEMONICS`, `MNEMONIC_OFFSETS` and `CODE_FLAGS` are declared in `iced_x86/internal/fast_fmt.hpp`

/// Number of mnemonics in `MNEMONICS`
constexpr std::size_t MNEMONICS_COUNT = 1900;
/// Length of the longest mnemonic
constexpr std::size_t MAX_MNEMONIC_LEN = 18;
/// Number of readable bytes after each length byte (`FastStringMnemonic::SIZE`)
constexpr std::size_t MNEMONIC_VALID_STRING_LENGTH = 20;
/// Number of padding bytes after the last mnemonic
constexpr std::size_t MNEMONICS_PADDING_SIZE = 11;
/// Size of `MNEMONICS` in bytes
constexpr std::size_t MNEMONICS_SIZE = 16208;

} // namespace iced_x86::internal::fast
