// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// String constants shared by the gas/intel/masm/nasm formatters (Rust: formatter/fmt_consts.rs)

#pragma once

#include <array>
#include <string_view>

#include "iced_x86/iced_constants.hpp"
#include "internal/formatter/formatter_string.hpp"
#include "internal/formatter/gas/instr_op_info_flags.hpp"
#include "internal/formatter/intel/instr_op_info_flags.hpp"
#include "internal/formatter/nasm/instr_op_info_flags.hpp"

namespace iced_x86::internal {

struct MvexFormatterConstants {
	FormatterString swizzle_cdab;
	FormatterString swizzle_badc;
	FormatterString swizzle_dacb;
	FormatterString swizzle_aaaa;
	FormatterString swizzle_bbbb;
	FormatterString swizzle_cccc;
	FormatterString swizzle_dddd;
	FormatterString mem_1to16;
	FormatterString mem_1to8;
	FormatterString mem_4to16;
	FormatterString mem_4to8;
	FormatterString mem_float16;
	FormatterString mem_uint8;
	FormatterString mem_sint8;
	FormatterString mem_uint16;
	FormatterString mem_sint16;
	FormatterString eh;

	constexpr MvexFormatterConstants() noexcept;
};

struct FormatterConstants {
	FormatterString empty;
	// GENERATOR-BEGIN: FormatterConstantsDef
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	FormatterString b1to16;
	FormatterString b1to2;
	FormatterString b1to32;
	FormatterString b1to4;
	FormatterString b1to8;
	FormatterString bcst;
	FormatterString byte;
	FormatterString dword;
	FormatterString far;
	FormatterString fpuenv14;
	FormatterString fpuenv28;
	FormatterString fpustate108;
	FormatterString fpustate94;
	FormatterString fword;
	FormatterString mem384;
	FormatterString mmword;
	FormatterString oword;
	FormatterString ptr;
	FormatterString qword;
	FormatterString tbyte;
	FormatterString tword;
	FormatterString word;
	FormatterString xmmword;
	FormatterString ymmword;
	FormatterString yword;
	FormatterString zmmword;
	FormatterString zword;
	// GENERATOR-END: FormatterConstantsDef
	FormatterString bnd;
	FormatterString dot_byte;
	FormatterString hint_not_taken;
	FormatterString hint_taken;
	FormatterString hnt;
	FormatterString ht;
	FormatterString lock;
	FormatterString near;
	FormatterString notrack;
	FormatterString offset;
	FormatterString pn;
	FormatterString pt;
	FormatterString rel;
	FormatterString rep;
	std::array<FormatterString, 2> repe;
	std::array<FormatterString, 2> repne;
	FormatterString rex_w;
	FormatterString rne_sae;
	FormatterString rn_sae;
	FormatterString rd_sae;
	FormatterString ru_sae;
	FormatterString rz_sae;
	FormatterString sae;
	FormatterString rne;
	FormatterString rn;
	FormatterString rd;
	FormatterString ru;
	FormatterString rz;
	FormatterString short_;
	FormatterString to;
	FormatterString xacquire;
	FormatterString xrelease;
	FormatterString z;
	FormatterString a16;
	FormatterString a32;
	FormatterString a64;
	FormatterString addr16;
	FormatterString addr32;
	FormatterString addr64;
	FormatterString data16;
	FormatterString data32;
	FormatterString data64;
	FormatterString o16;
	FormatterString o32;
	FormatterString o64;
	MvexFormatterConstants mvex;

	constexpr FormatterConstants() noexcept;
};

/// The formatter constants (constant data)
extern const FormatterConstants FORMATTER_CONSTANTS;

/// Gets the formatter constants
inline const FormatterConstants& get_formatter_constants() noexcept { return FORMATTER_CONSTANTS; }

struct FormatterArrayConstants {
	std::array<const FormatterString*, 0> nothing;
	// GENERATOR-BEGIN: FormatterArrayConstantsDef
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	std::array<const FormatterString*, 2> byte_ptr;
	std::array<const FormatterString*, 2> dword_bcst;
	std::array<const FormatterString*, 2> dword_ptr;
	std::array<const FormatterString*, 2> fpuenv14_ptr;
	std::array<const FormatterString*, 2> fpuenv28_ptr;
	std::array<const FormatterString*, 2> fpustate108_ptr;
	std::array<const FormatterString*, 2> fpustate94_ptr;
	std::array<const FormatterString*, 2> fword_ptr;
	std::array<const FormatterString*, 2> mem384_ptr;
	std::array<const FormatterString*, 2> mmword_ptr;
	std::array<const FormatterString*, 2> oword_ptr;
	std::array<const FormatterString*, 2> qword_bcst;
	std::array<const FormatterString*, 2> qword_ptr;
	std::array<const FormatterString*, 2> tbyte_ptr;
	std::array<const FormatterString*, 2> word_bcst;
	std::array<const FormatterString*, 2> word_ptr;
	std::array<const FormatterString*, 2> xmmword_ptr;
	std::array<const FormatterString*, 2> ymmword_ptr;
	std::array<const FormatterString*, 2> zmmword_ptr;
	// GENERATOR-END: FormatterArrayConstantsDef
	std::array<const FormatterString*, gas::InstrOpInfoFlags::SIZE_OVERRIDE_MASK + 1> gas_op_size_strings;
	std::array<const FormatterString*, gas::InstrOpInfoFlags::SIZE_OVERRIDE_MASK + 1> gas_addr_size_strings;
	std::array<const FormatterString*, intel::InstrOpInfoFlags::SIZE_OVERRIDE_MASK + 1> intel_op_size_strings;
	std::array<const FormatterString*, intel::InstrOpInfoFlags::SIZE_OVERRIDE_MASK + 1> intel_addr_size_strings;
	std::array<const FormatterString*, IcedConstants::ROUNDING_CONTROL_ENUM_COUNT> intel_rc_strings;
	std::array<const FormatterString*, IcedConstants::ROUNDING_CONTROL_ENUM_COUNT> intel_rc_sae_strings;
	std::array<FormatterStringSlice, intel::InstrOpInfoFlags::BRANCH_SIZE_INFO_MASK + 1> intel_branch_infos;
	std::array<const FormatterString*, IcedConstants::ROUNDING_CONTROL_ENUM_COUNT> masm_rc_strings;
	std::array<const FormatterString*, IcedConstants::ROUNDING_CONTROL_ENUM_COUNT> masm_rc_sae_strings;
	std::array<const FormatterString*, nasm::InstrOpInfoFlags::SIZE_OVERRIDE_MASK + 1> nasm_op_size_strings;
	std::array<const FormatterString*, nasm::InstrOpInfoFlags::SIZE_OVERRIDE_MASK + 1> nasm_addr_size_strings;
	std::array<FormatterStringSlice, nasm::InstrOpInfoFlags::BRANCH_SIZE_INFO_MASK + 1> nasm_branch_infos;
	std::array<const FormatterString*, nasm::InstrOpInfoFlags::MEMORY_SIZE_INFO_MASK + 1> nasm_mem_size_infos;
	std::array<const FormatterString*, nasm::InstrOpInfoFlags::FAR_MEMORY_SIZE_INFO_MASK + 1> nasm_far_mem_size_infos;
	std::array<const FormatterString*, IcedConstants::MVEX_REG_MEM_CONV_ENUM_COUNT> mvex_reg_mem_consts_32;
	std::array<const FormatterString*, IcedConstants::MVEX_REG_MEM_CONV_ENUM_COUNT> mvex_reg_mem_consts_64;

	constexpr explicit FormatterArrayConstants(const FormatterConstants& c) noexcept;
};

/// The formatter array constants (constant data)
extern const FormatterArrayConstants ARRAY_CONSTANTS;

/// Gets the formatter array constants
inline const FormatterArrayConstants& get_array_constants() noexcept { return ARRAY_CONSTANTS; }

/// Scale strings (index = scale value 0-3)
inline constexpr std::string_view SCALE_NUMBERS[4] = {"1", "2", "4", "8"};

} // namespace iced_x86::internal
