// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class FormatterFlowControl : std::uint8_t {
	AlwaysShortBranch = 0,
	ShortBranch = 1,
	NearBranch = 2,
	NearCall = 3,
	FarBranch = 4,
	FarCall = 5,
	Xbegin = 6,
};

} // namespace iced_x86::internal
