// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class PseudoOpsKind : std::uint8_t {
	cmpps = 0,
	vcmpps = 1,
	cmppd = 2,
	vcmppd = 3,
	cmpss = 4,
	vcmpss = 5,
	cmpsd = 6,
	vcmpsd = 7,
	pclmulqdq = 8,
	vpclmulqdq = 9,
	vpcomb = 10,
	vpcomw = 11,
	vpcomd = 12,
	vpcomq = 13,
	vpcomub = 14,
	vpcomuw = 15,
	vpcomud = 16,
	vpcomuq = 17,
	vpcmpb = 18,
	vpcmpw = 19,
	vpcmpd = 20,
	vpcmpq = 21,
	vpcmpub = 22,
	vpcmpuw = 23,
	vpcmpud = 24,
	vpcmpuq = 25,
	vcmpph = 26,
	vcmpsh = 27,
	vcmpps8 = 28,
	vcmppd8 = 29,
	vpcmpd6 = 30,
	vpcmpud6 = 31,
};

} // namespace iced_x86::internal
