// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include "iced_x86/code_asm/mem.hpp"
#include "iced_x86/code_asm/memory_operand_size.hpp"

namespace iced_x86::code_asm {

/// Creates a memory operand with no size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = ptr(rax);
/// auto m2 = ptr(0x12345678).fs();
/// auto m3 = ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::None);
}

/// Creates a memory operand with a `BYTE PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = byte_ptr(rax);
/// auto m2 = byte_ptr(0x12345678).fs();
/// auto m3 = byte_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand byte_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Byte);
}

/// Creates a memory operand with a `WORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = word_ptr(rax);
/// auto m2 = word_ptr(0x12345678).fs();
/// auto m3 = word_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand word_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Word);
}

/// Creates a memory operand with a `DWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = dword_ptr(rax);
/// auto m2 = dword_ptr(0x12345678).fs();
/// auto m3 = dword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand dword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Dword);
}

/// Creates a memory operand with a `QWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = qword_ptr(rax);
/// auto m2 = qword_ptr(0x12345678).fs();
/// auto m3 = qword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand qword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Qword);
}

/// Creates a memory operand with an `MMWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = mmword_ptr(rax);
/// auto m2 = mmword_ptr(0x12345678).fs();
/// auto m3 = mmword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand mmword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Qword);
}

/// Creates a memory operand with a `TBYTE PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = tbyte_ptr(rax);
/// auto m2 = tbyte_ptr(0x12345678).fs();
/// auto m3 = tbyte_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand tbyte_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Tbyte);
}

/// Creates a memory operand with a `TWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = tword_ptr(rax);
/// auto m2 = tword_ptr(0x12345678).fs();
/// auto m3 = tword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand tword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Tbyte);
}

/// Creates a memory operand with an `FWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = fword_ptr(rax);
/// auto m2 = fword_ptr(0x12345678).fs();
/// auto m3 = fword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand fword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Fword);
}

/// Creates a memory operand with an `OWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = oword_ptr(rax);
/// auto m2 = oword_ptr(0x12345678).fs();
/// auto m3 = oword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand oword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Xword);
}

/// Creates a memory operand with an `XMMWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = xmmword_ptr(rax);
/// auto m2 = xmmword_ptr(0x12345678).fs();
/// auto m3 = xmmword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand xmmword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Xword);
}

/// Creates a memory operand with a `YMMWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = ymmword_ptr(rax);
/// auto m2 = ymmword_ptr(0x12345678).fs();
/// auto m3 = ymmword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand ymmword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Yword);
}

/// Creates a memory operand with a `ZMMWORD PTR` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = zmmword_ptr(rax);
/// auto m2 = zmmword_ptr(0x12345678).fs();
/// auto m3 = zmmword_ptr(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand zmmword_ptr(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_ptr(MemoryOperandSize::Zword);
}

/// Creates a broadcast memory operand with no size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = bcst(rax);
/// auto m2 = bcst(0x12345678).fs();
/// auto m3 = bcst(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand bcst(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_bcst(MemoryOperandSize::None);
}

/// Creates a broadcast memory operand with a `WORD BCST` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = word_bcst(rax);
/// auto m2 = word_bcst(0x12345678).fs();
/// auto m3 = word_bcst(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand word_bcst(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_bcst(MemoryOperandSize::Word);
}

/// Creates a broadcast memory operand with a `DWORD BCST` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = dword_bcst(rax);
/// auto m2 = dword_bcst(0x12345678).fs();
/// auto m3 = dword_bcst(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand dword_bcst(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_bcst(MemoryOperandSize::Dword);
}

/// Creates a broadcast memory operand with a `QWORD BCST` size hint
///
/// @param mem Memory operand, register (base), label or displacement
///
/// # Examples
///
/// ```cpp
/// using namespace iced_x86::code_asm;
///
/// auto m1 = qword_bcst(rax);
/// auto m2 = qword_bcst(0x12345678).fs();
/// auto m3 = qword_bcst(rdx * 4 + rcx - 123);
/// ```
[[nodiscard]] constexpr AsmMemoryOperand qword_bcst(const AsmMemoryOperandArg& mem) noexcept {
	return mem.value().with_bcst(MemoryOperandSize::Qword);
}

} // namespace iced_x86::code_asm
