// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::code_asm {

enum class MemoryOperandSize : std::uint8_t {
	None = 0,
	Byte = 1,
	Word = 2,
	Dword = 3,
	Qword = 4,
	Tbyte = 5,
	Fword = 6,
	Xword = 7,
	Yword = 8,
	Zword = 9,
};

/// Gets the name of a `MemoryOperandSize` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(MemoryOperandSize value) noexcept;

} // namespace iced_x86::code_asm
