// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include "iced_x86/code_asm/op_state.hpp"
#include "iced_x86/register.hpp"

namespace iced_x86::code_asm {

/// All 8-bit general purpose registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegister8 {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_gpr8()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegister8(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegister8& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegister8& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All 16-bit general purpose registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegister16 {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_gpr16()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegister16(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegister16& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegister16& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All 32-bit general purpose registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegister32 {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_gpr32()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegister32(Register register_) noexcept : reg_(register_), state_() {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	/// Gets the operand state (opmask, `{z}`, `{sae}`, rounding control)
	[[nodiscard]] constexpr CodeAsmOpState state() const noexcept { return state_; }

	/// Adds a `{k1}` opmask register
	[[nodiscard]] constexpr AsmRegister32 k1() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_k1();
		return result;
	}

	/// Adds a `{k2}` opmask register
	[[nodiscard]] constexpr AsmRegister32 k2() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_k2();
		return result;
	}

	/// Adds a `{k3}` opmask register
	[[nodiscard]] constexpr AsmRegister32 k3() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_k3();
		return result;
	}

	/// Adds a `{k4}` opmask register
	[[nodiscard]] constexpr AsmRegister32 k4() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_k4();
		return result;
	}

	/// Adds a `{k5}` opmask register
	[[nodiscard]] constexpr AsmRegister32 k5() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_k5();
		return result;
	}

	/// Adds a `{k6}` opmask register
	[[nodiscard]] constexpr AsmRegister32 k6() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_k6();
		return result;
	}

	/// Adds a `{k7}` opmask register
	[[nodiscard]] constexpr AsmRegister32 k7() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_k7();
		return result;
	}

	/// Enables zeroing masking `{z}`
	[[nodiscard]] constexpr AsmRegister32 z() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_zeroing_masking();
		return result;
	}

	/// Enables suppress all exceptions `{sae}`
	[[nodiscard]] constexpr AsmRegister32 sae() const noexcept {
		AsmRegister32 result = *this;
		result.state_.set_suppress_all_exceptions();
		return result;
	}

	/// Round to nearest (even)
	[[nodiscard]] constexpr AsmRegister32 rn_sae() const noexcept {
		AsmRegister32 result = *this;
		result.state_.rn_sae();
		return result;
	}

	/// Round down (toward -inf)
	[[nodiscard]] constexpr AsmRegister32 rd_sae() const noexcept {
		AsmRegister32 result = *this;
		result.state_.rd_sae();
		return result;
	}

	/// Round up (toward +inf)
	[[nodiscard]] constexpr AsmRegister32 ru_sae() const noexcept {
		AsmRegister32 result = *this;
		result.state_.ru_sae();
		return result;
	}

	/// Round toward zero (truncate)
	[[nodiscard]] constexpr AsmRegister32 rz_sae() const noexcept {
		AsmRegister32 result = *this;
		result.state_.rz_sae();
		return result;
	}

	constexpr bool operator==(const AsmRegister32& other) const noexcept { return reg_ == other.reg_ && state_ == other.state_; }
	constexpr bool operator!=(const AsmRegister32& other) const noexcept { return !(*this == other); }

private:
	Register reg_;
	CodeAsmOpState state_;
};

/// All 64-bit general purpose registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegister64 {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_gpr64()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegister64(Register register_) noexcept : reg_(register_), state_() {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	/// Gets the operand state (opmask, `{z}`, `{sae}`, rounding control)
	[[nodiscard]] constexpr CodeAsmOpState state() const noexcept { return state_; }

	/// Adds a `{k1}` opmask register
	[[nodiscard]] constexpr AsmRegister64 k1() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_k1();
		return result;
	}

	/// Adds a `{k2}` opmask register
	[[nodiscard]] constexpr AsmRegister64 k2() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_k2();
		return result;
	}

	/// Adds a `{k3}` opmask register
	[[nodiscard]] constexpr AsmRegister64 k3() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_k3();
		return result;
	}

	/// Adds a `{k4}` opmask register
	[[nodiscard]] constexpr AsmRegister64 k4() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_k4();
		return result;
	}

	/// Adds a `{k5}` opmask register
	[[nodiscard]] constexpr AsmRegister64 k5() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_k5();
		return result;
	}

	/// Adds a `{k6}` opmask register
	[[nodiscard]] constexpr AsmRegister64 k6() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_k6();
		return result;
	}

	/// Adds a `{k7}` opmask register
	[[nodiscard]] constexpr AsmRegister64 k7() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_k7();
		return result;
	}

	/// Enables zeroing masking `{z}`
	[[nodiscard]] constexpr AsmRegister64 z() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_zeroing_masking();
		return result;
	}

	/// Enables suppress all exceptions `{sae}`
	[[nodiscard]] constexpr AsmRegister64 sae() const noexcept {
		AsmRegister64 result = *this;
		result.state_.set_suppress_all_exceptions();
		return result;
	}

	/// Round to nearest (even)
	[[nodiscard]] constexpr AsmRegister64 rn_sae() const noexcept {
		AsmRegister64 result = *this;
		result.state_.rn_sae();
		return result;
	}

	/// Round down (toward -inf)
	[[nodiscard]] constexpr AsmRegister64 rd_sae() const noexcept {
		AsmRegister64 result = *this;
		result.state_.rd_sae();
		return result;
	}

	/// Round up (toward +inf)
	[[nodiscard]] constexpr AsmRegister64 ru_sae() const noexcept {
		AsmRegister64 result = *this;
		result.state_.ru_sae();
		return result;
	}

	/// Round toward zero (truncate)
	[[nodiscard]] constexpr AsmRegister64 rz_sae() const noexcept {
		AsmRegister64 result = *this;
		result.state_.rz_sae();
		return result;
	}

	constexpr bool operator==(const AsmRegister64& other) const noexcept { return reg_ == other.reg_ && state_ == other.state_; }
	constexpr bool operator!=(const AsmRegister64& other) const noexcept { return !(*this == other); }

private:
	Register reg_;
	CodeAsmOpState state_;
};

/// All segment registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterSegment {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_segment()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterSegment(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterSegment& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterSegment& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All control registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterCr {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_cr()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterCr(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterCr& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterCr& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All debug registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterDr {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_dr()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterDr(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterDr& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterDr& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All test registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterTr {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_tr()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterTr(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterTr& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterTr& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All FPU registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterSt {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_st()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterSt(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterSt& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterSt& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All MMX registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterMm {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_mm()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterMm(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterMm& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterMm& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All 128-bit vector registers (XMM).
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterXmm {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_xmm()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterXmm(Register register_) noexcept : reg_(register_), state_() {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	/// Gets the operand state (opmask, `{z}`, `{sae}`, rounding control)
	[[nodiscard]] constexpr CodeAsmOpState state() const noexcept { return state_; }

	/// Adds a `{k1}` opmask register
	[[nodiscard]] constexpr AsmRegisterXmm k1() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_k1();
		return result;
	}

	/// Adds a `{k2}` opmask register
	[[nodiscard]] constexpr AsmRegisterXmm k2() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_k2();
		return result;
	}

	/// Adds a `{k3}` opmask register
	[[nodiscard]] constexpr AsmRegisterXmm k3() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_k3();
		return result;
	}

	/// Adds a `{k4}` opmask register
	[[nodiscard]] constexpr AsmRegisterXmm k4() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_k4();
		return result;
	}

	/// Adds a `{k5}` opmask register
	[[nodiscard]] constexpr AsmRegisterXmm k5() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_k5();
		return result;
	}

	/// Adds a `{k6}` opmask register
	[[nodiscard]] constexpr AsmRegisterXmm k6() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_k6();
		return result;
	}

	/// Adds a `{k7}` opmask register
	[[nodiscard]] constexpr AsmRegisterXmm k7() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_k7();
		return result;
	}

	/// Enables zeroing masking `{z}`
	[[nodiscard]] constexpr AsmRegisterXmm z() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_zeroing_masking();
		return result;
	}

	/// Enables suppress all exceptions `{sae}`
	[[nodiscard]] constexpr AsmRegisterXmm sae() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.set_suppress_all_exceptions();
		return result;
	}

	/// Round to nearest (even)
	[[nodiscard]] constexpr AsmRegisterXmm rn_sae() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.rn_sae();
		return result;
	}

	/// Round down (toward -inf)
	[[nodiscard]] constexpr AsmRegisterXmm rd_sae() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.rd_sae();
		return result;
	}

	/// Round up (toward +inf)
	[[nodiscard]] constexpr AsmRegisterXmm ru_sae() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.ru_sae();
		return result;
	}

	/// Round toward zero (truncate)
	[[nodiscard]] constexpr AsmRegisterXmm rz_sae() const noexcept {
		AsmRegisterXmm result = *this;
		result.state_.rz_sae();
		return result;
	}

	constexpr bool operator==(const AsmRegisterXmm& other) const noexcept { return reg_ == other.reg_ && state_ == other.state_; }
	constexpr bool operator!=(const AsmRegisterXmm& other) const noexcept { return !(*this == other); }

private:
	Register reg_;
	CodeAsmOpState state_;
};

/// All 256-bit vector registers (YMM).
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterYmm {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_ymm()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterYmm(Register register_) noexcept : reg_(register_), state_() {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	/// Gets the operand state (opmask, `{z}`, `{sae}`, rounding control)
	[[nodiscard]] constexpr CodeAsmOpState state() const noexcept { return state_; }

	/// Adds a `{k1}` opmask register
	[[nodiscard]] constexpr AsmRegisterYmm k1() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_k1();
		return result;
	}

	/// Adds a `{k2}` opmask register
	[[nodiscard]] constexpr AsmRegisterYmm k2() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_k2();
		return result;
	}

	/// Adds a `{k3}` opmask register
	[[nodiscard]] constexpr AsmRegisterYmm k3() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_k3();
		return result;
	}

	/// Adds a `{k4}` opmask register
	[[nodiscard]] constexpr AsmRegisterYmm k4() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_k4();
		return result;
	}

	/// Adds a `{k5}` opmask register
	[[nodiscard]] constexpr AsmRegisterYmm k5() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_k5();
		return result;
	}

	/// Adds a `{k6}` opmask register
	[[nodiscard]] constexpr AsmRegisterYmm k6() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_k6();
		return result;
	}

	/// Adds a `{k7}` opmask register
	[[nodiscard]] constexpr AsmRegisterYmm k7() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_k7();
		return result;
	}

	/// Enables zeroing masking `{z}`
	[[nodiscard]] constexpr AsmRegisterYmm z() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_zeroing_masking();
		return result;
	}

	/// Enables suppress all exceptions `{sae}`
	[[nodiscard]] constexpr AsmRegisterYmm sae() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.set_suppress_all_exceptions();
		return result;
	}

	/// Round to nearest (even)
	[[nodiscard]] constexpr AsmRegisterYmm rn_sae() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.rn_sae();
		return result;
	}

	/// Round down (toward -inf)
	[[nodiscard]] constexpr AsmRegisterYmm rd_sae() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.rd_sae();
		return result;
	}

	/// Round up (toward +inf)
	[[nodiscard]] constexpr AsmRegisterYmm ru_sae() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.ru_sae();
		return result;
	}

	/// Round toward zero (truncate)
	[[nodiscard]] constexpr AsmRegisterYmm rz_sae() const noexcept {
		AsmRegisterYmm result = *this;
		result.state_.rz_sae();
		return result;
	}

	constexpr bool operator==(const AsmRegisterYmm& other) const noexcept { return reg_ == other.reg_ && state_ == other.state_; }
	constexpr bool operator!=(const AsmRegisterYmm& other) const noexcept { return !(*this == other); }

private:
	Register reg_;
	CodeAsmOpState state_;
};

/// All 512-bit vector registers (ZMM).
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterZmm {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_zmm()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterZmm(Register register_) noexcept : reg_(register_), state_() {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	/// Gets the operand state (opmask, `{z}`, `{sae}`, rounding control)
	[[nodiscard]] constexpr CodeAsmOpState state() const noexcept { return state_; }

	/// Adds a `{k1}` opmask register
	[[nodiscard]] constexpr AsmRegisterZmm k1() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_k1();
		return result;
	}

	/// Adds a `{k2}` opmask register
	[[nodiscard]] constexpr AsmRegisterZmm k2() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_k2();
		return result;
	}

	/// Adds a `{k3}` opmask register
	[[nodiscard]] constexpr AsmRegisterZmm k3() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_k3();
		return result;
	}

	/// Adds a `{k4}` opmask register
	[[nodiscard]] constexpr AsmRegisterZmm k4() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_k4();
		return result;
	}

	/// Adds a `{k5}` opmask register
	[[nodiscard]] constexpr AsmRegisterZmm k5() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_k5();
		return result;
	}

	/// Adds a `{k6}` opmask register
	[[nodiscard]] constexpr AsmRegisterZmm k6() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_k6();
		return result;
	}

	/// Adds a `{k7}` opmask register
	[[nodiscard]] constexpr AsmRegisterZmm k7() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_k7();
		return result;
	}

	/// Enables zeroing masking `{z}`
	[[nodiscard]] constexpr AsmRegisterZmm z() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_zeroing_masking();
		return result;
	}

	/// Enables suppress all exceptions `{sae}`
	[[nodiscard]] constexpr AsmRegisterZmm sae() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.set_suppress_all_exceptions();
		return result;
	}

	/// Round to nearest (even)
	[[nodiscard]] constexpr AsmRegisterZmm rn_sae() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.rn_sae();
		return result;
	}

	/// Round down (toward -inf)
	[[nodiscard]] constexpr AsmRegisterZmm rd_sae() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.rd_sae();
		return result;
	}

	/// Round up (toward +inf)
	[[nodiscard]] constexpr AsmRegisterZmm ru_sae() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.ru_sae();
		return result;
	}

	/// Round toward zero (truncate)
	[[nodiscard]] constexpr AsmRegisterZmm rz_sae() const noexcept {
		AsmRegisterZmm result = *this;
		result.state_.rz_sae();
		return result;
	}

	constexpr bool operator==(const AsmRegisterZmm& other) const noexcept { return reg_ == other.reg_ && state_ == other.state_; }
	constexpr bool operator!=(const AsmRegisterZmm& other) const noexcept { return !(*this == other); }

private:
	Register reg_;
	CodeAsmOpState state_;
};

/// All tile registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterTmm {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_tmm()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterTmm(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterTmm& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterTmm& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

/// All opmask registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterK {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_k()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterK(Register register_) noexcept : reg_(register_), state_() {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	/// Gets the operand state (opmask, `{z}`, `{sae}`, rounding control)
	[[nodiscard]] constexpr CodeAsmOpState state() const noexcept { return state_; }

	/// Adds a `{k1}` opmask register
	[[nodiscard]] constexpr AsmRegisterK k1() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_k1();
		return result;
	}

	/// Adds a `{k2}` opmask register
	[[nodiscard]] constexpr AsmRegisterK k2() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_k2();
		return result;
	}

	/// Adds a `{k3}` opmask register
	[[nodiscard]] constexpr AsmRegisterK k3() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_k3();
		return result;
	}

	/// Adds a `{k4}` opmask register
	[[nodiscard]] constexpr AsmRegisterK k4() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_k4();
		return result;
	}

	/// Adds a `{k5}` opmask register
	[[nodiscard]] constexpr AsmRegisterK k5() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_k5();
		return result;
	}

	/// Adds a `{k6}` opmask register
	[[nodiscard]] constexpr AsmRegisterK k6() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_k6();
		return result;
	}

	/// Adds a `{k7}` opmask register
	[[nodiscard]] constexpr AsmRegisterK k7() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_k7();
		return result;
	}

	/// Enables zeroing masking `{z}`
	[[nodiscard]] constexpr AsmRegisterK z() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_zeroing_masking();
		return result;
	}

	/// Enables suppress all exceptions `{sae}`
	[[nodiscard]] constexpr AsmRegisterK sae() const noexcept {
		AsmRegisterK result = *this;
		result.state_.set_suppress_all_exceptions();
		return result;
	}

	/// Round to nearest (even)
	[[nodiscard]] constexpr AsmRegisterK rn_sae() const noexcept {
		AsmRegisterK result = *this;
		result.state_.rn_sae();
		return result;
	}

	/// Round down (toward -inf)
	[[nodiscard]] constexpr AsmRegisterK rd_sae() const noexcept {
		AsmRegisterK result = *this;
		result.state_.rd_sae();
		return result;
	}

	/// Round up (toward +inf)
	[[nodiscard]] constexpr AsmRegisterK ru_sae() const noexcept {
		AsmRegisterK result = *this;
		result.state_.ru_sae();
		return result;
	}

	/// Round toward zero (truncate)
	[[nodiscard]] constexpr AsmRegisterK rz_sae() const noexcept {
		AsmRegisterK result = *this;
		result.state_.rz_sae();
		return result;
	}

	constexpr bool operator==(const AsmRegisterK& other) const noexcept { return reg_ == other.reg_ && state_ == other.state_; }
	constexpr bool operator!=(const AsmRegisterK& other) const noexcept { return !(*this == other); }

private:
	Register reg_;
	CodeAsmOpState state_;
};

/// All bound registers.
///
/// The register constants (eg. `eax`, `xmm0`) are part of the public API. The register *types* are
/// an implementation detail. See the `iced_x86::code_asm::registers` namespace.
class AsmRegisterBnd {
public:
	/// Creates a register. The register isn't verified, see also
	/// `registers::get_bnd()` which verifies the input register.
	///
	/// @param register_ Register
	explicit constexpr AsmRegisterBnd(Register register_) noexcept : reg_(register_) {}

	/// Gets the register
	[[nodiscard]] constexpr Register register_() const noexcept { return reg_; }

	/// Gets the register
	explicit constexpr operator Register() const noexcept { return reg_; }

	constexpr bool operator==(const AsmRegisterBnd& other) const noexcept { return reg_ == other.reg_; }
	constexpr bool operator!=(const AsmRegisterBnd& other) const noexcept { return reg_ != other.reg_; }

private:
	Register reg_;
};

} // namespace iced_x86::code_asm
