// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include "iced_x86/code_asm/reg.hpp"
#include "iced_x86/register.hpp"
#include "iced_x86/register_ext.hpp"

#include <optional>

/// This namespace contains all registers that can be used by the code assembler.
///
/// All register identifiers (eg. `eax`, `cr8`) are part of the public API. They're `constexpr`
/// constants and they're also available in the `iced_x86::code_asm` namespace:
///
/// ```cpp
/// using namespace iced_x86::code_asm;
/// ```
///
/// or only the registers you need:
///
/// ```cpp
/// using namespace iced_x86::code_asm::registers::gpr32;
/// using namespace iced_x86::code_asm::registers::gpr64;
/// using namespace iced_x86::code_asm::registers::xmm;
/// ```
namespace iced_x86::code_asm::registers {

/// All 8-bit general purpose registers.
namespace gpr8 {

/// `AL` register
inline constexpr AsmRegister8 al{Register::AL};
/// `CL` register
inline constexpr AsmRegister8 cl{Register::CL};
/// `DL` register
inline constexpr AsmRegister8 dl{Register::DL};
/// `BL` register
inline constexpr AsmRegister8 bl{Register::BL};
/// `AH` register
inline constexpr AsmRegister8 ah{Register::AH};
/// `CH` register
inline constexpr AsmRegister8 ch{Register::CH};
/// `DH` register
inline constexpr AsmRegister8 dh{Register::DH};
/// `BH` register
inline constexpr AsmRegister8 bh{Register::BH};
/// `SPL` register
inline constexpr AsmRegister8 spl{Register::SPL};
/// `BPL` register
inline constexpr AsmRegister8 bpl{Register::BPL};
/// `SIL` register
inline constexpr AsmRegister8 sil{Register::SIL};
/// `DIL` register
inline constexpr AsmRegister8 dil{Register::DIL};
/// `R8L` register
inline constexpr AsmRegister8 r8b{Register::R8L};
/// `R9L` register
inline constexpr AsmRegister8 r9b{Register::R9L};
/// `R10L` register
inline constexpr AsmRegister8 r10b{Register::R10L};
/// `R11L` register
inline constexpr AsmRegister8 r11b{Register::R11L};
/// `R12L` register
inline constexpr AsmRegister8 r12b{Register::R12L};
/// `R13L` register
inline constexpr AsmRegister8 r13b{Register::R13L};
/// `R14L` register
inline constexpr AsmRegister8 r14b{Register::R14L};
/// `R15L` register
inline constexpr AsmRegister8 r15b{Register::R15L};

/// Gets a `GPR8` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegister8> get_gpr8(Register register_) noexcept {
	if (register_ext::is_gpr8(register_))
		return AsmRegister8(register_);
	return std::nullopt;
}

} // namespace gpr8

/// All 16-bit general purpose registers.
namespace gpr16 {

/// `AX` register
inline constexpr AsmRegister16 ax{Register::AX};
/// `CX` register
inline constexpr AsmRegister16 cx{Register::CX};
/// `DX` register
inline constexpr AsmRegister16 dx{Register::DX};
/// `BX` register
inline constexpr AsmRegister16 bx{Register::BX};
/// `SP` register
inline constexpr AsmRegister16 sp{Register::SP};
/// `BP` register
inline constexpr AsmRegister16 bp{Register::BP};
/// `SI` register
inline constexpr AsmRegister16 si{Register::SI};
/// `DI` register
inline constexpr AsmRegister16 di{Register::DI};
/// `R8W` register
inline constexpr AsmRegister16 r8w{Register::R8W};
/// `R9W` register
inline constexpr AsmRegister16 r9w{Register::R9W};
/// `R10W` register
inline constexpr AsmRegister16 r10w{Register::R10W};
/// `R11W` register
inline constexpr AsmRegister16 r11w{Register::R11W};
/// `R12W` register
inline constexpr AsmRegister16 r12w{Register::R12W};
/// `R13W` register
inline constexpr AsmRegister16 r13w{Register::R13W};
/// `R14W` register
inline constexpr AsmRegister16 r14w{Register::R14W};
/// `R15W` register
inline constexpr AsmRegister16 r15w{Register::R15W};

/// Gets a `GPR16` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegister16> get_gpr16(Register register_) noexcept {
	if (register_ext::is_gpr16(register_))
		return AsmRegister16(register_);
	return std::nullopt;
}

} // namespace gpr16

/// All 32-bit general purpose registers.
namespace gpr32 {

/// `EAX` register
inline constexpr AsmRegister32 eax{Register::EAX};
/// `ECX` register
inline constexpr AsmRegister32 ecx{Register::ECX};
/// `EDX` register
inline constexpr AsmRegister32 edx{Register::EDX};
/// `EBX` register
inline constexpr AsmRegister32 ebx{Register::EBX};
/// `ESP` register
inline constexpr AsmRegister32 esp{Register::ESP};
/// `EBP` register
inline constexpr AsmRegister32 ebp{Register::EBP};
/// `ESI` register
inline constexpr AsmRegister32 esi{Register::ESI};
/// `EDI` register
inline constexpr AsmRegister32 edi{Register::EDI};
/// `R8D` register
inline constexpr AsmRegister32 r8d{Register::R8D};
/// `R9D` register
inline constexpr AsmRegister32 r9d{Register::R9D};
/// `R10D` register
inline constexpr AsmRegister32 r10d{Register::R10D};
/// `R11D` register
inline constexpr AsmRegister32 r11d{Register::R11D};
/// `R12D` register
inline constexpr AsmRegister32 r12d{Register::R12D};
/// `R13D` register
inline constexpr AsmRegister32 r13d{Register::R13D};
/// `R14D` register
inline constexpr AsmRegister32 r14d{Register::R14D};
/// `R15D` register
inline constexpr AsmRegister32 r15d{Register::R15D};

/// Gets a `GPR32` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegister32> get_gpr32(Register register_) noexcept {
	if (register_ext::is_gpr32(register_))
		return AsmRegister32(register_);
	return std::nullopt;
}

} // namespace gpr32

/// All 64-bit general purpose registers.
namespace gpr64 {

/// `RAX` register
inline constexpr AsmRegister64 rax{Register::RAX};
/// `RCX` register
inline constexpr AsmRegister64 rcx{Register::RCX};
/// `RDX` register
inline constexpr AsmRegister64 rdx{Register::RDX};
/// `RBX` register
inline constexpr AsmRegister64 rbx{Register::RBX};
/// `RSP` register
inline constexpr AsmRegister64 rsp{Register::RSP};
/// `RBP` register
inline constexpr AsmRegister64 rbp{Register::RBP};
/// `RSI` register
inline constexpr AsmRegister64 rsi{Register::RSI};
/// `RDI` register
inline constexpr AsmRegister64 rdi{Register::RDI};
/// `R8` register
inline constexpr AsmRegister64 r8{Register::R8};
/// `R9` register
inline constexpr AsmRegister64 r9{Register::R9};
/// `R10` register
inline constexpr AsmRegister64 r10{Register::R10};
/// `R11` register
inline constexpr AsmRegister64 r11{Register::R11};
/// `R12` register
inline constexpr AsmRegister64 r12{Register::R12};
/// `R13` register
inline constexpr AsmRegister64 r13{Register::R13};
/// `R14` register
inline constexpr AsmRegister64 r14{Register::R14};
/// `R15` register
inline constexpr AsmRegister64 r15{Register::R15};

/// Gets a `GPR64` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegister64> get_gpr64(Register register_) noexcept {
	if (register_ext::is_gpr64(register_))
		return AsmRegister64(register_);
	return std::nullopt;
}

} // namespace gpr64

/// All segment registers.
namespace segment {

/// `ES` register
inline constexpr AsmRegisterSegment es{Register::ES};
/// `CS` register
inline constexpr AsmRegisterSegment cs{Register::CS};
/// `SS` register
inline constexpr AsmRegisterSegment ss{Register::SS};
/// `DS` register
inline constexpr AsmRegisterSegment ds{Register::DS};
/// `FS` register
inline constexpr AsmRegisterSegment fs{Register::FS};
/// `GS` register
inline constexpr AsmRegisterSegment gs{Register::GS};

/// Gets a `SEGMENT` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterSegment> get_segment(Register register_) noexcept {
	if (register_ext::is_segment_register(register_))
		return AsmRegisterSegment(register_);
	return std::nullopt;
}

} // namespace segment

/// All FPU registers.
namespace st {

/// `ST0` register
inline constexpr AsmRegisterSt st0{Register::ST0};
/// `ST1` register
inline constexpr AsmRegisterSt st1{Register::ST1};
/// `ST2` register
inline constexpr AsmRegisterSt st2{Register::ST2};
/// `ST3` register
inline constexpr AsmRegisterSt st3{Register::ST3};
/// `ST4` register
inline constexpr AsmRegisterSt st4{Register::ST4};
/// `ST5` register
inline constexpr AsmRegisterSt st5{Register::ST5};
/// `ST6` register
inline constexpr AsmRegisterSt st6{Register::ST6};
/// `ST7` register
inline constexpr AsmRegisterSt st7{Register::ST7};

/// Gets an `ST` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterSt> get_st(Register register_) noexcept {
	if (register_ext::is_st(register_))
		return AsmRegisterSt(register_);
	return std::nullopt;
}

} // namespace st

/// All control registers.
namespace cr {

/// `CR0` register
inline constexpr AsmRegisterCr cr0{Register::CR0};
/// `CR1` register
inline constexpr AsmRegisterCr cr1{Register::CR1};
/// `CR2` register
inline constexpr AsmRegisterCr cr2{Register::CR2};
/// `CR3` register
inline constexpr AsmRegisterCr cr3{Register::CR3};
/// `CR4` register
inline constexpr AsmRegisterCr cr4{Register::CR4};
/// `CR5` register
inline constexpr AsmRegisterCr cr5{Register::CR5};
/// `CR6` register
inline constexpr AsmRegisterCr cr6{Register::CR6};
/// `CR7` register
inline constexpr AsmRegisterCr cr7{Register::CR7};
/// `CR8` register
inline constexpr AsmRegisterCr cr8{Register::CR8};
/// `CR9` register
inline constexpr AsmRegisterCr cr9{Register::CR9};
/// `CR10` register
inline constexpr AsmRegisterCr cr10{Register::CR10};
/// `CR11` register
inline constexpr AsmRegisterCr cr11{Register::CR11};
/// `CR12` register
inline constexpr AsmRegisterCr cr12{Register::CR12};
/// `CR13` register
inline constexpr AsmRegisterCr cr13{Register::CR13};
/// `CR14` register
inline constexpr AsmRegisterCr cr14{Register::CR14};
/// `CR15` register
inline constexpr AsmRegisterCr cr15{Register::CR15};

/// Gets a `CR` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterCr> get_cr(Register register_) noexcept {
	if (register_ext::is_cr(register_))
		return AsmRegisterCr(register_);
	return std::nullopt;
}

} // namespace cr

/// All debug registers.
namespace dr {

/// `DR0` register
inline constexpr AsmRegisterDr dr0{Register::DR0};
/// `DR1` register
inline constexpr AsmRegisterDr dr1{Register::DR1};
/// `DR2` register
inline constexpr AsmRegisterDr dr2{Register::DR2};
/// `DR3` register
inline constexpr AsmRegisterDr dr3{Register::DR3};
/// `DR4` register
inline constexpr AsmRegisterDr dr4{Register::DR4};
/// `DR5` register
inline constexpr AsmRegisterDr dr5{Register::DR5};
/// `DR6` register
inline constexpr AsmRegisterDr dr6{Register::DR6};
/// `DR7` register
inline constexpr AsmRegisterDr dr7{Register::DR7};
/// `DR8` register
inline constexpr AsmRegisterDr dr8{Register::DR8};
/// `DR9` register
inline constexpr AsmRegisterDr dr9{Register::DR9};
/// `DR10` register
inline constexpr AsmRegisterDr dr10{Register::DR10};
/// `DR11` register
inline constexpr AsmRegisterDr dr11{Register::DR11};
/// `DR12` register
inline constexpr AsmRegisterDr dr12{Register::DR12};
/// `DR13` register
inline constexpr AsmRegisterDr dr13{Register::DR13};
/// `DR14` register
inline constexpr AsmRegisterDr dr14{Register::DR14};
/// `DR15` register
inline constexpr AsmRegisterDr dr15{Register::DR15};

/// Gets a `DR` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterDr> get_dr(Register register_) noexcept {
	if (register_ext::is_dr(register_))
		return AsmRegisterDr(register_);
	return std::nullopt;
}

} // namespace dr

/// All test registers.
namespace tr {

/// `TR0` register
inline constexpr AsmRegisterTr tr0{Register::TR0};
/// `TR1` register
inline constexpr AsmRegisterTr tr1{Register::TR1};
/// `TR2` register
inline constexpr AsmRegisterTr tr2{Register::TR2};
/// `TR3` register
inline constexpr AsmRegisterTr tr3{Register::TR3};
/// `TR4` register
inline constexpr AsmRegisterTr tr4{Register::TR4};
/// `TR5` register
inline constexpr AsmRegisterTr tr5{Register::TR5};
/// `TR6` register
inline constexpr AsmRegisterTr tr6{Register::TR6};
/// `TR7` register
inline constexpr AsmRegisterTr tr7{Register::TR7};

/// Gets a `TR` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterTr> get_tr(Register register_) noexcept {
	if (register_ext::is_tr(register_))
		return AsmRegisterTr(register_);
	return std::nullopt;
}

} // namespace tr

/// All bound registers.
namespace bnd {

/// `BND0` register
inline constexpr AsmRegisterBnd bnd0{Register::BND0};
/// `BND1` register
inline constexpr AsmRegisterBnd bnd1{Register::BND1};
/// `BND2` register
inline constexpr AsmRegisterBnd bnd2{Register::BND2};
/// `BND3` register
inline constexpr AsmRegisterBnd bnd3{Register::BND3};

/// Gets a `BND` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterBnd> get_bnd(Register register_) noexcept {
	if (register_ext::is_bnd(register_))
		return AsmRegisterBnd(register_);
	return std::nullopt;
}

} // namespace bnd

/// All opmask registers.
namespace k {

/// `K0` register
inline constexpr AsmRegisterK k0{Register::K0};
/// `K1` register
inline constexpr AsmRegisterK k1{Register::K1};
/// `K2` register
inline constexpr AsmRegisterK k2{Register::K2};
/// `K3` register
inline constexpr AsmRegisterK k3{Register::K3};
/// `K4` register
inline constexpr AsmRegisterK k4{Register::K4};
/// `K5` register
inline constexpr AsmRegisterK k5{Register::K5};
/// `K6` register
inline constexpr AsmRegisterK k6{Register::K6};
/// `K7` register
inline constexpr AsmRegisterK k7{Register::K7};

/// Gets a `K` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterK> get_k(Register register_) noexcept {
	if (register_ext::is_k(register_))
		return AsmRegisterK(register_);
	return std::nullopt;
}

} // namespace k

/// All MMX registers.
namespace mm {

/// `MM0` register
inline constexpr AsmRegisterMm mm0{Register::MM0};
/// `MM1` register
inline constexpr AsmRegisterMm mm1{Register::MM1};
/// `MM2` register
inline constexpr AsmRegisterMm mm2{Register::MM2};
/// `MM3` register
inline constexpr AsmRegisterMm mm3{Register::MM3};
/// `MM4` register
inline constexpr AsmRegisterMm mm4{Register::MM4};
/// `MM5` register
inline constexpr AsmRegisterMm mm5{Register::MM5};
/// `MM6` register
inline constexpr AsmRegisterMm mm6{Register::MM6};
/// `MM7` register
inline constexpr AsmRegisterMm mm7{Register::MM7};

/// Gets an `MM` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterMm> get_mm(Register register_) noexcept {
	if (register_ext::is_mm(register_))
		return AsmRegisterMm(register_);
	return std::nullopt;
}

} // namespace mm

/// All 128-bit vector registers (XMM).
namespace xmm {

/// `XMM0` register
inline constexpr AsmRegisterXmm xmm0{Register::XMM0};
/// `XMM1` register
inline constexpr AsmRegisterXmm xmm1{Register::XMM1};
/// `XMM2` register
inline constexpr AsmRegisterXmm xmm2{Register::XMM2};
/// `XMM3` register
inline constexpr AsmRegisterXmm xmm3{Register::XMM3};
/// `XMM4` register
inline constexpr AsmRegisterXmm xmm4{Register::XMM4};
/// `XMM5` register
inline constexpr AsmRegisterXmm xmm5{Register::XMM5};
/// `XMM6` register
inline constexpr AsmRegisterXmm xmm6{Register::XMM6};
/// `XMM7` register
inline constexpr AsmRegisterXmm xmm7{Register::XMM7};
/// `XMM8` register
inline constexpr AsmRegisterXmm xmm8{Register::XMM8};
/// `XMM9` register
inline constexpr AsmRegisterXmm xmm9{Register::XMM9};
/// `XMM10` register
inline constexpr AsmRegisterXmm xmm10{Register::XMM10};
/// `XMM11` register
inline constexpr AsmRegisterXmm xmm11{Register::XMM11};
/// `XMM12` register
inline constexpr AsmRegisterXmm xmm12{Register::XMM12};
/// `XMM13` register
inline constexpr AsmRegisterXmm xmm13{Register::XMM13};
/// `XMM14` register
inline constexpr AsmRegisterXmm xmm14{Register::XMM14};
/// `XMM15` register
inline constexpr AsmRegisterXmm xmm15{Register::XMM15};
/// `XMM16` register
inline constexpr AsmRegisterXmm xmm16{Register::XMM16};
/// `XMM17` register
inline constexpr AsmRegisterXmm xmm17{Register::XMM17};
/// `XMM18` register
inline constexpr AsmRegisterXmm xmm18{Register::XMM18};
/// `XMM19` register
inline constexpr AsmRegisterXmm xmm19{Register::XMM19};
/// `XMM20` register
inline constexpr AsmRegisterXmm xmm20{Register::XMM20};
/// `XMM21` register
inline constexpr AsmRegisterXmm xmm21{Register::XMM21};
/// `XMM22` register
inline constexpr AsmRegisterXmm xmm22{Register::XMM22};
/// `XMM23` register
inline constexpr AsmRegisterXmm xmm23{Register::XMM23};
/// `XMM24` register
inline constexpr AsmRegisterXmm xmm24{Register::XMM24};
/// `XMM25` register
inline constexpr AsmRegisterXmm xmm25{Register::XMM25};
/// `XMM26` register
inline constexpr AsmRegisterXmm xmm26{Register::XMM26};
/// `XMM27` register
inline constexpr AsmRegisterXmm xmm27{Register::XMM27};
/// `XMM28` register
inline constexpr AsmRegisterXmm xmm28{Register::XMM28};
/// `XMM29` register
inline constexpr AsmRegisterXmm xmm29{Register::XMM29};
/// `XMM30` register
inline constexpr AsmRegisterXmm xmm30{Register::XMM30};
/// `XMM31` register
inline constexpr AsmRegisterXmm xmm31{Register::XMM31};

/// Gets an `XMM` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterXmm> get_xmm(Register register_) noexcept {
	if (register_ext::is_xmm(register_))
		return AsmRegisterXmm(register_);
	return std::nullopt;
}

} // namespace xmm

/// All 256-bit vector registers (YMM).
namespace ymm {

/// `YMM0` register
inline constexpr AsmRegisterYmm ymm0{Register::YMM0};
/// `YMM1` register
inline constexpr AsmRegisterYmm ymm1{Register::YMM1};
/// `YMM2` register
inline constexpr AsmRegisterYmm ymm2{Register::YMM2};
/// `YMM3` register
inline constexpr AsmRegisterYmm ymm3{Register::YMM3};
/// `YMM4` register
inline constexpr AsmRegisterYmm ymm4{Register::YMM4};
/// `YMM5` register
inline constexpr AsmRegisterYmm ymm5{Register::YMM5};
/// `YMM6` register
inline constexpr AsmRegisterYmm ymm6{Register::YMM6};
/// `YMM7` register
inline constexpr AsmRegisterYmm ymm7{Register::YMM7};
/// `YMM8` register
inline constexpr AsmRegisterYmm ymm8{Register::YMM8};
/// `YMM9` register
inline constexpr AsmRegisterYmm ymm9{Register::YMM9};
/// `YMM10` register
inline constexpr AsmRegisterYmm ymm10{Register::YMM10};
/// `YMM11` register
inline constexpr AsmRegisterYmm ymm11{Register::YMM11};
/// `YMM12` register
inline constexpr AsmRegisterYmm ymm12{Register::YMM12};
/// `YMM13` register
inline constexpr AsmRegisterYmm ymm13{Register::YMM13};
/// `YMM14` register
inline constexpr AsmRegisterYmm ymm14{Register::YMM14};
/// `YMM15` register
inline constexpr AsmRegisterYmm ymm15{Register::YMM15};
/// `YMM16` register
inline constexpr AsmRegisterYmm ymm16{Register::YMM16};
/// `YMM17` register
inline constexpr AsmRegisterYmm ymm17{Register::YMM17};
/// `YMM18` register
inline constexpr AsmRegisterYmm ymm18{Register::YMM18};
/// `YMM19` register
inline constexpr AsmRegisterYmm ymm19{Register::YMM19};
/// `YMM20` register
inline constexpr AsmRegisterYmm ymm20{Register::YMM20};
/// `YMM21` register
inline constexpr AsmRegisterYmm ymm21{Register::YMM21};
/// `YMM22` register
inline constexpr AsmRegisterYmm ymm22{Register::YMM22};
/// `YMM23` register
inline constexpr AsmRegisterYmm ymm23{Register::YMM23};
/// `YMM24` register
inline constexpr AsmRegisterYmm ymm24{Register::YMM24};
/// `YMM25` register
inline constexpr AsmRegisterYmm ymm25{Register::YMM25};
/// `YMM26` register
inline constexpr AsmRegisterYmm ymm26{Register::YMM26};
/// `YMM27` register
inline constexpr AsmRegisterYmm ymm27{Register::YMM27};
/// `YMM28` register
inline constexpr AsmRegisterYmm ymm28{Register::YMM28};
/// `YMM29` register
inline constexpr AsmRegisterYmm ymm29{Register::YMM29};
/// `YMM30` register
inline constexpr AsmRegisterYmm ymm30{Register::YMM30};
/// `YMM31` register
inline constexpr AsmRegisterYmm ymm31{Register::YMM31};

/// Gets a `YMM` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterYmm> get_ymm(Register register_) noexcept {
	if (register_ext::is_ymm(register_))
		return AsmRegisterYmm(register_);
	return std::nullopt;
}

} // namespace ymm

/// All 512-bit vector registers (ZMM).
namespace zmm {

/// `ZMM0` register
inline constexpr AsmRegisterZmm zmm0{Register::ZMM0};
/// `ZMM1` register
inline constexpr AsmRegisterZmm zmm1{Register::ZMM1};
/// `ZMM2` register
inline constexpr AsmRegisterZmm zmm2{Register::ZMM2};
/// `ZMM3` register
inline constexpr AsmRegisterZmm zmm3{Register::ZMM3};
/// `ZMM4` register
inline constexpr AsmRegisterZmm zmm4{Register::ZMM4};
/// `ZMM5` register
inline constexpr AsmRegisterZmm zmm5{Register::ZMM5};
/// `ZMM6` register
inline constexpr AsmRegisterZmm zmm6{Register::ZMM6};
/// `ZMM7` register
inline constexpr AsmRegisterZmm zmm7{Register::ZMM7};
/// `ZMM8` register
inline constexpr AsmRegisterZmm zmm8{Register::ZMM8};
/// `ZMM9` register
inline constexpr AsmRegisterZmm zmm9{Register::ZMM9};
/// `ZMM10` register
inline constexpr AsmRegisterZmm zmm10{Register::ZMM10};
/// `ZMM11` register
inline constexpr AsmRegisterZmm zmm11{Register::ZMM11};
/// `ZMM12` register
inline constexpr AsmRegisterZmm zmm12{Register::ZMM12};
/// `ZMM13` register
inline constexpr AsmRegisterZmm zmm13{Register::ZMM13};
/// `ZMM14` register
inline constexpr AsmRegisterZmm zmm14{Register::ZMM14};
/// `ZMM15` register
inline constexpr AsmRegisterZmm zmm15{Register::ZMM15};
/// `ZMM16` register
inline constexpr AsmRegisterZmm zmm16{Register::ZMM16};
/// `ZMM17` register
inline constexpr AsmRegisterZmm zmm17{Register::ZMM17};
/// `ZMM18` register
inline constexpr AsmRegisterZmm zmm18{Register::ZMM18};
/// `ZMM19` register
inline constexpr AsmRegisterZmm zmm19{Register::ZMM19};
/// `ZMM20` register
inline constexpr AsmRegisterZmm zmm20{Register::ZMM20};
/// `ZMM21` register
inline constexpr AsmRegisterZmm zmm21{Register::ZMM21};
/// `ZMM22` register
inline constexpr AsmRegisterZmm zmm22{Register::ZMM22};
/// `ZMM23` register
inline constexpr AsmRegisterZmm zmm23{Register::ZMM23};
/// `ZMM24` register
inline constexpr AsmRegisterZmm zmm24{Register::ZMM24};
/// `ZMM25` register
inline constexpr AsmRegisterZmm zmm25{Register::ZMM25};
/// `ZMM26` register
inline constexpr AsmRegisterZmm zmm26{Register::ZMM26};
/// `ZMM27` register
inline constexpr AsmRegisterZmm zmm27{Register::ZMM27};
/// `ZMM28` register
inline constexpr AsmRegisterZmm zmm28{Register::ZMM28};
/// `ZMM29` register
inline constexpr AsmRegisterZmm zmm29{Register::ZMM29};
/// `ZMM30` register
inline constexpr AsmRegisterZmm zmm30{Register::ZMM30};
/// `ZMM31` register
inline constexpr AsmRegisterZmm zmm31{Register::ZMM31};

/// Gets a `ZMM` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterZmm> get_zmm(Register register_) noexcept {
	if (register_ext::is_zmm(register_))
		return AsmRegisterZmm(register_);
	return std::nullopt;
}

} // namespace zmm

/// All tile registers.
namespace tmm {

/// `TMM0` register
inline constexpr AsmRegisterTmm tmm0{Register::TMM0};
/// `TMM1` register
inline constexpr AsmRegisterTmm tmm1{Register::TMM1};
/// `TMM2` register
inline constexpr AsmRegisterTmm tmm2{Register::TMM2};
/// `TMM3` register
inline constexpr AsmRegisterTmm tmm3{Register::TMM3};
/// `TMM4` register
inline constexpr AsmRegisterTmm tmm4{Register::TMM4};
/// `TMM5` register
inline constexpr AsmRegisterTmm tmm5{Register::TMM5};
/// `TMM6` register
inline constexpr AsmRegisterTmm tmm6{Register::TMM6};
/// `TMM7` register
inline constexpr AsmRegisterTmm tmm7{Register::TMM7};

/// Gets a `TMM` register or `std::nullopt` if input is invalid.
///
/// @param register_ Register
[[nodiscard]] constexpr std::optional<AsmRegisterTmm> get_tmm(Register register_) noexcept {
	if (register_ext::is_tmm(register_))
		return AsmRegisterTmm(register_);
	return std::nullopt;
}

} // namespace tmm

using bnd::bnd0;
using bnd::bnd1;
using bnd::bnd2;
using bnd::bnd3;
using bnd::get_bnd;
using cr::cr0;
using cr::cr1;
using cr::cr2;
using cr::cr3;
using cr::cr4;
using cr::cr5;
using cr::cr6;
using cr::cr7;
using cr::cr8;
using cr::cr9;
using cr::cr10;
using cr::cr11;
using cr::cr12;
using cr::cr13;
using cr::cr14;
using cr::cr15;
using cr::get_cr;
using dr::dr0;
using dr::dr1;
using dr::dr2;
using dr::dr3;
using dr::dr4;
using dr::dr5;
using dr::dr6;
using dr::dr7;
using dr::dr8;
using dr::dr9;
using dr::dr10;
using dr::dr11;
using dr::dr12;
using dr::dr13;
using dr::dr14;
using dr::dr15;
using dr::get_dr;
using gpr16::ax;
using gpr16::cx;
using gpr16::dx;
using gpr16::bx;
using gpr16::sp;
using gpr16::bp;
using gpr16::si;
using gpr16::di;
using gpr16::r8w;
using gpr16::r9w;
using gpr16::r10w;
using gpr16::r11w;
using gpr16::r12w;
using gpr16::r13w;
using gpr16::r14w;
using gpr16::r15w;
using gpr16::get_gpr16;
using gpr32::eax;
using gpr32::ecx;
using gpr32::edx;
using gpr32::ebx;
using gpr32::esp;
using gpr32::ebp;
using gpr32::esi;
using gpr32::edi;
using gpr32::r8d;
using gpr32::r9d;
using gpr32::r10d;
using gpr32::r11d;
using gpr32::r12d;
using gpr32::r13d;
using gpr32::r14d;
using gpr32::r15d;
using gpr32::get_gpr32;
using gpr64::rax;
using gpr64::rcx;
using gpr64::rdx;
using gpr64::rbx;
using gpr64::rsp;
using gpr64::rbp;
using gpr64::rsi;
using gpr64::rdi;
using gpr64::r8;
using gpr64::r9;
using gpr64::r10;
using gpr64::r11;
using gpr64::r12;
using gpr64::r13;
using gpr64::r14;
using gpr64::r15;
using gpr64::get_gpr64;
using gpr8::al;
using gpr8::cl;
using gpr8::dl;
using gpr8::bl;
using gpr8::ah;
using gpr8::ch;
using gpr8::dh;
using gpr8::bh;
using gpr8::spl;
using gpr8::bpl;
using gpr8::sil;
using gpr8::dil;
using gpr8::r8b;
using gpr8::r9b;
using gpr8::r10b;
using gpr8::r11b;
using gpr8::r12b;
using gpr8::r13b;
using gpr8::r14b;
using gpr8::r15b;
using gpr8::get_gpr8;
using k::k0;
using k::k1;
using k::k2;
using k::k3;
using k::k4;
using k::k5;
using k::k6;
using k::k7;
using k::get_k;
using mm::mm0;
using mm::mm1;
using mm::mm2;
using mm::mm3;
using mm::mm4;
using mm::mm5;
using mm::mm6;
using mm::mm7;
using mm::get_mm;
using segment::es;
using segment::cs;
using segment::ss;
using segment::ds;
using segment::fs;
using segment::gs;
using segment::get_segment;
using st::st0;
using st::st1;
using st::st2;
using st::st3;
using st::st4;
using st::st5;
using st::st6;
using st::st7;
using st::get_st;
using tmm::tmm0;
using tmm::tmm1;
using tmm::tmm2;
using tmm::tmm3;
using tmm::tmm4;
using tmm::tmm5;
using tmm::tmm6;
using tmm::tmm7;
using tmm::get_tmm;
using tr::tr0;
using tr::tr1;
using tr::tr2;
using tr::tr3;
using tr::tr4;
using tr::tr5;
using tr::tr6;
using tr::tr7;
using tr::get_tr;
using xmm::xmm0;
using xmm::xmm1;
using xmm::xmm2;
using xmm::xmm3;
using xmm::xmm4;
using xmm::xmm5;
using xmm::xmm6;
using xmm::xmm7;
using xmm::xmm8;
using xmm::xmm9;
using xmm::xmm10;
using xmm::xmm11;
using xmm::xmm12;
using xmm::xmm13;
using xmm::xmm14;
using xmm::xmm15;
using xmm::xmm16;
using xmm::xmm17;
using xmm::xmm18;
using xmm::xmm19;
using xmm::xmm20;
using xmm::xmm21;
using xmm::xmm22;
using xmm::xmm23;
using xmm::xmm24;
using xmm::xmm25;
using xmm::xmm26;
using xmm::xmm27;
using xmm::xmm28;
using xmm::xmm29;
using xmm::xmm30;
using xmm::xmm31;
using xmm::get_xmm;
using ymm::ymm0;
using ymm::ymm1;
using ymm::ymm2;
using ymm::ymm3;
using ymm::ymm4;
using ymm::ymm5;
using ymm::ymm6;
using ymm::ymm7;
using ymm::ymm8;
using ymm::ymm9;
using ymm::ymm10;
using ymm::ymm11;
using ymm::ymm12;
using ymm::ymm13;
using ymm::ymm14;
using ymm::ymm15;
using ymm::ymm16;
using ymm::ymm17;
using ymm::ymm18;
using ymm::ymm19;
using ymm::ymm20;
using ymm::ymm21;
using ymm::ymm22;
using ymm::ymm23;
using ymm::ymm24;
using ymm::ymm25;
using ymm::ymm26;
using ymm::ymm27;
using ymm::ymm28;
using ymm::ymm29;
using ymm::ymm30;
using ymm::ymm31;
using ymm::get_ymm;
using zmm::zmm0;
using zmm::zmm1;
using zmm::zmm2;
using zmm::zmm3;
using zmm::zmm4;
using zmm::zmm5;
using zmm::zmm6;
using zmm::zmm7;
using zmm::zmm8;
using zmm::zmm9;
using zmm::zmm10;
using zmm::zmm11;
using zmm::zmm12;
using zmm::zmm13;
using zmm::zmm14;
using zmm::zmm15;
using zmm::zmm16;
using zmm::zmm17;
using zmm::zmm18;
using zmm::zmm19;
using zmm::zmm20;
using zmm::zmm21;
using zmm::zmm22;
using zmm::zmm23;
using zmm::zmm24;
using zmm::zmm25;
using zmm::zmm26;
using zmm::zmm27;
using zmm::zmm28;
using zmm::zmm29;
using zmm::zmm30;
using zmm::zmm31;
using zmm::get_zmm;

} // namespace iced_x86::code_asm::registers

namespace iced_x86::code_asm {

using registers::bnd0;
using registers::bnd1;
using registers::bnd2;
using registers::bnd3;
using registers::get_bnd;
using registers::cr0;
using registers::cr1;
using registers::cr2;
using registers::cr3;
using registers::cr4;
using registers::cr5;
using registers::cr6;
using registers::cr7;
using registers::cr8;
using registers::cr9;
using registers::cr10;
using registers::cr11;
using registers::cr12;
using registers::cr13;
using registers::cr14;
using registers::cr15;
using registers::get_cr;
using registers::dr0;
using registers::dr1;
using registers::dr2;
using registers::dr3;
using registers::dr4;
using registers::dr5;
using registers::dr6;
using registers::dr7;
using registers::dr8;
using registers::dr9;
using registers::dr10;
using registers::dr11;
using registers::dr12;
using registers::dr13;
using registers::dr14;
using registers::dr15;
using registers::get_dr;
using registers::ax;
using registers::cx;
using registers::dx;
using registers::bx;
using registers::sp;
using registers::bp;
using registers::si;
using registers::di;
using registers::r8w;
using registers::r9w;
using registers::r10w;
using registers::r11w;
using registers::r12w;
using registers::r13w;
using registers::r14w;
using registers::r15w;
using registers::get_gpr16;
using registers::eax;
using registers::ecx;
using registers::edx;
using registers::ebx;
using registers::esp;
using registers::ebp;
using registers::esi;
using registers::edi;
using registers::r8d;
using registers::r9d;
using registers::r10d;
using registers::r11d;
using registers::r12d;
using registers::r13d;
using registers::r14d;
using registers::r15d;
using registers::get_gpr32;
using registers::rax;
using registers::rcx;
using registers::rdx;
using registers::rbx;
using registers::rsp;
using registers::rbp;
using registers::rsi;
using registers::rdi;
using registers::r8;
using registers::r9;
using registers::r10;
using registers::r11;
using registers::r12;
using registers::r13;
using registers::r14;
using registers::r15;
using registers::get_gpr64;
using registers::al;
using registers::cl;
using registers::dl;
using registers::bl;
using registers::ah;
using registers::ch;
using registers::dh;
using registers::bh;
using registers::spl;
using registers::bpl;
using registers::sil;
using registers::dil;
using registers::r8b;
using registers::r9b;
using registers::r10b;
using registers::r11b;
using registers::r12b;
using registers::r13b;
using registers::r14b;
using registers::r15b;
using registers::get_gpr8;
using registers::k0;
using registers::k1;
using registers::k2;
using registers::k3;
using registers::k4;
using registers::k5;
using registers::k6;
using registers::k7;
using registers::get_k;
using registers::mm0;
using registers::mm1;
using registers::mm2;
using registers::mm3;
using registers::mm4;
using registers::mm5;
using registers::mm6;
using registers::mm7;
using registers::get_mm;
using registers::es;
using registers::cs;
using registers::ss;
using registers::ds;
using registers::fs;
using registers::gs;
using registers::get_segment;
using registers::st0;
using registers::st1;
using registers::st2;
using registers::st3;
using registers::st4;
using registers::st5;
using registers::st6;
using registers::st7;
using registers::get_st;
using registers::tmm0;
using registers::tmm1;
using registers::tmm2;
using registers::tmm3;
using registers::tmm4;
using registers::tmm5;
using registers::tmm6;
using registers::tmm7;
using registers::get_tmm;
using registers::tr0;
using registers::tr1;
using registers::tr2;
using registers::tr3;
using registers::tr4;
using registers::tr5;
using registers::tr6;
using registers::tr7;
using registers::get_tr;
using registers::xmm0;
using registers::xmm1;
using registers::xmm2;
using registers::xmm3;
using registers::xmm4;
using registers::xmm5;
using registers::xmm6;
using registers::xmm7;
using registers::xmm8;
using registers::xmm9;
using registers::xmm10;
using registers::xmm11;
using registers::xmm12;
using registers::xmm13;
using registers::xmm14;
using registers::xmm15;
using registers::xmm16;
using registers::xmm17;
using registers::xmm18;
using registers::xmm19;
using registers::xmm20;
using registers::xmm21;
using registers::xmm22;
using registers::xmm23;
using registers::xmm24;
using registers::xmm25;
using registers::xmm26;
using registers::xmm27;
using registers::xmm28;
using registers::xmm29;
using registers::xmm30;
using registers::xmm31;
using registers::get_xmm;
using registers::ymm0;
using registers::ymm1;
using registers::ymm2;
using registers::ymm3;
using registers::ymm4;
using registers::ymm5;
using registers::ymm6;
using registers::ymm7;
using registers::ymm8;
using registers::ymm9;
using registers::ymm10;
using registers::ymm11;
using registers::ymm12;
using registers::ymm13;
using registers::ymm14;
using registers::ymm15;
using registers::ymm16;
using registers::ymm17;
using registers::ymm18;
using registers::ymm19;
using registers::ymm20;
using registers::ymm21;
using registers::ymm22;
using registers::ymm23;
using registers::ymm24;
using registers::ymm25;
using registers::ymm26;
using registers::ymm27;
using registers::ymm28;
using registers::ymm29;
using registers::ymm30;
using registers::ymm31;
using registers::get_ymm;
using registers::zmm0;
using registers::zmm1;
using registers::zmm2;
using registers::zmm3;
using registers::zmm4;
using registers::zmm5;
using registers::zmm6;
using registers::zmm7;
using registers::zmm8;
using registers::zmm9;
using registers::zmm10;
using registers::zmm11;
using registers::zmm12;
using registers::zmm13;
using registers::zmm14;
using registers::zmm15;
using registers::zmm16;
using registers::zmm17;
using registers::zmm18;
using registers::zmm19;
using registers::zmm20;
using registers::zmm21;
using registers::zmm22;
using registers::zmm23;
using registers::zmm24;
using registers::zmm25;
using registers::zmm26;
using registers::zmm27;
using registers::zmm28;
using registers::zmm29;
using registers::zmm30;
using registers::zmm31;
using registers::get_zmm;

} // namespace iced_x86::code_asm
