// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::nasm {

enum class BranchSizeInfo : std::uint8_t {
	None = 0,
	Near = 1,
	NearWord = 2,
	NearDword = 3,
	Word = 4,
	Dword = 5,
	Short = 6,
};

} // namespace iced_x86::internal::nasm
