// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::nasm {

enum class FarMemorySizeInfo : std::uint8_t {
	None = 0,
	Word = 1,
	Dword = 2,
};

} // namespace iced_x86::internal::nasm
