// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::nasm {

struct InstrOpInfoFlags {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t MEM_SIZE_NOTHING = 0x0000'0001;
	static constexpr std::uint32_t SHOW_NO_MEM_SIZE_FORCE_SIZE = 0x0000'0002;
	static constexpr std::uint32_t SHOW_MIN_MEM_SIZE_FORCE_SIZE = 0x0000'0004;
	static constexpr std::uint32_t SIZE_OVERRIDE_MASK = 0x0000'0003;
	static constexpr std::uint32_t OP_SIZE_SHIFT = 0x0000'0003;
	static constexpr std::uint32_t OP_SIZE16 = 0x0000'0008;
	static constexpr std::uint32_t OP_SIZE32 = 0x0000'0010;
	static constexpr std::uint32_t OP_SIZE64 = 0x0000'0018;
	static constexpr std::uint32_t ADDR_SIZE_SHIFT = 0x0000'0005;
	static constexpr std::uint32_t ADDR_SIZE16 = 0x0000'0020;
	static constexpr std::uint32_t ADDR_SIZE32 = 0x0000'0040;
	static constexpr std::uint32_t ADDR_SIZE64 = 0x0000'0060;
	static constexpr std::uint32_t BRANCH_SIZE_INFO_SHIFT = 0x0000'0007;
	static constexpr std::uint32_t BRANCH_SIZE_INFO_MASK = 0x0000'0007;
	static constexpr std::uint32_t BRANCH_SIZE_INFO_SHORT = 0x0000'0300;
	static constexpr std::uint32_t SIGN_EXTEND_INFO_SHIFT = 0x0000'000A;
	static constexpr std::uint32_t SIGN_EXTEND_INFO_MASK = 0x0000'0007;
	static constexpr std::uint32_t MEMORY_SIZE_INFO_SHIFT = 0x0000'000D;
	static constexpr std::uint32_t MEMORY_SIZE_INFO_MASK = 0x0000'0003;
	static constexpr std::uint32_t FAR_MEMORY_SIZE_INFO_SHIFT = 0x0000'000F;
	static constexpr std::uint32_t FAR_MEMORY_SIZE_INFO_MASK = 0x0000'0003;
	static constexpr std::uint32_t REGISTER_TO = 0x0002'0000;
	static constexpr std::uint32_t BND_PREFIX = 0x0004'0000;
	static constexpr std::uint32_t MNEMONIC_IS_DIRECTIVE = 0x0008'0000;
	static constexpr std::uint32_t JCC_NOT_TAKEN = 0x0010'0000;
	static constexpr std::uint32_t JCC_TAKEN = 0x0020'0000;
	static constexpr std::uint32_t MEMORY_SIZE_BITS = 0x0000'0008;
	static constexpr std::uint32_t MEMORY_SIZE_SHIFT = 0x0000'0016;
	static constexpr std::uint32_t MEMORY_SIZE_MASK = 0x0000'00FF;
};

} // namespace iced_x86::internal::nasm
