// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::nasm {

enum class SignExtendInfo : std::uint8_t {
	None = 0,
	Sex1to2 = 1,
	Sex1to4 = 2,
	Sex1to8 = 3,
	Sex4to8 = 4,
	Sex2 = 5,
	Sex4 = 6,
};

} // namespace iced_x86::internal::nasm
