// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct InfoFlags1 {
	static constexpr std::uint32_t OP_INFO0_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t OP_INFO0_MASK = 0x0000'000F;
	static constexpr std::uint32_t OP_INFO1_SHIFT = 0x0000'0004;
	static constexpr std::uint32_t OP_INFO1_MASK = 0x0000'0007;
	static constexpr std::uint32_t OP_INFO2_SHIFT = 0x0000'0007;
	static constexpr std::uint32_t OP_INFO2_MASK = 0x0000'0003;
	static constexpr std::uint32_t OP_INFO3_SHIFT = 0x0000'0009;
	static constexpr std::uint32_t OP_INFO3_MASK = 0x0000'0001;
	static constexpr std::uint32_t OP_INFO4_SHIFT = 0x0000'000A;
	static constexpr std::uint32_t OP_INFO4_MASK = 0x0000'0001;
	static constexpr std::uint32_t RFLAGS_INFO_SHIFT = 0x0000'000D;
	static constexpr std::uint32_t RFLAGS_INFO_MASK = 0x0000'007F;
	static constexpr std::uint32_t IMPLIED_ACCESS_SHIFT = 0x0000'0014;
	static constexpr std::uint32_t IMPLIED_ACCESS_MASK = 0x0000'00FF;
	static constexpr std::uint32_t IGNORES_INDEX_VA = 0x2000'0000;
	static constexpr std::uint32_t OP_MASK_READ_WRITE = 0x4000'0000;
	static constexpr std::uint32_t IGNORES_SEGMENT = 0x8000'0000;
};

} // namespace iced_x86::internal
