// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct InfoFlags2 {
	static constexpr std::uint32_t ENCODING_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t ENCODING_MASK = 0x0000'0007;
	static constexpr std::uint32_t SAVE_RESTORE = 0x0002'0000;
	static constexpr std::uint32_t STACK_INSTRUCTION = 0x0004'0000;
	static constexpr std::uint32_t PRIVILEGED = 0x0008'0000;
	static constexpr std::uint32_t FLOW_CONTROL_SHIFT = 0x0000'0014;
	static constexpr std::uint32_t FLOW_CONTROL_MASK = 0x0000'000F;
	static constexpr std::uint32_t CPUID_FEATURE_INTERNAL_SHIFT = 0x0000'0018;
	static constexpr std::uint32_t CPUID_FEATURE_INTERNAL_MASK = 0x0000'00FF;
};

} // namespace iced_x86::internal
