// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>

namespace iced_x86::internal {

struct InstrInfoConstants {
	static constexpr std::size_t OP_INFO0_COUNT = 13;
	static constexpr std::size_t OP_INFO1_COUNT = 7;
	static constexpr std::size_t OP_INFO2_COUNT = 3;
	static constexpr std::size_t OP_INFO3_COUNT = 2;
	static constexpr std::size_t OP_INFO4_COUNT = 2;
	static constexpr std::size_t RFLAGS_INFO_COUNT = 79;
	static constexpr std::size_t DEFAULT_USED_REGISTER_COLL_CAPACITY = 10;
	static constexpr std::size_t DEFAULT_USED_MEMORY_COLL_CAPACITY = 8;
};

} // namespace iced_x86::internal
