// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include "iced_x86/op_access.hpp"

namespace iced_x86::internal {

inline constexpr OpAccess OP_ACCESS_1[7] = {
	OpAccess::None,
	OpAccess::CondRead,
	OpAccess::NoMemAccess,
	OpAccess::Read,
	OpAccess::Read,
	OpAccess::ReadWrite,
	OpAccess::Write,
};

inline constexpr OpAccess OP_ACCESS_2[3] = {
	OpAccess::None,
	OpAccess::Read,
	OpAccess::ReadWrite,
};

} // namespace iced_x86::internal
