// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class OpInfo2 : std::uint8_t {
	None = 0,
	Read = 1,
	ReadWrite = 2,
};

} // namespace iced_x86::internal
