// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class OpInfo1 : std::uint8_t {
	None = 0,
	CondRead = 1,
	NoMemAccess = 2,
	Read = 3,
	ReadP3 = 4,
	ReadWrite = 5,
	Write = 6,
};

} // namespace iced_x86::internal
