// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class OpInfo0 : std::uint8_t {
	None = 0,
	CondWrite = 1,
	CondWrite32_ReadWrite64 = 2,
	NoMemAccess = 3,
	Read = 4,
	ReadCondWrite = 5,
	ReadWrite = 6,
	Write = 7,
	WriteVmm = 8,
	ReadWriteVmm = 9,
	WriteForce = 10,
	WriteMem_ReadWriteReg = 11,
	WriteForceP1 = 12,
};

} // namespace iced_x86::internal
