// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::intel {

enum class BranchSizeInfo : std::uint8_t {
	None = 0,
	Short = 1,
};

} // namespace iced_x86::internal::intel
