// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::intel {

enum class SizeOverride : std::uint8_t {
	None = 0,
	Size16 = 1,
	Size32 = 2,
	Size64 = 3,
};

} // namespace iced_x86::internal::intel
