// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#include "internal/decoder/data_mvex.hpp"
#include "internal/decoder/mvex_ctors.hpp"

namespace iced_x86::internal::decoder_data_mvex {

// clang-format off
constexpr auto H0 = mvex_ctors::M(Code::MVEX_Vprefetchnta_m);
constexpr auto H1 = mvex_ctors::MandatoryPrefix2(&H0, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H2 = mvex_ctors::M(Code::MVEX_Vprefetch0_m);
constexpr auto H3 = mvex_ctors::MandatoryPrefix2(&H2, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H4 = mvex_ctors::M(Code::MVEX_Vprefetch1_m);
constexpr auto H5 = mvex_ctors::MandatoryPrefix2(&H4, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H6 = mvex_ctors::M(Code::MVEX_Vprefetch2_m);
constexpr auto H7 = mvex_ctors::MandatoryPrefix2(&H6, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H8 = mvex_ctors::M(Code::MVEX_Vprefetchenta_m);
constexpr auto H9 = mvex_ctors::MandatoryPrefix2(&H8, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H10 = mvex_ctors::M(Code::MVEX_Vprefetche0_m);
constexpr auto H11 = mvex_ctors::MandatoryPrefix2(&H10, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H12 = mvex_ctors::M(Code::MVEX_Vprefetche1_m);
constexpr auto H13 = mvex_ctors::MandatoryPrefix2(&H12, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H14 = mvex_ctors::M(Code::MVEX_Vprefetche2_m);
constexpr auto H15 = mvex_ctors::MandatoryPrefix2(&H14, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H16 = mvex_ctors::HWIb(Code::MVEX_Vpsrld_zmm_k1_zmmmt_imm8);
constexpr auto H17 = mvex_ctors::W(&H16, &INVALID_HANDLER);
constexpr auto H18 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H17, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H19 = mvex_ctors::HWIb(Code::MVEX_Vpsrad_zmm_k1_zmmmt_imm8);
constexpr auto H20 = mvex_ctors::W(&H19, &INVALID_HANDLER);
constexpr auto H21 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H20, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H22 = mvex_ctors::HWIb(Code::MVEX_Vpslld_zmm_k1_zmmmt_imm8);
constexpr auto H23 = mvex_ctors::W(&H22, &INVALID_HANDLER);
constexpr auto H24 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H23, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H25 = mvex_ctors::M(Code::MVEX_Clevict1_m);
constexpr auto H26 = mvex_ctors::M(Code::MVEX_Clevict0_m);
constexpr auto H27 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &INVALID_HANDLER, &H25, &H26);
constexpr auto H28 = mvex_ctors::VSIB(Code::MVEX_Vgatherpf0hintdps_mvt_k1);
constexpr auto H29 = mvex_ctors::RM(&INVALID_HANDLER, &H28);
constexpr auto H30 = mvex_ctors::VSIB(Code::MVEX_Vgatherpf0hintdpd_mvt_k1);
constexpr auto H31 = mvex_ctors::RM(&INVALID_HANDLER, &H30);
constexpr auto H32 = mvex_ctors::W(&H29, &H31);
constexpr auto H33 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H32, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H34 = mvex_ctors::VSIB(Code::MVEX_Vgatherpf0dps_mvt_k1);
constexpr auto H35 = mvex_ctors::RM(&INVALID_HANDLER, &H34);
constexpr auto H36 = mvex_ctors::W(&H35, &INVALID_HANDLER);
constexpr auto H37 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H36, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H38 = mvex_ctors::VSIB(Code::MVEX_Vgatherpf1dps_mvt_k1);
constexpr auto H39 = mvex_ctors::RM(&INVALID_HANDLER, &H38);
constexpr auto H40 = mvex_ctors::W(&H39, &INVALID_HANDLER);
constexpr auto H41 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H40, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H42 = mvex_ctors::VSIB(Code::MVEX_Vscatterpf0hintdps_mvt_k1);
constexpr auto H43 = mvex_ctors::RM(&INVALID_HANDLER, &H42);
constexpr auto H44 = mvex_ctors::VSIB(Code::MVEX_Vscatterpf0hintdpd_mvt_k1);
constexpr auto H45 = mvex_ctors::RM(&INVALID_HANDLER, &H44);
constexpr auto H46 = mvex_ctors::W(&H43, &H45);
constexpr auto H47 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H46, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H48 = mvex_ctors::VSIB(Code::MVEX_Vscatterpf0dps_mvt_k1);
constexpr auto H49 = mvex_ctors::RM(&INVALID_HANDLER, &H48);
constexpr auto H50 = mvex_ctors::W(&H49, &INVALID_HANDLER);
constexpr auto H51 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H50, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H52 = mvex_ctors::VSIB(Code::MVEX_Vscatterpf1dps_mvt_k1);
constexpr auto H53 = mvex_ctors::RM(&INVALID_HANDLER, &H52);
constexpr auto H54 = mvex_ctors::W(&H53, &INVALID_HANDLER);
constexpr auto H55 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H54, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H56 = mvex_ctors::VW(Code::MVEX_Vbroadcastss_zmm_k1_mt);
constexpr auto H57 = mvex_ctors::RM(&INVALID_HANDLER, &H56);
constexpr auto H58 = mvex_ctors::W(&H57, &INVALID_HANDLER);
constexpr auto H59 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H58, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H60 = mvex_ctors::VW(Code::MVEX_Vbroadcastsd_zmm_k1_mt);
constexpr auto H61 = mvex_ctors::RM(&INVALID_HANDLER, &H60);
constexpr auto H62 = mvex_ctors::W(&INVALID_HANDLER, &H61);
constexpr auto H63 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H62, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H64 = mvex_ctors::VW(Code::MVEX_Vbroadcastf32x4_zmm_k1_mt);
constexpr auto H65 = mvex_ctors::RM(&INVALID_HANDLER, &H64);
constexpr auto H66 = mvex_ctors::W(&H65, &INVALID_HANDLER);
constexpr auto H67 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H66, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H68 = mvex_ctors::VW(Code::MVEX_Vbroadcastf64x4_zmm_k1_mt);
constexpr auto H69 = mvex_ctors::RM(&INVALID_HANDLER, &H68);
constexpr auto H70 = mvex_ctors::W(&INVALID_HANDLER, &H69);
constexpr auto H71 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H70, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H72 = mvex_ctors::KHW(Code::MVEX_Vptestmd_kr_k1_zmm_zmmmt);
constexpr auto H73 = mvex_ctors::W(&H72, &INVALID_HANDLER);
constexpr auto H74 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H73, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H75 = mvex_ctors::VHW(Code::MVEX_Vpermd_zmm_k1_zmm_zmmmt);
constexpr auto H76 = mvex_ctors::W(&H75, &INVALID_HANDLER);
constexpr auto H77 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H76, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H78 = mvex_ctors::VHW(Code::MVEX_Vpminsd_zmm_k1_zmm_zmmmt);
constexpr auto H79 = mvex_ctors::W(&H78, &INVALID_HANDLER);
constexpr auto H80 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H79, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H81 = mvex_ctors::VHW(Code::MVEX_Vpminud_zmm_k1_zmm_zmmmt);
constexpr auto H82 = mvex_ctors::W(&H81, &INVALID_HANDLER);
constexpr auto H83 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H82, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H84 = mvex_ctors::VHW(Code::MVEX_Vpmaxsd_zmm_k1_zmm_zmmmt);
constexpr auto H85 = mvex_ctors::W(&H84, &INVALID_HANDLER);
constexpr auto H86 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H85, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H87 = mvex_ctors::VHW(Code::MVEX_Vpmaxud_zmm_k1_zmm_zmmmt);
constexpr auto H88 = mvex_ctors::W(&H87, &INVALID_HANDLER);
constexpr auto H89 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H88, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H90 = mvex_ctors::VHW(Code::MVEX_Vpmulld_zmm_k1_zmm_zmmmt);
constexpr auto H91 = mvex_ctors::W(&H90, &INVALID_HANDLER);
constexpr auto H92 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H91, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H93 = mvex_ctors::VW(Code::MVEX_Vgetexpps_zmm_k1_zmmmt);
constexpr auto H94 = mvex_ctors::VW(Code::MVEX_Vgetexppd_zmm_k1_zmmmt);
constexpr auto H95 = mvex_ctors::W(&H93, &H94);
constexpr auto H96 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H95, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H97 = mvex_ctors::VHW(Code::MVEX_Vpsrlvd_zmm_k1_zmm_zmmmt);
constexpr auto H98 = mvex_ctors::W(&H97, &INVALID_HANDLER);
constexpr auto H99 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H98, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H100 = mvex_ctors::VHW(Code::MVEX_Vpsravd_zmm_k1_zmm_zmmmt);
constexpr auto H101 = mvex_ctors::W(&H100, &INVALID_HANDLER);
constexpr auto H102 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H101, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H103 = mvex_ctors::VHW(Code::MVEX_Vpsllvd_zmm_k1_zmm_zmmmt);
constexpr auto H104 = mvex_ctors::W(&H103, &INVALID_HANDLER);
constexpr auto H105 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H104, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H106 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_48);
constexpr auto H107 = mvex_ctors::W(&H106, &INVALID_HANDLER);
constexpr auto H108 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H107, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H109 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_49);
constexpr auto H110 = mvex_ctors::W(&H109, &INVALID_HANDLER);
constexpr auto H111 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H110, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H112 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_4A);
constexpr auto H113 = mvex_ctors::W(&H112, &INVALID_HANDLER);
constexpr auto H114 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H113, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H115 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_4B);
constexpr auto H116 = mvex_ctors::W(&H115, &INVALID_HANDLER);
constexpr auto H117 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H116, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H118 = mvex_ctors::VHW(Code::MVEX_Vaddnps_zmm_k1_zmm_zmmmt);
constexpr auto H119 = mvex_ctors::VHW(Code::MVEX_Vaddnpd_zmm_k1_zmm_zmmmt);
constexpr auto H120 = mvex_ctors::W(&H118, &H119);
constexpr auto H121 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H120, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H122 = mvex_ctors::VHW(Code::MVEX_Vgmaxabsps_zmm_k1_zmm_zmmmt);
constexpr auto H123 = mvex_ctors::W(&H122, &INVALID_HANDLER);
constexpr auto H124 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H123, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H125 = mvex_ctors::VHW(Code::MVEX_Vgminps_zmm_k1_zmm_zmmmt);
constexpr auto H126 = mvex_ctors::VHW(Code::MVEX_Vgminpd_zmm_k1_zmm_zmmmt);
constexpr auto H127 = mvex_ctors::W(&H125, &H126);
constexpr auto H128 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H127, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H129 = mvex_ctors::VHW(Code::MVEX_Vgmaxps_zmm_k1_zmm_zmmmt);
constexpr auto H130 = mvex_ctors::VHW(Code::MVEX_Vgmaxpd_zmm_k1_zmm_zmmmt);
constexpr auto H131 = mvex_ctors::W(&H129, &H130);
constexpr auto H132 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H131, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H133 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_54);
constexpr auto H134 = mvex_ctors::W(&H133, &INVALID_HANDLER);
constexpr auto H135 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H134, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H136 = mvex_ctors::VHW(Code::MVEX_Vfixupnanps_zmm_k1_zmm_zmmmt);
constexpr auto H137 = mvex_ctors::VHW(Code::MVEX_Vfixupnanpd_zmm_k1_zmm_zmmmt);
constexpr auto H138 = mvex_ctors::W(&H136, &H137);
constexpr auto H139 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H138, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H140 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_56);
constexpr auto H141 = mvex_ctors::W(&H140, &INVALID_HANDLER);
constexpr auto H142 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H141, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H143 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_57);
constexpr auto H144 = mvex_ctors::W(&H143, &INVALID_HANDLER);
constexpr auto H145 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H144, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H146 = mvex_ctors::VW(Code::MVEX_Vpbroadcastd_zmm_k1_mt);
constexpr auto H147 = mvex_ctors::RM(&INVALID_HANDLER, &H146);
constexpr auto H148 = mvex_ctors::W(&H147, &INVALID_HANDLER);
constexpr auto H149 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H148, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H150 = mvex_ctors::VW(Code::MVEX_Vpbroadcastq_zmm_k1_mt);
constexpr auto H151 = mvex_ctors::RM(&INVALID_HANDLER, &H150);
constexpr auto H152 = mvex_ctors::W(&INVALID_HANDLER, &H151);
constexpr auto H153 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H152, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H154 = mvex_ctors::VW(Code::MVEX_Vbroadcasti32x4_zmm_k1_mt);
constexpr auto H155 = mvex_ctors::RM(&INVALID_HANDLER, &H154);
constexpr auto H156 = mvex_ctors::W(&H155, &INVALID_HANDLER);
constexpr auto H157 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H156, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H158 = mvex_ctors::VW(Code::MVEX_Vbroadcasti64x4_zmm_k1_mt);
constexpr auto H159 = mvex_ctors::RM(&INVALID_HANDLER, &H158);
constexpr auto H160 = mvex_ctors::W(&INVALID_HANDLER, &H159);
constexpr auto H161 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H160, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H162 = mvex_ctors::VKW(Code::MVEX_Vpadcd_zmm_k1_kr_zmmmt);
constexpr auto H163 = mvex_ctors::W(&H162, &INVALID_HANDLER);
constexpr auto H164 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H163, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H165 = mvex_ctors::VKW(Code::MVEX_Vpaddsetcd_zmm_k1_kr_zmmmt);
constexpr auto H166 = mvex_ctors::W(&H165, &INVALID_HANDLER);
constexpr auto H167 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H166, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H168 = mvex_ctors::VKW(Code::MVEX_Vpsbbd_zmm_k1_kr_zmmmt);
constexpr auto H169 = mvex_ctors::W(&H168, &INVALID_HANDLER);
constexpr auto H170 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H169, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H171 = mvex_ctors::VKW(Code::MVEX_Vpsubsetbd_zmm_k1_kr_zmmmt);
constexpr auto H172 = mvex_ctors::W(&H171, &INVALID_HANDLER);
constexpr auto H173 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H172, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H174 = mvex_ctors::VHW(Code::MVEX_Vpblendmd_zmm_k1_zmm_zmmmt);
constexpr auto H175 = mvex_ctors::VHW(Code::MVEX_Vpblendmq_zmm_k1_zmm_zmmmt);
constexpr auto H176 = mvex_ctors::W(&H174, &H175);
constexpr auto H177 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H176, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H178 = mvex_ctors::VHW(Code::MVEX_Vblendmps_zmm_k1_zmm_zmmmt);
constexpr auto H179 = mvex_ctors::VHW(Code::MVEX_Vblendmpd_zmm_k1_zmm_zmmmt);
constexpr auto H180 = mvex_ctors::W(&H178, &H179);
constexpr auto H181 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H180, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H182 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_67);
constexpr auto H183 = mvex_ctors::W(&H182, &INVALID_HANDLER);
constexpr auto H184 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H183, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H185 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_68);
constexpr auto H186 = mvex_ctors::W(&H185, &INVALID_HANDLER);
constexpr auto H187 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H186, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H188 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_69);
constexpr auto H189 = mvex_ctors::W(&H188, &INVALID_HANDLER);
constexpr auto H190 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H189, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H191 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_6A);
constexpr auto H192 = mvex_ctors::W(&H191, &INVALID_HANDLER);
constexpr auto H193 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H192, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H194 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_6B);
constexpr auto H195 = mvex_ctors::W(&H194, &INVALID_HANDLER);
constexpr auto H196 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H195, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H197 = mvex_ctors::VHW(Code::MVEX_Vpsubrd_zmm_k1_zmm_zmmmt);
constexpr auto H198 = mvex_ctors::W(&H197, &INVALID_HANDLER);
constexpr auto H199 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H198, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H200 = mvex_ctors::VHW(Code::MVEX_Vsubrps_zmm_k1_zmm_zmmmt);
constexpr auto H201 = mvex_ctors::VHW(Code::MVEX_Vsubrpd_zmm_k1_zmm_zmmmt);
constexpr auto H202 = mvex_ctors::W(&H200, &H201);
constexpr auto H203 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H202, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H204 = mvex_ctors::VKW(Code::MVEX_Vpsbbrd_zmm_k1_kr_zmmmt);
constexpr auto H205 = mvex_ctors::W(&H204, &INVALID_HANDLER);
constexpr auto H206 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H205, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H207 = mvex_ctors::VKW(Code::MVEX_Vpsubrsetbd_zmm_k1_kr_zmmmt);
constexpr auto H208 = mvex_ctors::W(&H207, &INVALID_HANDLER);
constexpr auto H209 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H208, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H210 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_70);
constexpr auto H211 = mvex_ctors::W(&H210, &INVALID_HANDLER);
constexpr auto H212 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H211, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H213 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_71);
constexpr auto H214 = mvex_ctors::W(&H213, &INVALID_HANDLER);
constexpr auto H215 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H214, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H216 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_72);
constexpr auto H217 = mvex_ctors::W(&H216, &INVALID_HANDLER);
constexpr auto H218 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H217, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H219 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_73);
constexpr auto H220 = mvex_ctors::W(&H219, &INVALID_HANDLER);
constexpr auto H221 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H220, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H222 = mvex_ctors::KHW(Code::MVEX_Vpcmpltd_kr_k1_zmm_zmmmt);
constexpr auto H223 = mvex_ctors::W(&H222, &INVALID_HANDLER);
constexpr auto H224 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H223, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H225 = mvex_ctors::VHW(Code::MVEX_Vscaleps_zmm_k1_zmm_zmmmt);
constexpr auto H226 = mvex_ctors::W(&H225, &INVALID_HANDLER);
constexpr auto H227 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H226, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H228 = mvex_ctors::VHW(Code::MVEX_Vpmulhud_zmm_k1_zmm_zmmmt);
constexpr auto H229 = mvex_ctors::W(&H228, &INVALID_HANDLER);
constexpr auto H230 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H229, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H231 = mvex_ctors::VHW(Code::MVEX_Vpmulhd_zmm_k1_zmm_zmmmt);
constexpr auto H232 = mvex_ctors::W(&H231, &INVALID_HANDLER);
constexpr auto H233 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H232, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H234 = mvex_ctors::V_VSIB(Code::MVEX_Vpgatherdd_zmm_k1_mvt);
constexpr auto H235 = mvex_ctors::V_VSIB(Code::MVEX_Vpgatherdq_zmm_k1_mvt);
constexpr auto H236 = mvex_ctors::W(&H234, &H235);
constexpr auto H237 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H236, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H238 = mvex_ctors::V_VSIB(Code::MVEX_Vgatherdps_zmm_k1_mvt);
constexpr auto H239 = mvex_ctors::V_VSIB(Code::MVEX_Vgatherdpd_zmm_k1_mvt);
constexpr auto H240 = mvex_ctors::W(&H238, &H239);
constexpr auto H241 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H240, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H242 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_94);
constexpr auto H243 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W1_94);
constexpr auto H244 = mvex_ctors::W(&H242, &H243);
constexpr auto H245 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H244, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H246 = mvex_ctors::VHW(Code::MVEX_Vfmadd132ps_zmm_k1_zmm_zmmmt);
constexpr auto H247 = mvex_ctors::VHW(Code::MVEX_Vfmadd132pd_zmm_k1_zmm_zmmmt);
constexpr auto H248 = mvex_ctors::W(&H246, &H247);
constexpr auto H249 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H248, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H250 = mvex_ctors::VHW(Code::MVEX_Vfmsub132ps_zmm_k1_zmm_zmmmt);
constexpr auto H251 = mvex_ctors::VHW(Code::MVEX_Vfmsub132pd_zmm_k1_zmm_zmmmt);
constexpr auto H252 = mvex_ctors::W(&H250, &H251);
constexpr auto H253 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H252, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H254 = mvex_ctors::VHW(Code::MVEX_Vfnmadd132ps_zmm_k1_zmm_zmmmt);
constexpr auto H255 = mvex_ctors::VHW(Code::MVEX_Vfnmadd132pd_zmm_k1_zmm_zmmmt);
constexpr auto H256 = mvex_ctors::W(&H254, &H255);
constexpr auto H257 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H256, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H258 = mvex_ctors::VHW(Code::MVEX_Vfnmsub132ps_zmm_k1_zmm_zmmmt);
constexpr auto H259 = mvex_ctors::VHW(Code::MVEX_Vfnmsub132pd_zmm_k1_zmm_zmmmt);
constexpr auto H260 = mvex_ctors::W(&H258, &H259);
constexpr auto H261 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H260, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H262 = mvex_ctors::VSIB_V(Code::MVEX_Vpscatterdd_mvt_k1_zmm);
constexpr auto H263 = mvex_ctors::VSIB_V(Code::MVEX_Vpscatterdq_mvt_k1_zmm);
constexpr auto H264 = mvex_ctors::W(&H262, &H263);
constexpr auto H265 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H264, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H266 = mvex_ctors::VSIB_V(Code::MVEX_Vscatterdps_mvt_k1_zmm);
constexpr auto H267 = mvex_ctors::VSIB_V(Code::MVEX_Vscatterdpd_mvt_k1_zmm);
constexpr auto H268 = mvex_ctors::W(&H266, &H267);
constexpr auto H269 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H268, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H270 = mvex_ctors::VHW(Code::MVEX_Vfmadd233ps_zmm_k1_zmm_zmmmt);
constexpr auto H271 = mvex_ctors::W(&H270, &INVALID_HANDLER);
constexpr auto H272 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H271, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H273 = mvex_ctors::VHW(Code::MVEX_Vfmadd213ps_zmm_k1_zmm_zmmmt);
constexpr auto H274 = mvex_ctors::VHW(Code::MVEX_Vfmadd213pd_zmm_k1_zmm_zmmmt);
constexpr auto H275 = mvex_ctors::W(&H273, &H274);
constexpr auto H276 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H275, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H277 = mvex_ctors::VHW(Code::MVEX_Vfmsub213ps_zmm_k1_zmm_zmmmt);
constexpr auto H278 = mvex_ctors::VHW(Code::MVEX_Vfmsub213pd_zmm_k1_zmm_zmmmt);
constexpr auto H279 = mvex_ctors::W(&H277, &H278);
constexpr auto H280 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H279, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H281 = mvex_ctors::VHW(Code::MVEX_Vfnmadd213ps_zmm_k1_zmm_zmmmt);
constexpr auto H282 = mvex_ctors::VHW(Code::MVEX_Vfnmadd213pd_zmm_k1_zmm_zmmmt);
constexpr auto H283 = mvex_ctors::W(&H281, &H282);
constexpr auto H284 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H283, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H285 = mvex_ctors::VHW(Code::MVEX_Vfnmsub213ps_zmm_k1_zmm_zmmmt);
constexpr auto H286 = mvex_ctors::VHW(Code::MVEX_Vfnmsub213pd_zmm_k1_zmm_zmmmt);
constexpr auto H287 = mvex_ctors::W(&H285, &H286);
constexpr auto H288 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H287, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H289 = mvex_ctors::V_VSIB(Code::MVEX_Undoc_zmm_k1_mvt_512_66_0F38_W0_B0);
constexpr auto H290 = mvex_ctors::W(&H289, &INVALID_HANDLER);
constexpr auto H291 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H290, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H292 = mvex_ctors::V_VSIB(Code::MVEX_Undoc_zmm_k1_mvt_512_66_0F38_W0_B2);
constexpr auto H293 = mvex_ctors::W(&H292, &INVALID_HANDLER);
constexpr auto H294 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H293, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H295 = mvex_ctors::VHW(Code::MVEX_Vpmadd233d_zmm_k1_zmm_zmmmt);
constexpr auto H296 = mvex_ctors::W(&H295, &INVALID_HANDLER);
constexpr auto H297 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H296, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H298 = mvex_ctors::VHW(Code::MVEX_Vpmadd231d_zmm_k1_zmm_zmmmt);
constexpr auto H299 = mvex_ctors::W(&H298, &INVALID_HANDLER);
constexpr auto H300 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H299, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H301 = mvex_ctors::VHW(Code::MVEX_Vfmadd231ps_zmm_k1_zmm_zmmmt);
constexpr auto H302 = mvex_ctors::VHW(Code::MVEX_Vfmadd231pd_zmm_k1_zmm_zmmmt);
constexpr auto H303 = mvex_ctors::W(&H301, &H302);
constexpr auto H304 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H303, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H305 = mvex_ctors::VHW(Code::MVEX_Vfmsub231ps_zmm_k1_zmm_zmmmt);
constexpr auto H306 = mvex_ctors::VHW(Code::MVEX_Vfmsub231pd_zmm_k1_zmm_zmmmt);
constexpr auto H307 = mvex_ctors::W(&H305, &H306);
constexpr auto H308 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H307, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H309 = mvex_ctors::VHW(Code::MVEX_Vfnmadd231ps_zmm_k1_zmm_zmmmt);
constexpr auto H310 = mvex_ctors::VHW(Code::MVEX_Vfnmadd231pd_zmm_k1_zmm_zmmmt);
constexpr auto H311 = mvex_ctors::W(&H309, &H310);
constexpr auto H312 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H311, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H313 = mvex_ctors::VHW(Code::MVEX_Vfnmsub231ps_zmm_k1_zmm_zmmmt);
constexpr auto H314 = mvex_ctors::VHW(Code::MVEX_Vfnmsub231pd_zmm_k1_zmm_zmmmt);
constexpr auto H315 = mvex_ctors::W(&H313, &H314);
constexpr auto H316 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H315, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H317 = mvex_ctors::V_VSIB(Code::MVEX_Undoc_zmm_k1_mvt_512_66_0F38_W0_C0);
constexpr auto H318 = mvex_ctors::W(&H317, &INVALID_HANDLER);
constexpr auto H319 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H318, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H320 = mvex_ctors::Group({&H33, &H37, &H41, &INVALID_HANDLER, &H47, &H51, &H55, &INVALID_HANDLER});
constexpr auto H321 = mvex_ctors::VW(Code::MVEX_Vexp223ps_zmm_k1_zmmmt);
constexpr auto H322 = mvex_ctors::W(&H321, &INVALID_HANDLER);
constexpr auto H323 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H322, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H324 = mvex_ctors::VW(Code::MVEX_Vlog2ps_zmm_k1_zmmmt);
constexpr auto H325 = mvex_ctors::W(&H324, &INVALID_HANDLER);
constexpr auto H326 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H325, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H327 = mvex_ctors::VW(Code::MVEX_Vrcp23ps_zmm_k1_zmmmt);
constexpr auto H328 = mvex_ctors::W(&H327, &INVALID_HANDLER);
constexpr auto H329 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H328, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H330 = mvex_ctors::VW(Code::MVEX_Vrsqrt23ps_zmm_k1_zmmmt);
constexpr auto H331 = mvex_ctors::W(&H330, &INVALID_HANDLER);
constexpr auto H332 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H331, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H333 = mvex_ctors::VHW(Code::MVEX_Vaddsetsps_zmm_k1_zmm_zmmmt);
constexpr auto H334 = mvex_ctors::W(&H333, &INVALID_HANDLER);
constexpr auto H335 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H334, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H336 = mvex_ctors::VHW(Code::MVEX_Vpaddsetsd_zmm_k1_zmm_zmmmt);
constexpr auto H337 = mvex_ctors::W(&H336, &INVALID_HANDLER);
constexpr auto H338 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H337, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H339 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_CE);
constexpr auto H340 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W1_CE);
constexpr auto H341 = mvex_ctors::W(&H339, &H340);
constexpr auto H342 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H341, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H343 = mvex_ctors::VHW(Code::MVEX_Undoc_zmm_k1_zmm_zmmmt_512_66_0F38_W0_CF);
constexpr auto H344 = mvex_ctors::W(&H343, &INVALID_HANDLER);
constexpr auto H345 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H344, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H346 = mvex_ctors::VW(Code::MVEX_Vloadunpackld_zmm_k1_mt);
constexpr auto H347 = mvex_ctors::RM(&INVALID_HANDLER, &H346);
constexpr auto H348 = mvex_ctors::VW(Code::MVEX_Vloadunpacklq_zmm_k1_mt);
constexpr auto H349 = mvex_ctors::RM(&INVALID_HANDLER, &H348);
constexpr auto H350 = mvex_ctors::W(&H347, &H349);
constexpr auto H351 = mvex_ctors::MV(Code::MVEX_Vpackstoreld_mt_k1_zmm);
constexpr auto H352 = mvex_ctors::MV(Code::MVEX_Vpackstorelq_mt_k1_zmm);
constexpr auto H353 = mvex_ctors::W(&H351, &H352);
constexpr auto H354 = mvex_ctors::MandatoryPrefix2(&H350, &H353, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H355 = mvex_ctors::VW(Code::MVEX_Vloadunpacklps_zmm_k1_mt);
constexpr auto H356 = mvex_ctors::RM(&INVALID_HANDLER, &H355);
constexpr auto H357 = mvex_ctors::VW(Code::MVEX_Vloadunpacklpd_zmm_k1_mt);
constexpr auto H358 = mvex_ctors::RM(&INVALID_HANDLER, &H357);
constexpr auto H359 = mvex_ctors::W(&H356, &H358);
constexpr auto H360 = mvex_ctors::MV(Code::MVEX_Vpackstorelps_mt_k1_zmm);
constexpr auto H361 = mvex_ctors::MV(Code::MVEX_Vpackstorelpd_mt_k1_zmm);
constexpr auto H362 = mvex_ctors::W(&H360, &H361);
constexpr auto H363 = mvex_ctors::MandatoryPrefix2(&H359, &H362, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H364 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_0F38_W0_D2);
constexpr auto H365 = mvex_ctors::W(&H364, &INVALID_HANDLER);
constexpr auto H366 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_D2);
constexpr auto H367 = mvex_ctors::W(&H366, &INVALID_HANDLER);
constexpr auto H368 = mvex_ctors::MandatoryPrefix2(&H365, &H367, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H369 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_0F38_W0_D3);
constexpr auto H370 = mvex_ctors::W(&H369, &INVALID_HANDLER);
constexpr auto H371 = mvex_ctors::MandatoryPrefix2(&H370, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H372 = mvex_ctors::VW(Code::MVEX_Vloadunpackhd_zmm_k1_mt);
constexpr auto H373 = mvex_ctors::RM(&INVALID_HANDLER, &H372);
constexpr auto H374 = mvex_ctors::VW(Code::MVEX_Vloadunpackhq_zmm_k1_mt);
constexpr auto H375 = mvex_ctors::RM(&INVALID_HANDLER, &H374);
constexpr auto H376 = mvex_ctors::W(&H373, &H375);
constexpr auto H377 = mvex_ctors::MV(Code::MVEX_Vpackstorehd_mt_k1_zmm);
constexpr auto H378 = mvex_ctors::MV(Code::MVEX_Vpackstorehq_mt_k1_zmm);
constexpr auto H379 = mvex_ctors::W(&H377, &H378);
constexpr auto H380 = mvex_ctors::MandatoryPrefix2(&H376, &H379, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H381 = mvex_ctors::VW(Code::MVEX_Vloadunpackhps_zmm_k1_mt);
constexpr auto H382 = mvex_ctors::RM(&INVALID_HANDLER, &H381);
constexpr auto H383 = mvex_ctors::VW(Code::MVEX_Vloadunpackhpd_zmm_k1_mt);
constexpr auto H384 = mvex_ctors::RM(&INVALID_HANDLER, &H383);
constexpr auto H385 = mvex_ctors::W(&H382, &H384);
constexpr auto H386 = mvex_ctors::MV(Code::MVEX_Vpackstorehps_mt_k1_zmm);
constexpr auto H387 = mvex_ctors::MV(Code::MVEX_Vpackstorehpd_mt_k1_zmm);
constexpr auto H388 = mvex_ctors::W(&H386, &H387);
constexpr auto H389 = mvex_ctors::MandatoryPrefix2(&H385, &H388, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H390 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_0F38_W0_D6);
constexpr auto H391 = mvex_ctors::W(&H390, &INVALID_HANDLER);
constexpr auto H392 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_66_0F38_W0_D6);
constexpr auto H393 = mvex_ctors::W(&H392, &INVALID_HANDLER);
constexpr auto H394 = mvex_ctors::MandatoryPrefix2(&H391, &H393, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H395 = mvex_ctors::VW(Code::MVEX_Undoc_zmm_k1_zmmmt_512_0F38_W0_D7);
constexpr auto H396 = mvex_ctors::W(&H395, &INVALID_HANDLER);
constexpr auto H397 = mvex_ctors::MandatoryPrefix2(&H396, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr HandlerEntry HANDLERS_0F38[0x100] = {
	to_handler_entry(&INVALID_HANDLER), // 0x00
	to_handler_entry(&INVALID_HANDLER), // 0x01
	to_handler_entry(&INVALID_HANDLER), // 0x02
	to_handler_entry(&INVALID_HANDLER), // 0x03
	to_handler_entry(&INVALID_HANDLER), // 0x04
	to_handler_entry(&INVALID_HANDLER), // 0x05
	to_handler_entry(&INVALID_HANDLER), // 0x06
	to_handler_entry(&INVALID_HANDLER), // 0x07
	to_handler_entry(&INVALID_HANDLER), // 0x08
	to_handler_entry(&INVALID_HANDLER), // 0x09
	to_handler_entry(&INVALID_HANDLER), // 0x0A
	to_handler_entry(&INVALID_HANDLER), // 0x0B
	to_handler_entry(&INVALID_HANDLER), // 0x0C
	to_handler_entry(&INVALID_HANDLER), // 0x0D
	to_handler_entry(&INVALID_HANDLER), // 0x0E
	to_handler_entry(&INVALID_HANDLER), // 0x0F
	to_handler_entry(&INVALID_HANDLER), // 0x10
	to_handler_entry(&INVALID_HANDLER), // 0x11
	to_handler_entry(&INVALID_HANDLER), // 0x12
	to_handler_entry(&INVALID_HANDLER), // 0x13
	to_handler_entry(&INVALID_HANDLER), // 0x14
	to_handler_entry(&INVALID_HANDLER), // 0x15
	to_handler_entry(&INVALID_HANDLER), // 0x16
	to_handler_entry(&INVALID_HANDLER), // 0x17
	to_handler_entry(&H59), // 0x18
	to_handler_entry(&H63), // 0x19
	to_handler_entry(&H67), // 0x1A
	to_handler_entry(&H71), // 0x1B
	to_handler_entry(&INVALID_HANDLER), // 0x1C
	to_handler_entry(&INVALID_HANDLER), // 0x1D
	to_handler_entry(&INVALID_HANDLER), // 0x1E
	to_handler_entry(&INVALID_HANDLER), // 0x1F
	to_handler_entry(&INVALID_HANDLER), // 0x20
	to_handler_entry(&INVALID_HANDLER), // 0x21
	to_handler_entry(&INVALID_HANDLER), // 0x22
	to_handler_entry(&INVALID_HANDLER), // 0x23
	to_handler_entry(&INVALID_HANDLER), // 0x24
	to_handler_entry(&INVALID_HANDLER), // 0x25
	to_handler_entry(&INVALID_HANDLER), // 0x26
	to_handler_entry(&H74), // 0x27
	to_handler_entry(&INVALID_HANDLER), // 0x28
	to_handler_entry(&INVALID_HANDLER), // 0x29
	to_handler_entry(&INVALID_HANDLER), // 0x2A
	to_handler_entry(&INVALID_HANDLER), // 0x2B
	to_handler_entry(&INVALID_HANDLER), // 0x2C
	to_handler_entry(&INVALID_HANDLER), // 0x2D
	to_handler_entry(&INVALID_HANDLER), // 0x2E
	to_handler_entry(&INVALID_HANDLER), // 0x2F
	to_handler_entry(&INVALID_HANDLER), // 0x30
	to_handler_entry(&INVALID_HANDLER), // 0x31
	to_handler_entry(&INVALID_HANDLER), // 0x32
	to_handler_entry(&INVALID_HANDLER), // 0x33
	to_handler_entry(&INVALID_HANDLER), // 0x34
	to_handler_entry(&INVALID_HANDLER), // 0x35
	to_handler_entry(&H77), // 0x36
	to_handler_entry(&INVALID_HANDLER), // 0x37
	to_handler_entry(&INVALID_HANDLER), // 0x38
	to_handler_entry(&H80), // 0x39
	to_handler_entry(&INVALID_HANDLER), // 0x3A
	to_handler_entry(&H83), // 0x3B
	to_handler_entry(&INVALID_HANDLER), // 0x3C
	to_handler_entry(&H86), // 0x3D
	to_handler_entry(&INVALID_HANDLER), // 0x3E
	to_handler_entry(&H89), // 0x3F
	to_handler_entry(&H92), // 0x40
	to_handler_entry(&INVALID_HANDLER), // 0x41
	to_handler_entry(&H96), // 0x42
	to_handler_entry(&INVALID_HANDLER), // 0x43
	to_handler_entry(&INVALID_HANDLER), // 0x44
	to_handler_entry(&H99), // 0x45
	to_handler_entry(&H102), // 0x46
	to_handler_entry(&H105), // 0x47
	to_handler_entry(&H108), // 0x48
	to_handler_entry(&H111), // 0x49
	to_handler_entry(&H114), // 0x4A
	to_handler_entry(&H117), // 0x4B
	to_handler_entry(&INVALID_HANDLER), // 0x4C
	to_handler_entry(&INVALID_HANDLER), // 0x4D
	to_handler_entry(&INVALID_HANDLER), // 0x4E
	to_handler_entry(&INVALID_HANDLER), // 0x4F
	to_handler_entry(&H121), // 0x50
	to_handler_entry(&H124), // 0x51
	to_handler_entry(&H128), // 0x52
	to_handler_entry(&H132), // 0x53
	to_handler_entry(&H135), // 0x54
	to_handler_entry(&H139), // 0x55
	to_handler_entry(&H142), // 0x56
	to_handler_entry(&H145), // 0x57
	to_handler_entry(&H149), // 0x58
	to_handler_entry(&H153), // 0x59
	to_handler_entry(&H157), // 0x5A
	to_handler_entry(&H161), // 0x5B
	to_handler_entry(&H164), // 0x5C
	to_handler_entry(&H167), // 0x5D
	to_handler_entry(&H170), // 0x5E
	to_handler_entry(&H173), // 0x5F
	to_handler_entry(&INVALID_HANDLER), // 0x60
	to_handler_entry(&INVALID_HANDLER), // 0x61
	to_handler_entry(&INVALID_HANDLER), // 0x62
	to_handler_entry(&INVALID_HANDLER), // 0x63
	to_handler_entry(&H177), // 0x64
	to_handler_entry(&H181), // 0x65
	to_handler_entry(&INVALID_HANDLER), // 0x66
	to_handler_entry(&H184), // 0x67
	to_handler_entry(&H187), // 0x68
	to_handler_entry(&H190), // 0x69
	to_handler_entry(&H193), // 0x6A
	to_handler_entry(&H196), // 0x6B
	to_handler_entry(&H199), // 0x6C
	to_handler_entry(&H203), // 0x6D
	to_handler_entry(&H206), // 0x6E
	to_handler_entry(&H209), // 0x6F
	to_handler_entry(&H212), // 0x70
	to_handler_entry(&H215), // 0x71
	to_handler_entry(&H218), // 0x72
	to_handler_entry(&H221), // 0x73
	to_handler_entry(&H224), // 0x74
	to_handler_entry(&INVALID_HANDLER), // 0x75
	to_handler_entry(&INVALID_HANDLER), // 0x76
	to_handler_entry(&INVALID_HANDLER), // 0x77
	to_handler_entry(&INVALID_HANDLER), // 0x78
	to_handler_entry(&INVALID_HANDLER), // 0x79
	to_handler_entry(&INVALID_HANDLER), // 0x7A
	to_handler_entry(&INVALID_HANDLER), // 0x7B
	to_handler_entry(&INVALID_HANDLER), // 0x7C
	to_handler_entry(&INVALID_HANDLER), // 0x7D
	to_handler_entry(&INVALID_HANDLER), // 0x7E
	to_handler_entry(&INVALID_HANDLER), // 0x7F
	to_handler_entry(&INVALID_HANDLER), // 0x80
	to_handler_entry(&INVALID_HANDLER), // 0x81
	to_handler_entry(&INVALID_HANDLER), // 0x82
	to_handler_entry(&INVALID_HANDLER), // 0x83
	to_handler_entry(&H227), // 0x84
	to_handler_entry(&INVALID_HANDLER), // 0x85
	to_handler_entry(&H230), // 0x86
	to_handler_entry(&H233), // 0x87
	to_handler_entry(&INVALID_HANDLER), // 0x88
	to_handler_entry(&INVALID_HANDLER), // 0x89
	to_handler_entry(&INVALID_HANDLER), // 0x8A
	to_handler_entry(&INVALID_HANDLER), // 0x8B
	to_handler_entry(&INVALID_HANDLER), // 0x8C
	to_handler_entry(&INVALID_HANDLER), // 0x8D
	to_handler_entry(&INVALID_HANDLER), // 0x8E
	to_handler_entry(&INVALID_HANDLER), // 0x8F
	to_handler_entry(&H237), // 0x90
	to_handler_entry(&INVALID_HANDLER), // 0x91
	to_handler_entry(&H241), // 0x92
	to_handler_entry(&INVALID_HANDLER), // 0x93
	to_handler_entry(&H245), // 0x94
	to_handler_entry(&INVALID_HANDLER), // 0x95
	to_handler_entry(&INVALID_HANDLER), // 0x96
	to_handler_entry(&INVALID_HANDLER), // 0x97
	to_handler_entry(&H249), // 0x98
	to_handler_entry(&INVALID_HANDLER), // 0x99
	to_handler_entry(&H253), // 0x9A
	to_handler_entry(&INVALID_HANDLER), // 0x9B
	to_handler_entry(&H257), // 0x9C
	to_handler_entry(&INVALID_HANDLER), // 0x9D
	to_handler_entry(&H261), // 0x9E
	to_handler_entry(&INVALID_HANDLER), // 0x9F
	to_handler_entry(&H265), // 0xA0
	to_handler_entry(&INVALID_HANDLER), // 0xA1
	to_handler_entry(&H269), // 0xA2
	to_handler_entry(&INVALID_HANDLER), // 0xA3
	to_handler_entry(&H272), // 0xA4
	to_handler_entry(&INVALID_HANDLER), // 0xA5
	to_handler_entry(&INVALID_HANDLER), // 0xA6
	to_handler_entry(&INVALID_HANDLER), // 0xA7
	to_handler_entry(&H276), // 0xA8
	to_handler_entry(&INVALID_HANDLER), // 0xA9
	to_handler_entry(&H280), // 0xAA
	to_handler_entry(&INVALID_HANDLER), // 0xAB
	to_handler_entry(&H284), // 0xAC
	to_handler_entry(&INVALID_HANDLER), // 0xAD
	to_handler_entry(&H288), // 0xAE
	to_handler_entry(&INVALID_HANDLER), // 0xAF
	to_handler_entry(&H291), // 0xB0
	to_handler_entry(&INVALID_HANDLER), // 0xB1
	to_handler_entry(&H294), // 0xB2
	to_handler_entry(&INVALID_HANDLER), // 0xB3
	to_handler_entry(&H297), // 0xB4
	to_handler_entry(&H300), // 0xB5
	to_handler_entry(&INVALID_HANDLER), // 0xB6
	to_handler_entry(&INVALID_HANDLER), // 0xB7
	to_handler_entry(&H304), // 0xB8
	to_handler_entry(&INVALID_HANDLER), // 0xB9
	to_handler_entry(&H308), // 0xBA
	to_handler_entry(&INVALID_HANDLER), // 0xBB
	to_handler_entry(&H312), // 0xBC
	to_handler_entry(&INVALID_HANDLER), // 0xBD
	to_handler_entry(&H316), // 0xBE
	to_handler_entry(&INVALID_HANDLER), // 0xBF
	to_handler_entry(&H319), // 0xC0
	to_handler_entry(&INVALID_HANDLER), // 0xC1
	to_handler_entry(&INVALID_HANDLER), // 0xC2
	to_handler_entry(&INVALID_HANDLER), // 0xC3
	to_handler_entry(&INVALID_HANDLER), // 0xC4
	to_handler_entry(&INVALID_HANDLER), // 0xC5
	to_handler_entry(&H320), // 0xC6
	to_handler_entry(&INVALID_HANDLER), // 0xC7
	to_handler_entry(&H323), // 0xC8
	to_handler_entry(&H326), // 0xC9
	to_handler_entry(&H329), // 0xCA
	to_handler_entry(&H332), // 0xCB
	to_handler_entry(&H335), // 0xCC
	to_handler_entry(&H338), // 0xCD
	to_handler_entry(&H342), // 0xCE
	to_handler_entry(&H345), // 0xCF
	to_handler_entry(&H354), // 0xD0
	to_handler_entry(&H363), // 0xD1
	to_handler_entry(&H368), // 0xD2
	to_handler_entry(&H371), // 0xD3
	to_handler_entry(&H380), // 0xD4
	to_handler_entry(&H389), // 0xD5
	to_handler_entry(&H394), // 0xD6
	to_handler_entry(&H397), // 0xD7
	to_handler_entry(&INVALID_HANDLER), // 0xD8
	to_handler_entry(&INVALID_HANDLER), // 0xD9
	to_handler_entry(&INVALID_HANDLER), // 0xDA
	to_handler_entry(&INVALID_HANDLER), // 0xDB
	to_handler_entry(&INVALID_HANDLER), // 0xDC
	to_handler_entry(&INVALID_HANDLER), // 0xDD
	to_handler_entry(&INVALID_HANDLER), // 0xDE
	to_handler_entry(&INVALID_HANDLER), // 0xDF
	to_handler_entry(&INVALID_HANDLER), // 0xE0
	to_handler_entry(&INVALID_HANDLER), // 0xE1
	to_handler_entry(&INVALID_HANDLER), // 0xE2
	to_handler_entry(&INVALID_HANDLER), // 0xE3
	to_handler_entry(&INVALID_HANDLER), // 0xE4
	to_handler_entry(&INVALID_HANDLER), // 0xE5
	to_handler_entry(&INVALID_HANDLER), // 0xE6
	to_handler_entry(&INVALID_HANDLER), // 0xE7
	to_handler_entry(&INVALID_HANDLER), // 0xE8
	to_handler_entry(&INVALID_HANDLER), // 0xE9
	to_handler_entry(&INVALID_HANDLER), // 0xEA
	to_handler_entry(&INVALID_HANDLER), // 0xEB
	to_handler_entry(&INVALID_HANDLER), // 0xEC
	to_handler_entry(&INVALID_HANDLER), // 0xED
	to_handler_entry(&INVALID_HANDLER), // 0xEE
	to_handler_entry(&INVALID_HANDLER), // 0xEF
	to_handler_entry(&INVALID_HANDLER), // 0xF0
	to_handler_entry(&INVALID_HANDLER), // 0xF1
	to_handler_entry(&INVALID_HANDLER), // 0xF2
	to_handler_entry(&INVALID_HANDLER), // 0xF3
	to_handler_entry(&INVALID_HANDLER), // 0xF4
	to_handler_entry(&INVALID_HANDLER), // 0xF5
	to_handler_entry(&INVALID_HANDLER), // 0xF6
	to_handler_entry(&INVALID_HANDLER), // 0xF7
	to_handler_entry(&INVALID_HANDLER), // 0xF8
	to_handler_entry(&INVALID_HANDLER), // 0xF9
	to_handler_entry(&INVALID_HANDLER), // 0xFA
	to_handler_entry(&INVALID_HANDLER), // 0xFB
	to_handler_entry(&INVALID_HANDLER), // 0xFC
	to_handler_entry(&INVALID_HANDLER), // 0xFD
	to_handler_entry(&INVALID_HANDLER), // 0xFE
	to_handler_entry(&INVALID_HANDLER), // 0xFF
};
constexpr auto H398 = mvex_ctors::VHWIb(Code::MVEX_Valignd_zmm_k1_zmm_zmmmt_imm8);
constexpr auto H399 = mvex_ctors::W(&H398, &INVALID_HANDLER);
constexpr auto H400 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H399, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H401 = mvex_ctors::VWIb(Code::MVEX_Vpermf32x4_zmm_k1_zmmmt_imm8);
constexpr auto H402 = mvex_ctors::W(&H401, &INVALID_HANDLER);
constexpr auto H403 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H402, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H404 = mvex_ctors::KHWIb(Code::MVEX_Vpcmpud_kr_k1_zmm_zmmmt_imm8);
constexpr auto H405 = mvex_ctors::W(&H404, &INVALID_HANDLER);
constexpr auto H406 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H405, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H407 = mvex_ctors::KHWIb(Code::MVEX_Vpcmpd_kr_k1_zmm_zmmmt_imm8);
constexpr auto H408 = mvex_ctors::W(&H407, &INVALID_HANDLER);
constexpr auto H409 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H408, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H410 = mvex_ctors::VWIb(Code::MVEX_Vgetmantps_zmm_k1_zmmmt_imm8);
constexpr auto H411 = mvex_ctors::VWIb(Code::MVEX_Vgetmantpd_zmm_k1_zmmmt_imm8);
constexpr auto H412 = mvex_ctors::W(&H410, &H411);
constexpr auto H413 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H412, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H414 = mvex_ctors::VWIb(Code::MVEX_Vrndfxpntps_zmm_k1_zmmmt_imm8);
constexpr auto H415 = mvex_ctors::VWIb(Code::MVEX_Vrndfxpntpd_zmm_k1_zmmmt_imm8);
constexpr auto H416 = mvex_ctors::W(&H414, &H415);
constexpr auto H417 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H416, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H418 = mvex_ctors::VWIb(Code::MVEX_Vcvtfxpntudq2ps_zmm_k1_zmmmt_imm8);
constexpr auto H419 = mvex_ctors::W(&H418, &INVALID_HANDLER);
constexpr auto H420 = mvex_ctors::VWIb(Code::MVEX_Vcvtfxpntps2udq_zmm_k1_zmmmt_imm8);
constexpr auto H421 = mvex_ctors::W(&H420, &INVALID_HANDLER);
constexpr auto H422 = mvex_ctors::VWIb(Code::MVEX_Vcvtfxpntpd2udq_zmm_k1_zmmmt_imm8);
constexpr auto H423 = mvex_ctors::W(&INVALID_HANDLER, &H422);
constexpr auto H424 = mvex_ctors::MandatoryPrefix2(&H419, &H421, &INVALID_HANDLER, &H423);
constexpr auto H425 = mvex_ctors::VWIb(Code::MVEX_Vcvtfxpntdq2ps_zmm_k1_zmmmt_imm8);
constexpr auto H426 = mvex_ctors::W(&H425, &INVALID_HANDLER);
constexpr auto H427 = mvex_ctors::VWIb(Code::MVEX_Vcvtfxpntps2dq_zmm_k1_zmmmt_imm8);
constexpr auto H428 = mvex_ctors::W(&H427, &INVALID_HANDLER);
constexpr auto H429 = mvex_ctors::MandatoryPrefix2(&H426, &H428, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H430 = mvex_ctors::VWIb(Code::MVEX_Undoc_zmm_k1_zmmmt_imm8_512_66_0F3A_W0_D0);
constexpr auto H431 = mvex_ctors::W(&H430, &INVALID_HANDLER);
constexpr auto H432 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H431, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H433 = mvex_ctors::VWIb(Code::MVEX_Undoc_zmm_k1_zmmmt_imm8_512_66_0F3A_W0_D1);
constexpr auto H434 = mvex_ctors::W(&H433, &INVALID_HANDLER);
constexpr auto H435 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H434, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H436 = mvex_ctors::VWIb(Code::MVEX_Vcvtfxpntpd2dq_zmm_k1_zmmmt_imm8);
constexpr auto H437 = mvex_ctors::W(&INVALID_HANDLER, &H436);
constexpr auto H438 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &H437);
constexpr HandlerEntry HANDLERS_0F3A[0x100] = {
	to_handler_entry(&INVALID_HANDLER), // 0x00
	to_handler_entry(&INVALID_HANDLER), // 0x01
	to_handler_entry(&INVALID_HANDLER), // 0x02
	to_handler_entry(&H400), // 0x03
	to_handler_entry(&INVALID_HANDLER), // 0x04
	to_handler_entry(&INVALID_HANDLER), // 0x05
	to_handler_entry(&INVALID_HANDLER), // 0x06
	to_handler_entry(&H403), // 0x07
	to_handler_entry(&INVALID_HANDLER), // 0x08
	to_handler_entry(&INVALID_HANDLER), // 0x09
	to_handler_entry(&INVALID_HANDLER), // 0x0A
	to_handler_entry(&INVALID_HANDLER), // 0x0B
	to_handler_entry(&INVALID_HANDLER), // 0x0C
	to_handler_entry(&INVALID_HANDLER), // 0x0D
	to_handler_entry(&INVALID_HANDLER), // 0x0E
	to_handler_entry(&INVALID_HANDLER), // 0x0F
	to_handler_entry(&INVALID_HANDLER), // 0x10
	to_handler_entry(&INVALID_HANDLER), // 0x11
	to_handler_entry(&INVALID_HANDLER), // 0x12
	to_handler_entry(&INVALID_HANDLER), // 0x13
	to_handler_entry(&INVALID_HANDLER), // 0x14
	to_handler_entry(&INVALID_HANDLER), // 0x15
	to_handler_entry(&INVALID_HANDLER), // 0x16
	to_handler_entry(&INVALID_HANDLER), // 0x17
	to_handler_entry(&INVALID_HANDLER), // 0x18
	to_handler_entry(&INVALID_HANDLER), // 0x19
	to_handler_entry(&INVALID_HANDLER), // 0x1A
	to_handler_entry(&INVALID_HANDLER), // 0x1B
	to_handler_entry(&INVALID_HANDLER), // 0x1C
	to_handler_entry(&INVALID_HANDLER), // 0x1D
	to_handler_entry(&H406), // 0x1E
	to_handler_entry(&H409), // 0x1F
	to_handler_entry(&INVALID_HANDLER), // 0x20
	to_handler_entry(&INVALID_HANDLER), // 0x21
	to_handler_entry(&INVALID_HANDLER), // 0x22
	to_handler_entry(&INVALID_HANDLER), // 0x23
	to_handler_entry(&INVALID_HANDLER), // 0x24
	to_handler_entry(&INVALID_HANDLER), // 0x25
	to_handler_entry(&H413), // 0x26
	to_handler_entry(&INVALID_HANDLER), // 0x27
	to_handler_entry(&INVALID_HANDLER), // 0x28
	to_handler_entry(&INVALID_HANDLER), // 0x29
	to_handler_entry(&INVALID_HANDLER), // 0x2A
	to_handler_entry(&INVALID_HANDLER), // 0x2B
	to_handler_entry(&INVALID_HANDLER), // 0x2C
	to_handler_entry(&INVALID_HANDLER), // 0x2D
	to_handler_entry(&INVALID_HANDLER), // 0x2E
	to_handler_entry(&INVALID_HANDLER), // 0x2F
	to_handler_entry(&INVALID_HANDLER), // 0x30
	to_handler_entry(&INVALID_HANDLER), // 0x31
	to_handler_entry(&INVALID_HANDLER), // 0x32
	to_handler_entry(&INVALID_HANDLER), // 0x33
	to_handler_entry(&INVALID_HANDLER), // 0x34
	to_handler_entry(&INVALID_HANDLER), // 0x35
	to_handler_entry(&INVALID_HANDLER), // 0x36
	to_handler_entry(&INVALID_HANDLER), // 0x37
	to_handler_entry(&INVALID_HANDLER), // 0x38
	to_handler_entry(&INVALID_HANDLER), // 0x39
	to_handler_entry(&INVALID_HANDLER), // 0x3A
	to_handler_entry(&INVALID_HANDLER), // 0x3B
	to_handler_entry(&INVALID_HANDLER), // 0x3C
	to_handler_entry(&INVALID_HANDLER), // 0x3D
	to_handler_entry(&INVALID_HANDLER), // 0x3E
	to_handler_entry(&INVALID_HANDLER), // 0x3F
	to_handler_entry(&INVALID_HANDLER), // 0x40
	to_handler_entry(&INVALID_HANDLER), // 0x41
	to_handler_entry(&INVALID_HANDLER), // 0x42
	to_handler_entry(&INVALID_HANDLER), // 0x43
	to_handler_entry(&INVALID_HANDLER), // 0x44
	to_handler_entry(&INVALID_HANDLER), // 0x45
	to_handler_entry(&INVALID_HANDLER), // 0x46
	to_handler_entry(&INVALID_HANDLER), // 0x47
	to_handler_entry(&INVALID_HANDLER), // 0x48
	to_handler_entry(&INVALID_HANDLER), // 0x49
	to_handler_entry(&INVALID_HANDLER), // 0x4A
	to_handler_entry(&INVALID_HANDLER), // 0x4B
	to_handler_entry(&INVALID_HANDLER), // 0x4C
	to_handler_entry(&INVALID_HANDLER), // 0x4D
	to_handler_entry(&INVALID_HANDLER), // 0x4E
	to_handler_entry(&INVALID_HANDLER), // 0x4F
	to_handler_entry(&INVALID_HANDLER), // 0x50
	to_handler_entry(&INVALID_HANDLER), // 0x51
	to_handler_entry(&H417), // 0x52
	to_handler_entry(&INVALID_HANDLER), // 0x53
	to_handler_entry(&INVALID_HANDLER), // 0x54
	to_handler_entry(&INVALID_HANDLER), // 0x55
	to_handler_entry(&INVALID_HANDLER), // 0x56
	to_handler_entry(&INVALID_HANDLER), // 0x57
	to_handler_entry(&INVALID_HANDLER), // 0x58
	to_handler_entry(&INVALID_HANDLER), // 0x59
	to_handler_entry(&INVALID_HANDLER), // 0x5A
	to_handler_entry(&INVALID_HANDLER), // 0x5B
	to_handler_entry(&INVALID_HANDLER), // 0x5C
	to_handler_entry(&INVALID_HANDLER), // 0x5D
	to_handler_entry(&INVALID_HANDLER), // 0x5E
	to_handler_entry(&INVALID_HANDLER), // 0x5F
	to_handler_entry(&INVALID_HANDLER), // 0x60
	to_handler_entry(&INVALID_HANDLER), // 0x61
	to_handler_entry(&INVALID_HANDLER), // 0x62
	to_handler_entry(&INVALID_HANDLER), // 0x63
	to_handler_entry(&INVALID_HANDLER), // 0x64
	to_handler_entry(&INVALID_HANDLER), // 0x65
	to_handler_entry(&INVALID_HANDLER), // 0x66
	to_handler_entry(&INVALID_HANDLER), // 0x67
	to_handler_entry(&INVALID_HANDLER), // 0x68
	to_handler_entry(&INVALID_HANDLER), // 0x69
	to_handler_entry(&INVALID_HANDLER), // 0x6A
	to_handler_entry(&INVALID_HANDLER), // 0x6B
	to_handler_entry(&INVALID_HANDLER), // 0x6C
	to_handler_entry(&INVALID_HANDLER), // 0x6D
	to_handler_entry(&INVALID_HANDLER), // 0x6E
	to_handler_entry(&INVALID_HANDLER), // 0x6F
	to_handler_entry(&INVALID_HANDLER), // 0x70
	to_handler_entry(&INVALID_HANDLER), // 0x71
	to_handler_entry(&INVALID_HANDLER), // 0x72
	to_handler_entry(&INVALID_HANDLER), // 0x73
	to_handler_entry(&INVALID_HANDLER), // 0x74
	to_handler_entry(&INVALID_HANDLER), // 0x75
	to_handler_entry(&INVALID_HANDLER), // 0x76
	to_handler_entry(&INVALID_HANDLER), // 0x77
	to_handler_entry(&INVALID_HANDLER), // 0x78
	to_handler_entry(&INVALID_HANDLER), // 0x79
	to_handler_entry(&INVALID_HANDLER), // 0x7A
	to_handler_entry(&INVALID_HANDLER), // 0x7B
	to_handler_entry(&INVALID_HANDLER), // 0x7C
	to_handler_entry(&INVALID_HANDLER), // 0x7D
	to_handler_entry(&INVALID_HANDLER), // 0x7E
	to_handler_entry(&INVALID_HANDLER), // 0x7F
	to_handler_entry(&INVALID_HANDLER), // 0x80
	to_handler_entry(&INVALID_HANDLER), // 0x81
	to_handler_entry(&INVALID_HANDLER), // 0x82
	to_handler_entry(&INVALID_HANDLER), // 0x83
	to_handler_entry(&INVALID_HANDLER), // 0x84
	to_handler_entry(&INVALID_HANDLER), // 0x85
	to_handler_entry(&INVALID_HANDLER), // 0x86
	to_handler_entry(&INVALID_HANDLER), // 0x87
	to_handler_entry(&INVALID_HANDLER), // 0x88
	to_handler_entry(&INVALID_HANDLER), // 0x89
	to_handler_entry(&INVALID_HANDLER), // 0x8A
	to_handler_entry(&INVALID_HANDLER), // 0x8B
	to_handler_entry(&INVALID_HANDLER), // 0x8C
	to_handler_entry(&INVALID_HANDLER), // 0x8D
	to_handler_entry(&INVALID_HANDLER), // 0x8E
	to_handler_entry(&INVALID_HANDLER), // 0x8F
	to_handler_entry(&INVALID_HANDLER), // 0x90
	to_handler_entry(&INVALID_HANDLER), // 0x91
	to_handler_entry(&INVALID_HANDLER), // 0x92
	to_handler_entry(&INVALID_HANDLER), // 0x93
	to_handler_entry(&INVALID_HANDLER), // 0x94
	to_handler_entry(&INVALID_HANDLER), // 0x95
	to_handler_entry(&INVALID_HANDLER), // 0x96
	to_handler_entry(&INVALID_HANDLER), // 0x97
	to_handler_entry(&INVALID_HANDLER), // 0x98
	to_handler_entry(&INVALID_HANDLER), // 0x99
	to_handler_entry(&INVALID_HANDLER), // 0x9A
	to_handler_entry(&INVALID_HANDLER), // 0x9B
	to_handler_entry(&INVALID_HANDLER), // 0x9C
	to_handler_entry(&INVALID_HANDLER), // 0x9D
	to_handler_entry(&INVALID_HANDLER), // 0x9E
	to_handler_entry(&INVALID_HANDLER), // 0x9F
	to_handler_entry(&INVALID_HANDLER), // 0xA0
	to_handler_entry(&INVALID_HANDLER), // 0xA1
	to_handler_entry(&INVALID_HANDLER), // 0xA2
	to_handler_entry(&INVALID_HANDLER), // 0xA3
	to_handler_entry(&INVALID_HANDLER), // 0xA4
	to_handler_entry(&INVALID_HANDLER), // 0xA5
	to_handler_entry(&INVALID_HANDLER), // 0xA6
	to_handler_entry(&INVALID_HANDLER), // 0xA7
	to_handler_entry(&INVALID_HANDLER), // 0xA8
	to_handler_entry(&INVALID_HANDLER), // 0xA9
	to_handler_entry(&INVALID_HANDLER), // 0xAA
	to_handler_entry(&INVALID_HANDLER), // 0xAB
	to_handler_entry(&INVALID_HANDLER), // 0xAC
	to_handler_entry(&INVALID_HANDLER), // 0xAD
	to_handler_entry(&INVALID_HANDLER), // 0xAE
	to_handler_entry(&INVALID_HANDLER), // 0xAF
	to_handler_entry(&INVALID_HANDLER), // 0xB0
	to_handler_entry(&INVALID_HANDLER), // 0xB1
	to_handler_entry(&INVALID_HANDLER), // 0xB2
	to_handler_entry(&INVALID_HANDLER), // 0xB3
	to_handler_entry(&INVALID_HANDLER), // 0xB4
	to_handler_entry(&INVALID_HANDLER), // 0xB5
	to_handler_entry(&INVALID_HANDLER), // 0xB6
	to_handler_entry(&INVALID_HANDLER), // 0xB7
	to_handler_entry(&INVALID_HANDLER), // 0xB8
	to_handler_entry(&INVALID_HANDLER), // 0xB9
	to_handler_entry(&INVALID_HANDLER), // 0xBA
	to_handler_entry(&INVALID_HANDLER), // 0xBB
	to_handler_entry(&INVALID_HANDLER), // 0xBC
	to_handler_entry(&INVALID_HANDLER), // 0xBD
	to_handler_entry(&INVALID_HANDLER), // 0xBE
	to_handler_entry(&INVALID_HANDLER), // 0xBF
	to_handler_entry(&INVALID_HANDLER), // 0xC0
	to_handler_entry(&INVALID_HANDLER), // 0xC1
	to_handler_entry(&INVALID_HANDLER), // 0xC2
	to_handler_entry(&INVALID_HANDLER), // 0xC3
	to_handler_entry(&INVALID_HANDLER), // 0xC4
	to_handler_entry(&INVALID_HANDLER), // 0xC5
	to_handler_entry(&INVALID_HANDLER), // 0xC6
	to_handler_entry(&INVALID_HANDLER), // 0xC7
	to_handler_entry(&INVALID_HANDLER), // 0xC8
	to_handler_entry(&INVALID_HANDLER), // 0xC9
	to_handler_entry(&H424), // 0xCA
	to_handler_entry(&H429), // 0xCB
	to_handler_entry(&INVALID_HANDLER), // 0xCC
	to_handler_entry(&INVALID_HANDLER), // 0xCD
	to_handler_entry(&INVALID_HANDLER), // 0xCE
	to_handler_entry(&INVALID_HANDLER), // 0xCF
	to_handler_entry(&H432), // 0xD0
	to_handler_entry(&H435), // 0xD1
	to_handler_entry(&INVALID_HANDLER), // 0xD2
	to_handler_entry(&INVALID_HANDLER), // 0xD3
	to_handler_entry(&INVALID_HANDLER), // 0xD4
	to_handler_entry(&INVALID_HANDLER), // 0xD5
	to_handler_entry(&INVALID_HANDLER), // 0xD6
	to_handler_entry(&INVALID_HANDLER), // 0xD7
	to_handler_entry(&INVALID_HANDLER), // 0xD8
	to_handler_entry(&INVALID_HANDLER), // 0xD9
	to_handler_entry(&INVALID_HANDLER), // 0xDA
	to_handler_entry(&INVALID_HANDLER), // 0xDB
	to_handler_entry(&INVALID_HANDLER), // 0xDC
	to_handler_entry(&INVALID_HANDLER), // 0xDD
	to_handler_entry(&INVALID_HANDLER), // 0xDE
	to_handler_entry(&INVALID_HANDLER), // 0xDF
	to_handler_entry(&INVALID_HANDLER), // 0xE0
	to_handler_entry(&INVALID_HANDLER), // 0xE1
	to_handler_entry(&INVALID_HANDLER), // 0xE2
	to_handler_entry(&INVALID_HANDLER), // 0xE3
	to_handler_entry(&INVALID_HANDLER), // 0xE4
	to_handler_entry(&INVALID_HANDLER), // 0xE5
	to_handler_entry(&H438), // 0xE6
	to_handler_entry(&INVALID_HANDLER), // 0xE7
	to_handler_entry(&INVALID_HANDLER), // 0xE8
	to_handler_entry(&INVALID_HANDLER), // 0xE9
	to_handler_entry(&INVALID_HANDLER), // 0xEA
	to_handler_entry(&INVALID_HANDLER), // 0xEB
	to_handler_entry(&INVALID_HANDLER), // 0xEC
	to_handler_entry(&INVALID_HANDLER), // 0xED
	to_handler_entry(&INVALID_HANDLER), // 0xEE
	to_handler_entry(&INVALID_HANDLER), // 0xEF
	to_handler_entry(&INVALID_HANDLER), // 0xF0
	to_handler_entry(&INVALID_HANDLER), // 0xF1
	to_handler_entry(&INVALID_HANDLER), // 0xF2
	to_handler_entry(&INVALID_HANDLER), // 0xF3
	to_handler_entry(&INVALID_HANDLER), // 0xF4
	to_handler_entry(&INVALID_HANDLER), // 0xF5
	to_handler_entry(&INVALID_HANDLER), // 0xF6
	to_handler_entry(&INVALID_HANDLER), // 0xF7
	to_handler_entry(&INVALID_HANDLER), // 0xF8
	to_handler_entry(&INVALID_HANDLER), // 0xF9
	to_handler_entry(&INVALID_HANDLER), // 0xFA
	to_handler_entry(&INVALID_HANDLER), // 0xFB
	to_handler_entry(&INVALID_HANDLER), // 0xFC
	to_handler_entry(&INVALID_HANDLER), // 0xFD
	to_handler_entry(&INVALID_HANDLER), // 0xFE
	to_handler_entry(&INVALID_HANDLER), // 0xFF
};
constexpr auto H439 = mvex_ctors::Group({&H1, &H3, &H5, &H7, &H9, &H11, &H13, &H15});
constexpr auto H440 = mvex_ctors::VW(Code::MVEX_Vmovaps_zmm_k1_zmmmt);
constexpr auto H441 = mvex_ctors::W(&H440, &INVALID_HANDLER);
constexpr auto H442 = mvex_ctors::VW(Code::MVEX_Vmovapd_zmm_k1_zmmmt);
constexpr auto H443 = mvex_ctors::W(&INVALID_HANDLER, &H442);
constexpr auto H444 = mvex_ctors::MandatoryPrefix2(&H441, &H443, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H445 = mvex_ctors::MV(Code::MVEX_Vmovaps_mt_k1_zmm);
constexpr auto H446 = mvex_ctors::W(&H445, &INVALID_HANDLER);
constexpr auto H447 = mvex_ctors::MV(Code::MVEX_Vmovapd_mt_k1_zmm);
constexpr auto H448 = mvex_ctors::W(&INVALID_HANDLER, &H447);
constexpr auto H449 = mvex_ctors::MV(Code::MVEX_Vmovnrapd_m_k1_zmm);
constexpr auto H450 = mvex_ctors::MV(Code::MVEX_Vmovnrngoapd_m_k1_zmm);
constexpr auto H451 = mvex_ctors::EH(&H449, &H450);
constexpr auto H452 = mvex_ctors::W(&INVALID_HANDLER, &H451);
constexpr auto H453 = mvex_ctors::MV(Code::MVEX_Vmovnraps_m_k1_zmm);
constexpr auto H454 = mvex_ctors::MV(Code::MVEX_Vmovnrngoaps_m_k1_zmm);
constexpr auto H455 = mvex_ctors::EH(&H453, &H454);
constexpr auto H456 = mvex_ctors::W(&H455, &INVALID_HANDLER);
constexpr auto H457 = mvex_ctors::MandatoryPrefix2(&H446, &H448, &H452, &H456);
constexpr auto H458 = mvex_ctors::VHW(Code::MVEX_Vaddps_zmm_k1_zmm_zmmmt);
constexpr auto H459 = mvex_ctors::W(&H458, &INVALID_HANDLER);
constexpr auto H460 = mvex_ctors::VHW(Code::MVEX_Vaddpd_zmm_k1_zmm_zmmmt);
constexpr auto H461 = mvex_ctors::W(&INVALID_HANDLER, &H460);
constexpr auto H462 = mvex_ctors::MandatoryPrefix2(&H459, &H461, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H463 = mvex_ctors::VHW(Code::MVEX_Vmulps_zmm_k1_zmm_zmmmt);
constexpr auto H464 = mvex_ctors::W(&H463, &INVALID_HANDLER);
constexpr auto H465 = mvex_ctors::VHW(Code::MVEX_Vmulpd_zmm_k1_zmm_zmmmt);
constexpr auto H466 = mvex_ctors::W(&INVALID_HANDLER, &H465);
constexpr auto H467 = mvex_ctors::MandatoryPrefix2(&H464, &H466, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H468 = mvex_ctors::VW(Code::MVEX_Vcvtps2pd_zmm_k1_zmmmt);
constexpr auto H469 = mvex_ctors::W(&H468, &INVALID_HANDLER);
constexpr auto H470 = mvex_ctors::VW(Code::MVEX_Vcvtpd2ps_zmm_k1_zmmmt);
constexpr auto H471 = mvex_ctors::W(&INVALID_HANDLER, &H470);
constexpr auto H472 = mvex_ctors::MandatoryPrefix2(&H469, &H471, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H473 = mvex_ctors::VHW(Code::MVEX_Vsubps_zmm_k1_zmm_zmmmt);
constexpr auto H474 = mvex_ctors::W(&H473, &INVALID_HANDLER);
constexpr auto H475 = mvex_ctors::VHW(Code::MVEX_Vsubpd_zmm_k1_zmm_zmmmt);
constexpr auto H476 = mvex_ctors::W(&INVALID_HANDLER, &H475);
constexpr auto H477 = mvex_ctors::MandatoryPrefix2(&H474, &H476, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H478 = mvex_ctors::KHW(Code::MVEX_Vpcmpgtd_kr_k1_zmm_zmmmt);
constexpr auto H479 = mvex_ctors::W(&H478, &INVALID_HANDLER);
constexpr auto H480 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H479, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H481 = mvex_ctors::VW(Code::MVEX_Vmovdqa32_zmm_k1_zmmmt);
constexpr auto H482 = mvex_ctors::VW(Code::MVEX_Vmovdqa64_zmm_k1_zmmmt);
constexpr auto H483 = mvex_ctors::W(&H481, &H482);
constexpr auto H484 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H483, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H485 = mvex_ctors::VWIb(Code::MVEX_Vpshufd_zmm_k1_zmmmt_imm8);
constexpr auto H486 = mvex_ctors::W(&H485, &INVALID_HANDLER);
constexpr auto H487 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H486, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H488 = mvex_ctors::Group({&INVALID_HANDLER, &INVALID_HANDLER, &H18, &INVALID_HANDLER, &H21, &INVALID_HANDLER, &H24, &INVALID_HANDLER});
constexpr auto H489 = mvex_ctors::KHW(Code::MVEX_Vpcmpeqd_kr_k1_zmm_zmmmt);
constexpr auto H490 = mvex_ctors::W(&H489, &INVALID_HANDLER);
constexpr auto H491 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H490, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H492 = mvex_ctors::VW(Code::MVEX_Vcvtudq2pd_zmm_k1_zmmmt);
constexpr auto H493 = mvex_ctors::W(&H492, &INVALID_HANDLER);
constexpr auto H494 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &INVALID_HANDLER, &H493, &INVALID_HANDLER);
constexpr auto H495 = mvex_ctors::MV(Code::MVEX_Vmovdqa32_mt_k1_zmm);
constexpr auto H496 = mvex_ctors::MV(Code::MVEX_Vmovdqa64_mt_k1_zmm);
constexpr auto H497 = mvex_ctors::W(&H495, &H496);
constexpr auto H498 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H497, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H499 = mvex_ctors::Group({&INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &H27});
constexpr auto H500 = mvex_ctors::KHWIb(Code::MVEX_Vcmpps_kr_k1_zmm_zmmmt_imm8);
constexpr auto H501 = mvex_ctors::W(&H500, &INVALID_HANDLER);
constexpr auto H502 = mvex_ctors::KHWIb(Code::MVEX_Vcmppd_kr_k1_zmm_zmmmt_imm8);
constexpr auto H503 = mvex_ctors::W(&INVALID_HANDLER, &H502);
constexpr auto H504 = mvex_ctors::MandatoryPrefix2(&H501, &H503, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H505 = mvex_ctors::VHW(Code::MVEX_Vpandd_zmm_k1_zmm_zmmmt);
constexpr auto H506 = mvex_ctors::VHW(Code::MVEX_Vpandq_zmm_k1_zmm_zmmmt);
constexpr auto H507 = mvex_ctors::W(&H505, &H506);
constexpr auto H508 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H507, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H509 = mvex_ctors::VHW(Code::MVEX_Vpandnd_zmm_k1_zmm_zmmmt);
constexpr auto H510 = mvex_ctors::VHW(Code::MVEX_Vpandnq_zmm_k1_zmm_zmmmt);
constexpr auto H511 = mvex_ctors::W(&H509, &H510);
constexpr auto H512 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H511, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H513 = mvex_ctors::VW(Code::MVEX_Vcvtdq2pd_zmm_k1_zmmmt);
constexpr auto H514 = mvex_ctors::W(&H513, &INVALID_HANDLER);
constexpr auto H515 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &INVALID_HANDLER, &H514, &INVALID_HANDLER);
constexpr auto H516 = mvex_ctors::VHW(Code::MVEX_Vpord_zmm_k1_zmm_zmmmt);
constexpr auto H517 = mvex_ctors::VHW(Code::MVEX_Vporq_zmm_k1_zmm_zmmmt);
constexpr auto H518 = mvex_ctors::W(&H516, &H517);
constexpr auto H519 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H518, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H520 = mvex_ctors::VHW(Code::MVEX_Vpxord_zmm_k1_zmm_zmmmt);
constexpr auto H521 = mvex_ctors::VHW(Code::MVEX_Vpxorq_zmm_k1_zmm_zmmmt);
constexpr auto H522 = mvex_ctors::W(&H520, &H521);
constexpr auto H523 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H522, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H524 = mvex_ctors::VHW(Code::MVEX_Vpsubd_zmm_k1_zmm_zmmmt);
constexpr auto H525 = mvex_ctors::W(&H524, &INVALID_HANDLER);
constexpr auto H526 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H525, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr auto H527 = mvex_ctors::VHW(Code::MVEX_Vpaddd_zmm_k1_zmm_zmmmt);
constexpr auto H528 = mvex_ctors::W(&H527, &INVALID_HANDLER);
constexpr auto H529 = mvex_ctors::MandatoryPrefix2(&INVALID_HANDLER, &H528, &INVALID_HANDLER, &INVALID_HANDLER);
constexpr HandlerEntry HANDLERS_0F[0x100] = {
	to_handler_entry(&INVALID_HANDLER), // 0x00
	to_handler_entry(&INVALID_HANDLER), // 0x01
	to_handler_entry(&INVALID_HANDLER), // 0x02
	to_handler_entry(&INVALID_HANDLER), // 0x03
	to_handler_entry(&INVALID_HANDLER), // 0x04
	to_handler_entry(&INVALID_HANDLER), // 0x05
	to_handler_entry(&INVALID_HANDLER), // 0x06
	to_handler_entry(&INVALID_HANDLER), // 0x07
	to_handler_entry(&INVALID_HANDLER), // 0x08
	to_handler_entry(&INVALID_HANDLER), // 0x09
	to_handler_entry(&INVALID_HANDLER), // 0x0A
	to_handler_entry(&INVALID_HANDLER), // 0x0B
	to_handler_entry(&INVALID_HANDLER), // 0x0C
	to_handler_entry(&INVALID_HANDLER), // 0x0D
	to_handler_entry(&INVALID_HANDLER), // 0x0E
	to_handler_entry(&INVALID_HANDLER), // 0x0F
	to_handler_entry(&INVALID_HANDLER), // 0x10
	to_handler_entry(&INVALID_HANDLER), // 0x11
	to_handler_entry(&INVALID_HANDLER), // 0x12
	to_handler_entry(&INVALID_HANDLER), // 0x13
	to_handler_entry(&INVALID_HANDLER), // 0x14
	to_handler_entry(&INVALID_HANDLER), // 0x15
	to_handler_entry(&INVALID_HANDLER), // 0x16
	to_handler_entry(&INVALID_HANDLER), // 0x17
	to_handler_entry(&H439), // 0x18
	to_handler_entry(&INVALID_HANDLER), // 0x19
	to_handler_entry(&INVALID_HANDLER), // 0x1A
	to_handler_entry(&INVALID_HANDLER), // 0x1B
	to_handler_entry(&INVALID_HANDLER), // 0x1C
	to_handler_entry(&INVALID_HANDLER), // 0x1D
	to_handler_entry(&INVALID_HANDLER), // 0x1E
	to_handler_entry(&INVALID_HANDLER), // 0x1F
	to_handler_entry(&INVALID_HANDLER), // 0x20
	to_handler_entry(&INVALID_HANDLER), // 0x21
	to_handler_entry(&INVALID_HANDLER), // 0x22
	to_handler_entry(&INVALID_HANDLER), // 0x23
	to_handler_entry(&INVALID_HANDLER), // 0x24
	to_handler_entry(&INVALID_HANDLER), // 0x25
	to_handler_entry(&INVALID_HANDLER), // 0x26
	to_handler_entry(&INVALID_HANDLER), // 0x27
	to_handler_entry(&H444), // 0x28
	to_handler_entry(&H457), // 0x29
	to_handler_entry(&INVALID_HANDLER), // 0x2A
	to_handler_entry(&INVALID_HANDLER), // 0x2B
	to_handler_entry(&INVALID_HANDLER), // 0x2C
	to_handler_entry(&INVALID_HANDLER), // 0x2D
	to_handler_entry(&INVALID_HANDLER), // 0x2E
	to_handler_entry(&INVALID_HANDLER), // 0x2F
	to_handler_entry(&INVALID_HANDLER), // 0x30
	to_handler_entry(&INVALID_HANDLER), // 0x31
	to_handler_entry(&INVALID_HANDLER), // 0x32
	to_handler_entry(&INVALID_HANDLER), // 0x33
	to_handler_entry(&INVALID_HANDLER), // 0x34
	to_handler_entry(&INVALID_HANDLER), // 0x35
	to_handler_entry(&INVALID_HANDLER), // 0x36
	to_handler_entry(&INVALID_HANDLER), // 0x37
	to_handler_entry(&INVALID_HANDLER), // 0x38
	to_handler_entry(&INVALID_HANDLER), // 0x39
	to_handler_entry(&INVALID_HANDLER), // 0x3A
	to_handler_entry(&INVALID_HANDLER), // 0x3B
	to_handler_entry(&INVALID_HANDLER), // 0x3C
	to_handler_entry(&INVALID_HANDLER), // 0x3D
	to_handler_entry(&INVALID_HANDLER), // 0x3E
	to_handler_entry(&INVALID_HANDLER), // 0x3F
	to_handler_entry(&INVALID_HANDLER), // 0x40
	to_handler_entry(&INVALID_HANDLER), // 0x41
	to_handler_entry(&INVALID_HANDLER), // 0x42
	to_handler_entry(&INVALID_HANDLER), // 0x43
	to_handler_entry(&INVALID_HANDLER), // 0x44
	to_handler_entry(&INVALID_HANDLER), // 0x45
	to_handler_entry(&INVALID_HANDLER), // 0x46
	to_handler_entry(&INVALID_HANDLER), // 0x47
	to_handler_entry(&INVALID_HANDLER), // 0x48
	to_handler_entry(&INVALID_HANDLER), // 0x49
	to_handler_entry(&INVALID_HANDLER), // 0x4A
	to_handler_entry(&INVALID_HANDLER), // 0x4B
	to_handler_entry(&INVALID_HANDLER), // 0x4C
	to_handler_entry(&INVALID_HANDLER), // 0x4D
	to_handler_entry(&INVALID_HANDLER), // 0x4E
	to_handler_entry(&INVALID_HANDLER), // 0x4F
	to_handler_entry(&INVALID_HANDLER), // 0x50
	to_handler_entry(&INVALID_HANDLER), // 0x51
	to_handler_entry(&INVALID_HANDLER), // 0x52
	to_handler_entry(&INVALID_HANDLER), // 0x53
	to_handler_entry(&INVALID_HANDLER), // 0x54
	to_handler_entry(&INVALID_HANDLER), // 0x55
	to_handler_entry(&INVALID_HANDLER), // 0x56
	to_handler_entry(&INVALID_HANDLER), // 0x57
	to_handler_entry(&H462), // 0x58
	to_handler_entry(&H467), // 0x59
	to_handler_entry(&H472), // 0x5A
	to_handler_entry(&INVALID_HANDLER), // 0x5B
	to_handler_entry(&H477), // 0x5C
	to_handler_entry(&INVALID_HANDLER), // 0x5D
	to_handler_entry(&INVALID_HANDLER), // 0x5E
	to_handler_entry(&INVALID_HANDLER), // 0x5F
	to_handler_entry(&INVALID_HANDLER), // 0x60
	to_handler_entry(&INVALID_HANDLER), // 0x61
	to_handler_entry(&INVALID_HANDLER), // 0x62
	to_handler_entry(&INVALID_HANDLER), // 0x63
	to_handler_entry(&INVALID_HANDLER), // 0x64
	to_handler_entry(&INVALID_HANDLER), // 0x65
	to_handler_entry(&H480), // 0x66
	to_handler_entry(&INVALID_HANDLER), // 0x67
	to_handler_entry(&INVALID_HANDLER), // 0x68
	to_handler_entry(&INVALID_HANDLER), // 0x69
	to_handler_entry(&INVALID_HANDLER), // 0x6A
	to_handler_entry(&INVALID_HANDLER), // 0x6B
	to_handler_entry(&INVALID_HANDLER), // 0x6C
	to_handler_entry(&INVALID_HANDLER), // 0x6D
	to_handler_entry(&INVALID_HANDLER), // 0x6E
	to_handler_entry(&H484), // 0x6F
	to_handler_entry(&H487), // 0x70
	to_handler_entry(&INVALID_HANDLER), // 0x71
	to_handler_entry(&H488), // 0x72
	to_handler_entry(&INVALID_HANDLER), // 0x73
	to_handler_entry(&INVALID_HANDLER), // 0x74
	to_handler_entry(&INVALID_HANDLER), // 0x75
	to_handler_entry(&H491), // 0x76
	to_handler_entry(&INVALID_HANDLER), // 0x77
	to_handler_entry(&INVALID_HANDLER), // 0x78
	to_handler_entry(&INVALID_HANDLER), // 0x79
	to_handler_entry(&H494), // 0x7A
	to_handler_entry(&INVALID_HANDLER), // 0x7B
	to_handler_entry(&INVALID_HANDLER), // 0x7C
	to_handler_entry(&INVALID_HANDLER), // 0x7D
	to_handler_entry(&INVALID_HANDLER), // 0x7E
	to_handler_entry(&H498), // 0x7F
	to_handler_entry(&INVALID_HANDLER), // 0x80
	to_handler_entry(&INVALID_HANDLER), // 0x81
	to_handler_entry(&INVALID_HANDLER), // 0x82
	to_handler_entry(&INVALID_HANDLER), // 0x83
	to_handler_entry(&INVALID_HANDLER), // 0x84
	to_handler_entry(&INVALID_HANDLER), // 0x85
	to_handler_entry(&INVALID_HANDLER), // 0x86
	to_handler_entry(&INVALID_HANDLER), // 0x87
	to_handler_entry(&INVALID_HANDLER), // 0x88
	to_handler_entry(&INVALID_HANDLER), // 0x89
	to_handler_entry(&INVALID_HANDLER), // 0x8A
	to_handler_entry(&INVALID_HANDLER), // 0x8B
	to_handler_entry(&INVALID_HANDLER), // 0x8C
	to_handler_entry(&INVALID_HANDLER), // 0x8D
	to_handler_entry(&INVALID_HANDLER), // 0x8E
	to_handler_entry(&INVALID_HANDLER), // 0x8F
	to_handler_entry(&INVALID_HANDLER), // 0x90
	to_handler_entry(&INVALID_HANDLER), // 0x91
	to_handler_entry(&INVALID_HANDLER), // 0x92
	to_handler_entry(&INVALID_HANDLER), // 0x93
	to_handler_entry(&INVALID_HANDLER), // 0x94
	to_handler_entry(&INVALID_HANDLER), // 0x95
	to_handler_entry(&INVALID_HANDLER), // 0x96
	to_handler_entry(&INVALID_HANDLER), // 0x97
	to_handler_entry(&INVALID_HANDLER), // 0x98
	to_handler_entry(&INVALID_HANDLER), // 0x99
	to_handler_entry(&INVALID_HANDLER), // 0x9A
	to_handler_entry(&INVALID_HANDLER), // 0x9B
	to_handler_entry(&INVALID_HANDLER), // 0x9C
	to_handler_entry(&INVALID_HANDLER), // 0x9D
	to_handler_entry(&INVALID_HANDLER), // 0x9E
	to_handler_entry(&INVALID_HANDLER), // 0x9F
	to_handler_entry(&INVALID_HANDLER), // 0xA0
	to_handler_entry(&INVALID_HANDLER), // 0xA1
	to_handler_entry(&INVALID_HANDLER), // 0xA2
	to_handler_entry(&INVALID_HANDLER), // 0xA3
	to_handler_entry(&INVALID_HANDLER), // 0xA4
	to_handler_entry(&INVALID_HANDLER), // 0xA5
	to_handler_entry(&INVALID_HANDLER), // 0xA6
	to_handler_entry(&INVALID_HANDLER), // 0xA7
	to_handler_entry(&INVALID_HANDLER), // 0xA8
	to_handler_entry(&INVALID_HANDLER), // 0xA9
	to_handler_entry(&INVALID_HANDLER), // 0xAA
	to_handler_entry(&INVALID_HANDLER), // 0xAB
	to_handler_entry(&INVALID_HANDLER), // 0xAC
	to_handler_entry(&INVALID_HANDLER), // 0xAD
	to_handler_entry(&H499), // 0xAE
	to_handler_entry(&INVALID_HANDLER), // 0xAF
	to_handler_entry(&INVALID_HANDLER), // 0xB0
	to_handler_entry(&INVALID_HANDLER), // 0xB1
	to_handler_entry(&INVALID_HANDLER), // 0xB2
	to_handler_entry(&INVALID_HANDLER), // 0xB3
	to_handler_entry(&INVALID_HANDLER), // 0xB4
	to_handler_entry(&INVALID_HANDLER), // 0xB5
	to_handler_entry(&INVALID_HANDLER), // 0xB6
	to_handler_entry(&INVALID_HANDLER), // 0xB7
	to_handler_entry(&INVALID_HANDLER), // 0xB8
	to_handler_entry(&INVALID_HANDLER), // 0xB9
	to_handler_entry(&INVALID_HANDLER), // 0xBA
	to_handler_entry(&INVALID_HANDLER), // 0xBB
	to_handler_entry(&INVALID_HANDLER), // 0xBC
	to_handler_entry(&INVALID_HANDLER), // 0xBD
	to_handler_entry(&INVALID_HANDLER), // 0xBE
	to_handler_entry(&INVALID_HANDLER), // 0xBF
	to_handler_entry(&INVALID_HANDLER), // 0xC0
	to_handler_entry(&INVALID_HANDLER), // 0xC1
	to_handler_entry(&H504), // 0xC2
	to_handler_entry(&INVALID_HANDLER), // 0xC3
	to_handler_entry(&INVALID_HANDLER), // 0xC4
	to_handler_entry(&INVALID_HANDLER), // 0xC5
	to_handler_entry(&INVALID_HANDLER), // 0xC6
	to_handler_entry(&INVALID_HANDLER), // 0xC7
	to_handler_entry(&INVALID_HANDLER), // 0xC8
	to_handler_entry(&INVALID_HANDLER), // 0xC9
	to_handler_entry(&INVALID_HANDLER), // 0xCA
	to_handler_entry(&INVALID_HANDLER), // 0xCB
	to_handler_entry(&INVALID_HANDLER), // 0xCC
	to_handler_entry(&INVALID_HANDLER), // 0xCD
	to_handler_entry(&INVALID_HANDLER), // 0xCE
	to_handler_entry(&INVALID_HANDLER), // 0xCF
	to_handler_entry(&INVALID_HANDLER), // 0xD0
	to_handler_entry(&INVALID_HANDLER), // 0xD1
	to_handler_entry(&INVALID_HANDLER), // 0xD2
	to_handler_entry(&INVALID_HANDLER), // 0xD3
	to_handler_entry(&INVALID_HANDLER), // 0xD4
	to_handler_entry(&INVALID_HANDLER), // 0xD5
	to_handler_entry(&INVALID_HANDLER), // 0xD6
	to_handler_entry(&INVALID_HANDLER), // 0xD7
	to_handler_entry(&INVALID_HANDLER), // 0xD8
	to_handler_entry(&INVALID_HANDLER), // 0xD9
	to_handler_entry(&INVALID_HANDLER), // 0xDA
	to_handler_entry(&H508), // 0xDB
	to_handler_entry(&INVALID_HANDLER), // 0xDC
	to_handler_entry(&INVALID_HANDLER), // 0xDD
	to_handler_entry(&INVALID_HANDLER), // 0xDE
	to_handler_entry(&H512), // 0xDF
	to_handler_entry(&INVALID_HANDLER), // 0xE0
	to_handler_entry(&INVALID_HANDLER), // 0xE1
	to_handler_entry(&INVALID_HANDLER), // 0xE2
	to_handler_entry(&INVALID_HANDLER), // 0xE3
	to_handler_entry(&INVALID_HANDLER), // 0xE4
	to_handler_entry(&INVALID_HANDLER), // 0xE5
	to_handler_entry(&H515), // 0xE6
	to_handler_entry(&INVALID_HANDLER), // 0xE7
	to_handler_entry(&INVALID_HANDLER), // 0xE8
	to_handler_entry(&INVALID_HANDLER), // 0xE9
	to_handler_entry(&INVALID_HANDLER), // 0xEA
	to_handler_entry(&H519), // 0xEB
	to_handler_entry(&INVALID_HANDLER), // 0xEC
	to_handler_entry(&INVALID_HANDLER), // 0xED
	to_handler_entry(&INVALID_HANDLER), // 0xEE
	to_handler_entry(&H523), // 0xEF
	to_handler_entry(&INVALID_HANDLER), // 0xF0
	to_handler_entry(&INVALID_HANDLER), // 0xF1
	to_handler_entry(&INVALID_HANDLER), // 0xF2
	to_handler_entry(&INVALID_HANDLER), // 0xF3
	to_handler_entry(&INVALID_HANDLER), // 0xF4
	to_handler_entry(&INVALID_HANDLER), // 0xF5
	to_handler_entry(&INVALID_HANDLER), // 0xF6
	to_handler_entry(&INVALID_HANDLER), // 0xF7
	to_handler_entry(&INVALID_HANDLER), // 0xF8
	to_handler_entry(&INVALID_HANDLER), // 0xF9
	to_handler_entry(&H526), // 0xFA
	to_handler_entry(&INVALID_HANDLER), // 0xFB
	to_handler_entry(&INVALID_HANDLER), // 0xFC
	to_handler_entry(&INVALID_HANDLER), // 0xFD
	to_handler_entry(&H529), // 0xFE
	to_handler_entry(&INVALID_HANDLER), // 0xFF
};
// clang-format on

} // namespace iced_x86::internal::decoder_data_mvex
