// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#include "internal/decoder/data_xop.hpp"
#include "internal/decoder/vex_ctors.hpp"

namespace iced_x86::internal::decoder_data_xop {

// clang-format off
constexpr auto H0 = vex_ctors::Hv_Ev(Code::XOP_Blcfill_r32_rm32, Code::XOP_Blcfill_r64_rm64);
constexpr auto H1 = vex_ctors::VectorLength(&H0, &INVALID_HANDLER);
constexpr auto H2 = vex_ctors::MandatoryPrefix2_1(&H1);
constexpr auto H3 = vex_ctors::Hv_Ev(Code::XOP_Blsfill_r32_rm32, Code::XOP_Blsfill_r64_rm64);
constexpr auto H4 = vex_ctors::VectorLength(&H3, &INVALID_HANDLER);
constexpr auto H5 = vex_ctors::MandatoryPrefix2_1(&H4);
constexpr auto H6 = vex_ctors::Hv_Ev(Code::XOP_Blcs_r32_rm32, Code::XOP_Blcs_r64_rm64);
constexpr auto H7 = vex_ctors::VectorLength(&H6, &INVALID_HANDLER);
constexpr auto H8 = vex_ctors::MandatoryPrefix2_1(&H7);
constexpr auto H9 = vex_ctors::Hv_Ev(Code::XOP_Tzmsk_r32_rm32, Code::XOP_Tzmsk_r64_rm64);
constexpr auto H10 = vex_ctors::VectorLength(&H9, &INVALID_HANDLER);
constexpr auto H11 = vex_ctors::MandatoryPrefix2_1(&H10);
constexpr auto H12 = vex_ctors::Hv_Ev(Code::XOP_Blcic_r32_rm32, Code::XOP_Blcic_r64_rm64);
constexpr auto H13 = vex_ctors::VectorLength(&H12, &INVALID_HANDLER);
constexpr auto H14 = vex_ctors::MandatoryPrefix2_1(&H13);
constexpr auto H15 = vex_ctors::Hv_Ev(Code::XOP_Blsic_r32_rm32, Code::XOP_Blsic_r64_rm64);
constexpr auto H16 = vex_ctors::VectorLength(&H15, &INVALID_HANDLER);
constexpr auto H17 = vex_ctors::MandatoryPrefix2_1(&H16);
constexpr auto H18 = vex_ctors::Hv_Ev(Code::XOP_T1mskc_r32_rm32, Code::XOP_T1mskc_r64_rm64);
constexpr auto H19 = vex_ctors::VectorLength(&H18, &INVALID_HANDLER);
constexpr auto H20 = vex_ctors::MandatoryPrefix2_1(&H19);
constexpr auto H21 = vex_ctors::Hv_Ev(Code::XOP_Blcmsk_r32_rm32, Code::XOP_Blcmsk_r64_rm64);
constexpr auto H22 = vex_ctors::VectorLength(&H21, &INVALID_HANDLER);
constexpr auto H23 = vex_ctors::MandatoryPrefix2_1(&H22);
constexpr auto H24 = vex_ctors::Hv_Ev(Code::XOP_Blci_r32_rm32, Code::XOP_Blci_r64_rm64);
constexpr auto H25 = vex_ctors::VectorLength(&H24, &INVALID_HANDLER);
constexpr auto H26 = vex_ctors::MandatoryPrefix2_1(&H25);
constexpr auto H27 = vex_ctors::RdRq(Code::XOP_Llwpcb_r32, Code::XOP_Llwpcb_r64);
constexpr auto H28 = vex_ctors::VectorLength(&H27, &INVALID_HANDLER);
constexpr auto H29 = vex_ctors::MandatoryPrefix2_1(&H28);
constexpr auto H30 = vex_ctors::RdRq(Code::XOP_Slwpcb_r32, Code::XOP_Slwpcb_r64);
constexpr auto H31 = vex_ctors::VectorLength(&H30, &INVALID_HANDLER);
constexpr auto H32 = vex_ctors::MandatoryPrefix2_1(&H31);
constexpr auto H33 = vex_ctors::Hv_Ed_Id(Code::XOP_Lwpins_r32_rm32_imm32, Code::XOP_Lwpins_r64_rm32_imm32);
constexpr auto H34 = vex_ctors::VectorLength(&H33, &INVALID_HANDLER);
constexpr auto H35 = vex_ctors::MandatoryPrefix2_1(&H34);
constexpr auto H36 = vex_ctors::Hv_Ed_Id(Code::XOP_Lwpval_r32_rm32_imm32, Code::XOP_Lwpval_r64_rm32_imm32);
constexpr auto H37 = vex_ctors::VectorLength(&H36, &INVALID_HANDLER);
constexpr auto H38 = vex_ctors::MandatoryPrefix2_1(&H37);
constexpr auto H39 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacssww_xmm_xmm_xmmm128_xmm);
constexpr auto H40 = vex_ctors::W(&H39, &INVALID_HANDLER);
constexpr auto H41 = vex_ctors::VectorLength(&H40, &INVALID_HANDLER);
constexpr auto H42 = vex_ctors::MandatoryPrefix2_1(&H41);
constexpr auto H43 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacsswd_xmm_xmm_xmmm128_xmm);
constexpr auto H44 = vex_ctors::W(&H43, &INVALID_HANDLER);
constexpr auto H45 = vex_ctors::VectorLength(&H44, &INVALID_HANDLER);
constexpr auto H46 = vex_ctors::MandatoryPrefix2_1(&H45);
constexpr auto H47 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacssdql_xmm_xmm_xmmm128_xmm);
constexpr auto H48 = vex_ctors::W(&H47, &INVALID_HANDLER);
constexpr auto H49 = vex_ctors::VectorLength(&H48, &INVALID_HANDLER);
constexpr auto H50 = vex_ctors::MandatoryPrefix2_1(&H49);
constexpr auto H51 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacssdd_xmm_xmm_xmmm128_xmm);
constexpr auto H52 = vex_ctors::W(&H51, &INVALID_HANDLER);
constexpr auto H53 = vex_ctors::VectorLength(&H52, &INVALID_HANDLER);
constexpr auto H54 = vex_ctors::MandatoryPrefix2_1(&H53);
constexpr auto H55 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacssdqh_xmm_xmm_xmmm128_xmm);
constexpr auto H56 = vex_ctors::W(&H55, &INVALID_HANDLER);
constexpr auto H57 = vex_ctors::VectorLength(&H56, &INVALID_HANDLER);
constexpr auto H58 = vex_ctors::MandatoryPrefix2_1(&H57);
constexpr auto H59 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacsww_xmm_xmm_xmmm128_xmm);
constexpr auto H60 = vex_ctors::W(&H59, &INVALID_HANDLER);
constexpr auto H61 = vex_ctors::VectorLength(&H60, &INVALID_HANDLER);
constexpr auto H62 = vex_ctors::MandatoryPrefix2_1(&H61);
constexpr auto H63 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacswd_xmm_xmm_xmmm128_xmm);
constexpr auto H64 = vex_ctors::W(&H63, &INVALID_HANDLER);
constexpr auto H65 = vex_ctors::VectorLength(&H64, &INVALID_HANDLER);
constexpr auto H66 = vex_ctors::MandatoryPrefix2_1(&H65);
constexpr auto H67 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacsdql_xmm_xmm_xmmm128_xmm);
constexpr auto H68 = vex_ctors::W(&H67, &INVALID_HANDLER);
constexpr auto H69 = vex_ctors::VectorLength(&H68, &INVALID_HANDLER);
constexpr auto H70 = vex_ctors::MandatoryPrefix2_1(&H69);
constexpr auto H71 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacsdd_xmm_xmm_xmmm128_xmm);
constexpr auto H72 = vex_ctors::W(&H71, &INVALID_HANDLER);
constexpr auto H73 = vex_ctors::VectorLength(&H72, &INVALID_HANDLER);
constexpr auto H74 = vex_ctors::MandatoryPrefix2_1(&H73);
constexpr auto H75 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmacsdqh_xmm_xmm_xmmm128_xmm);
constexpr auto H76 = vex_ctors::W(&H75, &INVALID_HANDLER);
constexpr auto H77 = vex_ctors::VectorLength(&H76, &INVALID_HANDLER);
constexpr auto H78 = vex_ctors::MandatoryPrefix2_1(&H77);
constexpr auto H79 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpcmov_xmm_xmm_xmmm128_xmm);
constexpr auto H80 = vex_ctors::VHWIs4(Register::YMM0, Code::XOP_Vpcmov_ymm_ymm_ymmm256_ymm);
constexpr auto H81 = vex_ctors::VectorLength(&H79, &H80);
constexpr auto H82 = vex_ctors::VHIs4W(Register::XMM0, Code::XOP_Vpcmov_xmm_xmm_xmm_xmmm128);
constexpr auto H83 = vex_ctors::VHIs4W(Register::YMM0, Code::XOP_Vpcmov_ymm_ymm_ymm_ymmm256);
constexpr auto H84 = vex_ctors::VectorLength(&H82, &H83);
constexpr auto H85 = vex_ctors::W(&H81, &H84);
constexpr auto H86 = vex_ctors::MandatoryPrefix2_1(&H85);
constexpr auto H87 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpperm_xmm_xmm_xmmm128_xmm);
constexpr auto H88 = vex_ctors::VectorLength(&H87, &INVALID_HANDLER);
constexpr auto H89 = vex_ctors::VHIs4W(Register::XMM0, Code::XOP_Vpperm_xmm_xmm_xmm_xmmm128);
constexpr auto H90 = vex_ctors::VectorLength(&H89, &INVALID_HANDLER);
constexpr auto H91 = vex_ctors::W(&H88, &H90);
constexpr auto H92 = vex_ctors::MandatoryPrefix2_1(&H91);
constexpr auto H93 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmadcsswd_xmm_xmm_xmmm128_xmm);
constexpr auto H94 = vex_ctors::W(&H93, &INVALID_HANDLER);
constexpr auto H95 = vex_ctors::VectorLength(&H94, &INVALID_HANDLER);
constexpr auto H96 = vex_ctors::MandatoryPrefix2_1(&H95);
constexpr auto H97 = vex_ctors::VHWIs4(Register::XMM0, Code::XOP_Vpmadcswd_xmm_xmm_xmmm128_xmm);
constexpr auto H98 = vex_ctors::W(&H97, &INVALID_HANDLER);
constexpr auto H99 = vex_ctors::VectorLength(&H98, &INVALID_HANDLER);
constexpr auto H100 = vex_ctors::MandatoryPrefix2_1(&H99);
constexpr auto H101 = vex_ctors::VWIb_2(Register::XMM0, Code::XOP_Vprotb_xmm_xmmm128_imm8);
constexpr auto H102 = vex_ctors::W(&H101, &INVALID_HANDLER);
constexpr auto H103 = vex_ctors::VectorLength(&H102, &INVALID_HANDLER);
constexpr auto H104 = vex_ctors::MandatoryPrefix2_1(&H103);
constexpr auto H105 = vex_ctors::VWIb_2(Register::XMM0, Code::XOP_Vprotw_xmm_xmmm128_imm8);
constexpr auto H106 = vex_ctors::W(&H105, &INVALID_HANDLER);
constexpr auto H107 = vex_ctors::VectorLength(&H106, &INVALID_HANDLER);
constexpr auto H108 = vex_ctors::MandatoryPrefix2_1(&H107);
constexpr auto H109 = vex_ctors::VWIb_2(Register::XMM0, Code::XOP_Vprotd_xmm_xmmm128_imm8);
constexpr auto H110 = vex_ctors::W(&H109, &INVALID_HANDLER);
constexpr auto H111 = vex_ctors::VectorLength(&H110, &INVALID_HANDLER);
constexpr auto H112 = vex_ctors::MandatoryPrefix2_1(&H111);
constexpr auto H113 = vex_ctors::VWIb_2(Register::XMM0, Code::XOP_Vprotq_xmm_xmmm128_imm8);
constexpr auto H114 = vex_ctors::W(&H113, &INVALID_HANDLER);
constexpr auto H115 = vex_ctors::VectorLength(&H114, &INVALID_HANDLER);
constexpr auto H116 = vex_ctors::MandatoryPrefix2_1(&H115);
constexpr auto H117 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomb_xmm_xmm_xmmm128_imm8);
constexpr auto H118 = vex_ctors::W(&H117, &INVALID_HANDLER);
constexpr auto H119 = vex_ctors::VectorLength(&H118, &INVALID_HANDLER);
constexpr auto H120 = vex_ctors::MandatoryPrefix2_1(&H119);
constexpr auto H121 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomw_xmm_xmm_xmmm128_imm8);
constexpr auto H122 = vex_ctors::W(&H121, &INVALID_HANDLER);
constexpr auto H123 = vex_ctors::VectorLength(&H122, &INVALID_HANDLER);
constexpr auto H124 = vex_ctors::MandatoryPrefix2_1(&H123);
constexpr auto H125 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomd_xmm_xmm_xmmm128_imm8);
constexpr auto H126 = vex_ctors::W(&H125, &INVALID_HANDLER);
constexpr auto H127 = vex_ctors::VectorLength(&H126, &INVALID_HANDLER);
constexpr auto H128 = vex_ctors::MandatoryPrefix2_1(&H127);
constexpr auto H129 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomq_xmm_xmm_xmmm128_imm8);
constexpr auto H130 = vex_ctors::W(&H129, &INVALID_HANDLER);
constexpr auto H131 = vex_ctors::VectorLength(&H130, &INVALID_HANDLER);
constexpr auto H132 = vex_ctors::MandatoryPrefix2_1(&H131);
constexpr auto H133 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomub_xmm_xmm_xmmm128_imm8);
constexpr auto H134 = vex_ctors::W(&H133, &INVALID_HANDLER);
constexpr auto H135 = vex_ctors::VectorLength(&H134, &INVALID_HANDLER);
constexpr auto H136 = vex_ctors::MandatoryPrefix2_1(&H135);
constexpr auto H137 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomuw_xmm_xmm_xmmm128_imm8);
constexpr auto H138 = vex_ctors::W(&H137, &INVALID_HANDLER);
constexpr auto H139 = vex_ctors::VectorLength(&H138, &INVALID_HANDLER);
constexpr auto H140 = vex_ctors::MandatoryPrefix2_1(&H139);
constexpr auto H141 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomud_xmm_xmm_xmmm128_imm8);
constexpr auto H142 = vex_ctors::W(&H141, &INVALID_HANDLER);
constexpr auto H143 = vex_ctors::VectorLength(&H142, &INVALID_HANDLER);
constexpr auto H144 = vex_ctors::MandatoryPrefix2_1(&H143);
constexpr auto H145 = vex_ctors::VHWIb_2(Register::XMM0, Code::XOP_Vpcomuq_xmm_xmm_xmmm128_imm8);
constexpr auto H146 = vex_ctors::W(&H145, &INVALID_HANDLER);
constexpr auto H147 = vex_ctors::VectorLength(&H146, &INVALID_HANDLER);
constexpr auto H148 = vex_ctors::MandatoryPrefix2_1(&H147);
constexpr HandlerEntry HANDLERS_MAP8[0x100] = {
	to_handler_entry(&INVALID_HANDLER), // 0x00
	to_handler_entry(&INVALID_HANDLER), // 0x01
	to_handler_entry(&INVALID_HANDLER), // 0x02
	to_handler_entry(&INVALID_HANDLER), // 0x03
	to_handler_entry(&INVALID_HANDLER), // 0x04
	to_handler_entry(&INVALID_HANDLER), // 0x05
	to_handler_entry(&INVALID_HANDLER), // 0x06
	to_handler_entry(&INVALID_HANDLER), // 0x07
	to_handler_entry(&INVALID_HANDLER), // 0x08
	to_handler_entry(&INVALID_HANDLER), // 0x09
	to_handler_entry(&INVALID_HANDLER), // 0x0A
	to_handler_entry(&INVALID_HANDLER), // 0x0B
	to_handler_entry(&INVALID_HANDLER), // 0x0C
	to_handler_entry(&INVALID_HANDLER), // 0x0D
	to_handler_entry(&INVALID_HANDLER), // 0x0E
	to_handler_entry(&INVALID_HANDLER), // 0x0F
	to_handler_entry(&INVALID_HANDLER), // 0x10
	to_handler_entry(&INVALID_HANDLER), // 0x11
	to_handler_entry(&INVALID_HANDLER), // 0x12
	to_handler_entry(&INVALID_HANDLER), // 0x13
	to_handler_entry(&INVALID_HANDLER), // 0x14
	to_handler_entry(&INVALID_HANDLER), // 0x15
	to_handler_entry(&INVALID_HANDLER), // 0x16
	to_handler_entry(&INVALID_HANDLER), // 0x17
	to_handler_entry(&INVALID_HANDLER), // 0x18
	to_handler_entry(&INVALID_HANDLER), // 0x19
	to_handler_entry(&INVALID_HANDLER), // 0x1A
	to_handler_entry(&INVALID_HANDLER), // 0x1B
	to_handler_entry(&INVALID_HANDLER), // 0x1C
	to_handler_entry(&INVALID_HANDLER), // 0x1D
	to_handler_entry(&INVALID_HANDLER), // 0x1E
	to_handler_entry(&INVALID_HANDLER), // 0x1F
	to_handler_entry(&INVALID_HANDLER), // 0x20
	to_handler_entry(&INVALID_HANDLER), // 0x21
	to_handler_entry(&INVALID_HANDLER), // 0x22
	to_handler_entry(&INVALID_HANDLER), // 0x23
	to_handler_entry(&INVALID_HANDLER), // 0x24
	to_handler_entry(&INVALID_HANDLER), // 0x25
	to_handler_entry(&INVALID_HANDLER), // 0x26
	to_handler_entry(&INVALID_HANDLER), // 0x27
	to_handler_entry(&INVALID_HANDLER), // 0x28
	to_handler_entry(&INVALID_HANDLER), // 0x29
	to_handler_entry(&INVALID_HANDLER), // 0x2A
	to_handler_entry(&INVALID_HANDLER), // 0x2B
	to_handler_entry(&INVALID_HANDLER), // 0x2C
	to_handler_entry(&INVALID_HANDLER), // 0x2D
	to_handler_entry(&INVALID_HANDLER), // 0x2E
	to_handler_entry(&INVALID_HANDLER), // 0x2F
	to_handler_entry(&INVALID_HANDLER), // 0x30
	to_handler_entry(&INVALID_HANDLER), // 0x31
	to_handler_entry(&INVALID_HANDLER), // 0x32
	to_handler_entry(&INVALID_HANDLER), // 0x33
	to_handler_entry(&INVALID_HANDLER), // 0x34
	to_handler_entry(&INVALID_HANDLER), // 0x35
	to_handler_entry(&INVALID_HANDLER), // 0x36
	to_handler_entry(&INVALID_HANDLER), // 0x37
	to_handler_entry(&INVALID_HANDLER), // 0x38
	to_handler_entry(&INVALID_HANDLER), // 0x39
	to_handler_entry(&INVALID_HANDLER), // 0x3A
	to_handler_entry(&INVALID_HANDLER), // 0x3B
	to_handler_entry(&INVALID_HANDLER), // 0x3C
	to_handler_entry(&INVALID_HANDLER), // 0x3D
	to_handler_entry(&INVALID_HANDLER), // 0x3E
	to_handler_entry(&INVALID_HANDLER), // 0x3F
	to_handler_entry(&INVALID_HANDLER), // 0x40
	to_handler_entry(&INVALID_HANDLER), // 0x41
	to_handler_entry(&INVALID_HANDLER), // 0x42
	to_handler_entry(&INVALID_HANDLER), // 0x43
	to_handler_entry(&INVALID_HANDLER), // 0x44
	to_handler_entry(&INVALID_HANDLER), // 0x45
	to_handler_entry(&INVALID_HANDLER), // 0x46
	to_handler_entry(&INVALID_HANDLER), // 0x47
	to_handler_entry(&INVALID_HANDLER), // 0x48
	to_handler_entry(&INVALID_HANDLER), // 0x49
	to_handler_entry(&INVALID_HANDLER), // 0x4A
	to_handler_entry(&INVALID_HANDLER), // 0x4B
	to_handler_entry(&INVALID_HANDLER), // 0x4C
	to_handler_entry(&INVALID_HANDLER), // 0x4D
	to_handler_entry(&INVALID_HANDLER), // 0x4E
	to_handler_entry(&INVALID_HANDLER), // 0x4F
	to_handler_entry(&INVALID_HANDLER), // 0x50
	to_handler_entry(&INVALID_HANDLER), // 0x51
	to_handler_entry(&INVALID_HANDLER), // 0x52
	to_handler_entry(&INVALID_HANDLER), // 0x53
	to_handler_entry(&INVALID_HANDLER), // 0x54
	to_handler_entry(&INVALID_HANDLER), // 0x55
	to_handler_entry(&INVALID_HANDLER), // 0x56
	to_handler_entry(&INVALID_HANDLER), // 0x57
	to_handler_entry(&INVALID_HANDLER), // 0x58
	to_handler_entry(&INVALID_HANDLER), // 0x59
	to_handler_entry(&INVALID_HANDLER), // 0x5A
	to_handler_entry(&INVALID_HANDLER), // 0x5B
	to_handler_entry(&INVALID_HANDLER), // 0x5C
	to_handler_entry(&INVALID_HANDLER), // 0x5D
	to_handler_entry(&INVALID_HANDLER), // 0x5E
	to_handler_entry(&INVALID_HANDLER), // 0x5F
	to_handler_entry(&INVALID_HANDLER), // 0x60
	to_handler_entry(&INVALID_HANDLER), // 0x61
	to_handler_entry(&INVALID_HANDLER), // 0x62
	to_handler_entry(&INVALID_HANDLER), // 0x63
	to_handler_entry(&INVALID_HANDLER), // 0x64
	to_handler_entry(&INVALID_HANDLER), // 0x65
	to_handler_entry(&INVALID_HANDLER), // 0x66
	to_handler_entry(&INVALID_HANDLER), // 0x67
	to_handler_entry(&INVALID_HANDLER), // 0x68
	to_handler_entry(&INVALID_HANDLER), // 0x69
	to_handler_entry(&INVALID_HANDLER), // 0x6A
	to_handler_entry(&INVALID_HANDLER), // 0x6B
	to_handler_entry(&INVALID_HANDLER), // 0x6C
	to_handler_entry(&INVALID_HANDLER), // 0x6D
	to_handler_entry(&INVALID_HANDLER), // 0x6E
	to_handler_entry(&INVALID_HANDLER), // 0x6F
	to_handler_entry(&INVALID_HANDLER), // 0x70
	to_handler_entry(&INVALID_HANDLER), // 0x71
	to_handler_entry(&INVALID_HANDLER), // 0x72
	to_handler_entry(&INVALID_HANDLER), // 0x73
	to_handler_entry(&INVALID_HANDLER), // 0x74
	to_handler_entry(&INVALID_HANDLER), // 0x75
	to_handler_entry(&INVALID_HANDLER), // 0x76
	to_handler_entry(&INVALID_HANDLER), // 0x77
	to_handler_entry(&INVALID_HANDLER), // 0x78
	to_handler_entry(&INVALID_HANDLER), // 0x79
	to_handler_entry(&INVALID_HANDLER), // 0x7A
	to_handler_entry(&INVALID_HANDLER), // 0x7B
	to_handler_entry(&INVALID_HANDLER), // 0x7C
	to_handler_entry(&INVALID_HANDLER), // 0x7D
	to_handler_entry(&INVALID_HANDLER), // 0x7E
	to_handler_entry(&INVALID_HANDLER), // 0x7F
	to_handler_entry(&INVALID_HANDLER), // 0x80
	to_handler_entry(&INVALID_HANDLER), // 0x81
	to_handler_entry(&INVALID_HANDLER), // 0x82
	to_handler_entry(&INVALID_HANDLER), // 0x83
	to_handler_entry(&INVALID_HANDLER), // 0x84
	to_handler_entry(&H42), // 0x85
	to_handler_entry(&H46), // 0x86
	to_handler_entry(&H50), // 0x87
	to_handler_entry(&INVALID_HANDLER), // 0x88
	to_handler_entry(&INVALID_HANDLER), // 0x89
	to_handler_entry(&INVALID_HANDLER), // 0x8A
	to_handler_entry(&INVALID_HANDLER), // 0x8B
	to_handler_entry(&INVALID_HANDLER), // 0x8C
	to_handler_entry(&INVALID_HANDLER), // 0x8D
	to_handler_entry(&H54), // 0x8E
	to_handler_entry(&H58), // 0x8F
	to_handler_entry(&INVALID_HANDLER), // 0x90
	to_handler_entry(&INVALID_HANDLER), // 0x91
	to_handler_entry(&INVALID_HANDLER), // 0x92
	to_handler_entry(&INVALID_HANDLER), // 0x93
	to_handler_entry(&INVALID_HANDLER), // 0x94
	to_handler_entry(&H62), // 0x95
	to_handler_entry(&H66), // 0x96
	to_handler_entry(&H70), // 0x97
	to_handler_entry(&INVALID_HANDLER), // 0x98
	to_handler_entry(&INVALID_HANDLER), // 0x99
	to_handler_entry(&INVALID_HANDLER), // 0x9A
	to_handler_entry(&INVALID_HANDLER), // 0x9B
	to_handler_entry(&INVALID_HANDLER), // 0x9C
	to_handler_entry(&INVALID_HANDLER), // 0x9D
	to_handler_entry(&H74), // 0x9E
	to_handler_entry(&H78), // 0x9F
	to_handler_entry(&INVALID_HANDLER), // 0xA0
	to_handler_entry(&INVALID_HANDLER), // 0xA1
	to_handler_entry(&H86), // 0xA2
	to_handler_entry(&H92), // 0xA3
	to_handler_entry(&INVALID_HANDLER), // 0xA4
	to_handler_entry(&INVALID_HANDLER), // 0xA5
	to_handler_entry(&H96), // 0xA6
	to_handler_entry(&INVALID_HANDLER), // 0xA7
	to_handler_entry(&INVALID_HANDLER), // 0xA8
	to_handler_entry(&INVALID_HANDLER), // 0xA9
	to_handler_entry(&INVALID_HANDLER), // 0xAA
	to_handler_entry(&INVALID_HANDLER), // 0xAB
	to_handler_entry(&INVALID_HANDLER), // 0xAC
	to_handler_entry(&INVALID_HANDLER), // 0xAD
	to_handler_entry(&INVALID_HANDLER), // 0xAE
	to_handler_entry(&INVALID_HANDLER), // 0xAF
	to_handler_entry(&INVALID_HANDLER), // 0xB0
	to_handler_entry(&INVALID_HANDLER), // 0xB1
	to_handler_entry(&INVALID_HANDLER), // 0xB2
	to_handler_entry(&INVALID_HANDLER), // 0xB3
	to_handler_entry(&INVALID_HANDLER), // 0xB4
	to_handler_entry(&INVALID_HANDLER), // 0xB5
	to_handler_entry(&H100), // 0xB6
	to_handler_entry(&INVALID_HANDLER), // 0xB7
	to_handler_entry(&INVALID_HANDLER), // 0xB8
	to_handler_entry(&INVALID_HANDLER), // 0xB9
	to_handler_entry(&INVALID_HANDLER), // 0xBA
	to_handler_entry(&INVALID_HANDLER), // 0xBB
	to_handler_entry(&INVALID_HANDLER), // 0xBC
	to_handler_entry(&INVALID_HANDLER), // 0xBD
	to_handler_entry(&INVALID_HANDLER), // 0xBE
	to_handler_entry(&INVALID_HANDLER), // 0xBF
	to_handler_entry(&H104), // 0xC0
	to_handler_entry(&H108), // 0xC1
	to_handler_entry(&H112), // 0xC2
	to_handler_entry(&H116), // 0xC3
	to_handler_entry(&INVALID_HANDLER), // 0xC4
	to_handler_entry(&INVALID_HANDLER), // 0xC5
	to_handler_entry(&INVALID_HANDLER), // 0xC6
	to_handler_entry(&INVALID_HANDLER), // 0xC7
	to_handler_entry(&INVALID_HANDLER), // 0xC8
	to_handler_entry(&INVALID_HANDLER), // 0xC9
	to_handler_entry(&INVALID_HANDLER), // 0xCA
	to_handler_entry(&INVALID_HANDLER), // 0xCB
	to_handler_entry(&H120), // 0xCC
	to_handler_entry(&H124), // 0xCD
	to_handler_entry(&H128), // 0xCE
	to_handler_entry(&H132), // 0xCF
	to_handler_entry(&INVALID_HANDLER), // 0xD0
	to_handler_entry(&INVALID_HANDLER), // 0xD1
	to_handler_entry(&INVALID_HANDLER), // 0xD2
	to_handler_entry(&INVALID_HANDLER), // 0xD3
	to_handler_entry(&INVALID_HANDLER), // 0xD4
	to_handler_entry(&INVALID_HANDLER), // 0xD5
	to_handler_entry(&INVALID_HANDLER), // 0xD6
	to_handler_entry(&INVALID_HANDLER), // 0xD7
	to_handler_entry(&INVALID_HANDLER), // 0xD8
	to_handler_entry(&INVALID_HANDLER), // 0xD9
	to_handler_entry(&INVALID_HANDLER), // 0xDA
	to_handler_entry(&INVALID_HANDLER), // 0xDB
	to_handler_entry(&INVALID_HANDLER), // 0xDC
	to_handler_entry(&INVALID_HANDLER), // 0xDD
	to_handler_entry(&INVALID_HANDLER), // 0xDE
	to_handler_entry(&INVALID_HANDLER), // 0xDF
	to_handler_entry(&INVALID_HANDLER), // 0xE0
	to_handler_entry(&INVALID_HANDLER), // 0xE1
	to_handler_entry(&INVALID_HANDLER), // 0xE2
	to_handler_entry(&INVALID_HANDLER), // 0xE3
	to_handler_entry(&INVALID_HANDLER), // 0xE4
	to_handler_entry(&INVALID_HANDLER), // 0xE5
	to_handler_entry(&INVALID_HANDLER), // 0xE6
	to_handler_entry(&INVALID_HANDLER), // 0xE7
	to_handler_entry(&INVALID_HANDLER), // 0xE8
	to_handler_entry(&INVALID_HANDLER), // 0xE9
	to_handler_entry(&INVALID_HANDLER), // 0xEA
	to_handler_entry(&INVALID_HANDLER), // 0xEB
	to_handler_entry(&H136), // 0xEC
	to_handler_entry(&H140), // 0xED
	to_handler_entry(&H144), // 0xEE
	to_handler_entry(&H148), // 0xEF
	to_handler_entry(&INVALID_HANDLER), // 0xF0
	to_handler_entry(&INVALID_HANDLER), // 0xF1
	to_handler_entry(&INVALID_HANDLER), // 0xF2
	to_handler_entry(&INVALID_HANDLER), // 0xF3
	to_handler_entry(&INVALID_HANDLER), // 0xF4
	to_handler_entry(&INVALID_HANDLER), // 0xF5
	to_handler_entry(&INVALID_HANDLER), // 0xF6
	to_handler_entry(&INVALID_HANDLER), // 0xF7
	to_handler_entry(&INVALID_HANDLER), // 0xF8
	to_handler_entry(&INVALID_HANDLER), // 0xF9
	to_handler_entry(&INVALID_HANDLER), // 0xFA
	to_handler_entry(&INVALID_HANDLER), // 0xFB
	to_handler_entry(&INVALID_HANDLER), // 0xFC
	to_handler_entry(&INVALID_HANDLER), // 0xFD
	to_handler_entry(&INVALID_HANDLER), // 0xFE
	to_handler_entry(&INVALID_HANDLER), // 0xFF
};
constexpr auto H149 = vex_ctors::Group({&INVALID_HANDLER, &H2, &H5, &H8, &H11, &H14, &H17, &H20});
constexpr auto H150 = vex_ctors::Group({&INVALID_HANDLER, &H23, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &H26, &INVALID_HANDLER});
constexpr auto H151 = vex_ctors::Group({&H29, &H32, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER});
constexpr auto H152 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vfrczps_xmm_xmmm128);
constexpr auto H153 = vex_ctors::W(&H152, &INVALID_HANDLER);
constexpr auto H154 = vex_ctors::VW_2(Register::YMM0, Code::XOP_Vfrczps_ymm_ymmm256);
constexpr auto H155 = vex_ctors::W(&H154, &INVALID_HANDLER);
constexpr auto H156 = vex_ctors::VectorLength(&H153, &H155);
constexpr auto H157 = vex_ctors::MandatoryPrefix2_1(&H156);
constexpr auto H158 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vfrczpd_xmm_xmmm128);
constexpr auto H159 = vex_ctors::W(&H158, &INVALID_HANDLER);
constexpr auto H160 = vex_ctors::VW_2(Register::YMM0, Code::XOP_Vfrczpd_ymm_ymmm256);
constexpr auto H161 = vex_ctors::W(&H160, &INVALID_HANDLER);
constexpr auto H162 = vex_ctors::VectorLength(&H159, &H161);
constexpr auto H163 = vex_ctors::MandatoryPrefix2_1(&H162);
constexpr auto H164 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vfrczss_xmm_xmmm32);
constexpr auto H165 = vex_ctors::W(&H164, &INVALID_HANDLER);
constexpr auto H166 = vex_ctors::VectorLength(&H165, &INVALID_HANDLER);
constexpr auto H167 = vex_ctors::MandatoryPrefix2_1(&H166);
constexpr auto H168 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vfrczsd_xmm_xmmm64);
constexpr auto H169 = vex_ctors::W(&H168, &INVALID_HANDLER);
constexpr auto H170 = vex_ctors::VectorLength(&H169, &INVALID_HANDLER);
constexpr auto H171 = vex_ctors::MandatoryPrefix2_1(&H170);
constexpr auto H172 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vprotb_xmm_xmmm128_xmm);
constexpr auto H173 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vprotb_xmm_xmm_xmmm128);
constexpr auto H174 = vex_ctors::W(&H172, &H173);
constexpr auto H175 = vex_ctors::VectorLength(&H174, &INVALID_HANDLER);
constexpr auto H176 = vex_ctors::MandatoryPrefix2_1(&H175);
constexpr auto H177 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vprotw_xmm_xmmm128_xmm);
constexpr auto H178 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vprotw_xmm_xmm_xmmm128);
constexpr auto H179 = vex_ctors::W(&H177, &H178);
constexpr auto H180 = vex_ctors::VectorLength(&H179, &INVALID_HANDLER);
constexpr auto H181 = vex_ctors::MandatoryPrefix2_1(&H180);
constexpr auto H182 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vprotd_xmm_xmmm128_xmm);
constexpr auto H183 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vprotd_xmm_xmm_xmmm128);
constexpr auto H184 = vex_ctors::W(&H182, &H183);
constexpr auto H185 = vex_ctors::VectorLength(&H184, &INVALID_HANDLER);
constexpr auto H186 = vex_ctors::MandatoryPrefix2_1(&H185);
constexpr auto H187 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vprotq_xmm_xmmm128_xmm);
constexpr auto H188 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vprotq_xmm_xmm_xmmm128);
constexpr auto H189 = vex_ctors::W(&H187, &H188);
constexpr auto H190 = vex_ctors::VectorLength(&H189, &INVALID_HANDLER);
constexpr auto H191 = vex_ctors::MandatoryPrefix2_1(&H190);
constexpr auto H192 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshlb_xmm_xmmm128_xmm);
constexpr auto H193 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshlb_xmm_xmm_xmmm128);
constexpr auto H194 = vex_ctors::W(&H192, &H193);
constexpr auto H195 = vex_ctors::VectorLength(&H194, &INVALID_HANDLER);
constexpr auto H196 = vex_ctors::MandatoryPrefix2_1(&H195);
constexpr auto H197 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshlw_xmm_xmmm128_xmm);
constexpr auto H198 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshlw_xmm_xmm_xmmm128);
constexpr auto H199 = vex_ctors::W(&H197, &H198);
constexpr auto H200 = vex_ctors::VectorLength(&H199, &INVALID_HANDLER);
constexpr auto H201 = vex_ctors::MandatoryPrefix2_1(&H200);
constexpr auto H202 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshld_xmm_xmmm128_xmm);
constexpr auto H203 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshld_xmm_xmm_xmmm128);
constexpr auto H204 = vex_ctors::W(&H202, &H203);
constexpr auto H205 = vex_ctors::VectorLength(&H204, &INVALID_HANDLER);
constexpr auto H206 = vex_ctors::MandatoryPrefix2_1(&H205);
constexpr auto H207 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshlq_xmm_xmmm128_xmm);
constexpr auto H208 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshlq_xmm_xmm_xmmm128);
constexpr auto H209 = vex_ctors::W(&H207, &H208);
constexpr auto H210 = vex_ctors::VectorLength(&H209, &INVALID_HANDLER);
constexpr auto H211 = vex_ctors::MandatoryPrefix2_1(&H210);
constexpr auto H212 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshab_xmm_xmmm128_xmm);
constexpr auto H213 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshab_xmm_xmm_xmmm128);
constexpr auto H214 = vex_ctors::W(&H212, &H213);
constexpr auto H215 = vex_ctors::VectorLength(&H214, &INVALID_HANDLER);
constexpr auto H216 = vex_ctors::MandatoryPrefix2_1(&H215);
constexpr auto H217 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshaw_xmm_xmmm128_xmm);
constexpr auto H218 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshaw_xmm_xmm_xmmm128);
constexpr auto H219 = vex_ctors::W(&H217, &H218);
constexpr auto H220 = vex_ctors::VectorLength(&H219, &INVALID_HANDLER);
constexpr auto H221 = vex_ctors::MandatoryPrefix2_1(&H220);
constexpr auto H222 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshad_xmm_xmmm128_xmm);
constexpr auto H223 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshad_xmm_xmm_xmmm128);
constexpr auto H224 = vex_ctors::W(&H222, &H223);
constexpr auto H225 = vex_ctors::VectorLength(&H224, &INVALID_HANDLER);
constexpr auto H226 = vex_ctors::MandatoryPrefix2_1(&H225);
constexpr auto H227 = vex_ctors::VWH(Register::XMM0, Code::XOP_Vpshaq_xmm_xmmm128_xmm);
constexpr auto H228 = vex_ctors::VHW_2(Register::XMM0, Code::XOP_Vpshaq_xmm_xmm_xmmm128);
constexpr auto H229 = vex_ctors::W(&H227, &H228);
constexpr auto H230 = vex_ctors::VectorLength(&H229, &INVALID_HANDLER);
constexpr auto H231 = vex_ctors::MandatoryPrefix2_1(&H230);
constexpr auto H232 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddbw_xmm_xmmm128);
constexpr auto H233 = vex_ctors::W(&H232, &INVALID_HANDLER);
constexpr auto H234 = vex_ctors::VectorLength(&H233, &INVALID_HANDLER);
constexpr auto H235 = vex_ctors::MandatoryPrefix2_1(&H234);
constexpr auto H236 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddbd_xmm_xmmm128);
constexpr auto H237 = vex_ctors::W(&H236, &INVALID_HANDLER);
constexpr auto H238 = vex_ctors::VectorLength(&H237, &INVALID_HANDLER);
constexpr auto H239 = vex_ctors::MandatoryPrefix2_1(&H238);
constexpr auto H240 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddbq_xmm_xmmm128);
constexpr auto H241 = vex_ctors::W(&H240, &INVALID_HANDLER);
constexpr auto H242 = vex_ctors::VectorLength(&H241, &INVALID_HANDLER);
constexpr auto H243 = vex_ctors::MandatoryPrefix2_1(&H242);
constexpr auto H244 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddwd_xmm_xmmm128);
constexpr auto H245 = vex_ctors::W(&H244, &INVALID_HANDLER);
constexpr auto H246 = vex_ctors::VectorLength(&H245, &INVALID_HANDLER);
constexpr auto H247 = vex_ctors::MandatoryPrefix2_1(&H246);
constexpr auto H248 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddwq_xmm_xmmm128);
constexpr auto H249 = vex_ctors::W(&H248, &INVALID_HANDLER);
constexpr auto H250 = vex_ctors::VectorLength(&H249, &INVALID_HANDLER);
constexpr auto H251 = vex_ctors::MandatoryPrefix2_1(&H250);
constexpr auto H252 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphadddq_xmm_xmmm128);
constexpr auto H253 = vex_ctors::W(&H252, &INVALID_HANDLER);
constexpr auto H254 = vex_ctors::VectorLength(&H253, &INVALID_HANDLER);
constexpr auto H255 = vex_ctors::MandatoryPrefix2_1(&H254);
constexpr auto H256 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddubw_xmm_xmmm128);
constexpr auto H257 = vex_ctors::W(&H256, &INVALID_HANDLER);
constexpr auto H258 = vex_ctors::VectorLength(&H257, &INVALID_HANDLER);
constexpr auto H259 = vex_ctors::MandatoryPrefix2_1(&H258);
constexpr auto H260 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddubd_xmm_xmmm128);
constexpr auto H261 = vex_ctors::W(&H260, &INVALID_HANDLER);
constexpr auto H262 = vex_ctors::VectorLength(&H261, &INVALID_HANDLER);
constexpr auto H263 = vex_ctors::MandatoryPrefix2_1(&H262);
constexpr auto H264 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddubq_xmm_xmmm128);
constexpr auto H265 = vex_ctors::W(&H264, &INVALID_HANDLER);
constexpr auto H266 = vex_ctors::VectorLength(&H265, &INVALID_HANDLER);
constexpr auto H267 = vex_ctors::MandatoryPrefix2_1(&H266);
constexpr auto H268 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphadduwd_xmm_xmmm128);
constexpr auto H269 = vex_ctors::W(&H268, &INVALID_HANDLER);
constexpr auto H270 = vex_ctors::VectorLength(&H269, &INVALID_HANDLER);
constexpr auto H271 = vex_ctors::MandatoryPrefix2_1(&H270);
constexpr auto H272 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphadduwq_xmm_xmmm128);
constexpr auto H273 = vex_ctors::W(&H272, &INVALID_HANDLER);
constexpr auto H274 = vex_ctors::VectorLength(&H273, &INVALID_HANDLER);
constexpr auto H275 = vex_ctors::MandatoryPrefix2_1(&H274);
constexpr auto H276 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphaddudq_xmm_xmmm128);
constexpr auto H277 = vex_ctors::W(&H276, &INVALID_HANDLER);
constexpr auto H278 = vex_ctors::VectorLength(&H277, &INVALID_HANDLER);
constexpr auto H279 = vex_ctors::MandatoryPrefix2_1(&H278);
constexpr auto H280 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphsubbw_xmm_xmmm128);
constexpr auto H281 = vex_ctors::W(&H280, &INVALID_HANDLER);
constexpr auto H282 = vex_ctors::VectorLength(&H281, &INVALID_HANDLER);
constexpr auto H283 = vex_ctors::MandatoryPrefix2_1(&H282);
constexpr auto H284 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphsubwd_xmm_xmmm128);
constexpr auto H285 = vex_ctors::W(&H284, &INVALID_HANDLER);
constexpr auto H286 = vex_ctors::VectorLength(&H285, &INVALID_HANDLER);
constexpr auto H287 = vex_ctors::MandatoryPrefix2_1(&H286);
constexpr auto H288 = vex_ctors::VW_2(Register::XMM0, Code::XOP_Vphsubdq_xmm_xmmm128);
constexpr auto H289 = vex_ctors::W(&H288, &INVALID_HANDLER);
constexpr auto H290 = vex_ctors::VectorLength(&H289, &INVALID_HANDLER);
constexpr auto H291 = vex_ctors::MandatoryPrefix2_1(&H290);
constexpr HandlerEntry HANDLERS_MAP9[0x100] = {
	to_handler_entry(&INVALID_HANDLER), // 0x00
	to_handler_entry(&H149), // 0x01
	to_handler_entry(&H150), // 0x02
	to_handler_entry(&INVALID_HANDLER), // 0x03
	to_handler_entry(&INVALID_HANDLER), // 0x04
	to_handler_entry(&INVALID_HANDLER), // 0x05
	to_handler_entry(&INVALID_HANDLER), // 0x06
	to_handler_entry(&INVALID_HANDLER), // 0x07
	to_handler_entry(&INVALID_HANDLER), // 0x08
	to_handler_entry(&INVALID_HANDLER), // 0x09
	to_handler_entry(&INVALID_HANDLER), // 0x0A
	to_handler_entry(&INVALID_HANDLER), // 0x0B
	to_handler_entry(&INVALID_HANDLER), // 0x0C
	to_handler_entry(&INVALID_HANDLER), // 0x0D
	to_handler_entry(&INVALID_HANDLER), // 0x0E
	to_handler_entry(&INVALID_HANDLER), // 0x0F
	to_handler_entry(&INVALID_HANDLER), // 0x10
	to_handler_entry(&INVALID_HANDLER), // 0x11
	to_handler_entry(&H151), // 0x12
	to_handler_entry(&INVALID_HANDLER), // 0x13
	to_handler_entry(&INVALID_HANDLER), // 0x14
	to_handler_entry(&INVALID_HANDLER), // 0x15
	to_handler_entry(&INVALID_HANDLER), // 0x16
	to_handler_entry(&INVALID_HANDLER), // 0x17
	to_handler_entry(&INVALID_HANDLER), // 0x18
	to_handler_entry(&INVALID_HANDLER), // 0x19
	to_handler_entry(&INVALID_HANDLER), // 0x1A
	to_handler_entry(&INVALID_HANDLER), // 0x1B
	to_handler_entry(&INVALID_HANDLER), // 0x1C
	to_handler_entry(&INVALID_HANDLER), // 0x1D
	to_handler_entry(&INVALID_HANDLER), // 0x1E
	to_handler_entry(&INVALID_HANDLER), // 0x1F
	to_handler_entry(&INVALID_HANDLER), // 0x20
	to_handler_entry(&INVALID_HANDLER), // 0x21
	to_handler_entry(&INVALID_HANDLER), // 0x22
	to_handler_entry(&INVALID_HANDLER), // 0x23
	to_handler_entry(&INVALID_HANDLER), // 0x24
	to_handler_entry(&INVALID_HANDLER), // 0x25
	to_handler_entry(&INVALID_HANDLER), // 0x26
	to_handler_entry(&INVALID_HANDLER), // 0x27
	to_handler_entry(&INVALID_HANDLER), // 0x28
	to_handler_entry(&INVALID_HANDLER), // 0x29
	to_handler_entry(&INVALID_HANDLER), // 0x2A
	to_handler_entry(&INVALID_HANDLER), // 0x2B
	to_handler_entry(&INVALID_HANDLER), // 0x2C
	to_handler_entry(&INVALID_HANDLER), // 0x2D
	to_handler_entry(&INVALID_HANDLER), // 0x2E
	to_handler_entry(&INVALID_HANDLER), // 0x2F
	to_handler_entry(&INVALID_HANDLER), // 0x30
	to_handler_entry(&INVALID_HANDLER), // 0x31
	to_handler_entry(&INVALID_HANDLER), // 0x32
	to_handler_entry(&INVALID_HANDLER), // 0x33
	to_handler_entry(&INVALID_HANDLER), // 0x34
	to_handler_entry(&INVALID_HANDLER), // 0x35
	to_handler_entry(&INVALID_HANDLER), // 0x36
	to_handler_entry(&INVALID_HANDLER), // 0x37
	to_handler_entry(&INVALID_HANDLER), // 0x38
	to_handler_entry(&INVALID_HANDLER), // 0x39
	to_handler_entry(&INVALID_HANDLER), // 0x3A
	to_handler_entry(&INVALID_HANDLER), // 0x3B
	to_handler_entry(&INVALID_HANDLER), // 0x3C
	to_handler_entry(&INVALID_HANDLER), // 0x3D
	to_handler_entry(&INVALID_HANDLER), // 0x3E
	to_handler_entry(&INVALID_HANDLER), // 0x3F
	to_handler_entry(&INVALID_HANDLER), // 0x40
	to_handler_entry(&INVALID_HANDLER), // 0x41
	to_handler_entry(&INVALID_HANDLER), // 0x42
	to_handler_entry(&INVALID_HANDLER), // 0x43
	to_handler_entry(&INVALID_HANDLER), // 0x44
	to_handler_entry(&INVALID_HANDLER), // 0x45
	to_handler_entry(&INVALID_HANDLER), // 0x46
	to_handler_entry(&INVALID_HANDLER), // 0x47
	to_handler_entry(&INVALID_HANDLER), // 0x48
	to_handler_entry(&INVALID_HANDLER), // 0x49
	to_handler_entry(&INVALID_HANDLER), // 0x4A
	to_handler_entry(&INVALID_HANDLER), // 0x4B
	to_handler_entry(&INVALID_HANDLER), // 0x4C
	to_handler_entry(&INVALID_HANDLER), // 0x4D
	to_handler_entry(&INVALID_HANDLER), // 0x4E
	to_handler_entry(&INVALID_HANDLER), // 0x4F
	to_handler_entry(&INVALID_HANDLER), // 0x50
	to_handler_entry(&INVALID_HANDLER), // 0x51
	to_handler_entry(&INVALID_HANDLER), // 0x52
	to_handler_entry(&INVALID_HANDLER), // 0x53
	to_handler_entry(&INVALID_HANDLER), // 0x54
	to_handler_entry(&INVALID_HANDLER), // 0x55
	to_handler_entry(&INVALID_HANDLER), // 0x56
	to_handler_entry(&INVALID_HANDLER), // 0x57
	to_handler_entry(&INVALID_HANDLER), // 0x58
	to_handler_entry(&INVALID_HANDLER), // 0x59
	to_handler_entry(&INVALID_HANDLER), // 0x5A
	to_handler_entry(&INVALID_HANDLER), // 0x5B
	to_handler_entry(&INVALID_HANDLER), // 0x5C
	to_handler_entry(&INVALID_HANDLER), // 0x5D
	to_handler_entry(&INVALID_HANDLER), // 0x5E
	to_handler_entry(&INVALID_HANDLER), // 0x5F
	to_handler_entry(&INVALID_HANDLER), // 0x60
	to_handler_entry(&INVALID_HANDLER), // 0x61
	to_handler_entry(&INVALID_HANDLER), // 0x62
	to_handler_entry(&INVALID_HANDLER), // 0x63
	to_handler_entry(&INVALID_HANDLER), // 0x64
	to_handler_entry(&INVALID_HANDLER), // 0x65
	to_handler_entry(&INVALID_HANDLER), // 0x66
	to_handler_entry(&INVALID_HANDLER), // 0x67
	to_handler_entry(&INVALID_HANDLER), // 0x68
	to_handler_entry(&INVALID_HANDLER), // 0x69
	to_handler_entry(&INVALID_HANDLER), // 0x6A
	to_handler_entry(&INVALID_HANDLER), // 0x6B
	to_handler_entry(&INVALID_HANDLER), // 0x6C
	to_handler_entry(&INVALID_HANDLER), // 0x6D
	to_handler_entry(&INVALID_HANDLER), // 0x6E
	to_handler_entry(&INVALID_HANDLER), // 0x6F
	to_handler_entry(&INVALID_HANDLER), // 0x70
	to_handler_entry(&INVALID_HANDLER), // 0x71
	to_handler_entry(&INVALID_HANDLER), // 0x72
	to_handler_entry(&INVALID_HANDLER), // 0x73
	to_handler_entry(&INVALID_HANDLER), // 0x74
	to_handler_entry(&INVALID_HANDLER), // 0x75
	to_handler_entry(&INVALID_HANDLER), // 0x76
	to_handler_entry(&INVALID_HANDLER), // 0x77
	to_handler_entry(&INVALID_HANDLER), // 0x78
	to_handler_entry(&INVALID_HANDLER), // 0x79
	to_handler_entry(&INVALID_HANDLER), // 0x7A
	to_handler_entry(&INVALID_HANDLER), // 0x7B
	to_handler_entry(&INVALID_HANDLER), // 0x7C
	to_handler_entry(&INVALID_HANDLER), // 0x7D
	to_handler_entry(&INVALID_HANDLER), // 0x7E
	to_handler_entry(&INVALID_HANDLER), // 0x7F
	to_handler_entry(&H157), // 0x80
	to_handler_entry(&H163), // 0x81
	to_handler_entry(&H167), // 0x82
	to_handler_entry(&H171), // 0x83
	to_handler_entry(&INVALID_HANDLER), // 0x84
	to_handler_entry(&INVALID_HANDLER), // 0x85
	to_handler_entry(&INVALID_HANDLER), // 0x86
	to_handler_entry(&INVALID_HANDLER), // 0x87
	to_handler_entry(&INVALID_HANDLER), // 0x88
	to_handler_entry(&INVALID_HANDLER), // 0x89
	to_handler_entry(&INVALID_HANDLER), // 0x8A
	to_handler_entry(&INVALID_HANDLER), // 0x8B
	to_handler_entry(&INVALID_HANDLER), // 0x8C
	to_handler_entry(&INVALID_HANDLER), // 0x8D
	to_handler_entry(&INVALID_HANDLER), // 0x8E
	to_handler_entry(&INVALID_HANDLER), // 0x8F
	to_handler_entry(&H176), // 0x90
	to_handler_entry(&H181), // 0x91
	to_handler_entry(&H186), // 0x92
	to_handler_entry(&H191), // 0x93
	to_handler_entry(&H196), // 0x94
	to_handler_entry(&H201), // 0x95
	to_handler_entry(&H206), // 0x96
	to_handler_entry(&H211), // 0x97
	to_handler_entry(&H216), // 0x98
	to_handler_entry(&H221), // 0x99
	to_handler_entry(&H226), // 0x9A
	to_handler_entry(&H231), // 0x9B
	to_handler_entry(&INVALID_HANDLER), // 0x9C
	to_handler_entry(&INVALID_HANDLER), // 0x9D
	to_handler_entry(&INVALID_HANDLER), // 0x9E
	to_handler_entry(&INVALID_HANDLER), // 0x9F
	to_handler_entry(&INVALID_HANDLER), // 0xA0
	to_handler_entry(&INVALID_HANDLER), // 0xA1
	to_handler_entry(&INVALID_HANDLER), // 0xA2
	to_handler_entry(&INVALID_HANDLER), // 0xA3
	to_handler_entry(&INVALID_HANDLER), // 0xA4
	to_handler_entry(&INVALID_HANDLER), // 0xA5
	to_handler_entry(&INVALID_HANDLER), // 0xA6
	to_handler_entry(&INVALID_HANDLER), // 0xA7
	to_handler_entry(&INVALID_HANDLER), // 0xA8
	to_handler_entry(&INVALID_HANDLER), // 0xA9
	to_handler_entry(&INVALID_HANDLER), // 0xAA
	to_handler_entry(&INVALID_HANDLER), // 0xAB
	to_handler_entry(&INVALID_HANDLER), // 0xAC
	to_handler_entry(&INVALID_HANDLER), // 0xAD
	to_handler_entry(&INVALID_HANDLER), // 0xAE
	to_handler_entry(&INVALID_HANDLER), // 0xAF
	to_handler_entry(&INVALID_HANDLER), // 0xB0
	to_handler_entry(&INVALID_HANDLER), // 0xB1
	to_handler_entry(&INVALID_HANDLER), // 0xB2
	to_handler_entry(&INVALID_HANDLER), // 0xB3
	to_handler_entry(&INVALID_HANDLER), // 0xB4
	to_handler_entry(&INVALID_HANDLER), // 0xB5
	to_handler_entry(&INVALID_HANDLER), // 0xB6
	to_handler_entry(&INVALID_HANDLER), // 0xB7
	to_handler_entry(&INVALID_HANDLER), // 0xB8
	to_handler_entry(&INVALID_HANDLER), // 0xB9
	to_handler_entry(&INVALID_HANDLER), // 0xBA
	to_handler_entry(&INVALID_HANDLER), // 0xBB
	to_handler_entry(&INVALID_HANDLER), // 0xBC
	to_handler_entry(&INVALID_HANDLER), // 0xBD
	to_handler_entry(&INVALID_HANDLER), // 0xBE
	to_handler_entry(&INVALID_HANDLER), // 0xBF
	to_handler_entry(&INVALID_HANDLER), // 0xC0
	to_handler_entry(&H235), // 0xC1
	to_handler_entry(&H239), // 0xC2
	to_handler_entry(&H243), // 0xC3
	to_handler_entry(&INVALID_HANDLER), // 0xC4
	to_handler_entry(&INVALID_HANDLER), // 0xC5
	to_handler_entry(&H247), // 0xC6
	to_handler_entry(&H251), // 0xC7
	to_handler_entry(&INVALID_HANDLER), // 0xC8
	to_handler_entry(&INVALID_HANDLER), // 0xC9
	to_handler_entry(&INVALID_HANDLER), // 0xCA
	to_handler_entry(&H255), // 0xCB
	to_handler_entry(&INVALID_HANDLER), // 0xCC
	to_handler_entry(&INVALID_HANDLER), // 0xCD
	to_handler_entry(&INVALID_HANDLER), // 0xCE
	to_handler_entry(&INVALID_HANDLER), // 0xCF
	to_handler_entry(&INVALID_HANDLER), // 0xD0
	to_handler_entry(&H259), // 0xD1
	to_handler_entry(&H263), // 0xD2
	to_handler_entry(&H267), // 0xD3
	to_handler_entry(&INVALID_HANDLER), // 0xD4
	to_handler_entry(&INVALID_HANDLER), // 0xD5
	to_handler_entry(&H271), // 0xD6
	to_handler_entry(&H275), // 0xD7
	to_handler_entry(&INVALID_HANDLER), // 0xD8
	to_handler_entry(&INVALID_HANDLER), // 0xD9
	to_handler_entry(&INVALID_HANDLER), // 0xDA
	to_handler_entry(&H279), // 0xDB
	to_handler_entry(&INVALID_HANDLER), // 0xDC
	to_handler_entry(&INVALID_HANDLER), // 0xDD
	to_handler_entry(&INVALID_HANDLER), // 0xDE
	to_handler_entry(&INVALID_HANDLER), // 0xDF
	to_handler_entry(&INVALID_HANDLER), // 0xE0
	to_handler_entry(&H283), // 0xE1
	to_handler_entry(&H287), // 0xE2
	to_handler_entry(&H291), // 0xE3
	to_handler_entry(&INVALID_HANDLER), // 0xE4
	to_handler_entry(&INVALID_HANDLER), // 0xE5
	to_handler_entry(&INVALID_HANDLER), // 0xE6
	to_handler_entry(&INVALID_HANDLER), // 0xE7
	to_handler_entry(&INVALID_HANDLER), // 0xE8
	to_handler_entry(&INVALID_HANDLER), // 0xE9
	to_handler_entry(&INVALID_HANDLER), // 0xEA
	to_handler_entry(&INVALID_HANDLER), // 0xEB
	to_handler_entry(&INVALID_HANDLER), // 0xEC
	to_handler_entry(&INVALID_HANDLER), // 0xED
	to_handler_entry(&INVALID_HANDLER), // 0xEE
	to_handler_entry(&INVALID_HANDLER), // 0xEF
	to_handler_entry(&INVALID_HANDLER), // 0xF0
	to_handler_entry(&INVALID_HANDLER), // 0xF1
	to_handler_entry(&INVALID_HANDLER), // 0xF2
	to_handler_entry(&INVALID_HANDLER), // 0xF3
	to_handler_entry(&INVALID_HANDLER), // 0xF4
	to_handler_entry(&INVALID_HANDLER), // 0xF5
	to_handler_entry(&INVALID_HANDLER), // 0xF6
	to_handler_entry(&INVALID_HANDLER), // 0xF7
	to_handler_entry(&INVALID_HANDLER), // 0xF8
	to_handler_entry(&INVALID_HANDLER), // 0xF9
	to_handler_entry(&INVALID_HANDLER), // 0xFA
	to_handler_entry(&INVALID_HANDLER), // 0xFB
	to_handler_entry(&INVALID_HANDLER), // 0xFC
	to_handler_entry(&INVALID_HANDLER), // 0xFD
	to_handler_entry(&INVALID_HANDLER), // 0xFE
	to_handler_entry(&INVALID_HANDLER), // 0xFF
};
constexpr auto H292 = vex_ctors::Gv_Ev_Id(Code::XOP_Bextr_r32_rm32_imm32, Code::XOP_Bextr_r64_rm64_imm32);
constexpr auto H293 = vex_ctors::VectorLength(&H292, &INVALID_HANDLER);
constexpr auto H294 = vex_ctors::MandatoryPrefix2_1(&H293);
constexpr auto H295 = vex_ctors::Group({&H35, &H38, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER, &INVALID_HANDLER});
constexpr HandlerEntry HANDLERS_MAP10[0x100] = {
	to_handler_entry(&INVALID_HANDLER), // 0x00
	to_handler_entry(&INVALID_HANDLER), // 0x01
	to_handler_entry(&INVALID_HANDLER), // 0x02
	to_handler_entry(&INVALID_HANDLER), // 0x03
	to_handler_entry(&INVALID_HANDLER), // 0x04
	to_handler_entry(&INVALID_HANDLER), // 0x05
	to_handler_entry(&INVALID_HANDLER), // 0x06
	to_handler_entry(&INVALID_HANDLER), // 0x07
	to_handler_entry(&INVALID_HANDLER), // 0x08
	to_handler_entry(&INVALID_HANDLER), // 0x09
	to_handler_entry(&INVALID_HANDLER), // 0x0A
	to_handler_entry(&INVALID_HANDLER), // 0x0B
	to_handler_entry(&INVALID_HANDLER), // 0x0C
	to_handler_entry(&INVALID_HANDLER), // 0x0D
	to_handler_entry(&INVALID_HANDLER), // 0x0E
	to_handler_entry(&INVALID_HANDLER), // 0x0F
	to_handler_entry(&H294), // 0x10
	to_handler_entry(&INVALID_HANDLER), // 0x11
	to_handler_entry(&H295), // 0x12
	to_handler_entry(&INVALID_HANDLER), // 0x13
	to_handler_entry(&INVALID_HANDLER), // 0x14
	to_handler_entry(&INVALID_HANDLER), // 0x15
	to_handler_entry(&INVALID_HANDLER), // 0x16
	to_handler_entry(&INVALID_HANDLER), // 0x17
	to_handler_entry(&INVALID_HANDLER), // 0x18
	to_handler_entry(&INVALID_HANDLER), // 0x19
	to_handler_entry(&INVALID_HANDLER), // 0x1A
	to_handler_entry(&INVALID_HANDLER), // 0x1B
	to_handler_entry(&INVALID_HANDLER), // 0x1C
	to_handler_entry(&INVALID_HANDLER), // 0x1D
	to_handler_entry(&INVALID_HANDLER), // 0x1E
	to_handler_entry(&INVALID_HANDLER), // 0x1F
	to_handler_entry(&INVALID_HANDLER), // 0x20
	to_handler_entry(&INVALID_HANDLER), // 0x21
	to_handler_entry(&INVALID_HANDLER), // 0x22
	to_handler_entry(&INVALID_HANDLER), // 0x23
	to_handler_entry(&INVALID_HANDLER), // 0x24
	to_handler_entry(&INVALID_HANDLER), // 0x25
	to_handler_entry(&INVALID_HANDLER), // 0x26
	to_handler_entry(&INVALID_HANDLER), // 0x27
	to_handler_entry(&INVALID_HANDLER), // 0x28
	to_handler_entry(&INVALID_HANDLER), // 0x29
	to_handler_entry(&INVALID_HANDLER), // 0x2A
	to_handler_entry(&INVALID_HANDLER), // 0x2B
	to_handler_entry(&INVALID_HANDLER), // 0x2C
	to_handler_entry(&INVALID_HANDLER), // 0x2D
	to_handler_entry(&INVALID_HANDLER), // 0x2E
	to_handler_entry(&INVALID_HANDLER), // 0x2F
	to_handler_entry(&INVALID_HANDLER), // 0x30
	to_handler_entry(&INVALID_HANDLER), // 0x31
	to_handler_entry(&INVALID_HANDLER), // 0x32
	to_handler_entry(&INVALID_HANDLER), // 0x33
	to_handler_entry(&INVALID_HANDLER), // 0x34
	to_handler_entry(&INVALID_HANDLER), // 0x35
	to_handler_entry(&INVALID_HANDLER), // 0x36
	to_handler_entry(&INVALID_HANDLER), // 0x37
	to_handler_entry(&INVALID_HANDLER), // 0x38
	to_handler_entry(&INVALID_HANDLER), // 0x39
	to_handler_entry(&INVALID_HANDLER), // 0x3A
	to_handler_entry(&INVALID_HANDLER), // 0x3B
	to_handler_entry(&INVALID_HANDLER), // 0x3C
	to_handler_entry(&INVALID_HANDLER), // 0x3D
	to_handler_entry(&INVALID_HANDLER), // 0x3E
	to_handler_entry(&INVALID_HANDLER), // 0x3F
	to_handler_entry(&INVALID_HANDLER), // 0x40
	to_handler_entry(&INVALID_HANDLER), // 0x41
	to_handler_entry(&INVALID_HANDLER), // 0x42
	to_handler_entry(&INVALID_HANDLER), // 0x43
	to_handler_entry(&INVALID_HANDLER), // 0x44
	to_handler_entry(&INVALID_HANDLER), // 0x45
	to_handler_entry(&INVALID_HANDLER), // 0x46
	to_handler_entry(&INVALID_HANDLER), // 0x47
	to_handler_entry(&INVALID_HANDLER), // 0x48
	to_handler_entry(&INVALID_HANDLER), // 0x49
	to_handler_entry(&INVALID_HANDLER), // 0x4A
	to_handler_entry(&INVALID_HANDLER), // 0x4B
	to_handler_entry(&INVALID_HANDLER), // 0x4C
	to_handler_entry(&INVALID_HANDLER), // 0x4D
	to_handler_entry(&INVALID_HANDLER), // 0x4E
	to_handler_entry(&INVALID_HANDLER), // 0x4F
	to_handler_entry(&INVALID_HANDLER), // 0x50
	to_handler_entry(&INVALID_HANDLER), // 0x51
	to_handler_entry(&INVALID_HANDLER), // 0x52
	to_handler_entry(&INVALID_HANDLER), // 0x53
	to_handler_entry(&INVALID_HANDLER), // 0x54
	to_handler_entry(&INVALID_HANDLER), // 0x55
	to_handler_entry(&INVALID_HANDLER), // 0x56
	to_handler_entry(&INVALID_HANDLER), // 0x57
	to_handler_entry(&INVALID_HANDLER), // 0x58
	to_handler_entry(&INVALID_HANDLER), // 0x59
	to_handler_entry(&INVALID_HANDLER), // 0x5A
	to_handler_entry(&INVALID_HANDLER), // 0x5B
	to_handler_entry(&INVALID_HANDLER), // 0x5C
	to_handler_entry(&INVALID_HANDLER), // 0x5D
	to_handler_entry(&INVALID_HANDLER), // 0x5E
	to_handler_entry(&INVALID_HANDLER), // 0x5F
	to_handler_entry(&INVALID_HANDLER), // 0x60
	to_handler_entry(&INVALID_HANDLER), // 0x61
	to_handler_entry(&INVALID_HANDLER), // 0x62
	to_handler_entry(&INVALID_HANDLER), // 0x63
	to_handler_entry(&INVALID_HANDLER), // 0x64
	to_handler_entry(&INVALID_HANDLER), // 0x65
	to_handler_entry(&INVALID_HANDLER), // 0x66
	to_handler_entry(&INVALID_HANDLER), // 0x67
	to_handler_entry(&INVALID_HANDLER), // 0x68
	to_handler_entry(&INVALID_HANDLER), // 0x69
	to_handler_entry(&INVALID_HANDLER), // 0x6A
	to_handler_entry(&INVALID_HANDLER), // 0x6B
	to_handler_entry(&INVALID_HANDLER), // 0x6C
	to_handler_entry(&INVALID_HANDLER), // 0x6D
	to_handler_entry(&INVALID_HANDLER), // 0x6E
	to_handler_entry(&INVALID_HANDLER), // 0x6F
	to_handler_entry(&INVALID_HANDLER), // 0x70
	to_handler_entry(&INVALID_HANDLER), // 0x71
	to_handler_entry(&INVALID_HANDLER), // 0x72
	to_handler_entry(&INVALID_HANDLER), // 0x73
	to_handler_entry(&INVALID_HANDLER), // 0x74
	to_handler_entry(&INVALID_HANDLER), // 0x75
	to_handler_entry(&INVALID_HANDLER), // 0x76
	to_handler_entry(&INVALID_HANDLER), // 0x77
	to_handler_entry(&INVALID_HANDLER), // 0x78
	to_handler_entry(&INVALID_HANDLER), // 0x79
	to_handler_entry(&INVALID_HANDLER), // 0x7A
	to_handler_entry(&INVALID_HANDLER), // 0x7B
	to_handler_entry(&INVALID_HANDLER), // 0x7C
	to_handler_entry(&INVALID_HANDLER), // 0x7D
	to_handler_entry(&INVALID_HANDLER), // 0x7E
	to_handler_entry(&INVALID_HANDLER), // 0x7F
	to_handler_entry(&INVALID_HANDLER), // 0x80
	to_handler_entry(&INVALID_HANDLER), // 0x81
	to_handler_entry(&INVALID_HANDLER), // 0x82
	to_handler_entry(&INVALID_HANDLER), // 0x83
	to_handler_entry(&INVALID_HANDLER), // 0x84
	to_handler_entry(&INVALID_HANDLER), // 0x85
	to_handler_entry(&INVALID_HANDLER), // 0x86
	to_handler_entry(&INVALID_HANDLER), // 0x87
	to_handler_entry(&INVALID_HANDLER), // 0x88
	to_handler_entry(&INVALID_HANDLER), // 0x89
	to_handler_entry(&INVALID_HANDLER), // 0x8A
	to_handler_entry(&INVALID_HANDLER), // 0x8B
	to_handler_entry(&INVALID_HANDLER), // 0x8C
	to_handler_entry(&INVALID_HANDLER), // 0x8D
	to_handler_entry(&INVALID_HANDLER), // 0x8E
	to_handler_entry(&INVALID_HANDLER), // 0x8F
	to_handler_entry(&INVALID_HANDLER), // 0x90
	to_handler_entry(&INVALID_HANDLER), // 0x91
	to_handler_entry(&INVALID_HANDLER), // 0x92
	to_handler_entry(&INVALID_HANDLER), // 0x93
	to_handler_entry(&INVALID_HANDLER), // 0x94
	to_handler_entry(&INVALID_HANDLER), // 0x95
	to_handler_entry(&INVALID_HANDLER), // 0x96
	to_handler_entry(&INVALID_HANDLER), // 0x97
	to_handler_entry(&INVALID_HANDLER), // 0x98
	to_handler_entry(&INVALID_HANDLER), // 0x99
	to_handler_entry(&INVALID_HANDLER), // 0x9A
	to_handler_entry(&INVALID_HANDLER), // 0x9B
	to_handler_entry(&INVALID_HANDLER), // 0x9C
	to_handler_entry(&INVALID_HANDLER), // 0x9D
	to_handler_entry(&INVALID_HANDLER), // 0x9E
	to_handler_entry(&INVALID_HANDLER), // 0x9F
	to_handler_entry(&INVALID_HANDLER), // 0xA0
	to_handler_entry(&INVALID_HANDLER), // 0xA1
	to_handler_entry(&INVALID_HANDLER), // 0xA2
	to_handler_entry(&INVALID_HANDLER), // 0xA3
	to_handler_entry(&INVALID_HANDLER), // 0xA4
	to_handler_entry(&INVALID_HANDLER), // 0xA5
	to_handler_entry(&INVALID_HANDLER), // 0xA6
	to_handler_entry(&INVALID_HANDLER), // 0xA7
	to_handler_entry(&INVALID_HANDLER), // 0xA8
	to_handler_entry(&INVALID_HANDLER), // 0xA9
	to_handler_entry(&INVALID_HANDLER), // 0xAA
	to_handler_entry(&INVALID_HANDLER), // 0xAB
	to_handler_entry(&INVALID_HANDLER), // 0xAC
	to_handler_entry(&INVALID_HANDLER), // 0xAD
	to_handler_entry(&INVALID_HANDLER), // 0xAE
	to_handler_entry(&INVALID_HANDLER), // 0xAF
	to_handler_entry(&INVALID_HANDLER), // 0xB0
	to_handler_entry(&INVALID_HANDLER), // 0xB1
	to_handler_entry(&INVALID_HANDLER), // 0xB2
	to_handler_entry(&INVALID_HANDLER), // 0xB3
	to_handler_entry(&INVALID_HANDLER), // 0xB4
	to_handler_entry(&INVALID_HANDLER), // 0xB5
	to_handler_entry(&INVALID_HANDLER), // 0xB6
	to_handler_entry(&INVALID_HANDLER), // 0xB7
	to_handler_entry(&INVALID_HANDLER), // 0xB8
	to_handler_entry(&INVALID_HANDLER), // 0xB9
	to_handler_entry(&INVALID_HANDLER), // 0xBA
	to_handler_entry(&INVALID_HANDLER), // 0xBB
	to_handler_entry(&INVALID_HANDLER), // 0xBC
	to_handler_entry(&INVALID_HANDLER), // 0xBD
	to_handler_entry(&INVALID_HANDLER), // 0xBE
	to_handler_entry(&INVALID_HANDLER), // 0xBF
	to_handler_entry(&INVALID_HANDLER), // 0xC0
	to_handler_entry(&INVALID_HANDLER), // 0xC1
	to_handler_entry(&INVALID_HANDLER), // 0xC2
	to_handler_entry(&INVALID_HANDLER), // 0xC3
	to_handler_entry(&INVALID_HANDLER), // 0xC4
	to_handler_entry(&INVALID_HANDLER), // 0xC5
	to_handler_entry(&INVALID_HANDLER), // 0xC6
	to_handler_entry(&INVALID_HANDLER), // 0xC7
	to_handler_entry(&INVALID_HANDLER), // 0xC8
	to_handler_entry(&INVALID_HANDLER), // 0xC9
	to_handler_entry(&INVALID_HANDLER), // 0xCA
	to_handler_entry(&INVALID_HANDLER), // 0xCB
	to_handler_entry(&INVALID_HANDLER), // 0xCC
	to_handler_entry(&INVALID_HANDLER), // 0xCD
	to_handler_entry(&INVALID_HANDLER), // 0xCE
	to_handler_entry(&INVALID_HANDLER), // 0xCF
	to_handler_entry(&INVALID_HANDLER), // 0xD0
	to_handler_entry(&INVALID_HANDLER), // 0xD1
	to_handler_entry(&INVALID_HANDLER), // 0xD2
	to_handler_entry(&INVALID_HANDLER), // 0xD3
	to_handler_entry(&INVALID_HANDLER), // 0xD4
	to_handler_entry(&INVALID_HANDLER), // 0xD5
	to_handler_entry(&INVALID_HANDLER), // 0xD6
	to_handler_entry(&INVALID_HANDLER), // 0xD7
	to_handler_entry(&INVALID_HANDLER), // 0xD8
	to_handler_entry(&INVALID_HANDLER), // 0xD9
	to_handler_entry(&INVALID_HANDLER), // 0xDA
	to_handler_entry(&INVALID_HANDLER), // 0xDB
	to_handler_entry(&INVALID_HANDLER), // 0xDC
	to_handler_entry(&INVALID_HANDLER), // 0xDD
	to_handler_entry(&INVALID_HANDLER), // 0xDE
	to_handler_entry(&INVALID_HANDLER), // 0xDF
	to_handler_entry(&INVALID_HANDLER), // 0xE0
	to_handler_entry(&INVALID_HANDLER), // 0xE1
	to_handler_entry(&INVALID_HANDLER), // 0xE2
	to_handler_entry(&INVALID_HANDLER), // 0xE3
	to_handler_entry(&INVALID_HANDLER), // 0xE4
	to_handler_entry(&INVALID_HANDLER), // 0xE5
	to_handler_entry(&INVALID_HANDLER), // 0xE6
	to_handler_entry(&INVALID_HANDLER), // 0xE7
	to_handler_entry(&INVALID_HANDLER), // 0xE8
	to_handler_entry(&INVALID_HANDLER), // 0xE9
	to_handler_entry(&INVALID_HANDLER), // 0xEA
	to_handler_entry(&INVALID_HANDLER), // 0xEB
	to_handler_entry(&INVALID_HANDLER), // 0xEC
	to_handler_entry(&INVALID_HANDLER), // 0xED
	to_handler_entry(&INVALID_HANDLER), // 0xEE
	to_handler_entry(&INVALID_HANDLER), // 0xEF
	to_handler_entry(&INVALID_HANDLER), // 0xF0
	to_handler_entry(&INVALID_HANDLER), // 0xF1
	to_handler_entry(&INVALID_HANDLER), // 0xF2
	to_handler_entry(&INVALID_HANDLER), // 0xF3
	to_handler_entry(&INVALID_HANDLER), // 0xF4
	to_handler_entry(&INVALID_HANDLER), // 0xF5
	to_handler_entry(&INVALID_HANDLER), // 0xF6
	to_handler_entry(&INVALID_HANDLER), // 0xF7
	to_handler_entry(&INVALID_HANDLER), // 0xF8
	to_handler_entry(&INVALID_HANDLER), // 0xF9
	to_handler_entry(&INVALID_HANDLER), // 0xFA
	to_handler_entry(&INVALID_HANDLER), // 0xFB
	to_handler_entry(&INVALID_HANDLER), // 0xFC
	to_handler_entry(&INVALID_HANDLER), // 0xFD
	to_handler_entry(&INVALID_HANDLER), // 0xFE
	to_handler_entry(&INVALID_HANDLER), // 0xFF
};
// clang-format on

} // namespace iced_x86::internal::decoder_data_xop
