// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// Instruction::with*() methods (Rust: instruction_create.rs + the encoder parts of instruction_internal.rs)

#include "iced_x86/instruction.hpp"
#include "iced_x86/memory_operand.hpp"
#include "internal/encoder/op_code_handler.hpp"
#include "internal/iced_assert.hpp"
#include "internal/instruction_internal.hpp"
#include <cstdint>
#include <limits>
#include <string>

namespace iced_x86 {

using internal::InstructionInternal;

namespace {

// Returns the error if `expr` (a `Result<void>`) is an error
#define ICED_TRY(expr) \
	do { \
		auto iced_try_result_ = (expr); \
		if (iced_try_result_.is_err()) \
			return iced_try_result_.error(); \
	} while (0)

static_assert(static_cast<std::uint32_t>(OpKind::Register) == 0, "The generated code assumes OpKind::Register == 0");

void init_memory_operand(Instruction& instruction, const MemoryOperand& memory) {
	instruction.set_memory_base(memory.base);
	instruction.set_memory_index(memory.index);
	instruction.set_memory_index_scale(memory.scale);
	instruction.set_memory_displ_size(memory.displ_size);
	instruction.set_memory_displacement64(static_cast<std::uint64_t>(memory.displacement));
	instruction.set_is_broadcast(memory.is_broadcast);
	instruction.set_segment_prefix(memory.segment_prefix);
}

std::string code_str(Code code) {
#ifndef NDEBUG
	return to_string(code);
#else
	return "Code value " + std::to_string(static_cast<std::uint32_t>(code));
#endif
}

IcedError not_enough_operands_error(Code code, std::size_t operand) {
	return IcedError(code_str(code) + " doesn't have at least " + std::to_string(operand + 1) + " operands");
}

const internal::EncOpCodeHandler& get_handler(Code code) noexcept { return internal::OP_CODE_HANDLERS[static_cast<std::size_t>(code)]; }

} // namespace

// These InstructionInternal methods are implemented by the encoder since they use the encoder's op handlers

Result<OpKind> internal::InstructionInternal::get_immediate_op_kind(Code code, std::size_t operand) {
	const internal::EncOpCodeHandler& handler = get_handler(code);
	const std::size_t operands_len = handler.operands_len;
	if (operand < operands_len) {
		const auto op_kind = handler.operand(operand)->immediate_op_kind();
		if (op_kind) {
			if (*op_kind == OpKind::Immediate8 && operand > 0 && operand + 1 == operands_len) {
				const auto op_kind_prev = handler.operand(operand - 1)->immediate_op_kind();
				if (op_kind_prev && (*op_kind_prev == OpKind::Immediate8 || *op_kind_prev == OpKind::Immediate16))
					return OpKind::Immediate8_2nd;
			}
			return *op_kind;
		}
		return IcedError(code_str(code) + "'s op" + std::to_string(operand) + " isn't an immediate operand");
	}
	return not_enough_operands_error(code, operand);
}

Result<OpKind> internal::InstructionInternal::get_near_branch_op_kind(Code code, std::size_t operand) {
	const internal::EncOpCodeHandler& handler = get_handler(code);
	if (operand < handler.operands_len) {
		if (const auto op_kind = handler.operand(operand)->near_branch_op_kind())
			return *op_kind;
		return IcedError(code_str(code) + "'s op" + std::to_string(operand) + " isn't a near branch operand");
	}
	return not_enough_operands_error(code, operand);
}

Result<OpKind> internal::InstructionInternal::get_far_branch_op_kind(Code code, std::size_t operand) {
	const internal::EncOpCodeHandler& handler = get_handler(code);
	if (operand < handler.operands_len) {
		if (const auto op_kind = handler.operand(operand)->far_branch_op_kind())
			return *op_kind;
		return IcedError(code_str(code) + "'s op" + std::to_string(operand) + " isn't a far branch operand");
	}
	return not_enough_operands_error(code, operand);
}

// GENERATOR-BEGIN: Create
// ⚠️This was generated by GENERATOR!🦹‍♂️
Instruction Instruction::with(Code code) {
	Instruction instruction;
	instruction.set_code(code);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::with1(Code code, Register register_) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	ICED_DEBUG_ASSERT(instruction.op_count() == 1);
	return instruction;
}

Result<Instruction> Instruction::with1(Code code, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 0, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 1);
	return instruction;
}

Result<Instruction> Instruction::with1(Code code, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 0, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 1);
	return instruction;
}

Result<Instruction> Instruction::with1(Code code, const MemoryOperand& memory) {
	Instruction instruction;
	instruction.set_code(code);

	instruction.set_op0_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_DEBUG_ASSERT(instruction.op_count() == 1);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, Register register1, Register register2) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, Register register_, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 1, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, Register register_, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 1, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, Register register_, std::int64_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 1, immediate));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, Register register_, std::uint64_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 1, immediate));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, Register register_, const MemoryOperand& memory) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	instruction.set_op1_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, std::int32_t immediate, Register register_) {
	Instruction instruction;
	instruction.set_code(code);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 0, static_cast<std::int64_t>(immediate)));

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register_);

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, std::uint32_t immediate, Register register_) {
	Instruction instruction;
	instruction.set_code(code);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 0, static_cast<std::uint64_t>(immediate)));

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register_);

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, std::int32_t immediate1, std::int32_t immediate2) {
	Instruction instruction;
	instruction.set_code(code);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 0, static_cast<std::int64_t>(immediate1)));

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 1, static_cast<std::int64_t>(immediate2)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, std::uint32_t immediate1, std::uint32_t immediate2) {
	Instruction instruction;
	instruction.set_code(code);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 0, static_cast<std::uint64_t>(immediate1)));

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 1, static_cast<std::uint64_t>(immediate2)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, const MemoryOperand& memory, Register register_) {
	Instruction instruction;
	instruction.set_code(code);

	instruction.set_op0_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register_);

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, const MemoryOperand& memory, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	instruction.set_op0_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 1, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with2(Code code, const MemoryOperand& memory, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	instruction.set_op0_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 1, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 2);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register1, Register register2, Register register3) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register1, Register register2, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 2, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register1, Register register2, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 2, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register1, Register register2, const MemoryOperand& memory) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	instruction.set_op2_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register_, std::int32_t immediate1, std::int32_t immediate2) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 1, static_cast<std::int64_t>(immediate1)));

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 2, static_cast<std::int64_t>(immediate2)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register_, std::uint32_t immediate1, std::uint32_t immediate2) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 1, static_cast<std::uint64_t>(immediate1)));

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 2, static_cast<std::uint64_t>(immediate2)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register1, const MemoryOperand& memory, Register register2) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	instruction.set_op1_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register2);

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register_, const MemoryOperand& memory, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	instruction.set_op1_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 2, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, Register register_, const MemoryOperand& memory, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register_);

	instruction.set_op1_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 2, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, const MemoryOperand& memory, Register register1, Register register2) {
	Instruction instruction;
	instruction.set_code(code);

	instruction.set_op0_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register1);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register2);

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, const MemoryOperand& memory, Register register_, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	instruction.set_op0_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register_);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 2, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with3(Code code, const MemoryOperand& memory, Register register_, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	instruction.set_op0_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register_);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 2, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 3);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, Register register3, Register register4) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	// OpKind::Register == 0 so set_op3_kind() isn't needed
	instruction.set_op3_register(register4);

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, Register register3, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 3, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, Register register3, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 3, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, Register register3, const MemoryOperand& memory) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	instruction.set_op3_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, std::int32_t immediate1, std::int32_t immediate2) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 2, static_cast<std::int64_t>(immediate1)));

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 3, static_cast<std::int64_t>(immediate2)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, std::uint32_t immediate1, std::uint32_t immediate2) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 2, static_cast<std::uint64_t>(immediate1)));

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 3, static_cast<std::uint64_t>(immediate2)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, const MemoryOperand& memory, Register register3) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	instruction.set_op2_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op3_kind() isn't needed
	instruction.set_op3_register(register3);

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, const MemoryOperand& memory, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	instruction.set_op2_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 3, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with4(Code code, Register register1, Register register2, const MemoryOperand& memory, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	instruction.set_op2_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 3, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 4);
	return instruction;
}

Result<Instruction> Instruction::with5(Code code, Register register1, Register register2, Register register3, Register register4, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	// OpKind::Register == 0 so set_op3_kind() isn't needed
	instruction.set_op3_register(register4);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 4, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 5);
	return instruction;
}

Result<Instruction> Instruction::with5(Code code, Register register1, Register register2, Register register3, Register register4, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	// OpKind::Register == 0 so set_op3_kind() isn't needed
	instruction.set_op3_register(register4);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 4, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 5);
	return instruction;
}

Result<Instruction> Instruction::with5(Code code, Register register1, Register register2, Register register3, const MemoryOperand& memory, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	instruction.set_op3_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 4, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 5);
	return instruction;
}

Result<Instruction> Instruction::with5(Code code, Register register1, Register register2, Register register3, const MemoryOperand& memory, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	// OpKind::Register == 0 so set_op2_kind() isn't needed
	instruction.set_op2_register(register3);

	instruction.set_op3_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 4, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 5);
	return instruction;
}

Result<Instruction> Instruction::with5(Code code, Register register1, Register register2, const MemoryOperand& memory, Register register3, std::int32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	instruction.set_op2_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op3_kind() isn't needed
	instruction.set_op3_register(register3);

	ICED_TRY(InstructionInternal::initialize_signed_immediate(instruction, 4, static_cast<std::int64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 5);
	return instruction;
}

Result<Instruction> Instruction::with5(Code code, Register register1, Register register2, const MemoryOperand& memory, Register register3, std::uint32_t immediate) {
	Instruction instruction;
	instruction.set_code(code);

	// OpKind::Register == 0 so set_op0_kind() isn't needed
	instruction.set_op0_register(register1);

	// OpKind::Register == 0 so set_op1_kind() isn't needed
	instruction.set_op1_register(register2);

	instruction.set_op2_kind(OpKind::Memory);
	init_memory_operand(instruction, memory);

	// OpKind::Register == 0 so set_op3_kind() isn't needed
	instruction.set_op3_register(register3);

	ICED_TRY(InstructionInternal::initialize_unsigned_immediate(instruction, 4, static_cast<std::uint64_t>(immediate)));

	ICED_DEBUG_ASSERT(instruction.op_count() == 5);
	return instruction;
}

Result<Instruction> Instruction::with_branch(Code code, std::uint64_t target) {
	Instruction instruction;
	instruction.set_code(code);

	auto op_kind = InstructionInternal::get_near_branch_op_kind(code, 0);
	if (op_kind.is_err())
		return op_kind.error();
	instruction.set_op0_kind(op_kind.value());
	instruction.set_near_branch64(target);

	ICED_DEBUG_ASSERT(instruction.op_count() == 1);
	return instruction;
}

Result<Instruction> Instruction::with_far_branch(Code code, std::uint16_t selector, std::uint32_t offset) {
	Instruction instruction;
	instruction.set_code(code);

	auto op_kind = InstructionInternal::get_far_branch_op_kind(code, 0);
	if (op_kind.is_err())
		return op_kind.error();
	instruction.set_op0_kind(op_kind.value());
	instruction.set_far_branch_selector(selector);
	instruction.set_far_branch32(offset);

	ICED_DEBUG_ASSERT(instruction.op_count() == 1);
	return instruction;
}

Result<Instruction> Instruction::with_xbegin(std::uint32_t bitness, std::uint64_t target) {
	Instruction instruction;

	switch (bitness) {
	case 16:
		instruction.set_code(Code::Xbegin_rel16);
		instruction.set_op0_kind(OpKind::NearBranch32);
		instruction.set_near_branch32(static_cast<std::uint32_t>(target));
		break;

	case 32:
		instruction.set_code(Code::Xbegin_rel32);
		instruction.set_op0_kind(OpKind::NearBranch32);
		instruction.set_near_branch32(static_cast<std::uint32_t>(target));
		break;

	case 64:
		instruction.set_code(Code::Xbegin_rel32);
		instruction.set_op0_kind(OpKind::NearBranch64);
		instruction.set_near_branch64(target);
		break;

	default:
		return IcedError("Invalid bitness");
	}

	ICED_DEBUG_ASSERT(instruction.op_count() == 1);
	return instruction;
}

Result<Instruction> Instruction::with_outsb(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_segrsi(Code::Outsb_DX_m8, address_size, Register::DX, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_outsb(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_segrsi(Code::Outsb_DX_m8, address_size, Register::DX, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_outsw(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_segrsi(Code::Outsw_DX_m16, address_size, Register::DX, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_outsw(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_segrsi(Code::Outsw_DX_m16, address_size, Register::DX, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_outsd(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_segrsi(Code::Outsd_DX_m32, address_size, Register::DX, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_outsd(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_segrsi(Code::Outsd_DX_m32, address_size, Register::DX, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_lodsb(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsb_AL_m8, address_size, Register::AL, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_lodsb(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsb_AL_m8, address_size, Register::AL, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_lodsw(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsw_AX_m16, address_size, Register::AX, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_lodsw(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsw_AX_m16, address_size, Register::AX, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_lodsd(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsd_EAX_m32, address_size, Register::EAX, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_lodsd(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsd_EAX_m32, address_size, Register::EAX, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_lodsq(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsq_RAX_m64, address_size, Register::RAX, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_lodsq(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_segrsi(Code::Lodsq_RAX_m64, address_size, Register::RAX, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_scasb(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasb_AL_m8, address_size, Register::AL, rep_prefix);
}

Result<Instruction> Instruction::with_repe_scasb(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasb_AL_m8, address_size, Register::AL, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_scasb(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasb_AL_m8, address_size, Register::AL, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_scasw(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasw_AX_m16, address_size, Register::AX, rep_prefix);
}

Result<Instruction> Instruction::with_repe_scasw(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasw_AX_m16, address_size, Register::AX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_scasw(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasw_AX_m16, address_size, Register::AX, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_scasd(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasd_EAX_m32, address_size, Register::EAX, rep_prefix);
}

Result<Instruction> Instruction::with_repe_scasd(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasd_EAX_m32, address_size, Register::EAX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_scasd(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasd_EAX_m32, address_size, Register::EAX, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_scasq(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasq_RAX_m64, address_size, Register::RAX, rep_prefix);
}

Result<Instruction> Instruction::with_repe_scasq(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasq_RAX_m64, address_size, Register::RAX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_scasq(std::uint32_t address_size) {
	return InstructionInternal::with_string_reg_esrdi(Code::Scasq_RAX_m64, address_size, Register::RAX, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_insb(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_reg(Code::Insb_m8_DX, address_size, Register::DX, rep_prefix);
}

Result<Instruction> Instruction::with_rep_insb(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_reg(Code::Insb_m8_DX, address_size, Register::DX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_insw(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_reg(Code::Insw_m16_DX, address_size, Register::DX, rep_prefix);
}

Result<Instruction> Instruction::with_rep_insw(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_reg(Code::Insw_m16_DX, address_size, Register::DX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_insd(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_reg(Code::Insd_m32_DX, address_size, Register::DX, rep_prefix);
}

Result<Instruction> Instruction::with_rep_insd(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_reg(Code::Insd_m32_DX, address_size, Register::DX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_stosb(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosb_m8_AL, address_size, Register::AL, rep_prefix);
}

Result<Instruction> Instruction::with_rep_stosb(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosb_m8_AL, address_size, Register::AL, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_stosw(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosw_m16_AX, address_size, Register::AX, rep_prefix);
}

Result<Instruction> Instruction::with_rep_stosw(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosw_m16_AX, address_size, Register::AX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_stosd(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosd_m32_EAX, address_size, Register::EAX, rep_prefix);
}

Result<Instruction> Instruction::with_rep_stosd(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosd_m32_EAX, address_size, Register::EAX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_stosq(std::uint32_t address_size, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosq_m64_RAX, address_size, Register::RAX, rep_prefix);
}

Result<Instruction> Instruction::with_rep_stosq(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_reg(Code::Stosq_m64_RAX, address_size, Register::RAX, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_cmpsb(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsb_m8_m8, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_repe_cmpsb(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsb_m8_m8, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_cmpsb(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsb_m8_m8, address_size, Register::None, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_cmpsw(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsw_m16_m16, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_repe_cmpsw(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsw_m16_m16, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_cmpsw(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsw_m16_m16, address_size, Register::None, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_cmpsd(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsd_m32_m32, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_repe_cmpsd(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsd_m32_m32, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_cmpsd(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsd_m32_m32, address_size, Register::None, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_cmpsq(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsq_m64_m64, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_repe_cmpsq(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsq_m64_m64, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_repne_cmpsq(std::uint32_t address_size) {
	return InstructionInternal::with_string_segrsi_esrdi(Code::Cmpsq_m64_m64, address_size, Register::None, RepPrefixKind::Repne);
}

Result<Instruction> Instruction::with_movsb(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsb_m8_m8, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_movsb(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsb_m8_m8, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_movsw(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsw_m16_m16, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_movsw(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsw_m16_m16, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_movsd(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsd_m32_m32, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_movsd(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsd_m32_m32, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_movsq(std::uint32_t address_size, Register segment_prefix, RepPrefixKind rep_prefix) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsq_m64_m64, address_size, segment_prefix, rep_prefix);
}

Result<Instruction> Instruction::with_rep_movsq(std::uint32_t address_size) {
	return InstructionInternal::with_string_esrdi_segrsi(Code::Movsq_m64_m64, address_size, Register::None, RepPrefixKind::Repe);
}

Result<Instruction> Instruction::with_maskmovq(std::uint32_t address_size, Register register1, Register register2, Register segment_prefix) {
	return InstructionInternal::with_maskmov(Code::Maskmovq_rDI_mm_mm, address_size, register1, register2, segment_prefix);
}

Result<Instruction> Instruction::with_maskmovdqu(std::uint32_t address_size, Register register1, Register register2, Register segment_prefix) {
	return InstructionInternal::with_maskmov(Code::Maskmovdqu_rDI_xmm_xmm, address_size, register1, register2, segment_prefix);
}

Result<Instruction> Instruction::with_vmaskmovdqu(std::uint32_t address_size, Register register1, Register register2, Register segment_prefix) {
	return InstructionInternal::with_maskmov(Code::VEX_Vmaskmovdqu_rDI_xmm_xmm, address_size, register1, register2, segment_prefix);
}

Instruction Instruction::with_declare_byte_1(std::uint8_t b0) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 1);

	instruction.set_declare_byte_value(0, b0);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_1(std::uint8_t b0) {
	return with_declare_byte_1(b0);
}

Instruction Instruction::with_declare_byte_2(std::uint8_t b0, std::uint8_t b1) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 2);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_2(std::uint8_t b0, std::uint8_t b1) {
	return with_declare_byte_2(b0, b1);
}

Instruction Instruction::with_declare_byte_3(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 3);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_3(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2) {
	return with_declare_byte_3(b0, b1, b2);
}

Instruction Instruction::with_declare_byte_4(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 4);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_4(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3) {
	return with_declare_byte_4(b0, b1, b2, b3);
}

Instruction Instruction::with_declare_byte_5(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 5);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_5(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4) {
	return with_declare_byte_5(b0, b1, b2, b3, b4);
}

Instruction Instruction::with_declare_byte_6(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 6);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_6(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5) {
	return with_declare_byte_6(b0, b1, b2, b3, b4, b5);
}

Instruction Instruction::with_declare_byte_7(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 7);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_7(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6) {
	return with_declare_byte_7(b0, b1, b2, b3, b4, b5, b6);
}

Instruction Instruction::with_declare_byte_8(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 8);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_8(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7) {
	return with_declare_byte_8(b0, b1, b2, b3, b4, b5, b6, b7);
}

Instruction Instruction::with_declare_byte_9(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 9);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_9(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8) {
	return with_declare_byte_9(b0, b1, b2, b3, b4, b5, b6, b7, b8);
}

Instruction Instruction::with_declare_byte_10(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 10);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);
	instruction.set_declare_byte_value(9, b9);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_10(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9) {
	return with_declare_byte_10(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9);
}

Instruction Instruction::with_declare_byte_11(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 11);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);
	instruction.set_declare_byte_value(9, b9);
	instruction.set_declare_byte_value(10, b10);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_11(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10) {
	return with_declare_byte_11(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10);
}

Instruction Instruction::with_declare_byte_12(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 12);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);
	instruction.set_declare_byte_value(9, b9);
	instruction.set_declare_byte_value(10, b10);
	instruction.set_declare_byte_value(11, b11);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_12(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11) {
	return with_declare_byte_12(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11);
}

Instruction Instruction::with_declare_byte_13(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 13);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);
	instruction.set_declare_byte_value(9, b9);
	instruction.set_declare_byte_value(10, b10);
	instruction.set_declare_byte_value(11, b11);
	instruction.set_declare_byte_value(12, b12);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_13(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12) {
	return with_declare_byte_13(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12);
}

Instruction Instruction::with_declare_byte_14(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12, std::uint8_t b13) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 14);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);
	instruction.set_declare_byte_value(9, b9);
	instruction.set_declare_byte_value(10, b10);
	instruction.set_declare_byte_value(11, b11);
	instruction.set_declare_byte_value(12, b12);
	instruction.set_declare_byte_value(13, b13);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_14(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12, std::uint8_t b13) {
	return with_declare_byte_14(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13);
}

Instruction Instruction::with_declare_byte_15(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12, std::uint8_t b13, std::uint8_t b14) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 15);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);
	instruction.set_declare_byte_value(9, b9);
	instruction.set_declare_byte_value(10, b10);
	instruction.set_declare_byte_value(11, b11);
	instruction.set_declare_byte_value(12, b12);
	instruction.set_declare_byte_value(13, b13);
	instruction.set_declare_byte_value(14, b14);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_15(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12, std::uint8_t b13, std::uint8_t b14) {
	return with_declare_byte_15(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14);
}

Instruction Instruction::with_declare_byte_16(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12, std::uint8_t b13, std::uint8_t b14, std::uint8_t b15) {
	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, 16);

	instruction.set_declare_byte_value(0, b0);
	instruction.set_declare_byte_value(1, b1);
	instruction.set_declare_byte_value(2, b2);
	instruction.set_declare_byte_value(3, b3);
	instruction.set_declare_byte_value(4, b4);
	instruction.set_declare_byte_value(5, b5);
	instruction.set_declare_byte_value(6, b6);
	instruction.set_declare_byte_value(7, b7);
	instruction.set_declare_byte_value(8, b8);
	instruction.set_declare_byte_value(9, b9);
	instruction.set_declare_byte_value(10, b10);
	instruction.set_declare_byte_value(11, b11);
	instruction.set_declare_byte_value(12, b12);
	instruction.set_declare_byte_value(13, b13);
	instruction.set_declare_byte_value(14, b14);
	instruction.set_declare_byte_value(15, b15);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_byte_16(std::uint8_t b0, std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6, std::uint8_t b7, std::uint8_t b8, std::uint8_t b9, std::uint8_t b10, std::uint8_t b11, std::uint8_t b12, std::uint8_t b13, std::uint8_t b14, std::uint8_t b15) {
	return with_declare_byte_16(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15);
}

Result<Instruction> Instruction::with_declare_byte(const std::uint8_t* data, std::size_t size) {
	if (size - 1 > 16 - 1)
		return IcedError("Invalid slice length");

	Instruction instruction;
	instruction.set_code(Code::DeclareByte);
	InstructionInternal::internal_set_declare_data_len(instruction, static_cast<std::uint32_t>(size));

	for (std::size_t i = 0; i < size; i++)
		instruction.set_declare_byte_value(i, data[i]);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Instruction Instruction::with_declare_word_1(std::uint16_t w0) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 1);

	instruction.set_declare_word_value(0, w0);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_1(std::uint16_t w0) {
	return with_declare_word_1(w0);
}

Instruction Instruction::with_declare_word_2(std::uint16_t w0, std::uint16_t w1) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 2);

	instruction.set_declare_word_value(0, w0);
	instruction.set_declare_word_value(1, w1);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_2(std::uint16_t w0, std::uint16_t w1) {
	return with_declare_word_2(w0, w1);
}

Instruction Instruction::with_declare_word_3(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 3);

	instruction.set_declare_word_value(0, w0);
	instruction.set_declare_word_value(1, w1);
	instruction.set_declare_word_value(2, w2);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_3(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2) {
	return with_declare_word_3(w0, w1, w2);
}

Instruction Instruction::with_declare_word_4(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 4);

	instruction.set_declare_word_value(0, w0);
	instruction.set_declare_word_value(1, w1);
	instruction.set_declare_word_value(2, w2);
	instruction.set_declare_word_value(3, w3);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_4(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3) {
	return with_declare_word_4(w0, w1, w2, w3);
}

Instruction Instruction::with_declare_word_5(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 5);

	instruction.set_declare_word_value(0, w0);
	instruction.set_declare_word_value(1, w1);
	instruction.set_declare_word_value(2, w2);
	instruction.set_declare_word_value(3, w3);
	instruction.set_declare_word_value(4, w4);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_5(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4) {
	return with_declare_word_5(w0, w1, w2, w3, w4);
}

Instruction Instruction::with_declare_word_6(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4, std::uint16_t w5) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 6);

	instruction.set_declare_word_value(0, w0);
	instruction.set_declare_word_value(1, w1);
	instruction.set_declare_word_value(2, w2);
	instruction.set_declare_word_value(3, w3);
	instruction.set_declare_word_value(4, w4);
	instruction.set_declare_word_value(5, w5);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_6(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4, std::uint16_t w5) {
	return with_declare_word_6(w0, w1, w2, w3, w4, w5);
}

Instruction Instruction::with_declare_word_7(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4, std::uint16_t w5, std::uint16_t w6) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 7);

	instruction.set_declare_word_value(0, w0);
	instruction.set_declare_word_value(1, w1);
	instruction.set_declare_word_value(2, w2);
	instruction.set_declare_word_value(3, w3);
	instruction.set_declare_word_value(4, w4);
	instruction.set_declare_word_value(5, w5);
	instruction.set_declare_word_value(6, w6);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_7(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4, std::uint16_t w5, std::uint16_t w6) {
	return with_declare_word_7(w0, w1, w2, w3, w4, w5, w6);
}

Instruction Instruction::with_declare_word_8(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4, std::uint16_t w5, std::uint16_t w6, std::uint16_t w7) {
	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, 8);

	instruction.set_declare_word_value(0, w0);
	instruction.set_declare_word_value(1, w1);
	instruction.set_declare_word_value(2, w2);
	instruction.set_declare_word_value(3, w3);
	instruction.set_declare_word_value(4, w4);
	instruction.set_declare_word_value(5, w5);
	instruction.set_declare_word_value(6, w6);
	instruction.set_declare_word_value(7, w7);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_word_8(std::uint16_t w0, std::uint16_t w1, std::uint16_t w2, std::uint16_t w3, std::uint16_t w4, std::uint16_t w5, std::uint16_t w6, std::uint16_t w7) {
	return with_declare_word_8(w0, w1, w2, w3, w4, w5, w6, w7);
}

Result<Instruction> Instruction::with_declare_word_slice_u8(const std::uint8_t* data, std::size_t size) {
	if (size - 1 > 16 - 1 || (size & 1) != 0)
		return IcedError("Invalid slice length");

	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, static_cast<std::uint32_t>(size / 2));

	for (std::size_t i = 0; i < size / 2; i++) {
		const std::uint16_t v = static_cast<std::uint16_t>(static_cast<std::uint16_t>(data[i * 2]) | (static_cast<std::uint16_t>(data[i * 2 + 1]) << 8));
		instruction.set_declare_word_value(i, v);
	}

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::with_declare_word(const std::uint16_t* data, std::size_t size) {
	if (size - 1 > 8 - 1)
		return IcedError("Invalid slice length");

	Instruction instruction;
	instruction.set_code(Code::DeclareWord);
	InstructionInternal::internal_set_declare_data_len(instruction, static_cast<std::uint32_t>(size));

	for (std::size_t i = 0; i < size; i++)
		instruction.set_declare_word_value(i, data[i]);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Instruction Instruction::with_declare_dword_1(std::uint32_t d0) {
	Instruction instruction;
	instruction.set_code(Code::DeclareDword);
	InstructionInternal::internal_set_declare_data_len(instruction, 1);

	instruction.set_declare_dword_value(0, d0);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_dword_1(std::uint32_t d0) {
	return with_declare_dword_1(d0);
}

Instruction Instruction::with_declare_dword_2(std::uint32_t d0, std::uint32_t d1) {
	Instruction instruction;
	instruction.set_code(Code::DeclareDword);
	InstructionInternal::internal_set_declare_data_len(instruction, 2);

	instruction.set_declare_dword_value(0, d0);
	instruction.set_declare_dword_value(1, d1);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_dword_2(std::uint32_t d0, std::uint32_t d1) {
	return with_declare_dword_2(d0, d1);
}

Instruction Instruction::with_declare_dword_3(std::uint32_t d0, std::uint32_t d1, std::uint32_t d2) {
	Instruction instruction;
	instruction.set_code(Code::DeclareDword);
	InstructionInternal::internal_set_declare_data_len(instruction, 3);

	instruction.set_declare_dword_value(0, d0);
	instruction.set_declare_dword_value(1, d1);
	instruction.set_declare_dword_value(2, d2);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_dword_3(std::uint32_t d0, std::uint32_t d1, std::uint32_t d2) {
	return with_declare_dword_3(d0, d1, d2);
}

Instruction Instruction::with_declare_dword_4(std::uint32_t d0, std::uint32_t d1, std::uint32_t d2, std::uint32_t d3) {
	Instruction instruction;
	instruction.set_code(Code::DeclareDword);
	InstructionInternal::internal_set_declare_data_len(instruction, 4);

	instruction.set_declare_dword_value(0, d0);
	instruction.set_declare_dword_value(1, d1);
	instruction.set_declare_dword_value(2, d2);
	instruction.set_declare_dword_value(3, d3);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_dword_4(std::uint32_t d0, std::uint32_t d1, std::uint32_t d2, std::uint32_t d3) {
	return with_declare_dword_4(d0, d1, d2, d3);
}

Result<Instruction> Instruction::with_declare_dword_slice_u8(const std::uint8_t* data, std::size_t size) {
	if (size - 1 > 16 - 1 || (size & 3) != 0)
		return IcedError("Invalid slice length");

	Instruction instruction;
	instruction.set_code(Code::DeclareDword);
	InstructionInternal::internal_set_declare_data_len(instruction, static_cast<std::uint32_t>(size / 4));

	for (std::size_t i = 0; i < size / 4; i++) {
		const std::uint32_t v = static_cast<std::uint32_t>(static_cast<std::uint32_t>(data[i * 4]) | (static_cast<std::uint32_t>(data[i * 4 + 1]) << 8) | (static_cast<std::uint32_t>(data[i * 4 + 2]) << 16) | (static_cast<std::uint32_t>(data[i * 4 + 3]) << 24));
		instruction.set_declare_dword_value(i, v);
	}

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::with_declare_dword(const std::uint32_t* data, std::size_t size) {
	if (size - 1 > 4 - 1)
		return IcedError("Invalid slice length");

	Instruction instruction;
	instruction.set_code(Code::DeclareDword);
	InstructionInternal::internal_set_declare_data_len(instruction, static_cast<std::uint32_t>(size));

	for (std::size_t i = 0; i < size; i++)
		instruction.set_declare_dword_value(i, data[i]);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Instruction Instruction::with_declare_qword_1(std::uint64_t q0) {
	Instruction instruction;
	instruction.set_code(Code::DeclareQword);
	InstructionInternal::internal_set_declare_data_len(instruction, 1);

	instruction.set_declare_qword_value(0, q0);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_qword_1(std::uint64_t q0) {
	return with_declare_qword_1(q0);
}

Instruction Instruction::with_declare_qword_2(std::uint64_t q0, std::uint64_t q1) {
	Instruction instruction;
	instruction.set_code(Code::DeclareQword);
	InstructionInternal::internal_set_declare_data_len(instruction, 2);

	instruction.set_declare_qword_value(0, q0);
	instruction.set_declare_qword_value(1, q1);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::try_with_declare_qword_2(std::uint64_t q0, std::uint64_t q1) {
	return with_declare_qword_2(q0, q1);
}

Result<Instruction> Instruction::with_declare_qword_slice_u8(const std::uint8_t* data, std::size_t size) {
	if (size - 1 > 16 - 1 || (size & 7) != 0)
		return IcedError("Invalid slice length");

	Instruction instruction;
	instruction.set_code(Code::DeclareQword);
	InstructionInternal::internal_set_declare_data_len(instruction, static_cast<std::uint32_t>(size / 8));

	for (std::size_t i = 0; i < size / 8; i++) {
		const std::uint64_t v = static_cast<std::uint64_t>(static_cast<std::uint64_t>(data[i * 8]) | (static_cast<std::uint64_t>(data[i * 8 + 1]) << 8) | (static_cast<std::uint64_t>(data[i * 8 + 2]) << 16) | (static_cast<std::uint64_t>(data[i * 8 + 3]) << 24) | (static_cast<std::uint64_t>(data[i * 8 + 4]) << 32) | (static_cast<std::uint64_t>(data[i * 8 + 5]) << 40) | (static_cast<std::uint64_t>(data[i * 8 + 6]) << 48) | (static_cast<std::uint64_t>(data[i * 8 + 7]) << 56));
		instruction.set_declare_qword_value(i, v);
	}

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}

Result<Instruction> Instruction::with_declare_qword(const std::uint64_t* data, std::size_t size) {
	if (size - 1 > 2 - 1)
		return IcedError("Invalid slice length");

	Instruction instruction;
	instruction.set_code(Code::DeclareQword);
	InstructionInternal::internal_set_declare_data_len(instruction, static_cast<std::uint32_t>(size));

	for (std::size_t i = 0; i < size; i++)
		instruction.set_declare_qword_value(i, data[i]);

	ICED_DEBUG_ASSERT(instruction.op_count() == 0);
	return instruction;
}
// GENERATOR-END: Create

#undef ICED_TRY

} // namespace iced_x86
