// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

#include "internal/formatter/fmt_consts.hpp"

#include "internal/encoder/const_init.hpp"

namespace iced_x86::internal {

namespace {
// Creates the constant data of a FormatterString
#define ICED_FMT_STR(name, s) constexpr FormatterStringData<sizeof(s)> STR_##name(s)
// clang-format off
ICED_FMT_STR(swizzle_cdab, "cdab");
ICED_FMT_STR(swizzle_badc, "badc");
ICED_FMT_STR(swizzle_dacb, "dacb");
ICED_FMT_STR(swizzle_aaaa, "aaaa");
ICED_FMT_STR(swizzle_bbbb, "bbbb");
ICED_FMT_STR(swizzle_cccc, "cccc");
ICED_FMT_STR(swizzle_dddd, "dddd");
ICED_FMT_STR(mem_1to16, "1to16");
ICED_FMT_STR(mem_1to8, "1to8");
ICED_FMT_STR(mem_4to16, "4to16");
ICED_FMT_STR(mem_4to8, "4to8");
ICED_FMT_STR(mem_float16, "float16");
ICED_FMT_STR(mem_uint8, "uint8");
ICED_FMT_STR(mem_sint8, "sint8");
ICED_FMT_STR(mem_uint16, "uint16");
ICED_FMT_STR(mem_sint16, "sint16");
ICED_FMT_STR(eh, "eh");
ICED_FMT_STR(empty, "");
ICED_FMT_STR(bnd, "bnd");
ICED_FMT_STR(dot_byte, ".byte");
ICED_FMT_STR(hint_not_taken, "hint-not-taken");
ICED_FMT_STR(hint_taken, "hint-taken");
ICED_FMT_STR(hnt, "hnt");
ICED_FMT_STR(ht, "ht");
ICED_FMT_STR(lock, "lock");
ICED_FMT_STR(near, "near");
ICED_FMT_STR(notrack, "notrack");
ICED_FMT_STR(offset, "offset");
ICED_FMT_STR(pn, "pn");
ICED_FMT_STR(pt, "pt");
ICED_FMT_STR(rel, "rel");
ICED_FMT_STR(rep, "rep");
ICED_FMT_STR(rex_w, "rex.w");
ICED_FMT_STR(rne_sae, "rne-sae");
ICED_FMT_STR(rn_sae, "rn-sae");
ICED_FMT_STR(rd_sae, "rd-sae");
ICED_FMT_STR(ru_sae, "ru-sae");
ICED_FMT_STR(rz_sae, "rz-sae");
ICED_FMT_STR(sae, "sae");
ICED_FMT_STR(rne, "rne");
ICED_FMT_STR(rn, "rn");
ICED_FMT_STR(rd, "rd");
ICED_FMT_STR(ru, "ru");
ICED_FMT_STR(rz, "rz");
ICED_FMT_STR(short_, "short");
ICED_FMT_STR(to, "to");
ICED_FMT_STR(xacquire, "xacquire");
ICED_FMT_STR(xrelease, "xrelease");
ICED_FMT_STR(z, "z");
ICED_FMT_STR(a16, "a16");
ICED_FMT_STR(a32, "a32");
ICED_FMT_STR(a64, "a64");
ICED_FMT_STR(addr16, "addr16");
ICED_FMT_STR(addr32, "addr32");
ICED_FMT_STR(addr64, "addr64");
ICED_FMT_STR(data16, "data16");
ICED_FMT_STR(data32, "data32");
ICED_FMT_STR(data64, "data64");
ICED_FMT_STR(o16, "o16");
ICED_FMT_STR(o32, "o32");
ICED_FMT_STR(o64, "o64");
ICED_FMT_STR(repe, "repe");
ICED_FMT_STR(repz, "repz");
ICED_FMT_STR(repne, "repne");
ICED_FMT_STR(repnz, "repnz");
// GENERATOR-BEGIN: FormatterConstantsData
// ⚠️This was generated by GENERATOR!🦹‍♂️
ICED_FMT_STR(b1to16, "1to16");
ICED_FMT_STR(b1to2, "1to2");
ICED_FMT_STR(b1to32, "1to32");
ICED_FMT_STR(b1to4, "1to4");
ICED_FMT_STR(b1to8, "1to8");
ICED_FMT_STR(bcst, "bcst");
ICED_FMT_STR(byte, "byte");
ICED_FMT_STR(dword, "dword");
ICED_FMT_STR(far, "far");
ICED_FMT_STR(fpuenv14, "fpuenv14");
ICED_FMT_STR(fpuenv28, "fpuenv28");
ICED_FMT_STR(fpustate108, "fpustate108");
ICED_FMT_STR(fpustate94, "fpustate94");
ICED_FMT_STR(fword, "fword");
ICED_FMT_STR(mem384, "mem384");
ICED_FMT_STR(mmword, "mmword");
ICED_FMT_STR(oword, "oword");
ICED_FMT_STR(ptr, "ptr");
ICED_FMT_STR(qword, "qword");
ICED_FMT_STR(tbyte, "tbyte");
ICED_FMT_STR(tword, "tword");
ICED_FMT_STR(word, "word");
ICED_FMT_STR(xmmword, "xmmword");
ICED_FMT_STR(ymmword, "ymmword");
ICED_FMT_STR(yword, "yword");
ICED_FMT_STR(zmmword, "zmmword");
ICED_FMT_STR(zword, "zword");
// GENERATOR-END: FormatterConstantsData
// clang-format on
#undef ICED_FMT_STR
} // namespace

constexpr MvexFormatterConstants::MvexFormatterConstants() noexcept
	: swizzle_cdab(STR_swizzle_cdab)
	, swizzle_badc(STR_swizzle_badc)
	, swizzle_dacb(STR_swizzle_dacb)
	, swizzle_aaaa(STR_swizzle_aaaa)
	, swizzle_bbbb(STR_swizzle_bbbb)
	, swizzle_cccc(STR_swizzle_cccc)
	, swizzle_dddd(STR_swizzle_dddd)
	, mem_1to16(STR_mem_1to16)
	, mem_1to8(STR_mem_1to8)
	, mem_4to16(STR_mem_4to16)
	, mem_4to8(STR_mem_4to8)
	, mem_float16(STR_mem_float16)
	, mem_uint8(STR_mem_uint8)
	, mem_sint8(STR_mem_sint8)
	, mem_uint16(STR_mem_uint16)
	, mem_sint16(STR_mem_sint16)
	, eh(STR_eh) {}

// clang-format off
constexpr FormatterConstants::FormatterConstants() noexcept
	: empty(STR_empty)
	// GENERATOR-BEGIN: FormatterConstantsInit
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	, b1to16(STR_b1to16)
	, b1to2(STR_b1to2)
	, b1to32(STR_b1to32)
	, b1to4(STR_b1to4)
	, b1to8(STR_b1to8)
	, bcst(STR_bcst)
	, byte(STR_byte)
	, dword(STR_dword)
	, far(STR_far)
	, fpuenv14(STR_fpuenv14)
	, fpuenv28(STR_fpuenv28)
	, fpustate108(STR_fpustate108)
	, fpustate94(STR_fpustate94)
	, fword(STR_fword)
	, mem384(STR_mem384)
	, mmword(STR_mmword)
	, oword(STR_oword)
	, ptr(STR_ptr)
	, qword(STR_qword)
	, tbyte(STR_tbyte)
	, tword(STR_tword)
	, word(STR_word)
	, xmmword(STR_xmmword)
	, ymmword(STR_ymmword)
	, yword(STR_yword)
	, zmmword(STR_zmmword)
	, zword(STR_zword)
	// GENERATOR-END: FormatterConstantsInit
	, bnd(STR_bnd)
	, dot_byte(STR_dot_byte)
	, hint_not_taken(STR_hint_not_taken)
	, hint_taken(STR_hint_taken)
	, hnt(STR_hnt)
	, ht(STR_ht)
	, lock(STR_lock)
	, near(STR_near)
	, notrack(STR_notrack)
	, offset(STR_offset)
	, pn(STR_pn)
	, pt(STR_pt)
	, rel(STR_rel)
	, rep(STR_rep)
	, repe{{FormatterString(STR_repe), FormatterString(STR_repz)}}
	, repne{{FormatterString(STR_repne), FormatterString(STR_repnz)}}
	, rex_w(STR_rex_w)
	, rne_sae(STR_rne_sae)
	, rn_sae(STR_rn_sae)
	, rd_sae(STR_rd_sae)
	, ru_sae(STR_ru_sae)
	, rz_sae(STR_rz_sae)
	, sae(STR_sae)
	, rne(STR_rne)
	, rn(STR_rn)
	, rd(STR_rd)
	, ru(STR_ru)
	, rz(STR_rz)
	, short_(STR_short_)
	, to(STR_to)
	, xacquire(STR_xacquire)
	, xrelease(STR_xrelease)
	, z(STR_z)
	, a16(STR_a16)
	, a32(STR_a32)
	, a64(STR_a64)
	, addr16(STR_addr16)
	, addr32(STR_addr32)
	, addr64(STR_addr64)
	, data16(STR_data16)
	, data32(STR_data32)
	, data64(STR_data64)
	, o16(STR_o16)
	, o32(STR_o32)
	, o64(STR_o64)
	, mvex() {}
// clang-format on

ICED_CONSTINIT const FormatterConstants FORMATTER_CONSTANTS;

namespace {
constexpr const FormatterString* BRANCH_SHORT[] = {&FORMATTER_CONSTANTS.short_};
constexpr const FormatterString* BRANCH_NEAR[] = {&FORMATTER_CONSTANTS.near};
constexpr const FormatterString* BRANCH_NEAR_WORD[] = {&FORMATTER_CONSTANTS.near, &FORMATTER_CONSTANTS.word};
constexpr const FormatterString* BRANCH_NEAR_DWORD[] = {&FORMATTER_CONSTANTS.near, &FORMATTER_CONSTANTS.dword};
constexpr const FormatterString* BRANCH_WORD[] = {&FORMATTER_CONSTANTS.word};
constexpr const FormatterString* BRANCH_DWORD[] = {&FORMATTER_CONSTANTS.dword};
} // namespace

// clang-format off
constexpr FormatterArrayConstants::FormatterArrayConstants(const FormatterConstants& c) noexcept
	: nothing{}
	// GENERATOR-BEGIN: FormatterArrayConstantsInit
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	, byte_ptr{{&c.byte, &c.ptr}}
	, dword_bcst{{&c.dword, &c.bcst}}
	, dword_ptr{{&c.dword, &c.ptr}}
	, fpuenv14_ptr{{&c.fpuenv14, &c.ptr}}
	, fpuenv28_ptr{{&c.fpuenv28, &c.ptr}}
	, fpustate108_ptr{{&c.fpustate108, &c.ptr}}
	, fpustate94_ptr{{&c.fpustate94, &c.ptr}}
	, fword_ptr{{&c.fword, &c.ptr}}
	, mem384_ptr{{&c.mem384, &c.ptr}}
	, mmword_ptr{{&c.mmword, &c.ptr}}
	, oword_ptr{{&c.oword, &c.ptr}}
	, qword_bcst{{&c.qword, &c.bcst}}
	, qword_ptr{{&c.qword, &c.ptr}}
	, tbyte_ptr{{&c.tbyte, &c.ptr}}
	, word_bcst{{&c.word, &c.bcst}}
	, word_ptr{{&c.word, &c.ptr}}
	, xmmword_ptr{{&c.xmmword, &c.ptr}}
	, ymmword_ptr{{&c.ymmword, &c.ptr}}
	, zmmword_ptr{{&c.zmmword, &c.ptr}}
	// GENERATOR-END: FormatterArrayConstantsInit
	, gas_op_size_strings{{
		&c.empty,
		&c.data16,
		&c.data32,
		&c.rex_w,
	}}
	, gas_addr_size_strings{{
		&c.empty,
		&c.addr16,
		&c.addr32,
		&c.addr64,
	}}
	, intel_op_size_strings{{
		&c.empty,
		&c.data16,
		&c.data32,
		&c.data64,
	}}
	, intel_addr_size_strings{{
		&c.empty,
		&c.addr16,
		&c.addr32,
		&c.addr64,
	}}
	, intel_rc_strings{{
		&c.empty,
		&c.rne,
		&c.rd,
		&c.ru,
		&c.rz,
	}}
	, intel_rc_sae_strings{{
		&c.empty,
		&c.rne_sae,
		&c.rd_sae,
		&c.ru_sae,
		&c.rz_sae,
	}}
	, intel_branch_infos{{
		FormatterStringSlice(),
		FormatterStringSlice(BRANCH_SHORT, 1),
	}}
	, masm_rc_strings{{
		&c.empty,
		&c.rn,
		&c.rd,
		&c.ru,
		&c.rz,
	}}
	, masm_rc_sae_strings{{
		&c.empty,
		&c.rn_sae,
		&c.rd_sae,
		&c.ru_sae,
		&c.rz_sae,
	}}
	, nasm_op_size_strings{{
		&c.empty,
		&c.o16,
		&c.o32,
		&c.o64,
	}}
	, nasm_addr_size_strings{{
		&c.empty,
		&c.a16,
		&c.a32,
		&c.a64,
	}}
	, nasm_branch_infos{{
		FormatterStringSlice(),
		FormatterStringSlice(BRANCH_NEAR, 1),
		FormatterStringSlice(BRANCH_NEAR_WORD, 2),
		FormatterStringSlice(BRANCH_NEAR_DWORD, 2),
		FormatterStringSlice(BRANCH_WORD, 1),
		FormatterStringSlice(BRANCH_DWORD, 1),
		FormatterStringSlice(BRANCH_SHORT, 1),
		FormatterStringSlice(),
	}}
	, nasm_mem_size_infos{{
		&c.empty,
		&c.word,
		&c.dword,
		&c.qword,
	}}
	, nasm_far_mem_size_infos{{
		&c.empty,
		&c.word,
		&c.dword,
		&c.empty,
	}}
	, mvex_reg_mem_consts_32{{
		&c.empty,
		&c.empty,
		&c.mvex.swizzle_cdab,
		&c.mvex.swizzle_badc,
		&c.mvex.swizzle_dacb,
		&c.mvex.swizzle_aaaa,
		&c.mvex.swizzle_bbbb,
		&c.mvex.swizzle_cccc,
		&c.mvex.swizzle_dddd,
		&c.empty,
		&c.mvex.mem_1to16,
		&c.mvex.mem_4to16,
		&c.mvex.mem_float16,
		&c.mvex.mem_uint8,
		&c.mvex.mem_sint8,
		&c.mvex.mem_uint16,
		&c.mvex.mem_sint16,
	}}
	, mvex_reg_mem_consts_64{{
		&c.empty,
		&c.empty,
		&c.mvex.swizzle_cdab,
		&c.mvex.swizzle_badc,
		&c.mvex.swizzle_dacb,
		&c.mvex.swizzle_aaaa,
		&c.mvex.swizzle_bbbb,
		&c.mvex.swizzle_cccc,
		&c.mvex.swizzle_dddd,
		&c.empty,
		&c.mvex.mem_1to8,
		&c.mvex.mem_4to8,
		&c.mvex.mem_float16,
		&c.mvex.mem_uint8,
		&c.mvex.mem_sint8,
		&c.mvex.mem_uint16,
		&c.mvex.mem_sint16,
	}} {}
// clang-format on

ICED_CONSTINIT const FormatterArrayConstants ARRAY_CONSTANTS(FORMATTER_CONSTANTS);

} // namespace iced_x86::internal
