// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#include "internal/info/info_tables.hpp"

namespace iced_x86::internal {

const CpuidFeature CPUID_FEATURES[231] = {
	CpuidFeature::INTEL8086,// INTEL8086
	CpuidFeature::INTEL8086_ONLY,// INTEL8086_ONLY
	CpuidFeature::INTEL186,// INTEL186
	CpuidFeature::INTEL286,// INTEL286
	CpuidFeature::INTEL286_ONLY,// INTEL286_ONLY
	CpuidFeature::INTEL386,// INTEL386
	CpuidFeature::INTEL386_ONLY,// INTEL386_ONLY
	CpuidFeature::INTEL386_A0_ONLY,// INTEL386_A0_ONLY
	CpuidFeature::INTEL486,// INTEL486
	CpuidFeature::INTEL486_A_ONLY,// INTEL486_A_ONLY
	CpuidFeature::UMOV,// UMOV
	CpuidFeature::IA64,// IA64
	CpuidFeature::X64,// X64
	CpuidFeature::ADX,// ADX
	CpuidFeature::AES,// AES
	CpuidFeature::AVX,// AVX
	CpuidFeature::AES, CpuidFeature::AVX,// AES_and_AVX
	CpuidFeature::AVX2,// AVX2
	CpuidFeature::AVX512_4FMAPS,// AVX512_4FMAPS
	CpuidFeature::AVX512_4VNNIW,// AVX512_4VNNIW
	CpuidFeature::AVX512_BITALG,// AVX512_BITALG
	CpuidFeature::AVX512_IFMA,// AVX512_IFMA
	CpuidFeature::AVX512_VBMI,// AVX512_VBMI
	CpuidFeature::AVX512_VBMI2,// AVX512_VBMI2
	CpuidFeature::AVX512_VNNI,// AVX512_VNNI
	CpuidFeature::AVX512_VPOPCNTDQ,// AVX512_VPOPCNTDQ
	CpuidFeature::AVX512BW,// AVX512BW
	CpuidFeature::AVX512CD,// AVX512CD
	CpuidFeature::AVX512DQ,// AVX512DQ
	CpuidFeature::AVX512ER,// AVX512ER
	CpuidFeature::AVX512F,// AVX512F
	CpuidFeature::AVX512F, CpuidFeature::AVX512_BF16,// AVX512F_and_AVX512_BF16
	CpuidFeature::AVX512F, CpuidFeature::AVX512_VP2INTERSECT,// AVX512F_and_AVX512_VP2INTERSECT
	CpuidFeature::AVX512PF,// AVX512PF
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_BF16,// AVX512VL_and_AVX512_BF16
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_BITALG,// AVX512VL_and_AVX512_BITALG
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_IFMA,// AVX512VL_and_AVX512_IFMA
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_VBMI,// AVX512VL_and_AVX512_VBMI
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_VBMI2,// AVX512VL_and_AVX512_VBMI2
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_VNNI,// AVX512VL_and_AVX512_VNNI
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_VP2INTERSECT,// AVX512VL_and_AVX512_VP2INTERSECT
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_VPOPCNTDQ,// AVX512VL_and_AVX512_VPOPCNTDQ
	CpuidFeature::AVX512VL, CpuidFeature::AVX512BW,// AVX512VL_and_AVX512BW
	CpuidFeature::AVX512VL, CpuidFeature::AVX512CD,// AVX512VL_and_AVX512CD
	CpuidFeature::AVX512VL, CpuidFeature::AVX512DQ,// AVX512VL_and_AVX512DQ
	CpuidFeature::AVX512VL, CpuidFeature::AVX512F,// AVX512VL_and_AVX512F
	CpuidFeature::BMI1,// BMI1
	CpuidFeature::BMI2,// BMI2
	CpuidFeature::CET_IBT,// CET_IBT
	CpuidFeature::CET_SS,// CET_SS
	CpuidFeature::CL1INVMB,// CL1INVMB
	CpuidFeature::CLDEMOTE,// CLDEMOTE
	CpuidFeature::CLFLUSHOPT,// CLFLUSHOPT
	CpuidFeature::CLFSH,// CLFSH
	CpuidFeature::CLWB,// CLWB
	CpuidFeature::CLZERO,// CLZERO
	CpuidFeature::CMOV,// CMOV
	CpuidFeature::CMPXCHG16B,// CMPXCHG16B
	CpuidFeature::CPUID,// CPUID
	CpuidFeature::CX8,// CX8
	CpuidFeature::D3NOW,// D3NOW
	CpuidFeature::D3NOWEXT,// D3NOWEXT
	CpuidFeature::OSS,// OSS
	CpuidFeature::ENQCMD,// ENQCMD
	CpuidFeature::F16C,// F16C
	CpuidFeature::FMA,// FMA
	CpuidFeature::FMA4,// FMA4
	CpuidFeature::FPU,// FPU
	CpuidFeature::FPU, CpuidFeature::CMOV,// FPU_and_CMOV
	CpuidFeature::FPU287,// FPU287
	CpuidFeature::FPU287XL_ONLY,// FPU287XL_ONLY
	CpuidFeature::FPU387,// FPU387
	CpuidFeature::FPU387SL_ONLY,// FPU387SL_ONLY
	CpuidFeature::FSGSBASE,// FSGSBASE
	CpuidFeature::FXSR,// FXSR
	CpuidFeature::CYRIX_D3NOW,// CYRIX_D3NOW
	CpuidFeature::GFNI,// GFNI
	CpuidFeature::AVX, CpuidFeature::GFNI,// AVX_and_GFNI
	CpuidFeature::AVX512F, CpuidFeature::GFNI,// AVX512F_and_GFNI
	CpuidFeature::AVX512VL, CpuidFeature::GFNI,// AVX512VL_and_GFNI
	CpuidFeature::HLE_or_RTM,// HLE_or_RTM
	CpuidFeature::INVPCID,// INVPCID
	CpuidFeature::LWP,// LWP
	CpuidFeature::LZCNT,// LZCNT
	CpuidFeature::MCOMMIT,// MCOMMIT
	CpuidFeature::MMX,// MMX
	CpuidFeature::MONITOR,// MONITOR
	CpuidFeature::MONITORX,// MONITORX
	CpuidFeature::MOVBE,// MOVBE
	CpuidFeature::MOVDIR64B,// MOVDIR64B
	CpuidFeature::MOVDIRI,// MOVDIRI
	CpuidFeature::MPX,// MPX
	CpuidFeature::MSR,// MSR
	CpuidFeature::MULTIBYTENOP,// MULTIBYTENOP
	CpuidFeature::PADLOCK_ACE,// PADLOCK_ACE
	CpuidFeature::PADLOCK_PHE,// PADLOCK_PHE
	CpuidFeature::PADLOCK_PMM,// PADLOCK_PMM
	CpuidFeature::PADLOCK_RNG,// PADLOCK_RNG
	CpuidFeature::PAUSE,// PAUSE
	CpuidFeature::PCLMULQDQ,// PCLMULQDQ
	CpuidFeature::PCLMULQDQ, CpuidFeature::AVX,// PCLMULQDQ_and_AVX
	CpuidFeature::PCOMMIT,// PCOMMIT
	CpuidFeature::PCONFIG,// PCONFIG
	CpuidFeature::PKU,// PKU
	CpuidFeature::POPCNT,// POPCNT
	CpuidFeature::PREFETCHW,// PREFETCHW
	CpuidFeature::PREFETCHWT1,// PREFETCHWT1
	CpuidFeature::PTWRITE,// PTWRITE
	CpuidFeature::RDPID,// RDPID
	CpuidFeature::RDPMC,// RDPMC
	CpuidFeature::RDPRU,// RDPRU
	CpuidFeature::RDRAND,// RDRAND
	CpuidFeature::RDSEED,// RDSEED
	CpuidFeature::RDTSCP,// RDTSCP
	CpuidFeature::RTM,// RTM
	CpuidFeature::SEP,// SEP
	CpuidFeature::SGX1,// SGX1
	CpuidFeature::SHA,// SHA
	CpuidFeature::SKINIT_or_SVM,// SKINIT_or_SVM
	CpuidFeature::SMAP,// SMAP
	CpuidFeature::SMX,// SMX
	CpuidFeature::SSE,// SSE
	CpuidFeature::SSE2,// SSE2
	CpuidFeature::SSE3,// SSE3
	CpuidFeature::FPU, CpuidFeature::SSE3,// FPU_and_SSE3
	CpuidFeature::SSE4_1,// SSE4_1
	CpuidFeature::SSE4_2,// SSE4_2
	CpuidFeature::SSE4A,// SSE4A
	CpuidFeature::SSSE3,// SSSE3
	CpuidFeature::SVM,// SVM
	CpuidFeature::SEV_ES,// SEV_ES
	CpuidFeature::SYSCALL,// SYSCALL
	CpuidFeature::TBM,// TBM
	CpuidFeature::TSC,// TSC
	CpuidFeature::VAES,// VAES
	CpuidFeature::AVX512F, CpuidFeature::VAES,// AVX512F_and_VAES
	CpuidFeature::AVX512VL, CpuidFeature::VAES,// AVX512VL_and_VAES
	CpuidFeature::VMX,// VMX
	CpuidFeature::VMX, CpuidFeature::INVEPT,// VMX_and_INVEPT
	CpuidFeature::VMX, CpuidFeature::INVVPID,// VMX_and_INVVPID
	CpuidFeature::VPCLMULQDQ,// VPCLMULQDQ
	CpuidFeature::AVX512F, CpuidFeature::VPCLMULQDQ,// AVX512F_and_VPCLMULQDQ
	CpuidFeature::AVX512VL, CpuidFeature::VPCLMULQDQ,// AVX512VL_and_VPCLMULQDQ
	CpuidFeature::WAITPKG,// WAITPKG
	CpuidFeature::WBNOINVD,// WBNOINVD
	CpuidFeature::XOP,// XOP
	CpuidFeature::XSAVE,// XSAVE
	CpuidFeature::XSAVEC,// XSAVEC
	CpuidFeature::XSAVEOPT,// XSAVEOPT
	CpuidFeature::XSAVES,// XSAVES
	CpuidFeature::SEV_SNP,// SEV_SNP
	CpuidFeature::SERIALIZE,// SERIALIZE
	CpuidFeature::TSXLDTRK,// TSXLDTRK
	CpuidFeature::INVLPGB,// INVLPGB
	CpuidFeature::AMX_BF16,// AMX_BF16
	CpuidFeature::AMX_TILE,// AMX_TILE
	CpuidFeature::AMX_INT8,// AMX_INT8
	CpuidFeature::CYRIX_FPU,// CYRIX_FPU
	CpuidFeature::CYRIX_SMM,// CYRIX_SMM
	CpuidFeature::CYRIX_SMINT,// CYRIX_SMINT
	CpuidFeature::CYRIX_SMINT_0F7E,// CYRIX_SMINT_0F7E
	CpuidFeature::CYRIX_SHR,// CYRIX_SHR
	CpuidFeature::CYRIX_DDI,// CYRIX_DDI
	CpuidFeature::CYRIX_EMMI,// CYRIX_EMMI
	CpuidFeature::CYRIX_DMI,// CYRIX_DMI
	CpuidFeature::CENTAUR_AIS,// CENTAUR_AIS
	CpuidFeature::MOV_TR,// MOV_TR
	CpuidFeature::SMM,// SMM
	CpuidFeature::TDX,// TDX
	CpuidFeature::KL,// KL
	CpuidFeature::AESKLE,// AESKLE
	CpuidFeature::AESKLE, CpuidFeature::WIDE_KL,// AESKLE_and_WIDE_KL
	CpuidFeature::UINTR,// UINTR
	CpuidFeature::HRESET,// HRESET
	CpuidFeature::AVX_VNNI,// AVX_VNNI
	CpuidFeature::PADLOCK_GMI,// PADLOCK_GMI
	CpuidFeature::FRED,// FRED
	CpuidFeature::LKGS,// LKGS
	CpuidFeature::AVX512_FP16,// AVX512_FP16
	CpuidFeature::AVX512VL, CpuidFeature::AVX512_FP16,// AVX512VL_and_AVX512_FP16
	CpuidFeature::UDBG,// UDBG
	CpuidFeature::KNC,// KNC
	CpuidFeature::PADLOCK_UNDOC,// PADLOCK_UNDOC
	CpuidFeature::RMPQUERY,// RMPQUERY
	CpuidFeature::RAO_INT,// RAO_INT
	CpuidFeature::PREFETCHITI,// PREFETCHITI
	CpuidFeature::AMX_FP16,// AMX_FP16
	CpuidFeature::CMPCCXADD,// CMPCCXADD
	CpuidFeature::AVX_IFMA,// AVX_IFMA
	CpuidFeature::AVX_NE_CONVERT,// AVX_NE_CONVERT
	CpuidFeature::AVX_VNNI_INT8,// AVX_VNNI_INT8
	CpuidFeature::MSRLIST,// MSRLIST
	CpuidFeature::WRMSRNS,// WRMSRNS
	CpuidFeature::AMX_COMPLEX,// AMX_COMPLEX
	CpuidFeature::AVX, CpuidFeature::SHA512,// AVX_and_SHA512
	CpuidFeature::AVX, CpuidFeature::SM3,// AVX_and_SM3
	CpuidFeature::AVX, CpuidFeature::SM4,// AVX_and_SM4
	CpuidFeature::TSE,// TSE
	CpuidFeature::AVX_VNNI_INT16,// AVX_VNNI_INT16
};

const CpuidTableEntry CPUID_TABLE[199] = {
	{0, 1},// INTEL8086
	{1, 1},// INTEL8086_ONLY
	{2, 1},// INTEL186
	{3, 1},// INTEL286
	{4, 1},// INTEL286_ONLY
	{5, 1},// INTEL386
	{6, 1},// INTEL386_ONLY
	{7, 1},// INTEL386_A0_ONLY
	{8, 1},// INTEL486
	{9, 1},// INTEL486_A_ONLY
	{10, 1},// UMOV
	{11, 1},// IA64
	{12, 1},// X64
	{13, 1},// ADX
	{14, 1},// AES
	{15, 1},// AVX
	{16, 2},// AES_and_AVX
	{18, 1},// AVX2
	{19, 1},// AVX512_4FMAPS
	{20, 1},// AVX512_4VNNIW
	{21, 1},// AVX512_BITALG
	{22, 1},// AVX512_IFMA
	{23, 1},// AVX512_VBMI
	{24, 1},// AVX512_VBMI2
	{25, 1},// AVX512_VNNI
	{26, 1},// AVX512_VPOPCNTDQ
	{27, 1},// AVX512BW
	{28, 1},// AVX512CD
	{29, 1},// AVX512DQ
	{30, 1},// AVX512ER
	{31, 1},// AVX512F
	{32, 2},// AVX512F_and_AVX512_BF16
	{34, 2},// AVX512F_and_AVX512_VP2INTERSECT
	{36, 1},// AVX512PF
	{37, 2},// AVX512VL_and_AVX512_BF16
	{39, 2},// AVX512VL_and_AVX512_BITALG
	{41, 2},// AVX512VL_and_AVX512_IFMA
	{43, 2},// AVX512VL_and_AVX512_VBMI
	{45, 2},// AVX512VL_and_AVX512_VBMI2
	{47, 2},// AVX512VL_and_AVX512_VNNI
	{49, 2},// AVX512VL_and_AVX512_VP2INTERSECT
	{51, 2},// AVX512VL_and_AVX512_VPOPCNTDQ
	{53, 2},// AVX512VL_and_AVX512BW
	{55, 2},// AVX512VL_and_AVX512CD
	{57, 2},// AVX512VL_and_AVX512DQ
	{59, 2},// AVX512VL_and_AVX512F
	{61, 1},// BMI1
	{62, 1},// BMI2
	{63, 1},// CET_IBT
	{64, 1},// CET_SS
	{65, 1},// CL1INVMB
	{66, 1},// CLDEMOTE
	{67, 1},// CLFLUSHOPT
	{68, 1},// CLFSH
	{69, 1},// CLWB
	{70, 1},// CLZERO
	{71, 1},// CMOV
	{72, 1},// CMPXCHG16B
	{73, 1},// CPUID
	{74, 1},// CX8
	{75, 1},// D3NOW
	{76, 1},// D3NOWEXT
	{77, 1},// OSS
	{78, 1},// ENQCMD
	{79, 1},// F16C
	{80, 1},// FMA
	{81, 1},// FMA4
	{82, 1},// FPU
	{83, 2},// FPU_and_CMOV
	{85, 1},// FPU287
	{86, 1},// FPU287XL_ONLY
	{87, 1},// FPU387
	{88, 1},// FPU387SL_ONLY
	{89, 1},// FSGSBASE
	{90, 1},// FXSR
	{91, 1},// CYRIX_D3NOW
	{92, 1},// GFNI
	{93, 2},// AVX_and_GFNI
	{95, 2},// AVX512F_and_GFNI
	{97, 2},// AVX512VL_and_GFNI
	{99, 1},// HLE_or_RTM
	{100, 1},// INVPCID
	{101, 1},// LWP
	{102, 1},// LZCNT
	{103, 1},// MCOMMIT
	{104, 1},// MMX
	{105, 1},// MONITOR
	{106, 1},// MONITORX
	{107, 1},// MOVBE
	{108, 1},// MOVDIR64B
	{109, 1},// MOVDIRI
	{110, 1},// MPX
	{111, 1},// MSR
	{112, 1},// MULTIBYTENOP
	{113, 1},// PADLOCK_ACE
	{114, 1},// PADLOCK_PHE
	{115, 1},// PADLOCK_PMM
	{116, 1},// PADLOCK_RNG
	{117, 1},// PAUSE
	{118, 1},// PCLMULQDQ
	{119, 2},// PCLMULQDQ_and_AVX
	{121, 1},// PCOMMIT
	{122, 1},// PCONFIG
	{123, 1},// PKU
	{124, 1},// POPCNT
	{125, 1},// PREFETCHW
	{126, 1},// PREFETCHWT1
	{127, 1},// PTWRITE
	{128, 1},// RDPID
	{129, 1},// RDPMC
	{130, 1},// RDPRU
	{131, 1},// RDRAND
	{132, 1},// RDSEED
	{133, 1},// RDTSCP
	{134, 1},// RTM
	{135, 1},// SEP
	{136, 1},// SGX1
	{137, 1},// SHA
	{138, 1},// SKINIT_or_SVM
	{139, 1},// SMAP
	{140, 1},// SMX
	{141, 1},// SSE
	{142, 1},// SSE2
	{143, 1},// SSE3
	{144, 2},// FPU_and_SSE3
	{146, 1},// SSE4_1
	{147, 1},// SSE4_2
	{148, 1},// SSE4A
	{149, 1},// SSSE3
	{150, 1},// SVM
	{151, 1},// SEV_ES
	{152, 1},// SYSCALL
	{153, 1},// TBM
	{154, 1},// TSC
	{155, 1},// VAES
	{156, 2},// AVX512F_and_VAES
	{158, 2},// AVX512VL_and_VAES
	{160, 1},// VMX
	{161, 2},// VMX_and_INVEPT
	{163, 2},// VMX_and_INVVPID
	{165, 1},// VPCLMULQDQ
	{166, 2},// AVX512F_and_VPCLMULQDQ
	{168, 2},// AVX512VL_and_VPCLMULQDQ
	{170, 1},// WAITPKG
	{171, 1},// WBNOINVD
	{172, 1},// XOP
	{173, 1},// XSAVE
	{174, 1},// XSAVEC
	{175, 1},// XSAVEOPT
	{176, 1},// XSAVES
	{177, 1},// SEV_SNP
	{178, 1},// SERIALIZE
	{179, 1},// TSXLDTRK
	{180, 1},// INVLPGB
	{181, 1},// AMX_BF16
	{182, 1},// AMX_TILE
	{183, 1},// AMX_INT8
	{184, 1},// CYRIX_FPU
	{185, 1},// CYRIX_SMM
	{186, 1},// CYRIX_SMINT
	{187, 1},// CYRIX_SMINT_0F7E
	{188, 1},// CYRIX_SHR
	{189, 1},// CYRIX_DDI
	{190, 1},// CYRIX_EMMI
	{191, 1},// CYRIX_DMI
	{192, 1},// CENTAUR_AIS
	{193, 1},// MOV_TR
	{194, 1},// SMM
	{195, 1},// TDX
	{196, 1},// KL
	{197, 1},// AESKLE
	{198, 2},// AESKLE_and_WIDE_KL
	{200, 1},// UINTR
	{201, 1},// HRESET
	{202, 1},// AVX_VNNI
	{203, 1},// PADLOCK_GMI
	{204, 1},// FRED
	{205, 1},// LKGS
	{206, 1},// AVX512_FP16
	{207, 2},// AVX512VL_and_AVX512_FP16
	{209, 1},// UDBG
	{210, 1},// KNC
	{211, 1},// PADLOCK_UNDOC
	{212, 1},// RMPQUERY
	{213, 1},// RAO_INT
	{214, 1},// PREFETCHITI
	{215, 1},// AMX_FP16
	{216, 1},// CMPCCXADD
	{217, 1},// AVX_IFMA
	{218, 1},// AVX_NE_CONVERT
	{219, 1},// AVX_VNNI_INT8
	{220, 1},// MSRLIST
	{221, 1},// WRMSRNS
	{222, 1},// AMX_COMPLEX
	{223, 2},// AVX_and_SHA512
	{225, 2},// AVX_and_SM3
	{227, 2},// AVX_and_SM4
	{229, 1},// TSE
	{230, 1},// AVX_VNNI_INT16
};

} // namespace iced_x86::internal
