// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// Instruction methods that need the instruction info tables (Rust: #[cfg(feature = "instr_info")] parts of instruction.rs)

#include "iced_x86/code.hpp"
#include "iced_x86/code_size.hpp"
#include "iced_x86/instruction.hpp"
#include "iced_x86/mnemonic.hpp"
#include "iced_x86/op_kind.hpp"
#include "internal/iced_assert.hpp"
#include "internal/info/implied_access.hpp"
#include "internal/info/info_flags1.hpp"
#include "internal/info/info_tables.hpp"
#include "internal/info/rflags_info.hpp"
#include <cstddef>
#include <cstdint>

namespace iced_x86 {

std::int32_t Instruction::stack_pointer_increment() const noexcept {
	switch (code()) {
	// GENERATOR-BEGIN: StackPointerIncrementTable
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Pushad:
		return -32;
	case Code::Pushaw:
	case Code::Call_m1664:
		return -16;
	case Code::Push_r64:
	case Code::Pushq_imm32:
	case Code::Pushq_imm8:
	case Code::Call_ptr1632:
	case Code::Pushfq:
	case Code::Call_rel32_64:
	case Code::Call_rm64:
	case Code::Call_m1632:
	case Code::Push_rm64:
	case Code::Pushq_FS:
	case Code::Pushq_GS:
		return -8;
	case Code::Pushd_ES:
	case Code::Pushd_CS:
	case Code::Pushd_SS:
	case Code::Pushd_DS:
	case Code::Push_r32:
	case Code::Pushd_imm32:
	case Code::Pushd_imm8:
	case Code::Call_ptr1616:
	case Code::Pushfd:
	case Code::Call_rel32_32:
	case Code::Call_rm32:
	case Code::Call_m1616:
	case Code::Push_rm32:
	case Code::Pushd_FS:
	case Code::Pushd_GS:
		return -4;
	case Code::Pushw_ES:
	case Code::Pushw_CS:
	case Code::Pushw_SS:
	case Code::Pushw_DS:
	case Code::Push_r16:
	case Code::Push_imm16:
	case Code::Pushw_imm8:
	case Code::Pushfw:
	case Code::Call_rel16:
	case Code::Call_rm16:
	case Code::Push_rm16:
	case Code::Pushw_FS:
	case Code::Pushw_GS:
		return -2;
	case Code::Popw_ES:
	case Code::Popw_CS:
	case Code::Popw_SS:
	case Code::Popw_DS:
	case Code::Pop_r16:
	case Code::Pop_rm16:
	case Code::Popfw:
	case Code::Retnw:
	case Code::Popw_FS:
	case Code::Popw_GS:
		return 2;
	case Code::Popd_ES:
	case Code::Popd_SS:
	case Code::Popd_DS:
	case Code::Pop_r32:
	case Code::Pop_rm32:
	case Code::Popfd:
	case Code::Retnd:
	case Code::Retfw:
	case Code::Popd_FS:
	case Code::Popd_GS:
		return 4;
	case Code::Pop_r64:
	case Code::Pop_rm64:
	case Code::Popfq:
	case Code::Retnq:
	case Code::Retfd:
	case Code::Popq_FS:
	case Code::Popq_GS:
		return 8;
	case Code::Popaw:
	case Code::Retfq:
		return 16;
	case Code::Uiret:
		return 24;
	case Code::Popad:
		return 32;
	case Code::Iretq:
		return 40;
	case Code::Eretu:
	case Code::Erets:
		return 48;
	case Code::Enterw_imm16_imm8:
		return -(2 + (static_cast<std::int32_t>(immediate8_2nd()) & 0x1F) * 2 + static_cast<std::int32_t>(immediate16()));
	case Code::Enterd_imm16_imm8:
		return -(4 + (static_cast<std::int32_t>(immediate8_2nd()) & 0x1F) * 4 + static_cast<std::int32_t>(immediate16()));
	case Code::Enterq_imm16_imm8:
		return -(8 + (static_cast<std::int32_t>(immediate8_2nd()) & 0x1F) * 8 + static_cast<std::int32_t>(immediate16()));
	case Code::Iretw:
		return code_size() == CodeSize::Code64 ? 2 * 5 : 2 * 3;
	case Code::Iretd:
		return code_size() == CodeSize::Code64 ? 4 * 5 : 4 * 3;
	case Code::Retnw_imm16:
		return 2 + static_cast<std::int32_t>(immediate16());
	case Code::Retnd_imm16:
	case Code::Retfw_imm16:
		return 4 + static_cast<std::int32_t>(immediate16());
	case Code::Retnq_imm16:
	case Code::Retfd_imm16:
		return 8 + static_cast<std::int32_t>(immediate16());
	case Code::Retfq_imm16:
		return 16 + static_cast<std::int32_t>(immediate16());
	// GENERATOR-END: StackPointerIncrementTable
	default:
		return 0;
	}
}

FpuStackIncrementInfo Instruction::fpu_stack_increment_info() const noexcept {
	switch (code()) {
	// GENERATOR-BEGIN: FpuStackIncrementInfoTable
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Fld_m32fp:
	case Code::Fld_sti:
	case Code::Fld1:
	case Code::Fldl2t:
	case Code::Fldl2e:
	case Code::Fldpi:
	case Code::Fldlg2:
	case Code::Fldln2:
	case Code::Fldz:
	case Code::Fxtract:
	case Code::Fdecstp:
	case Code::Fild_m32int:
	case Code::Fld_m80fp:
	case Code::Fld_m64fp:
	case Code::Fild_m16int:
	case Code::Fbld_m80bcd:
	case Code::Fild_m64int:
		return FpuStackIncrementInfo(-1, false, true);
	case Code::Fptan:
	case Code::Fsincos:
		return FpuStackIncrementInfo(-1, true, true);
	case Code::Fldenv_m14byte:
	case Code::Fldenv_m28byte:
	case Code::Fninit:
	case Code::Finit:
	case Code::Frstor_m94byte:
	case Code::Frstor_m108byte:
	case Code::Fnsave_m94byte:
	case Code::Fsave_m94byte:
	case Code::Fnsave_m108byte:
	case Code::Fsave_m108byte:
		return FpuStackIncrementInfo(0, false, true);
	case Code::Fcomp_m32fp:
	case Code::Fcomp_st0_sti:
	case Code::Fstp_m32fp:
	case Code::Fstpnce_sti:
	case Code::Fyl2x:
	case Code::Fpatan:
	case Code::Fincstp:
	case Code::Fyl2xp1:
	case Code::Ficomp_m32int:
	case Code::Fisttp_m32int:
	case Code::Fistp_m32int:
	case Code::Fstp_m80fp:
	case Code::Fcomp_m64fp:
	case Code::Fcomp_st0_sti_DCD8:
	case Code::Fisttp_m64int:
	case Code::Fstp_m64fp:
	case Code::Fstp_sti:
	case Code::Fucomp_st0_sti:
	case Code::Ficomp_m16int:
	case Code::Faddp_sti_st0:
	case Code::Fmulp_sti_st0:
	case Code::Fcomp_st0_sti_DED0:
	case Code::Fsubrp_sti_st0:
	case Code::Fsubp_sti_st0:
	case Code::Fdivrp_sti_st0:
	case Code::Fdivp_sti_st0:
	case Code::Fisttp_m16int:
	case Code::Fistp_m16int:
	case Code::Fbstp_m80bcd:
	case Code::Fistp_m64int:
	case Code::Ffreep_sti:
	case Code::Fstp_sti_DFD0:
	case Code::Fstp_sti_DFD8:
	case Code::Fucomip_st0_sti:
	case Code::Fcomip_st0_sti:
	case Code::Ftstp:
		return FpuStackIncrementInfo(1, false, true);
	case Code::Fucompp:
	case Code::Fcompp:
		return FpuStackIncrementInfo(2, false, true);
	// GENERATOR-END: FpuStackIncrementInfoTable
	default:
		return FpuStackIncrementInfo();
	}
}

namespace {

using internal::ImpliedAccess;
using internal::InfoFlags1;
using internal::RflagsInfo;

RflagsInfo get_rflags_info(const Instruction& instruction) noexcept {
	const std::uint32_t flags1 = internal::INFO_TABLE[static_cast<std::size_t>(instruction.code())].flags1;
	const std::uint32_t implied_access = (flags1 >> InfoFlags1::IMPLIED_ACCESS_SHIFT) & InfoFlags1::IMPLIED_ACCESS_MASK;
	static_assert(static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK1FMOD9) + 1 == static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK1FMOD11), "");
	static_assert(static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK1FMOD9) + 2 == static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK1F), "");
	static_assert(static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK1FMOD9) + 3 == static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK3F), "");
	static_assert(static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK1FMOD9) + 4 == static_cast<std::uint32_t>(ImpliedAccess::Clear_rflags), "");
	const RflagsInfo result = static_cast<RflagsInfo>((flags1 >> InfoFlags1::RFLAGS_INFO_SHIFT) & InfoFlags1::RFLAGS_INFO_MASK);
	const std::uint32_t e = implied_access - static_cast<std::uint32_t>(ImpliedAccess::Shift_Ib_MASK1FMOD9);
	switch (e) {
	case 0:
	case 1: {
		const std::uint32_t m = e == 0 ? 9 : 17;
		switch ((static_cast<std::uint32_t>(instruction.immediate8()) & 0x1F) % m) {
		case 0:
			return RflagsInfo::None;
		case 1:
			return RflagsInfo::R_c_W_co;
		default:
			break;
		}
		break;
	}

	case 2:
	case 3: {
		const std::uint32_t mask = e == 2 ? 0x1F : 0x3F;
		switch (static_cast<std::uint32_t>(instruction.immediate8()) & mask) {
		case 0:
			return RflagsInfo::None;
		case 1:
			if (result == RflagsInfo::W_c_U_o)
				return RflagsInfo::W_co;
			else if (result == RflagsInfo::R_c_W_c_U_o)
				return RflagsInfo::R_c_W_co;
			else {
				ICED_DEBUG_ASSERT(result == RflagsInfo::W_cpsz_U_ao);
				return RflagsInfo::W_copsz_U_a;
			}
		default:
			break;
		}
		break;
	}

	case 4:
		if (instruction.op0_register() == instruction.op1_register() && instruction.op0_kind() == OpKind::Register &&
			instruction.op1_kind() == OpKind::Register) {
			if (instruction.mnemonic() == Mnemonic::Xor)
				return RflagsInfo::C_cos_S_pz_U_a;
			else
				return RflagsInfo::C_acos_S_pz;
		}
		break;

	default:
		break;
	}
	return result;
}

} // namespace

std::uint32_t Instruction::rflags_read() const noexcept {
	return internal::FLAGS_READ[static_cast<std::size_t>(get_rflags_info(*this))];
}

std::uint32_t Instruction::rflags_written() const noexcept {
	return internal::FLAGS_WRITTEN[static_cast<std::size_t>(get_rflags_info(*this))];
}

std::uint32_t Instruction::rflags_cleared() const noexcept {
	return internal::FLAGS_CLEARED[static_cast<std::size_t>(get_rflags_info(*this))];
}

std::uint32_t Instruction::rflags_set() const noexcept {
	return internal::FLAGS_SET[static_cast<std::size_t>(get_rflags_info(*this))];
}

std::uint32_t Instruction::rflags_undefined() const noexcept {
	return internal::FLAGS_UNDEFINED[static_cast<std::size_t>(get_rflags_info(*this))];
}

std::uint32_t Instruction::rflags_modified() const noexcept {
	return internal::FLAGS_MODIFIED[static_cast<std::size_t>(get_rflags_info(*this))];
}

} // namespace iced_x86
