// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// Rust: the pub(crate) methods of `impl Code` (code.rs)

#pragma once

#include "iced_x86/code.hpp"

namespace iced_x86::internal {

constexpr bool code_ignores_segment(Code code) noexcept {
	switch (code) {
	// GENERATOR-BEGIN: IgnoresSegmentTable
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Lea_r16_m:
	case Code::Lea_r32_m:
	case Code::Lea_r64_m:
	case Code::Bndcl_bnd_rm32:
	case Code::Bndcl_bnd_rm64:
	case Code::Bndcu_bnd_rm32:
	case Code::Bndcu_bnd_rm64:
	case Code::Bndmk_bnd_m32:
	case Code::Bndmk_bnd_m64:
	case Code::Bndcn_bnd_rm32:
	case Code::Bndcn_bnd_rm64:
	// GENERATOR-END: IgnoresSegmentTable
		return true;
	default:
		return false;
	}
}

constexpr bool code_ignores_index(Code code) noexcept {
	switch (code) {
	// GENERATOR-BEGIN: IgnoresIndexTable
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Bndldx_bnd_mib:
	case Code::Bndstx_mib_bnd:
	// GENERATOR-END: IgnoresIndexTable
		return true;
	default:
		return false;
	}
}

constexpr bool code_is_tile_stride_index(Code code) noexcept {
	switch (code) {
	// GENERATOR-BEGIN: TileStrideIndexTable
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::VEX_Tileloaddt1_tmm_sibmem:
	case Code::VEX_Tilestored_sibmem_tmm:
	case Code::VEX_Tileloadd_tmm_sibmem:
	// GENERATOR-END: TileStrideIndexTable
		return true;
	default:
		return false;
	}
}

} // namespace iced_x86::internal
