// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct InstrFlags1 {
	static constexpr std::uint32_t SEGMENT_PREFIX_MASK = 0x0000'0007;
	static constexpr std::uint32_t SEGMENT_PREFIX_SHIFT = 0x0000'0005;
	static constexpr std::uint32_t DATA_LENGTH_MASK = 0x0000'000F;
	static constexpr std::uint32_t DATA_LENGTH_SHIFT = 0x0000'0008;
	static constexpr std::uint32_t ROUNDING_CONTROL_MASK = 0x0000'0007;
	static constexpr std::uint32_t ROUNDING_CONTROL_SHIFT = 0x0000'000C;
	static constexpr std::uint32_t OP_MASK_MASK = 0x0000'0007;
	static constexpr std::uint32_t OP_MASK_SHIFT = 0x0000'000F;
	static constexpr std::uint32_t CODE_SIZE_MASK = 0x0000'0003;
	static constexpr std::uint32_t CODE_SIZE_SHIFT = 0x0000'0012;
	static constexpr std::uint32_t BROADCAST = 0x0400'0000;
	static constexpr std::uint32_t SUPPRESS_ALL_EXCEPTIONS = 0x0800'0000;
	static constexpr std::uint32_t ZEROING_MASKING = 0x1000'0000;
	static constexpr std::uint32_t REPE_PREFIX = 0x2000'0000;
	static constexpr std::uint32_t REPNE_PREFIX = 0x4000'0000;
	static constexpr std::uint32_t LOCK_PREFIX = 0x8000'0000;
	static constexpr std::uint32_t EQUALS_IGNORE_MASK = 0x000C'0000;
};

} // namespace iced_x86::internal
