// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class MandatoryPrefixByte : std::uint32_t {
	None = 0,
	P66 = 1,
	PF3 = 2,
	PF2 = 3,
};

} // namespace iced_x86::internal
