// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct MvexInstrFlags {
	static constexpr std::uint32_t MVEX_REG_MEM_CONV_SHIFT = 0x0000'0010;
	static constexpr std::uint32_t MVEX_REG_MEM_CONV_MASK = 0x0000'001F;
	static constexpr std::uint32_t EVICTION_HINT = 0x8000'0000;
};

} // namespace iced_x86::internal
