// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct MvexInfoFlags1 {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t NDD = 0x0000'0001;
	static constexpr std::uint32_t NDS = 0x0000'0002;
	static constexpr std::uint32_t EVICTION_HINT = 0x0000'0004;
	static constexpr std::uint32_t IMM_ROUNDING_CONTROL = 0x0000'0008;
	static constexpr std::uint32_t ROUNDING_CONTROL = 0x0000'0010;
	static constexpr std::uint32_t SUPPRESS_ALL_EXCEPTIONS = 0x0000'0020;
	static constexpr std::uint32_t IGNORES_OP_MASK_REGISTER = 0x0000'0040;
	static constexpr std::uint32_t REQUIRE_OP_MASK_REGISTER = 0x0000'0080;
};

} // namespace iced_x86::internal
