// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct MvexInfoFlags2 {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t NO_SAE_ROUNDING_CONTROL = 0x0000'0001;
	static constexpr std::uint32_t CONV_FN32 = 0x0000'0002;
	static constexpr std::uint32_t IGNORES_EVICTION_HINT = 0x0000'0004;
};

} // namespace iced_x86::internal
