// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>
#include "iced_x86/tuple_type.hpp"
#include "internal/iced_assert.hpp"

namespace iced_x86::internal {

// { N, Nbcst }
inline constexpr std::uint8_t TUPLE_TYPE_TBL[19][2] = {
	{ 0x01, 0x01 },// TupleType::N1
	{ 0x02, 0x02 },// TupleType::N2
	{ 0x04, 0x04 },// TupleType::N4
	{ 0x08, 0x08 },// TupleType::N8
	{ 0x10, 0x10 },// TupleType::N16
	{ 0x20, 0x20 },// TupleType::N32
	{ 0x40, 0x40 },// TupleType::N64
	{ 0x08, 0x04 },// TupleType::N8b4
	{ 0x10, 0x04 },// TupleType::N16b4
	{ 0x20, 0x04 },// TupleType::N32b4
	{ 0x40, 0x04 },// TupleType::N64b4
	{ 0x10, 0x08 },// TupleType::N16b8
	{ 0x20, 0x08 },// TupleType::N32b8
	{ 0x40, 0x08 },// TupleType::N64b8
	{ 0x04, 0x02 },// TupleType::N4b2
	{ 0x08, 0x02 },// TupleType::N8b2
	{ 0x10, 0x02 },// TupleType::N16b2
	{ 0x20, 0x02 },// TupleType::N32b2
	{ 0x40, 0x02 },// TupleType::N64b2
};

ICED_FORCE_INLINE std::uint32_t get_disp8n(TupleType tuple_type, bool bcst) noexcept {
	return TUPLE_TYPE_TBL[static_cast<std::size_t>(tuple_type)][bcst ? 1 : 0];
}

} // namespace iced_x86::internal
