// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class VectorLength : std::uint32_t {
	L128 = 0,
	L256 = 1,
	L512 = 2,
	Unknown = 3,
};

} // namespace iced_x86::internal
