// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// `BlockEncoder` options
struct BlockEncoderOptions {
	/// No option is set
	static constexpr std::uint32_t NONE = 0x0000'0000;
	/// By default, branches get updated if the target is too far away, eg. `Jcc SHORT` -> `Jcc NEAR` or if 64-bit mode, `Jcc + JMP [RIP+mem]`. If this option is enabled, no branches are fixed.
	static constexpr std::uint32_t DONT_FIX_BRANCHES = 0x0000'0001;
	/// The `BlockEncoder` should return `RelocInfo`s
	static constexpr std::uint32_t RETURN_RELOC_INFOS = 0x0000'0002;
	/// The `BlockEncoder` should return new instruction offsets
	static constexpr std::uint32_t RETURN_NEW_INSTRUCTION_OFFSETS = 0x0000'0004;
	/// The `BlockEncoder` should return `ConstantOffsets`
	static constexpr std::uint32_t RETURN_CONSTANT_OFFSETS = 0x0000'0008;
};

} // namespace iced_x86
