// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JAE` / `JNB` / `JNC`)
enum class CC_ae : std::uint8_t {
	/// `JAE`, `CMOVAE`, `SETAE`
	ae = 0,
	/// `JNB`, `CMOVNB`, `SETNB`
	nb = 1,
	/// `JNC`, `CMOVNC`, `SETNC`
	nc = 2,
};

/// Gets the name of a `CC_ae` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_ae value) noexcept;

} // namespace iced_x86
