// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JB` / `JC` / `JNAE`)
enum class CC_b : std::uint8_t {
	/// `JB`, `CMOVB`, `SETB`
	b = 0,
	/// `JC`, `CMOVC`, `SETC`
	c = 1,
	/// `JNAE`, `CMOVNAE`, `SETNAE`
	nae = 2,
};

/// Gets the name of a `CC_b` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_b value) noexcept;

} // namespace iced_x86
