// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JBE` / `JNA`)
enum class CC_be : std::uint8_t {
	/// `JBE`, `CMOVBE`, `SETBE`
	be = 0,
	/// `JNA`, `CMOVNA`, `SETNA`
	na = 1,
};

/// Gets the name of a `CC_be` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_be value) noexcept;

} // namespace iced_x86
