// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JE` / `JZ`)
enum class CC_e : std::uint8_t {
	/// `JE`, `CMOVE`, `SETE`, `LOOPE`, `REPE`
	e = 0,
	/// `JZ`, `CMOVZ`, `SETZ`, `LOOPZ`, `REPZ`
	z = 1,
};

/// Gets the name of a `CC_e` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_e value) noexcept;

} // namespace iced_x86
