// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JG` / `JNLE`)
enum class CC_g : std::uint8_t {
	/// `JG`, `CMOVG`, `SETG`
	g = 0,
	/// `JNLE`, `CMOVNLE`, `SETNLE`
	nle = 1,
};

/// Gets the name of a `CC_g` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_g value) noexcept;

} // namespace iced_x86
