// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JGE` / `JNL`)
enum class CC_ge : std::uint8_t {
	/// `JGE`, `CMOVGE`, `SETGE`
	ge = 0,
	/// `JNL`, `CMOVNL`, `SETNL`
	nl = 1,
};

/// Gets the name of a `CC_ge` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_ge value) noexcept;

} // namespace iced_x86
