// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JL` / `JNGE`)
enum class CC_l : std::uint8_t {
	/// `JL`, `CMOVL`, `SETL`
	l = 0,
	/// `JNGE`, `CMOVNGE`, `SETNGE`
	nge = 1,
};

/// Gets the name of a `CC_l` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_l value) noexcept;

} // namespace iced_x86
