// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JNP` / `JPO`)
enum class CC_np : std::uint8_t {
	/// `JNP`, `CMOVNP`, `SETNP`
	np = 0,
	/// `JPO`, `CMOVPO`, `SETPO`
	po = 1,
};

/// Gets the name of a `CC_np` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_np value) noexcept;

} // namespace iced_x86
