// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JNE` / `JNZ`)
enum class CC_ne : std::uint8_t {
	/// `JNE`, `CMOVNE`, `SETNE`, `LOOPNE`, `REPNE`
	ne = 0,
	/// `JNZ`, `CMOVNZ`, `SETNZ`, `LOOPNZ`, `REPNZ`
	nz = 1,
};

/// Gets the name of a `CC_ne` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_ne value) noexcept;

} // namespace iced_x86
