// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mnemonic condition code selector (eg. `JP` / `JPE`)
enum class CC_p : std::uint8_t {
	/// `JP`, `CMOVP`, `SETP`
	p = 0,
	/// `JPE`, `CMOVPE`, `SETPE`
	pe = 1,
};

/// Gets the name of a `CC_p` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CC_p value) noexcept;

} // namespace iced_x86
