// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// The code size (16/32/64) that was used when an instruction was decoded
enum class CodeSize : std::uint8_t {
	/// Unknown size
	Unknown = 0,
	/// 16-bit code
	Code16 = 1,
	/// 32-bit code
	Code32 = 2,
	/// 64-bit code
	Code64 = 3,
};

/// Gets the name of a `CodeSize` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(CodeSize value) noexcept;

} // namespace iced_x86
