// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Decorator
enum class DecoratorKind : std::uint8_t {
	/// Broadcast decorator, eg. `{1to4}`
	Broadcast = 0,
	/// Rounding control, eg. `{rd-sae}`
	RoundingControl = 1,
	/// Suppress all exceptions: `{sae}`
	SuppressAllExceptions = 2,
	/// Zeroing masking: `{z}`
	ZeroingMasking = 3,
	/// MVEX swizzle or memory up/down conversion: `{dacb}` or `{sint16}`
	SwizzleMemConv = 4,
	/// MVEX eviction hint: `{eh}`
	EvictionHint = 5,
};

/// Gets the name of a `DecoratorKind` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(DecoratorKind value) noexcept;

} // namespace iced_x86
