// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Decoder error
enum class DecoderError : std::uint8_t {
	/// No error. The last decoded instruction is a valid instruction
	None = 0,
	/// It's an invalid instruction or an invalid encoding of an existing instruction (eg. some reserved bit is set/cleared)
	InvalidInstruction = 1,
	/// There's not enough bytes left to decode the instruction
	NoMoreBytes = 2,
};

/// Gets the name of a `DecoderError` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(DecoderError value) noexcept;

} // namespace iced_x86
