// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Decoder options
struct DecoderOptions {
	/// No option is enabled
	static constexpr std::uint32_t NONE = 0x0000'0000;
	/// Disable some checks for invalid encodings of instructions, eg. most instructions can't use a `LOCK` prefix so if one is found, they're decoded as `Code::INVALID` unless this option is enabled.
	static constexpr std::uint32_t NO_INVALID_CHECK = 0x0000'0001;
	/// AMD decoder: allow 16-bit branch/ret instructions in 64-bit mode, no `o64 CALL/JMP FAR [mem], o64 LSS/LFS/LGS`, `UD0` has no modr/m byte, decode `LOCK MOV CR`. The AMD decoder can still decode Intel instructions.
	static constexpr std::uint32_t AMD = 0x0000'0002;
	/// Decode opcodes `0F0D` and `0F18-0F1F` as reserved-nop instructions (eg. `Code::Reservednop_rm32_r32_0F1D`)
	static constexpr std::uint32_t FORCE_RESERVED_NOP = 0x0000'0004;
	/// Decode `UMOV` instructions
	static constexpr std::uint32_t UMOV = 0x0000'0008;
	/// Decode `XBTS`/`IBTS`
	static constexpr std::uint32_t XBTS = 0x0000'0010;
	/// Decode `0FA6`/`0FA7` as `CMPXCHG`
	static constexpr std::uint32_t CMPXCHG486A = 0x0000'0020;
	/// Decode some old removed FPU instructions (eg. `FRSTPM`)
	static constexpr std::uint32_t OLD_FPU = 0x0000'0040;
	/// Decode `PCOMMIT`
	static constexpr std::uint32_t PCOMMIT = 0x0000'0080;
	/// Decode 286 `STOREALL`/`LOADALL` (`0F04` and `0F05`)
	static constexpr std::uint32_t LOADALL286 = 0x0000'0100;
	/// Decode 386 `LOADALL`
	static constexpr std::uint32_t LOADALL386 = 0x0000'0200;
	/// Decode `CL1INVMB`
	static constexpr std::uint32_t CL1INVMB = 0x0000'0400;
	/// Decode `MOV r32,tr` and `MOV tr,r32`
	static constexpr std::uint32_t MOV_TR = 0x0000'0800;
	/// Decode `JMPE` instructions
	static constexpr std::uint32_t JMPE = 0x0000'1000;
	/// Don't decode `PAUSE`, decode `NOP` instead
	static constexpr std::uint32_t NO_PAUSE = 0x0000'2000;
	/// Don't decode `WBNOINVD`, decode `WBINVD` instead
	static constexpr std::uint32_t NO_WBNOINVD = 0x0000'4000;
	/// Decode undocumented Intel `RDUDBG` and `WRUDBG` instructions
	static constexpr std::uint32_t UDBG = 0x0000'8000;
	/// Don't decode `TZCNT`, decode `BSF` instead
	static constexpr std::uint32_t NO_MPFX_0FBC = 0x0001'0000;
	/// Don't decode `LZCNT`, decode `BSR` instead
	static constexpr std::uint32_t NO_MPFX_0FBD = 0x0002'0000;
	/// Don't decode `LAHF` and `SAHF` in 64-bit mode
	static constexpr std::uint32_t NO_LAHF_SAHF_64 = 0x0004'0000;
	/// Decode `MPX` instructions
	static constexpr std::uint32_t MPX = 0x0008'0000;
	/// Decode most Cyrix instructions: `FPU`, `EMMI`, `SMM`, `DDI`
	static constexpr std::uint32_t CYRIX = 0x0010'0000;
	/// Decode Cyrix `SMINT 0F7E` (Cyrix 6x86 or earlier)
	static constexpr std::uint32_t CYRIX_SMINT_0F7E = 0x0020'0000;
	/// Decode Cyrix `DMI` instructions (AMD Geode GX/LX)
	static constexpr std::uint32_t CYRIX_DMI = 0x0040'0000;
	/// Decode Centaur `ALTINST`
	static constexpr std::uint32_t ALTINST = 0x0080'0000;
	/// Decode Intel Knights Corner instructions
	static constexpr std::uint32_t KNC = 0x0100'0000;
};

} // namespace iced_x86
