// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Instruction encoding
enum class EncodingKind : std::uint8_t {
	/// Legacy encoding
	Legacy = 0,
	/// VEX encoding
	VEX = 1,
	/// EVEX encoding
	EVEX = 2,
	/// XOP encoding
	XOP = 3,
	/// 3DNow! encoding
	D3NOW = 4,
	/// MVEX encoding
	MVEX = 5,
};

/// Gets the name of a `EncodingKind` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(EncodingKind value) noexcept;

} // namespace iced_x86
