// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Format mnemonic options
struct FormatMnemonicOptions {
	/// No option is set
	static constexpr std::uint32_t NONE = 0x0000'0000;
	/// Don't add any prefixes
	static constexpr std::uint32_t NO_PREFIXES = 0x0000'0001;
	/// Don't add the mnemonic
	static constexpr std::uint32_t NO_MNEMONIC = 0x0000'0002;
};

} // namespace iced_x86
