// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>
#include "iced_x86/code.hpp"
#include "iced_x86/register.hpp"
#include "iced_x86/memory_size.hpp"

namespace iced_x86 {

struct IcedConstants {
	static constexpr std::size_t MAX_OP_COUNT = 5;
	static constexpr std::size_t MAX_INSTRUCTION_LENGTH = 15;
	static constexpr std::uint32_t REGISTER_BITS = 8;
	static constexpr Register VMM_FIRST = Register::ZMM0;
	static constexpr Register VMM_LAST = Register::ZMM31;
	static constexpr std::uint32_t VMM_COUNT = 32;
	static constexpr Register XMM_LAST = Register::XMM31;
	static constexpr Register YMM_LAST = Register::YMM31;
	static constexpr Register ZMM_LAST = Register::ZMM31;
	static constexpr Register TMM_LAST = Register::TMM7;
	static constexpr std::size_t MAX_CPUID_FEATURE_INTERNAL_VALUES = 199;
	static constexpr MemorySize FIRST_BROADCAST_MEMORY_SIZE = MemorySize::Broadcast32_Float16;
	static constexpr std::uint32_t MVEX_START = 4611;
	static constexpr std::uint32_t MVEX_LENGTH = 207;
	static constexpr std::size_t CC_A_ENUM_COUNT = 2;
	static constexpr std::size_t CC_AE_ENUM_COUNT = 3;
	static constexpr std::size_t CC_B_ENUM_COUNT = 3;
	static constexpr std::size_t CC_BE_ENUM_COUNT = 2;
	static constexpr std::size_t CC_E_ENUM_COUNT = 2;
	static constexpr std::size_t CC_G_ENUM_COUNT = 2;
	static constexpr std::size_t CC_GE_ENUM_COUNT = 2;
	static constexpr std::size_t CC_L_ENUM_COUNT = 2;
	static constexpr std::size_t CC_LE_ENUM_COUNT = 2;
	static constexpr std::size_t CC_NE_ENUM_COUNT = 2;
	static constexpr std::size_t CC_NP_ENUM_COUNT = 2;
	static constexpr std::size_t CC_P_ENUM_COUNT = 2;
	static constexpr std::size_t CODE_ENUM_COUNT = 4936;
	static constexpr std::size_t CODE_SIZE_ENUM_COUNT = 4;
	static constexpr std::size_t CONDITION_CODE_ENUM_COUNT = 17;
	static constexpr std::size_t CPUID_FEATURE_ENUM_COUNT = 178;
	static constexpr std::size_t DECODER_ERROR_ENUM_COUNT = 3;
	static constexpr std::size_t DECORATOR_KIND_ENUM_COUNT = 6;
	static constexpr std::size_t ENCODING_KIND_ENUM_COUNT = 6;
	static constexpr std::size_t FLOW_CONTROL_ENUM_COUNT = 10;
	static constexpr std::size_t FORMATTER_SYNTAX_ENUM_COUNT = 4;
	static constexpr std::size_t FORMATTER_TEXT_KIND_ENUM_COUNT = 16;
	static constexpr std::size_t MANDATORY_PREFIX_ENUM_COUNT = 5;
	static constexpr std::size_t MEMORY_SIZE_ENUM_COUNT = 162;
	static constexpr std::size_t MEMORY_SIZE_OPTIONS_ENUM_COUNT = 4;
	static constexpr std::size_t MNEMONIC_ENUM_COUNT = 1894;
	static constexpr std::size_t MVEX_CONV_FN_ENUM_COUNT = 13;
	static constexpr std::size_t MVEX_EHBIT_ENUM_COUNT = 3;
	static constexpr std::size_t MVEX_REG_MEM_CONV_ENUM_COUNT = 17;
	static constexpr std::size_t MVEX_TUPLE_TYPE_LUT_KIND_ENUM_COUNT = 14;
	static constexpr std::size_t NUMBER_BASE_ENUM_COUNT = 4;
	static constexpr std::size_t NUMBER_KIND_ENUM_COUNT = 8;
	static constexpr std::size_t OP_ACCESS_ENUM_COUNT = 8;
	static constexpr std::size_t OP_CODE_OPERAND_KIND_ENUM_COUNT = 109;
	static constexpr std::size_t OP_CODE_TABLE_KIND_ENUM_COUNT = 9;
	static constexpr std::size_t OP_KIND_ENUM_COUNT = 25;
	static constexpr std::size_t PREFIX_KIND_ENUM_COUNT = 18;
	static constexpr std::size_t REGISTER_ENUM_COUNT = 256;
	static constexpr std::size_t RELOC_KIND_ENUM_COUNT = 1;
	static constexpr std::size_t REP_PREFIX_KIND_ENUM_COUNT = 3;
	static constexpr std::size_t ROUNDING_CONTROL_ENUM_COUNT = 5;
	static constexpr std::size_t TUPLE_TYPE_ENUM_COUNT = 19;

	/// Returns `true` if it's an MVEX instruction
	static constexpr bool is_mvex(Code code) noexcept {
		return (static_cast<std::uint32_t>(code) - MVEX_START) < MVEX_LENGTH;
	}
};

} // namespace iced_x86
