// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Mandatory prefix
enum class MandatoryPrefix : std::uint8_t {
	/// No mandatory prefix (legacy and 3DNow! tables only)
	None = 0,
	/// Empty mandatory prefix (no `66`, `F3` or `F2` prefix)
	PNP = 1,
	/// `66` prefix
	P66 = 2,
	/// `F3` prefix
	PF3 = 3,
	/// `F2` prefix
	PF2 = 4,
};

/// Gets the name of a `MandatoryPrefix` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(MandatoryPrefix value) noexcept;

} // namespace iced_x86
