// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Memory size options used by the formatters
enum class MemorySizeOptions : std::uint8_t {
	/// Show memory size if the assembler requires it, else don't show anything
	Default = 0,
	/// Always show the memory size, even if the assembler doesn't need it
	Always = 1,
	/// Show memory size if a human can't figure out the size of the operand
	Minimal = 2,
	/// Never show memory size
	Never = 3,
};

/// Gets the name of a `MemorySizeOptions` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(MemorySizeOptions value) noexcept;

} // namespace iced_x86
