// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// MVEX conversion function
enum class MvexConvFn : std::uint8_t {
	/// No conversion function
	None = 0,
	/// Sf32(xxx)
	Sf32 = 1,
	/// Sf64(xxx)
	Sf64 = 2,
	/// Si32(xxx)
	Si32 = 3,
	/// Si64(xxx)
	Si64 = 4,
	/// Uf32(xxx)
	Uf32 = 5,
	/// Uf64(xxx)
	Uf64 = 6,
	/// Ui32(xxx)
	Ui32 = 7,
	/// Ui64(xxx)
	Ui64 = 8,
	/// Df32(xxx)
	Df32 = 9,
	/// Df64(xxx)
	Df64 = 10,
	/// Di32(xxx)
	Di32 = 11,
	/// Di64(xxx)
	Di64 = 12,
};

/// Gets the name of a `MvexConvFn` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(MvexConvFn value) noexcept;

} // namespace iced_x86
