// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// (MVEX) EH bit value
enum class MvexEHBit : std::uint8_t {
	/// Not hard coded to 0 or 1 so can be used for other purposes
	None = 0,
	/// EH bit must be 0
	EH0 = 1,
	/// EH bit must be 1
	EH1 = 2,
};

/// Gets the name of a `MvexEHBit` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(MvexEHBit value) noexcept;

} // namespace iced_x86
