// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// MVEX tuple type lut kind used together with the `MVEX.SSS` bits to get the tuple type
enum class MvexTupleTypeLutKind : std::uint8_t {
	/// `int32_t` elements, eg. `Si32`/`Di32`/`Ui32`
	Int32 = 0,
	/// `int32_t` elements, eg. `Si32`/`Di32`/`Ui32` with half memory size (32 bytes instead of 64 bytes, eg. `VCVTUDQ2PD`/`VCVTDQ2PD`)
	Int32_Half = 1,
	/// `int32_t` elements, eg. `Si32`/`Di32`/`Ui32` with built-in `{4to16}` broadcast
	Int32_4to16 = 2,
	/// `int32_t` elements, eg. `Si32`/`Di32`/`Ui32` with built-in `{1to16}` broadcast or element level
	Int32_1to16_or_elem = 3,
	/// `int64_t` elements, eg. `Si64`/`Di64`/`Ui64`
	Int64 = 4,
	/// `int64_t` elements, eg. `Si64`/`Di64`/`Ui64` with built-in `{4to8}` broadcast
	Int64_4to8 = 5,
	/// `int64_t` elements, eg. `Si64`/`Di64`/`Ui64` with built-in `{1to8}` broadcast or element level
	Int64_1to8_or_elem = 6,
	/// `float` elements, eg. `Sf32`/`Df32`/`Uf32`
	Float32 = 7,
	/// `float` elements, eg. `Sf32`/`Df32`/`Uf32` with half memory size (32 bytes instead of 64 bytes, eg. `VCVTPS2PD`
	Float32_Half = 8,
	/// `float` elements, eg. `Sf32`/`Df32`/`Uf32` with built-in `{4to16}` broadcast
	Float32_4to16 = 9,
	/// `float` elements, eg. `Sf32`/`Df32`/`Uf32` with built-in `{1to16}` broadcast or element level
	Float32_1to16_or_elem = 10,
	/// `double` elements, eg. `Sf64`/`Df64`/`Uf64`
	Float64 = 11,
	/// `double` elements, eg. `Sf64`/`Df64`/`Uf64` with built-in `{4to8}` broadcast
	Float64_4to8 = 12,
	/// `double` elements, eg. `Sf64`/`Df64`/`Uf64` with built-in `{1to8}` broadcast or element level
	Float64_1to8_or_elem = 13,
};

/// Gets the name of a `MvexTupleTypeLutKind` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(MvexTupleTypeLutKind value) noexcept;

} // namespace iced_x86
