// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Number kind
enum class NumberKind : std::uint8_t {
	Int8 = 0,
	UInt8 = 1,
	Int16 = 2,
	UInt16 = 3,
	Int32 = 4,
	UInt32 = 5,
	Int64 = 6,
	UInt64 = 7,
};

/// Gets the name of a `NumberKind` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(NumberKind value) noexcept;

} // namespace iced_x86
