// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Number base
enum class NumberBase : std::uint8_t {
	/// Hex numbers (base 16)
	Hexadecimal = 0,
	/// Decimal numbers (base 10)
	Decimal = 1,
	/// Octal numbers (base 8)
	Octal = 2,
	/// Binary numbers (base 2)
	Binary = 3,
};

/// Gets the name of a `NumberBase` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(NumberBase value) noexcept;

} // namespace iced_x86
