// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Opcode table
enum class OpCodeTableKind : std::uint8_t {
	/// Legacy/`MAP0` table
	Normal = 0,
	/// `0F`/`MAP1` table (legacy, VEX, EVEX, MVEX)
	T0F = 1,
	/// `0F38`/`MAP2` table (legacy, VEX, EVEX, MVEX)
	T0F38 = 2,
	/// `0F3A`/`MAP3` table (legacy, VEX, EVEX, MVEX)
	T0F3A = 3,
	/// `MAP5` table (EVEX)
	MAP5 = 4,
	/// `MAP6` table (EVEX)
	MAP6 = 5,
	/// `MAP8` table (XOP)
	MAP8 = 6,
	/// `MAP9` table (XOP)
	MAP9 = 7,
	/// `MAP10` table (XOP)
	MAP10 = 8,
};

/// Gets the name of a `OpCodeTableKind` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(OpCodeTableKind value) noexcept;

} // namespace iced_x86
