// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// `REP`/`REPE`/`REPNE` prefix
enum class RepPrefixKind : std::uint8_t {
	/// No `REP`/`REPE`/`REPNE` prefix
	None = 0,
	/// `REP`/`REPE` prefix
	Repe = 1,
	/// `REPNE` prefix
	Repne = 2,
};

/// Gets the name of a `RepPrefixKind` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(RepPrefixKind value) noexcept;

} // namespace iced_x86
