// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// `RFLAGS` bits, FPU condition code bits and misc bits (`UIF`) supported by the instruction info code
struct RflagsBits {
	/// No bit is set
	static constexpr std::uint32_t NONE = 0x0000'0000;
	/// `RFLAGS.OF`
	static constexpr std::uint32_t OF = 0x0000'0001;
	/// `RFLAGS.SF`
	static constexpr std::uint32_t SF = 0x0000'0002;
	/// `RFLAGS.ZF`
	static constexpr std::uint32_t ZF = 0x0000'0004;
	/// `RFLAGS.AF`
	static constexpr std::uint32_t AF = 0x0000'0008;
	/// `RFLAGS.CF`
	static constexpr std::uint32_t CF = 0x0000'0010;
	/// `RFLAGS.PF`
	static constexpr std::uint32_t PF = 0x0000'0020;
	/// `RFLAGS.DF`
	static constexpr std::uint32_t DF = 0x0000'0040;
	/// `RFLAGS.IF`
	static constexpr std::uint32_t IF = 0x0000'0080;
	/// `RFLAGS.AC`
	static constexpr std::uint32_t AC = 0x0000'0100;
	/// `UIF`
	static constexpr std::uint32_t UIF = 0x0000'0200;
	/// FPU status word bit `C0`
	static constexpr std::uint32_t C0 = 0x0000'0400;
	/// FPU status word bit `C1`
	static constexpr std::uint32_t C1 = 0x0000'0800;
	/// FPU status word bit `C2`
	static constexpr std::uint32_t C2 = 0x0000'1000;
	/// FPU status word bit `C3`
	static constexpr std::uint32_t C3 = 0x0000'2000;
};

} // namespace iced_x86
