// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Rounding control
enum class RoundingControl : std::uint8_t {
	/// No rounding mode
	None = 0,
	/// Round to nearest (even)
	RoundToNearest = 1,
	/// Round down (toward -inf)
	RoundDown = 2,
	/// Round up (toward +inf)
	RoundUp = 3,
	/// Round toward zero (truncate)
	RoundTowardZero = 4,
};

/// Gets the name of a `RoundingControl` value (eg. for debugging). Returns an empty string if it's an invalid value.
const char* to_string(RoundingControl value) noexcept;

} // namespace iced_x86
