// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86 {

/// Symbol flags
struct SymbolFlags {
	/// No bit is set
	static constexpr std::uint32_t NONE = 0x0000'0000;
	/// It's a symbol relative to a register, eg. a struct offset `[ebx+some_struct.field1]`. If this is cleared, it's the address of a symbol.
	static constexpr std::uint32_t RELATIVE = 0x0000'0001;
	/// It's a signed symbol and it should be displayed as `-symbol` or `reg-symbol` instead of `symbol` or `reg+symbol`
	static constexpr std::uint32_t SIGNED = 0x0000'0002;
};

} // namespace iced_x86
