// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include "iced_x86/decoder.hpp"

namespace iced_x86::internal::decoder_data_vex {

// 2142 handlers (constant data)
extern const HandlerEntry HANDLERS_0F38[0x100];
extern const HandlerEntry HANDLERS_0F3A[0x100];
extern const HandlerEntry HANDLERS_MAP0[0x100];
extern const HandlerEntry HANDLERS_0F[0x100];

} // namespace iced_x86::internal::decoder_data_vex
