// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include "iced_x86/decoder.hpp"

namespace iced_x86::internal::decoder_data_xop {

// 296 handlers (constant data)
extern const HandlerEntry HANDLERS_MAP8[0x100];
extern const HandlerEntry HANDLERS_MAP9[0x100];
extern const HandlerEntry HANDLERS_MAP10[0x100];

} // namespace iced_x86::internal::decoder_data_xop
