// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include "iced_x86/decoder.hpp"

namespace iced_x86::internal::decoder_data_legacy {

// 1850 handlers (constant data)
extern const HandlerEntry HANDLERS_MAP0[0x100];

} // namespace iced_x86::internal::decoder_data_legacy
