// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct HandlerFlags {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t XACQUIRE = 0x0000'0001;
	static constexpr std::uint32_t XRELEASE = 0x0000'0002;
	static constexpr std::uint32_t XACQUIRE_XRELEASE_NO_LOCK = 0x0000'0004;
	static constexpr std::uint32_t LOCK = 0x0000'0008;
};

} // namespace iced_x86::internal
