// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct LegacyHandlerFlags {
	static constexpr std::uint32_t HANDLER_REG = 0x0000'0001;
	static constexpr std::uint32_t HANDLER_MEM = 0x0000'0002;
	static constexpr std::uint32_t HANDLER_66_REG = 0x0000'0004;
	static constexpr std::uint32_t HANDLER_66_MEM = 0x0000'0008;
	static constexpr std::uint32_t HANDLER_F3_REG = 0x0000'0010;
	static constexpr std::uint32_t HANDLER_F3_MEM = 0x0000'0020;
	static constexpr std::uint32_t HANDLER_F2_REG = 0x0000'0040;
	static constexpr std::uint32_t HANDLER_F2_MEM = 0x0000'0080;
};

} // namespace iced_x86::internal
