// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class OpSize : std::uint8_t {
	Size16 = 0,
	Size32 = 1,
	Size64 = 2,
};

} // namespace iced_x86::internal
