// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct StateFlags {
	static constexpr std::uint32_t IP_REL64 = 0x0000'0001;
	static constexpr std::uint32_t IP_REL32 = 0x0000'0002;
	static constexpr std::uint32_t HAS_REX = 0x0000'0008;
	static constexpr std::uint32_t B = 0x0000'0010;
	static constexpr std::uint32_t Z = 0x0000'0020;
	static constexpr std::uint32_t IS_INVALID = 0x0000'0040;
	static constexpr std::uint32_t W = 0x0000'0080;
	static constexpr std::uint32_t NO_IMM = 0x0000'0100;
	static constexpr std::uint32_t ADDR64 = 0x0000'0200;
	static constexpr std::uint32_t BRANCH_IMM8 = 0x0000'0400;
	static constexpr std::uint32_t XBEGIN = 0x0000'0800;
	static constexpr std::uint32_t LOCK = 0x0000'1000;
	static constexpr std::uint32_t ALLOW_LOCK = 0x0000'2000;
	static constexpr std::uint32_t NO_MORE_BYTES = 0x0000'4000;
	static constexpr std::uint32_t HAS66 = 0x0000'8000;
	static constexpr std::uint32_t MVEX_SSS_MASK = 0x0000'0007;
	static constexpr std::uint32_t MVEX_SSS_SHIFT = 0x0000'0010;
	static constexpr std::uint32_t MVEX_EH = 0x0008'0000;
	static constexpr std::uint32_t ENCODING_MASK = 0x0000'0007;
	static constexpr std::uint32_t ENCODING_SHIFT = 0x0000'001D;
};

} // namespace iced_x86::internal
