// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::gas {

struct InstrOpInfoFlags {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t MNEMONIC_SUFFIX_IF_MEM = 0x0000'0001;
	static constexpr std::uint32_t SIZE_OVERRIDE_MASK = 0x0000'0003;
	static constexpr std::uint32_t OP_SIZE_SHIFT = 0x0000'0001;
	static constexpr std::uint32_t OP_SIZE16 = 0x0000'0002;
	static constexpr std::uint32_t OP_SIZE32 = 0x0000'0004;
	static constexpr std::uint32_t OP_SIZE64 = 0x0000'0006;
	static constexpr std::uint32_t ADDR_SIZE_SHIFT = 0x0000'0003;
	static constexpr std::uint32_t ADDR_SIZE16 = 0x0000'0008;
	static constexpr std::uint32_t ADDR_SIZE32 = 0x0000'0010;
	static constexpr std::uint32_t ADDR_SIZE64 = 0x0000'0018;
	static constexpr std::uint32_t INDIRECT_OPERAND = 0x0000'0020;
	static constexpr std::uint32_t OP_SIZE_IS_BYTE_DIRECTIVE = 0x0000'0040;
	static constexpr std::uint32_t KEEP_OPERAND_ORDER = 0x0000'0080;
	static constexpr std::uint32_t JCC_NOT_TAKEN = 0x0000'0100;
	static constexpr std::uint32_t JCC_TAKEN = 0x0000'0200;
	static constexpr std::uint32_t BND_PREFIX = 0x0000'0400;
	static constexpr std::uint32_t IGNORE_INDEX_REG = 0x0000'0800;
	static constexpr std::uint32_t MNEMONIC_IS_DIRECTIVE = 0x0000'1000;
};

} // namespace iced_x86::internal::gas
