// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>
#include "internal/formatter/fmt_consts.hpp"
#include "internal/iced_assert.hpp"

namespace iced_x86::internal::gas {

/// `BroadcastToKind` of each broadcast `MemorySize` (index = `MemorySize` - `IcedConstants::FIRST_BROADCAST_MEMORY_SIZE`)
// clang-format off
inline constexpr std::uint8_t BCST_TO_DATA[50] = {
	0x01,
	0x01,
	0x01,
	0x02,
	0x01,
	0x03,
	0x03,
	0x02,
	0x02,
	0x01,
	0x01,
	0x01,
	0x03,
	0x02,
	0x01,
	0x02,
	0x01,
	0x01,
	0x02,
	0x02,
	0x04,
	0x04,
	0x03,
	0x03,
	0x02,
	0x02,
	0x02,
	0x04,
	0x03,
	0x02,
	0x03,
	0x02,
	0x02,
	0x03,
	0x03,
	0x05,
	0x05,
	0x04,
	0x04,
	0x03,
	0x03,
	0x03,
	0x05,
	0x04,
	0x03,
	0x04,
	0x04,
	0x03,
	0x03,
	0x04,
};
// clang-format on

/// Converts a `BroadcastToKind` value to its string (eg. `1to8`)
constexpr const FormatterString& get_bcst_to_string(const FormatterConstants& c, std::uint32_t bcst_to_kind) noexcept {
	switch (bcst_to_kind) {
	case 0x00: return c.empty;
	case 0x01: return c.b1to2;
	case 0x02: return c.b1to4;
	case 0x03: return c.b1to8;
	case 0x04: return c.b1to16;
	case 0x05: return c.b1to32;
	default: ICED_UNREACHABLE();
	}
}

} // namespace iced_x86::internal::gas
