// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class DecOptionValue : std::uint8_t {
	None = 0,
	ALTINST = 1,
	Cl1invmb = 2,
	Cmpxchg486A = 3,
	Cyrix = 4,
	Cyrix_DMI = 5,
	Cyrix_SMINT_0F7E = 6,
	Jmpe = 7,
	Loadall286 = 8,
	Loadall386 = 9,
	MovTr = 10,
	MPX = 11,
	OldFpu = 12,
	Pcommit = 13,
	Umov = 14,
	Xbts = 15,
	Udbg = 16,
	KNC = 17,
};

} // namespace iced_x86::internal
