// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class DisplSize : std::uint8_t {
	None = 0,
	Size1 = 1,
	Size2 = 2,
	Size4 = 3,
	Size8 = 4,
	RipRelSize4_Target32 = 5,
	RipRelSize4_Target64 = 6,
};

} // namespace iced_x86::internal
