// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct EncFlags3 {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t ENCODING_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t ENCODING_MASK = 0x0000'0007;
	static constexpr std::uint32_t OPERAND_SIZE_SHIFT = 0x0000'0003;
	static constexpr std::uint32_t OPERAND_SIZE_MASK = 0x0000'0003;
	static constexpr std::uint32_t ADDRESS_SIZE_SHIFT = 0x0000'0005;
	static constexpr std::uint32_t ADDRESS_SIZE_MASK = 0x0000'0003;
	static constexpr std::uint32_t TUPLE_TYPE_SHIFT = 0x0000'0007;
	static constexpr std::uint32_t TUPLE_TYPE_MASK = 0x0000'001F;
	static constexpr std::uint32_t DEFAULT_OP_SIZE64 = 0x0000'1000;
	static constexpr std::uint32_t HAS_RM_GROUP_INDEX = 0x0000'2000;
	static constexpr std::uint32_t INTEL_FORCE_OP_SIZE64 = 0x0000'4000;
	static constexpr std::uint32_t FWAIT = 0x0000'8000;
	static constexpr std::uint32_t BIT16OR32 = 0x0001'0000;
	static constexpr std::uint32_t BIT64 = 0x0002'0000;
	static constexpr std::uint32_t LOCK = 0x0004'0000;
	static constexpr std::uint32_t XACQUIRE = 0x0008'0000;
	static constexpr std::uint32_t XRELEASE = 0x0010'0000;
	static constexpr std::uint32_t REP = 0x0020'0000;
	static constexpr std::uint32_t REPNE = 0x0040'0000;
	static constexpr std::uint32_t BND = 0x0080'0000;
	static constexpr std::uint32_t HINT_TAKEN = 0x0100'0000;
	static constexpr std::uint32_t NOTRACK = 0x0200'0000;
	static constexpr std::uint32_t BROADCAST = 0x0400'0000;
	static constexpr std::uint32_t ROUNDING_CONTROL = 0x0800'0000;
	static constexpr std::uint32_t SUPPRESS_ALL_EXCEPTIONS = 0x1000'0000;
	static constexpr std::uint32_t OP_MASK_REGISTER = 0x2000'0000;
	static constexpr std::uint32_t ZEROING_MASKING = 0x4000'0000;
	static constexpr std::uint32_t REQUIRE_OP_MASK_REGISTER = 0x8000'0000;
};

} // namespace iced_x86::internal
