// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct EncFlags1 {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t LEGACY_OP_MASK = 0x0000'007F;
	static constexpr std::uint32_t LEGACY_OP0_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t LEGACY_OP1_SHIFT = 0x0000'0007;
	static constexpr std::uint32_t LEGACY_OP2_SHIFT = 0x0000'000E;
	static constexpr std::uint32_t LEGACY_OP3_SHIFT = 0x0000'0015;
	static constexpr std::uint32_t VEX_OP_MASK = 0x0000'003F;
	static constexpr std::uint32_t VEX_OP0_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t VEX_OP1_SHIFT = 0x0000'0006;
	static constexpr std::uint32_t VEX_OP2_SHIFT = 0x0000'000C;
	static constexpr std::uint32_t VEX_OP3_SHIFT = 0x0000'0012;
	static constexpr std::uint32_t VEX_OP4_SHIFT = 0x0000'0018;
	static constexpr std::uint32_t XOP_OP_MASK = 0x0000'001F;
	static constexpr std::uint32_t XOP_OP0_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t XOP_OP1_SHIFT = 0x0000'0005;
	static constexpr std::uint32_t XOP_OP2_SHIFT = 0x0000'000A;
	static constexpr std::uint32_t XOP_OP3_SHIFT = 0x0000'000F;
	static constexpr std::uint32_t EVEX_OP_MASK = 0x0000'001F;
	static constexpr std::uint32_t EVEX_OP0_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t EVEX_OP1_SHIFT = 0x0000'0005;
	static constexpr std::uint32_t EVEX_OP2_SHIFT = 0x0000'000A;
	static constexpr std::uint32_t EVEX_OP3_SHIFT = 0x0000'000F;
	static constexpr std::uint32_t MVEX_OP_MASK = 0x0000'000F;
	static constexpr std::uint32_t MVEX_OP0_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t MVEX_OP1_SHIFT = 0x0000'0004;
	static constexpr std::uint32_t MVEX_OP2_SHIFT = 0x0000'0008;
	static constexpr std::uint32_t MVEX_OP3_SHIFT = 0x0000'000C;
	static constexpr std::uint32_t IGNORES_ROUNDING_CONTROL = 0x4000'0000;
	static constexpr std::uint32_t AMD_LOCK_REG_BIT = 0x8000'0000;
};

} // namespace iced_x86::internal
