// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct EncFlags2 {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t OP_CODE_SHIFT = 0x0000'0000;
	static constexpr std::uint32_t OP_CODE_IS2_BYTES = 0x0001'0000;
	static constexpr std::uint32_t TABLE_SHIFT = 0x0000'0011;
	static constexpr std::uint32_t TABLE_MASK = 0x0000'0007;
	static constexpr std::uint32_t MANDATORY_PREFIX_SHIFT = 0x0000'0014;
	static constexpr std::uint32_t MANDATORY_PREFIX_MASK = 0x0000'0003;
	static constexpr std::uint32_t WBIT_SHIFT = 0x0000'0016;
	static constexpr std::uint32_t WBIT_MASK = 0x0000'0003;
	static constexpr std::uint32_t LBIT_SHIFT = 0x0000'0018;
	static constexpr std::uint32_t LBIT_MASK = 0x0000'0007;
	static constexpr std::uint32_t GROUP_INDEX_SHIFT = 0x0000'001B;
	static constexpr std::uint32_t GROUP_INDEX_MASK = 0x0000'0007;
	static constexpr std::uint32_t HAS_MANDATORY_PREFIX = 0x4000'0000;
	static constexpr std::uint32_t HAS_GROUP_INDEX = 0x8000'0000;
};

} // namespace iced_x86::internal
