// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct EncoderFlags {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t B = 0x0000'0001;
	static constexpr std::uint32_t X = 0x0000'0002;
	static constexpr std::uint32_t R = 0x0000'0004;
	static constexpr std::uint32_t W = 0x0000'0008;
	static constexpr std::uint32_t MOD_RM = 0x0000'0010;
	static constexpr std::uint32_t SIB = 0x0000'0020;
	static constexpr std::uint32_t REX = 0x0000'0040;
	static constexpr std::uint32_t P66 = 0x0000'0080;
	static constexpr std::uint32_t P67 = 0x0000'0100;
	/// `EVEX.R'`
	static constexpr std::uint32_t R2 = 0x0000'0200;
	static constexpr std::uint32_t BROADCAST = 0x0000'0400;
	static constexpr std::uint32_t HIGH_LEGACY_8_BIT_REGS = 0x0000'0800;
	static constexpr std::uint32_t DISPL = 0x0000'1000;
	static constexpr std::uint32_t PF0 = 0x0000'2000;
	static constexpr std::uint32_t REG_IS_MEMORY = 0x0000'4000;
	static constexpr std::uint32_t MUST_USE_SIB = 0x0000'8000;
	static constexpr std::uint32_t VVVVV_SHIFT = 0x0000'001B;
	static constexpr std::uint32_t VVVVV_MASK = 0x0000'001F;
};

} // namespace iced_x86::internal
