// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class EvexOpCodeTable : std::uint8_t {
	MAP0F = 1,
	MAP0F38 = 2,
	MAP0F3A = 3,
	MAP5 = 5,
	MAP6 = 6,
};

} // namespace iced_x86::internal
