// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class ImmSize : std::uint8_t {
	None = 0,
	Size1 = 1,
	Size2 = 2,
	Size4 = 3,
	Size8 = 4,
	/// `ENTER xxxx,yy`
	Size2_1 = 5,
	/// `EXTRQ/INSERTQ xx,yy`
	Size1_1 = 6,
	/// `CALL16 FAR x:y`
	Size2_2 = 7,
	/// `CALL32 FAR x:y`
	Size4_2 = 8,
	RipRelSize1_Target16 = 9,
	RipRelSize1_Target32 = 10,
	RipRelSize1_Target64 = 11,
	RipRelSize2_Target16 = 12,
	RipRelSize2_Target32 = 13,
	RipRelSize2_Target64 = 14,
	RipRelSize4_Target32 = 15,
	RipRelSize4_Target64 = 16,
	SizeIbReg = 17,
	Size1OpCode = 18,
};

} // namespace iced_x86::internal
