// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class InstrStrFmtOption : std::uint8_t {
	None = 0,
	OpMaskIsK1_or_NoGprSuffix = 1,
	IncVecIndex = 2,
	NoVecIndex = 3,
	SwapVecIndex12 = 4,
	SkipOp0 = 5,
	VecIndexSameAsOpIndex = 6,
};

} // namespace iced_x86::internal
