// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class LBit : std::uint8_t {
	L0 = 0,
	L1 = 1,
	LIG = 2,
	LZ = 3,
	L128 = 4,
	L256 = 5,
	L512 = 6,
};

} // namespace iced_x86::internal
