// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class LKind : std::uint8_t {
	None = 0,
	/// .128, .256, .512
	L128 = 1,
	/// .L0, .L1
	L0 = 2,
	/// .LZ
	LZ = 3,
};

} // namespace iced_x86::internal
