// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class LegacyOpCodeTable : std::uint8_t {
	MAP0 = 0,
	MAP0F = 1,
	MAP0F38 = 2,
	MAP0F3A = 3,
};

} // namespace iced_x86::internal
