// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct OpCodeInfoFlags1 {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t CPL0_ONLY = 0x0000'0001;
	static constexpr std::uint32_t CPL3_ONLY = 0x0000'0002;
	static constexpr std::uint32_t INPUT_OUTPUT = 0x0000'0004;
	static constexpr std::uint32_t NOP = 0x0000'0008;
	static constexpr std::uint32_t RESERVED_NOP = 0x0000'0010;
	static constexpr std::uint32_t SERIALIZING_INTEL = 0x0000'0020;
	static constexpr std::uint32_t SERIALIZING_AMD = 0x0000'0040;
	static constexpr std::uint32_t MAY_REQUIRE_CPL0 = 0x0000'0080;
	static constexpr std::uint32_t CET_TRACKED = 0x0000'0100;
	static constexpr std::uint32_t NON_TEMPORAL = 0x0000'0200;
	static constexpr std::uint32_t FPU_NO_WAIT = 0x0000'0400;
	static constexpr std::uint32_t IGNORES_MOD_BITS = 0x0000'0800;
	static constexpr std::uint32_t NO66 = 0x0000'1000;
	static constexpr std::uint32_t NFX = 0x0000'2000;
	static constexpr std::uint32_t REQUIRES_UNIQUE_REG_NUMS = 0x0000'4000;
	static constexpr std::uint32_t PRIVILEGED = 0x0000'8000;
	static constexpr std::uint32_t SAVE_RESTORE = 0x0001'0000;
	static constexpr std::uint32_t STACK_INSTRUCTION = 0x0002'0000;
	static constexpr std::uint32_t IGNORES_SEGMENT = 0x0004'0000;
	static constexpr std::uint32_t OP_MASK_READ_WRITE = 0x0008'0000;
	static constexpr std::uint32_t MOD_REG_RM_STRING = 0x0010'0000;
	static constexpr std::uint32_t DEC_OPTION_VALUE_MASK = 0x0000'001F;
	static constexpr std::uint32_t DEC_OPTION_VALUE_SHIFT = 0x0000'0015;
	static constexpr std::uint32_t FORCE_OP_SIZE64 = 0x4000'0000;
	static constexpr std::uint32_t REQUIRES_UNIQUE_DEST_REG_NUM = 0x8000'0000;
};

} // namespace iced_x86::internal
