// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

struct OpCodeInfoFlags2 {
	static constexpr std::uint32_t NONE = 0x0000'0000;
	static constexpr std::uint32_t REAL_MODE = 0x0000'0001;
	static constexpr std::uint32_t PROTECTED_MODE = 0x0000'0002;
	static constexpr std::uint32_t VIRTUAL8086_MODE = 0x0000'0004;
	static constexpr std::uint32_t COMPATIBILITY_MODE = 0x0000'0008;
	static constexpr std::uint32_t USE_OUTSIDE_SMM = 0x0000'0010;
	static constexpr std::uint32_t USE_IN_SMM = 0x0000'0020;
	static constexpr std::uint32_t USE_OUTSIDE_ENCLAVE_SGX = 0x0000'0040;
	static constexpr std::uint32_t USE_IN_ENCLAVE_SGX1 = 0x0000'0080;
	static constexpr std::uint32_t USE_IN_ENCLAVE_SGX2 = 0x0000'0100;
	static constexpr std::uint32_t USE_OUTSIDE_VMX_OP = 0x0000'0200;
	static constexpr std::uint32_t USE_IN_VMX_ROOT_OP = 0x0000'0400;
	static constexpr std::uint32_t USE_IN_VMX_NON_ROOT_OP = 0x0000'0800;
	static constexpr std::uint32_t USE_OUTSIDE_SEAM = 0x0000'1000;
	static constexpr std::uint32_t USE_IN_SEAM = 0x0000'2000;
	static constexpr std::uint32_t TDX_NON_ROOT_GEN_UD = 0x0000'4000;
	static constexpr std::uint32_t TDX_NON_ROOT_GEN_VE = 0x0000'8000;
	static constexpr std::uint32_t TDX_NON_ROOT_MAY_GEN_EX = 0x0001'0000;
	static constexpr std::uint32_t INTEL_VM_EXIT = 0x0002'0000;
	static constexpr std::uint32_t INTEL_MAY_VM_EXIT = 0x0004'0000;
	static constexpr std::uint32_t INTEL_SMM_VM_EXIT = 0x0008'0000;
	static constexpr std::uint32_t AMD_VM_EXIT = 0x0010'0000;
	static constexpr std::uint32_t AMD_MAY_VM_EXIT = 0x0020'0000;
	static constexpr std::uint32_t TSX_ABORT = 0x0040'0000;
	static constexpr std::uint32_t TSX_IMPL_ABORT = 0x0080'0000;
	static constexpr std::uint32_t TSX_MAY_ABORT = 0x0100'0000;
	static constexpr std::uint32_t INTEL_DECODER16OR32 = 0x0200'0000;
	static constexpr std::uint32_t INTEL_DECODER64 = 0x0400'0000;
	static constexpr std::uint32_t AMD_DECODER16OR32 = 0x0800'0000;
	static constexpr std::uint32_t AMD_DECODER64 = 0x1000'0000;
	static constexpr std::uint32_t INSTR_STR_FMT_OPTION_MASK = 0x0000'0007;
	static constexpr std::uint32_t INSTR_STR_FMT_OPTION_SHIFT = 0x0000'001D;
};

} // namespace iced_x86::internal
