// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class WBit : std::uint8_t {
	W0 = 0,
	W1 = 1,
	WIG = 2,
	WIG32 = 3,
};

} // namespace iced_x86::internal
