// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class XopOpCodeTable : std::uint8_t {
	MAP8 = 0,
	MAP9 = 1,
	MAP10 = 2,
};

} // namespace iced_x86::internal
